import { listPrintingFactoryOptions } from '../../../data/fcs/printing-factories.ts'
import { listPrintingWorkOrders } from '../../../data/fcs/printing-task-domain.ts'
import { printingBusinessDate, printingCurrentAction, printingOrderIsOverdue } from '../../../data/fcs/printing-statistics.ts'
import { renderPrintingObjectImage } from './presentation.ts'
import { renderTablePagination } from '../../../components/ui/pagination.ts'
import { escapeHtml } from '../../../utils.ts'

let factoryId='',actionFilter='',currentPage=1
const pageSize=9
function amount(value:number,unit:string){return `${value.toLocaleString('zh-CN',{maximumFractionDigits:2})} ${escapeHtml(unit)}`}
export function renderCraftPrintingDashboardsPage():string {
 const orders=listPrintingWorkOrders(),factories=listPrintingFactoryOptions(orders).map(factory=>[factory.id,factory.name])
 const tasks=orders.filter(o=>!factoryId||o.printFactoryId===factoryId).flatMap(order=>{const action=printingCurrentAction(order);return action?[{order,action}]:[]}).sort((a,b)=>Number(printingOrderIsOverdue(b.order))-Number(printingOrderIsOverdue(a.order))||a.action.priority-b.action.priority)
 const categories=[...new Set(tasks.map(task=>task.action.label))],filtered=tasks.filter(task=>!actionFilter||task.action.label===actionFilter||actionFilter==='OVERDUE'&&printingOrderIsOverdue(task.order))
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));currentPage=Math.min(currentPage,totalPages)
 const start=(currentPage-1)*pageSize,visible=filtered.slice(start,start+pageSize)
 return `<div class="space-y-4 p-4" data-printing-dashboards-root data-skip-page-rerender="true"><header class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-xl font-semibold">印花执行大屏</h1><p class="mt-1 text-xs text-slate-500">业务日期 ${printingBusinessDate(new Date(),factoryId)} · 工厂时区 Asia/Jakarta · 只保留仍有现场动作的单据</p></div><label class="text-sm">加工厂 <select class="h-9 rounded border px-3" data-printing-dashboard-factory><option value="">全部加工厂</option>${factories.map(([id,name])=>`<option value="${escapeHtml(id)}" ${factoryId===id?'selected':''}>${escapeHtml(name)}</option>`).join('')}</select></label></header><div class="flex flex-wrap gap-2">${[['','全部待办',tasks.length],['OVERDUE','超期',tasks.filter(t=>printingOrderIsOverdue(t.order)).length],...categories.map(label=>[label,label,tasks.filter(t=>t.action.label===label).length])].map(([key,label,count])=>`<button class="h-12 rounded border px-3 text-sm ${actionFilter===key?'border-blue-500 bg-blue-50 text-blue-700':'bg-white'}" data-printing-dashboard-action="filter" data-value="${escapeHtml(key)}">${escapeHtml(label)} <strong>${count}</strong></button>`).join('')}</div><section class="grid gap-3 md:grid-cols-2 xl:grid-cols-3">${visible.map(({order,action})=>`<article class="flex flex-col rounded-lg border bg-white p-4"><div class="flex items-center justify-between gap-2"><span class="text-xs text-slate-500">${escapeHtml(order.printFactoryName)}</span>${printingOrderIsOverdue(order)?'<span class="rounded bg-amber-100 px-2 py-1 text-xs text-amber-900">超期待处理</span>':''}</div><div class="mt-3 flex gap-3">${renderPrintingObjectImage(order.output,'h-16 w-16')}<div class="min-w-0"><p class="font-semibold text-blue-700">${escapeHtml(order.printOrderNo)}</p><p class="text-sm">${escapeHtml(order.output.materialName)}</p><p class="break-all text-xs text-slate-500">${escapeHtml(order.output.sku)}</p></div></div><p class="mt-3 text-xs text-slate-500">需求来源：${escapeHtml(order.demandSource.sourceNo||order.demandSource.sourceLabel)}</p><div class="mt-2 space-y-1 border-t pt-2 text-sm"><p>本厂实收：${order.historicalInputQuantityUnknown?'历史未记录':amount(order.actualInput.receivedQty,order.plannedInput.qtyUnit)}</p><p>合格产出：${amount(order.output.completedQty,order.output.qtyUnit)}</p><p>下游待收：${amount(order.pendingWritebackQty,order.output.qtyUnit)}</p></div><a class="mt-4 rounded bg-blue-600 px-3 py-2 text-center text-sm font-medium text-white" href="${escapeHtml(action.route)}" data-nav="${escapeHtml(action.route)}">${escapeHtml(action.label)}</a></article>`).join('')||'<p class="col-span-full rounded border bg-white p-8 text-center text-slate-500">当前工厂没有符合条件的待办</p>'}</section><div class="rounded border bg-white p-3">${renderTablePagination({total:filtered.length,from:filtered.length?start+1:0,to:Math.min(filtered.length,start+pageSize),currentPage,totalPages,pageSize,actionPrefix:'printing-dashboard',fieldPrefix:'printing-dashboard',pageSizeOptions:[pageSize],skipPageRerender:true})}</div></div>`
}
export function handlePrintingDashboardsEvent(target:HTMLElement):boolean {
 const root=target.closest<HTMLElement>('[data-printing-dashboards-root]');if(!root)return false
 if(target.matches('[data-printing-dashboard-factory]')){factoryId=(target as HTMLSelectElement).value;currentPage=1}
 else {const button=target.closest<HTMLElement>('[data-printing-dashboard-action]');if(!button)return target.matches('[data-printing-dashboard-field]');const action=button.dataset.printingDashboardAction;if(action==='filter'){actionFilter=button.dataset.value||'';currentPage=1}else if(action==='prev-page')currentPage=Math.max(1,currentPage-1);else if(action==='next-page')currentPage++;else return false}
 const wrapper=document.createElement('div');wrapper.innerHTML=renderCraftPrintingDashboardsPage();root.replaceWith(wrapper.firstElementChild!);return true
}
