import {
  PRINTING_HANDOVER_STATUS_LABEL,
  PRINTING_PROCESSING_STATUS_LABEL,
  formatPrintingQty,
  listPrintingWorkOrders,
} from '../../../data/fcs/printing-work-order-business.ts'
import { buildPrintingWorkOrderDetailLink } from '../../../data/fcs/fcs-route-links.ts'
import { escapeHtml } from '../../../utils.ts'

export function renderCraftPrintingDashboardsPage(): string {
  const rows = listPrintingWorkOrders()
  const attention = rows.filter((row) => row.processingStatus !== 'CANCELLED' && (row.processingStatus !== 'PROCESS_COMPLETED' || row.handoverStatus !== 'RECEIVED' || row.handover.objectionQty > 0))
  return `<div class="min-h-full space-y-4 bg-slate-950 p-5 text-white"><header class="flex items-center justify-between"><div><h1 class="text-2xl font-semibold">印花执行大屏</h1><p class="mt-1 text-sm text-slate-300">现场只跟进加工五态与交出六态；花型/打印/转印保留在工艺要求和纸面确认单。</p></div><div class="rounded-lg bg-white/10 px-4 py-2 text-sm">待跟进 ${attention.length} 张</div></header>
    <section class="grid gap-3 md:grid-cols-3 xl:grid-cols-5"><article class="rounded-xl bg-blue-500/20 p-4"><p class="text-xs text-blue-100">待接收投入</p><strong class="mt-2 block text-3xl">${rows.filter((row) => row.processingStatus === 'WAIT_INPUT_RECEIPT').length}</strong></article><article class="rounded-xl bg-indigo-500/20 p-4"><p class="text-xs text-indigo-100">加工中</p><strong class="mt-2 block text-3xl">${rows.filter((row) => row.processingStatus === 'PROCESSING').length}</strong></article><article class="rounded-xl bg-amber-500/20 p-4"><p class="text-xs text-amber-100">待交出/部分交出</p><strong class="mt-2 block text-3xl">${rows.filter((row) => ['WAIT_HANDOVER', 'PARTIAL_HANDOVER'].includes(row.handoverStatus)).length}</strong></article><article class="rounded-xl bg-cyan-500/20 p-4"><p class="text-xs text-cyan-100">已交出待接收/部分接收</p><strong class="mt-2 block text-3xl">${rows.filter((row) => ['HANDOVER_WAIT_RECEIVE', 'PARTIAL_RECEIVED'].includes(row.handoverStatus)).length}</strong></article><article class="rounded-xl bg-red-500/20 p-4"><p class="text-xs text-red-100">存在差异/异议</p><strong class="mt-2 block text-3xl">${rows.filter((row) => row.handover.diffQty > 0 || row.handover.objectionQty > 0).length}</strong></article></section>
    <section class="overflow-hidden rounded-xl border border-white/10 bg-white/5"><div class="overflow-x-auto"><table class="min-w-[1200px] w-full text-left text-sm"><thead class="bg-white/5 text-xs text-slate-300"><tr><th class="p-3">印花单</th><th class="p-3">需求来源</th><th class="p-3">加工投入</th><th class="p-3">固定加工产出</th><th class="p-3">加工厂</th><th class="p-3">加工状态</th><th class="p-3">交出状态</th><th class="p-3 text-right">完成/计划</th><th class="p-3 text-right">交出/接收</th><th class="p-3">当前跟进</th></tr></thead><tbody>${attention.map((order) => `<tr class="border-t border-white/10"><td class="p-3"><a class="font-mono text-blue-300" href="${escapeHtml(buildPrintingWorkOrderDetailLink(order.workOrderId))}" data-nav="${escapeHtml(buildPrintingWorkOrderDetailLink(order.workOrderId))}">${escapeHtml(order.printOrderNo)}</a></td><td class="p-3">${escapeHtml(order.demandSource.sourceLabel)}</td><td class="p-3"><p>${escapeHtml(order.plannedInput.materialName)}</p><p class="font-mono text-xs text-slate-400">${escapeHtml(order.actualInput.actualSku)}</p></td><td class="p-3 font-mono text-xs">${escapeHtml(order.output.sku)}</td><td class="p-3">${escapeHtml(order.printFactoryName)}</td><td class="p-3">${escapeHtml(PRINTING_PROCESSING_STATUS_LABEL[order.processingStatus])}</td><td class="p-3">${escapeHtml(PRINTING_HANDOVER_STATUS_LABEL[order.handoverStatus])}</td><td class="p-3 text-right">${formatPrintingQty(order.output.completedQty)} / ${formatPrintingQty(order.output.plannedQty)} Yard</td><td class="p-3 text-right">${formatPrintingQty(order.handover.handedOverQty)} / ${formatPrintingQty(order.handover.receivedQty)} Yard</td><td class="p-3">${order.handover.objectionQty ? `<span class="text-red-300">${order.handover.objectionQty} 条异议待处理</span>` : order.processingStatus === 'PROCESSING' ? '跟进加工完成' : ['HANDOVER_WAIT_RECEIVE', 'PARTIAL_RECEIVED'].includes(order.handoverStatus) ? '跟进下游接收' : '按当前主动作处理'}</td></tr>`).join('')}</tbody></table></div></section>
  </div>`
}
