// @page-pattern: list
import { listPrintingFactoryOptions } from '../../../data/fcs/printing-factories.ts'
import { renderStandardListPage, renderStandardListStats } from '../../../components/ui/list-page.ts'
import { createProcessOrderListController, type ProcessOrderListControllerState } from '../../../components/ui/process-order-list-controller.ts'
import { PRINTING_DEMAND_SOURCE_LABEL, listPrintingWorkOrders } from '../../../data/fcs/printing-task-domain.ts'
import { getPrintingStatistics, summarizePrintingStatistics, formatPrintingStatistic, printingBusinessDate, printingEventTimestamp, normalizePrintingUnit, type PrintingStatisticsFilters, type PrintingStatisticsSummary } from '../../../data/fcs/printing-statistics.ts'
import { escapeHtml } from '../../../utils.ts'

type SummaryRow={name:string;factoryId?:string;craft?:string;summary:PrintingStatisticsSummary;date?:string;qty?:number;unit?:string;batches?:number}
let filters:PrintingStatisticsFilters={},dimension:'factory'|'craft'|'trend'='factory',rows:SummaryRow[]=[]
const state:ProcessOrderListControllerState={currentPage:1,sort:null,preferences:{order:[],visibleKeys:[],frozenKeys:[],pageSize:10},preferencesLoaded:false,showColumnSettings:false}
const prefix='printing-statistics'
function drillLink(row:SummaryRow):string {const params=new URLSearchParams();for(const [key,value] of Object.entries({...filters,factoryId:row.factoryId||filters.factoryId,craft:row.craft||filters.craft}))if(value)params.set(key,value);if(row.date)params.set('completedDate',row.date);const selected=getPrintingStatistics({...filters,factoryId:row.factoryId||filters.factoryId,craft:row.craft||filters.craft}).rows.filter(o=>!row.date||o.productionBatches?.some(b=>{const at=printingEventTimestamp(b.at,o.printFactoryId);return at!==undefined&&printingBusinessDate(at,o.printFactoryId)===row.date&&(!row.unit||normalizePrintingUnit(o.output.qtyUnit)===row.unit)}));params.set('workOrderIds',selected.map(o=>o.workOrderId).join(',')||'NONE');return `/fcs/craft/printing/work-orders?${params}`}
const metrics=[['planned','计划投入'],['localReceived','本厂实收'],['used','实际使用'],['completed','合格完成'],['handedOver','实际交出'],['downstreamReceived','下游实收'],['downstreamPending','下游待收'],['loss','已核算损耗']] as const
const controller=createProcessOrderListController({state,columns:[{key:'name',title:'工厂 / 工艺 / 完工日期',width:200,required:true,sortable:true,render:row=>`<a class="text-blue-600" href="${escapeHtml(drillLink(row))}" data-nav="${escapeHtml(drillLink(row))}">${escapeHtml(row.name)}</a>`,sortValue:row=>row.name},{key:'count',title:'加工单 / 完工批次',width:135,sortable:true,render:row=>String(row.batches??row.summary.orderCount),sortValue:row=>row.batches??row.summary.orderCount},...metrics.map(([key,title])=>({key,title,width:180,sortable:false,render:(row:SummaryRow)=>row.date?(key==='completed'?`${row.qty?.toLocaleString('zh-CN',{maximumFractionDigits:2})} ${escapeHtml(row.unit||'')}`:'不适用'):escapeHtml(formatPrintingStatistic(row.summary,key))})),{key:'coverage',title:'数据完整性',width:220,render:row=>row.date?'实际完工批次':`接收缺失 ${row.summary.unknownReceiptCount} 单；完工历史缺失 ${row.summary.unknownCompletionHistoryCount} 单；损耗未核算 ${row.summary.unknownLossCount} 单`}],defaultFrozenKeys:['name'],columnSettingsTitle:'印花统计列设置',preferenceKey:'/fcs/craft/printing/statistics',pageSizeOptions:[10,20,50],eventPrefix:prefix,rootSelector:'[data-printing-statistics-root]',tableSurfaceSelector:'[data-statistics-table]',paginationSurfaceSelector:'[data-statistics-pagination]',overlaysSurfaceSelector:'[data-statistics-overlays]',getRows:()=>rows,locallyManagedEvents:true,emptyText:'当前筛选范围暂无统计记录'})
function select(key:keyof PrintingStatisticsFilters,label:string,options:Array<[string,string]>):string{return `<label class="text-xs text-slate-500">${label}<select class="mt-1 block h-9 rounded border px-2 text-sm" data-statistics-filter="${key}"><option value="">全部</option>${options.map(([value,text])=>`<option value="${escapeHtml(value)}" ${filters[key]===value?'selected':''}>${escapeHtml(text)}</option>`).join('')}</select></label>`}
export function renderCraftPrintingStatisticsPage():string {
 const all=listPrintingWorkOrders(),view=getPrintingStatistics(filters),summary=view.summary
 if(dimension==='trend')rows=view.trend.map(t=>({name:t.date,date:t.date,qty:t.qty,unit:t.unit,batches:t.batches,summary:summarizePrintingStatistics([])}))
 else {const grouped=new Map<string,typeof all>();for(const order of view.rows){const key=dimension==='factory'?order.printFactoryId:`${order.requirement.craftName} · ${order.requirement.type}`;grouped.set(key,[...(grouped.get(key)||[]),order])}rows=[...grouped.entries()].map(([key,orders])=>({name:dimension==='factory'?orders[0].printFactoryName:key,factoryId:dimension==='factory'?key:undefined,craft:dimension==='craft'?key:undefined,summary:summarizePrintingStatistics(orders)}))}
 controller.installColumnDragEvents();const table=controller.getView()
 const unique=(values:string[])=>[...new Set(values)]
 const fields=`${select('factoryId','加工厂',listPrintingFactoryOptions(all).map(factory=>[factory.id,factory.name]))}${select('craft','工艺',unique(all.map(o=>`${o.requirement.craftName} · ${o.requirement.type}`)).map(v=>[v,v]))}${select('demandSource','需求来源',unique(all.map(o=>o.demandSource.type)).map(v=>[v,PRINTING_DEMAND_SOURCE_LABEL[v as keyof typeof PRINTING_DEMAND_SOURCE_LABEL]]))}${select('materialType','物料类型',unique(all.map(o=>o.materialType)).map(v=>[v,v]))}<label class="text-xs text-slate-500">加工单创建日期<input type="date" class="mt-1 block h-9 rounded border px-2 text-sm" data-statistics-filter="dateFrom" value="${escapeHtml(filters.dateFrom||'')}"></label><label class="text-xs text-slate-500">至<input type="date" class="mt-1 block h-9 rounded border px-2 text-sm" data-statistics-filter="dateTo" value="${escapeHtml(filters.dateTo||'')}"></label>`
 const filtersHtml=`<div class="rounded border bg-white p-3"><div class="flex flex-wrap gap-3">${fields}</div><div class="mt-3 flex gap-2"><button class="rounded bg-blue-600 px-4 py-2 text-sm text-white" data-statistics-action="query">查询</button><button class="rounded border px-4 py-2 text-sm" data-statistics-action="reset">重置</button><a class="rounded border px-4 py-2 text-sm" href="${escapeHtml(drillLink({name:'',summary}))}" data-nav="${escapeHtml(drillLink({name:'',summary}))}">查看同条件加工单</a></div></div>`
 const stats=renderStandardListStats([{label:'加工单 / 生产单 / 需求单',value:`${summary.orderCount} / ${summary.productionOrderCount} / ${summary.demandOrderCount}`},...metrics.map(([key,label])=>({label,value:formatPrintingStatistic(summary,key)})),{label:'今日计划尚需完成',value:formatPrintingStatistic(summary,'todayPlanned')},{label:'今日实际合格完成',value:formatPrintingStatistic(summary,'todayCompleted')},{label:'超期 / 未记录交期',value:`${summary.overdueCount} / ${summary.noDueDateCount}`}],{compact:true})
 const rate=Object.entries(summary.lossRates).map(([unit,value])=>`${unit}：${value===undefined?'不可计算':`${(value*100).toFixed(2)}%`}`).join(' / ')
 return `<div data-printing-statistics-root data-skip-page-rerender="true">${renderStandardListPage({title:'印花统计',filtersHtml,feedbackHtml:`<div class="space-y-1 text-xs text-slate-500"><p>业务日期 ${printingBusinessDate(new Date(),filters.factoryId)} · 按工厂时区（未配置采用 Asia/Jakarta）。日期筛选限定加工单创建范围，数量展示该范围累计事实；“今日实际完成”和趋势只计算最终合格完工批次增量。</p><p>已知数量覆盖：${summary.orderCount-summary.unknownReceiptCount}/${summary.orderCount} 单有本厂实收；${summary.unknownCompletionHistoryCount} 单缺少历史完工批次，不补入每日趋势；${summary.unknownLossCount} 单尚未核算损耗。</p><p>已核算可比完工批次损耗率：${escapeHtml(rate||'不可计算')}。不同计量维度分别汇总；不将印制和转印重复计为合格产出。</p></div>`,statsHtml:`<div class="overflow-x-auto [&_[data-standard-list-stats]]:flex-nowrap">${stats}</div>`,listTitle:'同口径汇总',listActionsHtml:`<div class="flex gap-2"><select class="h-8 rounded border px-2" data-statistics-dimension>${[['factory','按工厂'],['craft','按工艺'],['trend','每日实际完工']].map(([key,label])=>`<option value="${key}" ${dimension===key?'selected':''}>${label}</option>`).join('')}</select><button class="rounded border px-3 py-1 text-sm" data-statistics-action="columns">列设置</button></div>`,tableHtml:`<div data-statistics-table>${table.tableHtml}</div>`,paginationHtml:`<div data-statistics-pagination>${table.paginationHtml}</div>`,overlaysHtml:`<div data-statistics-overlays>${controller.renderColumnSettings()}</div>`})}</div>`
}
function refreshStatistics(){const root=document.querySelector<HTMLElement>('[data-printing-statistics-root]');if(!root)return;const wrapper=document.createElement('div');wrapper.innerHTML=renderCraftPrintingStatisticsPage();root.replaceWith(wrapper.firstElementChild!)}
export function handlePrintingStatisticsEvent(target:HTMLElement):boolean {
 const root=target.closest<HTMLElement>('[data-printing-statistics-root]');if(!root)return false
 if(target.matches('[data-statistics-filter]'))return true
 if(target.matches('[data-statistics-dimension]')){dimension=(target as HTMLSelectElement).value as typeof dimension;state.currentPage=1;refreshStatistics();return true}
 const field=target.closest<HTMLSelectElement>(`[data-${prefix}-field]`),button=target.closest<HTMLElement>(`[data-statistics-action],[data-${prefix}-action]`),action=button?.dataset.statisticsAction||button?.getAttribute(`data-${prefix}-action`)
 if(field?.getAttribute(`data-${prefix}-field`)==='pageSize')controller.setPageSize(Number(field.value))
 else if(action==='query'||action==='reset'){filters={};if(action==='query')root.querySelectorAll<HTMLInputElement>('[data-statistics-filter]').forEach(input=>{if(input.value)filters[input.dataset.statisticsFilter as keyof PrintingStatisticsFilters]=input.value});state.currentPage=1;refreshStatistics();return true}
 else if(action==='columns')state.showColumnSettings=true
 else if(action==='close-column-settings')state.showColumnSettings=false
 else if(action==='sort-column')controller.cycleSort(button?.dataset.columnKey||'')
 else if(action==='prev-page'||action==='next-page')controller.stepPage(action==='next-page'?1:-1)
 else if(action==='restore-column-settings')controller.restorePreferences()
 else if(action==='toggle-column-visibility'||action==='toggle-column-freeze')controller.updateColumnPreference(action,button?.getAttribute(`data-${prefix}-column-key`)||button?.closest(`[data-${prefix}-column-key]`)?.getAttribute(`data-${prefix}-column-key`)||'',target instanceof HTMLInputElement?target.checked:undefined)
 else return false
 controller.refresh({overlays:true});return true
}
