/** 仅供独立验收浏览器注入；不由产品入口导入。真实 IDB 故障/回读证据。 */
import * as repository from '../../src/data/fcs/cutting/cutting-record-repository.ts'
import * as release from '../../src/data/fcs/cut-piece-release.ts'
import * as validity from '../../src/data/fcs/cutting/cut-piece-ticket-validity.ts'
import * as facts from '../../src/data/fcs/cutting/cut-piece-release-facts.ts'
const check=(value:unknown,message:string)=>{if(!value)throw new Error(message)}
const same=(a:unknown,b:unknown,message:string)=>check(JSON.stringify(a)===JSON.stringify(b),message)
const legacyKey='higood-generated-cut-piece-release-v1'
async function run(){
 const results:Array<{name:string;passed:boolean;details?:unknown}>=[]
 const test=async(name:string,fn:()=>Promise<unknown>)=>{const details=await fn();results.push({name,passed:true,details})}
 const initial=await repository.readCuttingRecords()
 check(initial.records.length===0,'验收必须从独立浏览器空资料开始；不得清理用户数据')
 await test('普通读取及静态投影不落盘',async()=>{await release.hydrateCutPieceReleaseRecords(initial);release.listCutPieceReleaseRecords();same(await repository.readCuttingRecords(),initial,'普通读取写了种子')})
 let nonce=0
 const po='po-14671'
 const input=()=>{const summary=release.getCutPieceReleaseSummaryForProductionOrder(po)!;const version=release.listCutPieceReleaseAvailableQtyVersions(po).at(-1)!;return {productionOrderId:po,basisMatrixVersion:summary.latestMatrixVersion,basisTargetVersion:version.basisTargetVersion,releaseQtyByColorSize:{...version.releaseQtyByColorSize,'Black::M':201},riskReason:'验收维持原放行',confirmedBy:'独立验收',confirmedAt:new Date(Date.now()+(++nonce)*1000).toISOString()}}
 await test('事务 complete 才成功，保存仅新决定及必要元数据',async()=>{
  let completed=false;const db=await repository.openCuttingRecordDatabase(),original=db.transaction.bind(db)
  db.transaction=((stores:any,mode:any,...rest:any[])=>{const tx=original(stores,mode,...rest);if(mode==='readwrite')tx.addEventListener('complete',()=>{completed=true});return tx}) as any
  try{const result=await release.saveCutPieceReleaseAvailableQtyAction(input());check(result.ok,result.message);check(completed,'request success 被当成完整成功');const snapshot=await repository.readCuttingRecords();check(snapshot.records.some(r=>r.collection==='cut-piece-release-decision'),'决定未持久保存');check(!snapshot.records.some(r=>r.collection==='cut-piece-release-fact'),'不应整批落盘静态事实');return {revision:snapshot.revision,records:snapshot.records.map(r=>[r.id,r.collection])}}finally{db.transaction=original as any}
 })
 await test('重复保存返回同一决定，刷新重新独立读回',async()=>{const command=input(),a=await release.saveCutPieceReleaseAvailableQtyAction(command),before=await repository.readCuttingRecords(),b=await release.saveCutPieceReleaseAvailableQtyAction(command);same(a,b,'重复操作不同结果');same(await repository.readCuttingRecords(),before,'重复多写');await release.hydrateCutPieceReleaseRecords();same(release.listCutPieceReleaseAvailableQtyVersions(po).at(-1),a.version,'读回决定不一致');check(release.getCutPieceReleaseSummaryForProductionOrder(po)!.latestReleaseVersion===a.version!.releaseVersionNo,'直达读取选了旧V1有效标志')})
 await test('QuotaExceeded 及事务中止均不留下半套事实或虚假成功',async()=>{
  const before=await repository.readCuttingRecords(),oldVersion=release.listCutPieceReleaseAvailableQtyVersions(po).at(-1),db=await repository.openCuttingRecordDatabase(),original=db.transaction.bind(db)
  let writes=0;db.transaction=((stores:any,mode:any,...rest:any[])=>{const tx=original(stores,mode,...rest);if(mode==='readwrite'){const originalStore=tx.objectStore.bind(tx);tx.objectStore=((name:string)=>{const store=originalStore(name);if(name==='records'){const put=store.put.bind(store);store.put=((value:any)=>{writes++;return put(value)}) as any}if(name==='commands'){store.add=(()=>{throw new DOMException('验收写入空间不足','QuotaExceededError')}) as any}return store}) as any}return tx}) as any
  try{const result=await release.saveCutPieceReleaseAvailableQtyAction(input());check(!result.ok,'失败被当成成功');check(result.message.includes('未保存'),'未提示失败');same(await repository.readCuttingRecords(),before,'中止留下部分记录');same(release.listCutPieceReleaseAvailableQtyVersions(po).at(-1),oldVersion,'中止发布了内存决定');return result.message}finally{db.transaction=original as any}
 })
 await test('同版本两个事务仅一个提交，冲突保存不静默覆盖',async()=>{const before=await repository.readCuttingRecords();const results=await Promise.allSettled(['A','B'].map(id=>repository.commitCuttingRecords({revision:before.revision,change:{puts:[{id:`TEST-RACE-${id}`,collection:'test-verification',value:{id}}]},command:{id:`TEST-RACE-${id}`,intent:id,result:id,at:new Date().toISOString()}})));check(results.filter(r=>r.status==='fulfilled').length===1,'同版本双提交');check(results.filter(r=>r.status==='rejected').length===1,'缺少冲突提示');return results.map(r=>r.status==='fulfilled'?r.value:String(r.reason))})
 await test('localStorage 满额时业务仍保存于 IDB；无后备双写',async()=>{const proto=Storage.prototype,original=proto.setItem;proto.setItem=function(){throw new DOMException('验收localStorage满额','QuotaExceededError')};try{const saved=await release.saveCutPieceReleaseAvailableQtyAction(input());check(saved.ok,saved.message);check(localStorage.getItem(legacyKey)===null,'新增业务LS快照');return saved.version?.releaseVersionNo}finally{proto.setItem=original}})
 await test('localStorage 访问被禁时仍用 IDB 保存，不伪造空用户数据',async()=>{const descriptor=Object.getOwnPropertyDescriptor(window,'localStorage')!;Object.defineProperty(window,'localStorage',{configurable:true,get(){throw new DOMException('验收偏好存储被禁','SecurityError')}});try{const saved=await release.saveCutPieceReleaseAvailableQtyAction(input());check(saved.ok,saved.message);return saved.version!.releaseVersionNo}finally{Object.defineProperty(window,'localStorage',descriptor)}})
 await test('整票不可用保存、幂等、独立回读，原票和决定不变',async()=>{const detail=facts.listCutPieceReleaseTicketDetails().find(d=>d.ticketNo.startsWith('FT-DEMO'))!;check(detail,'缺演示票');const old=structuredClone(detail),decision=release.listCutPieceReleaseAvailableQtyVersions(po).at(-1);const command={ticketId:detail.ticketId,valid:false,reason:'整票质量不可用验收',operator:'独立验收'};const result=await validity.saveCutPieceReleaseTicketValidityAction(command);check(result.ok,result.message);const snapshot=await repository.readCuttingRecords();check((await validity.saveCutPieceReleaseTicketValidityAction(command)).ok,'同票重试失败');same(await repository.readCuttingRecords(),snapshot,'重复登记多写');const stale=await validity.saveCutPieceReleaseTicketValidityAction({...command,valid:true,reason:'旧页尝试覆盖',expectedVersion:0});check(!stale.ok && stale.message.includes('重新读取'),'旧页没有提示版本冲突');same(await repository.readCuttingRecords(),snapshot,'旧页覆盖了新登记');await release.hydrateCutPieceReleaseRecords();check(validity.getCutPieceTicketValidity(detail.ticketId)?.valid===false,'整票登记未读回');same(release.listCutPieceReleaseAvailableQtyVersions(po).at(-1),decision,'事实更正改了原决定');check(facts.listCutPieceReleaseTicketDetails().find(d=>d.ticketId===detail.ticketId)!.printedPieceQty===old.printedPieceQty,'改写原票');for(const valid of [true,false]){const saved=await validity.saveCutPieceReleaseTicketValidityAction({...command,valid,reason:valid?'整票复核恢复可用':'整票再次复核不可用'});check(saved.ok,saved.message)}
 const basis=release.getCutPieceReleaseSummaryForProductionOrder(po)!.latestMatrixVersion
 await release.hydrateCutPieceReleaseRecords();check(release.getCutPieceReleaseSummaryForProductionOrder(po)!.latestMatrixVersion===basis,'多次整票登记后刷新丢失矩阵依据')
 const maintained=await release.saveCutPieceReleaseAvailableQtyAction(input());check(maintained.ok,maintained.message);check(maintained.version!.basisMatrixVersion===basis,'维持放行未引用当前矩阵依据')
 return {ticketId:detail.ticketId,revision:(await repository.readCuttingRecords()).revision,basis,maintainedVersion:maintained.version!.releaseVersionNo}})
 await test('备份包含新增逐记录事实，冲突整批撤回不清空',async()=>{const backup=await repository.exportCuttingRecordBackup();check(backup.records.some(r=>r.collection==='cut-piece-ticket-validity'),'备份缺有效性');repository.validateCuttingRecordBackup(backup);const conflict=structuredClone(backup);conflict.records.find(r=>r.collection==='cut-piece-ticket-validity')!.value={invalid:true};const before=await repository.readCuttingRecords();let rejected=false;try{await repository.restoreCuttingRecordBackup(conflict)}catch{rejected=true}check(rejected,'冲突备份覆盖');same(await repository.readCuttingRecords(),before,'冲突恢复改变原数据');return {recordCount:backup.records.length,fileCount:backup.files.length}})
 return {passed:true,results}
}
async function migration(){
 const initial=await repository.readCuttingRecords();check(initial.records.length===0,'迁移在另一独立空浏览器运行')
 await release.hydrateCutPieceReleaseRecords(initial)
 const state=release.captureCutPieceReleaseState(),ids=['po-14672','po-14673']
 const items=ids.map(id=>{const item=structuredClone(state.releaseRepository.get(id)!);return {item:{...item,spreadingAdjustmentKeys:[...item.spreadingAdjustmentKeys]},targets:[...state.targetSnapshots.values()].filter(v=>v.productionOrderId===id),releases:state.releaseVersionRepository.get(id),late:[...state.lateEvents.values()].filter(v=>v.productionOrderId===id)}})
 const raw=JSON.stringify({version:1,items});localStorage.setItem(legacyKey,raw);localStorage.setItem('UNRELATED-TEST','retain')
 check(!(await release.migrateLegacyCutPieceReleaseRecords({otherPagesClosed:false})).ok,'没有关闭旧页确认就迁移')
 let calls=0;const db=await repository.openCuttingRecordDatabase(),original=db.transaction.bind(db)
 db.transaction=((stores:any,mode:any,...rest:any[])=>{if(mode==='readwrite' && ++calls===2)throw new Error('验收第二批中断');return original(stores,mode,...rest)}) as any
 let interrupted;try{interrupted=await release.migrateLegacyCutPieceReleaseRecords({otherPagesClosed:true});check(!interrupted.ok,'中断未显示');check(localStorage.getItem(legacyKey)===raw,'中断删除旧源')}finally{db.transaction=original as any}
 const result=await release.migrateLegacyCutPieceReleaseRecords({otherPagesClosed:true});check(result.ok,result.message);check(localStorage.getItem(legacyKey)===null,'核验后未清理独占键');check(localStorage.getItem('UNRELATED-TEST')==='retain','删了其他模块');const snapshot=await repository.readCuttingRecords();const backup=await repository.exportCuttingRecordBackup();check(backup.commands.filter(c=>c.id.startsWith('CUT-RELEASE-MIGRATION')).length===2,'断点续传重复新增');check(backup.commands.filter(c=>c.id.startsWith('CUT-RELEASE-MIGRATION')).every(c=>!(c.result as any).records && (c.result as any).manifest),'命令重复整包业务数据');for(const id of ids){same(release.listCutPieceReleaseAvailableQtyVersions(id).map(v=>v.releaseQtyByColorSize),state.releaseVersionRepository.get(id)!.map(v=>v.releaseQtyByColorSize),'迁移改了人工决定');check(snapshot.records.some(r=>r.collection==='cut-piece-release-fact' && (r.value as any).productionOrderId===id && (r.value as any).identityKnown===false),'迁移伪造装袋证据')}
 return {passed:true,interrupted,result,revision:snapshot.revision,recordCount:snapshot.records.length,manifestCommands:backup.commands.filter(c=>c.id.startsWith('CUT-RELEASE-MIGRATION')).length}
}
;(window as any).__releaseHarness={run,migration,repository,release,validity,facts}
