export type ProcessAssignmentGranularity = 'ORDER' | 'COLOR' | 'SKU' | 'DETAIL'
export type CraftStageCode = 'PREP' | 'PROD' | 'POST'
export type ProcessDocType = 'DEMAND' | 'TASK' | 'PREPARATION_ORDER'
export type TaskTypeMode = 'PROCESS' | 'CRAFT'
export type ProcessRole = 'EXTERNAL_TASK' | 'PREPARATION_ORDER' | 'INTERNAL_CAPACITY_NODE'
export type CapacityRollupMode = 'SELF' | 'CHILD_NODES' | 'NONE'
export type FactoryMobileExecutionMode = 'FULL_TASK' | 'INTERNAL_RECORD_ONLY' | 'NONE'
export type DetailSplitMode = 'COMPOSITE'
export type DetailSplitDimension = 'PATTERN' | 'MATERIAL_SKU' | 'GARMENT_COLOR' | 'GARMENT_SKU'
export type RuleSource = 'INHERIT_PROCESS' | 'OVERRIDE_CRAFT'
export type SpecialCraftSupportedTargetObject = 'CUT_PIECE' | 'FULL_FABRIC' | 'SEMI_FINISHED_GARMENT' | 'BINDING_STRIP'
export type SpecialCraftTargetObjectLabel = '已裁部位' | '完整面料' | '成衣' | '捆条'
export type ProcessTargetObject = 'CUT_PIECE_PART' | 'FABRIC' | 'ACCESSORY' | 'GARMENT_SEMI' | 'BOM_MATERIAL' | 'BINDING_STRIP'
export type ProcessTargetObjectName = '裁片部位' | '面料' | '辅料' | '成衣' | 'BOM物料' | '捆条'
export type SpecialCraftCategory = 'AUXILIARY' | 'SPECIAL'
export type SpecialCraftCategoryName = '辅助工艺' | '特种工艺'
export type SpecialCraftVisibleFactoryType =
  | 'CENTRAL_SPECIAL'
  | 'SATELLITE_FINISHING'
  | 'CENTRAL_DENIM_WASH'
  | 'CENTRAL_CUTTING'
  | 'CENTRAL_AUX'
export interface ProcessStageDefinition {
  stageCode: CraftStageCode
  stageName: string
  sort: number
  description: string
}

export interface ProcessDefinition {
  processCode: string
  systemProcessCode: string
  processName: string
  stageCode: CraftStageCode
  processRole: ProcessRole
  parentProcessCode?: string
  generatesExternalTask: boolean
  requiresTaskQr: boolean
  requiresHandoverOrder: boolean
  capacityEnabled: boolean
  capacityRollupMode: CapacityRollupMode
  factoryMobileExecutionMode: FactoryMobileExecutionMode
  isActive: boolean
  assignmentGranularity: ProcessAssignmentGranularity
  defaultDocType: ProcessDocType
  taskTypeMode: TaskTypeMode
  detailSplitMode: DetailSplitMode
  detailSplitDimensions: DetailSplitDimension[]
  isSpecialCraftContainer: boolean
  description?: string
  triggerSource?: string
  defaultDocLabel: string
}

export interface ProcessCraftDefinition {
  craftCode: string
  craftName: string
  legacyValue: number
  legacyCraftName: string
  processCode: string
  systemProcessCode: string
  stageCode: CraftStageCode
  processRole: ProcessRole
  parentProcessCode?: string
  generatesExternalTask: boolean
  requiresTaskQr: boolean
  requiresHandoverOrder: boolean
  capacityEnabled: boolean
  capacityRollupMode: CapacityRollupMode
  factoryMobileExecutionMode: FactoryMobileExecutionMode
  isActive: boolean
  assignmentGranularity: ProcessAssignmentGranularity
  ruleSource: RuleSource
  defaultDocType: ProcessDocType
  taskTypeMode: TaskTypeMode
  detailSplitMode: DetailSplitMode
  detailSplitDimensions: DetailSplitDimension[]
  isSpecialCraft: boolean
  targetObject: ProcessTargetObject
  targetObjectName: ProcessTargetObjectName
  supportedTargetObjects: SpecialCraftSupportedTargetObject[]
  supportedTargetObjectLabels: SpecialCraftTargetObjectLabel[]
  visibleFactoryTypes: SpecialCraftVisibleFactoryType[]
  carrySuggestion: string
  remark?: string
}

export interface LegacyCraftMappingDefinition {
  legacyValue: number
  legacyCraftName: string
  craftName: string
  processCode: string
  isSpecialCraft: boolean
  isActive?: boolean
  defaultDocument: string
  ruleSource?: RuleSource
  assignmentGranularity?: ProcessAssignmentGranularity
  detailSplitMode?: DetailSplitMode
  detailSplitDimensions?: DetailSplitDimension[]
  legacy?: boolean
  hiddenInNewDict?: boolean
  remark?: string
}

export interface PreparationProcessDefinition {
  processCode: string
  processName: string
  processStage: CraftStageCode
  processStageName: string
  targetObject: ProcessTargetObject
  targetObjectName: ProcessTargetObjectName
  isAutoGeneratedFromBom: boolean
  bomTriggerField: string
  canGeneratePreparationOrder: boolean
  description: string
}

export type ProcessCraftManagementDomain =
  | 'AUXILIARY_CRAFT_FACTORY'
  | 'SPECIAL_CRAFT_FACTORY'
  | 'CUTTING_FACTORY'

export type ProcessCraftManagementDomainName =
  | '辅助工艺工厂管理'
  | '特种工艺工厂管理'
  | '裁床厂管理'

export interface ModernSpecialCraftDefinition {
  craftCode: string
  craftName: string
  craftCategory: SpecialCraftCategory
  craftCategoryName: SpecialCraftCategoryName
  specialCraftType: SpecialCraftCategory
  specialCraftTypeName: SpecialCraftCategoryName
  managementDomain: ProcessCraftManagementDomain
  managementDomainName: ProcessCraftManagementDomainName
  targetObject: ProcessTargetObject
  targetObjectName: ProcessTargetObjectName
  canSelectInPatternPiece: boolean
  canSelectInBindingArea: boolean
  canTriggerFromMaterial: boolean
  canGenerateSpecialCraftTask: boolean
  description: string
}

export interface CuttingCraftDefinition {
  craftCode: string
  craftName: string
  processStage: CraftStageCode
  processStageName: string
  processGroup: 'CUTTING'
  processGroupName: '裁床工序'
  targetObject: ProcessTargetObject
  targetObjectName: ProcessTargetObjectName
  description: string
}

export type ProcessCraftDictRow = {
  craftCode: string
  craftName: string
  processCode: string
  processName: string
  stageCode: CraftStageCode
  stageName: string
  isActive: boolean
  statusLabel: string
  processRole: ProcessRole
  processRoleLabel: string
  taskScopeLabel: string
  parentProcessCode?: string
  parentProcessName?: string
  generatesExternalTask: boolean
  generatesExternalTaskLabel: string
  requiresTaskQr: boolean
  requiresTaskQrLabel: string
  requiresHandoverOrder: boolean
  requiresHandoverOrderLabel: string
  capacityEnabled: boolean
  capacityEnabledLabel: string
  capacityRollupMode: CapacityRollupMode
  factoryMobileExecutionMode: FactoryMobileExecutionMode
  assignmentGranularity: ProcessAssignmentGranularity
  assignmentGranularityLabel: string
  ruleSource: RuleSource
  ruleSourceLabel: string
  detailSplitMode: DetailSplitMode
  detailSplitModeLabel: string
  detailSplitDimensions: DetailSplitDimension[]
  detailSplitDimensionsText: string
  handoffAdvice: string
  legacyValue: number
  legacyCraftName: string
  isSpecialCraft: boolean
  targetObject: ProcessTargetObject
  targetObjectName: ProcessTargetObjectName
  supportedTargetObjects: SpecialCraftSupportedTargetObject[]
  supportedTargetObjectLabels: SpecialCraftTargetObjectLabel[]
  supportedTargetObjectText: string
  visibleFactoryTypes: SpecialCraftVisibleFactoryType[]
  defaultDocument: string
  defaultDocType: ProcessDocType
  taskTypeMode: TaskTypeMode
  processAssignmentGranularity: ProcessAssignmentGranularity
  processAssignmentGranularityLabel: string
  processDetailSplitMode: DetailSplitMode
  processDetailSplitModeLabel: string
  processDetailSplitDimensions: DetailSplitDimension[]
  processDetailSplitDimensionsText: string
  remark?: string
  processNote?: string
  triggerSource?: string
}

export const PROCESS_ASSIGNMENT_GRANULARITY_LABEL: Record<ProcessAssignmentGranularity, string> = {
  ORDER: '按生产单',
  COLOR: '按颜色',
  SKU: '按SKU',
  DETAIL: '按明细行',
}

export const SPECIAL_CRAFT_TARGET_OBJECT_LABEL: Record<SpecialCraftSupportedTargetObject, SpecialCraftTargetObjectLabel> = {
  CUT_PIECE: '已裁部位',
  FULL_FABRIC: '完整面料',
  SEMI_FINISHED_GARMENT: '成衣',
  BINDING_STRIP: '捆条',
}

export const PROCESS_TARGET_OBJECT_NAME: Record<ProcessTargetObject, ProcessTargetObjectName> = {
  CUT_PIECE_PART: '裁片部位',
  FABRIC: '面料',
  ACCESSORY: '辅料',
  GARMENT_SEMI: '成衣',
  BOM_MATERIAL: 'BOM物料',
  BINDING_STRIP: '捆条',
}

export const SPECIAL_CRAFT_CATEGORY_NAME: Record<SpecialCraftCategory, SpecialCraftCategoryName> = {
  AUXILIARY: '辅助工艺',
  SPECIAL: '特种工艺',
}

export const PROCESS_CRAFT_MANAGEMENT_DOMAIN_NAME: Record<ProcessCraftManagementDomain, ProcessCraftManagementDomainName> = {
  AUXILIARY_CRAFT_FACTORY: '辅助工艺工厂管理',
  SPECIAL_CRAFT_FACTORY: '特种工艺工厂管理',
  CUTTING_FACTORY: '裁床厂管理',
}

const AUXILIARY_CRAFT_FACTORY_CRAFT_NAMES = new Set([
  '绣花',
  '打条',
  '压褶',
  '打揽',
  '烫画',
  '直喷',
  '贝壳绣',
  '曲牙绣',
  '一字贝绣花',
  '盘扣',
  '花朵',
  '打褶',
  '烫钻',
])

const SPECIAL_CRAFT_FACTORY_CRAFT_NAMES = new Set([
  '模板工序',
  '模板机',
  '激光开袋',
  '特种车缝（花样机）',
  '特种车缝',
  '橡筋定长切割',
  '激光切',
])

const CUTTING_FACTORY_CRAFT_NAMES = new Set(['捆条'])

const SPECIAL_CRAFT_SUPPORTED_TARGET_OBJECTS_BY_LEGACY_VALUE: Record<number, SpecialCraftSupportedTargetObject[]> = {
  8: ['CUT_PIECE'],
  32: ['CUT_PIECE'],
  64: ['CUT_PIECE'],
  128: ['FULL_FABRIC'],
  8192: ['CUT_PIECE', 'SEMI_FINISHED_GARMENT'],
  16384: ['CUT_PIECE', 'SEMI_FINISHED_GARMENT'],
  131072: ['CUT_PIECE'],
  3100001: ['BINDING_STRIP'],
  3100002: ['CUT_PIECE'],
  3100003: ['CUT_PIECE'],
  3100004: ['CUT_PIECE'],
}

const SPECIAL_CRAFT_VISIBLE_FACTORY_TYPES_BY_LEGACY_VALUE: Record<number, SpecialCraftVisibleFactoryType[]> = {
  8: ['CENTRAL_SPECIAL', 'SATELLITE_FINISHING'],
  32: ['CENTRAL_SPECIAL', 'SATELLITE_FINISHING'],
  64: ['CENTRAL_SPECIAL', 'SATELLITE_FINISHING'],
  128: ['CENTRAL_DENIM_WASH'],
  8192: ['CENTRAL_SPECIAL', 'SATELLITE_FINISHING'],
  16384: ['CENTRAL_SPECIAL', 'SATELLITE_FINISHING'],
  131072: ['CENTRAL_SPECIAL', 'SATELLITE_FINISHING'],
  3100001: ['CENTRAL_AUX'],
  3100002: ['CENTRAL_AUX'],
  3100003: ['CENTRAL_AUX'],
  3100004: ['CENTRAL_AUX'],
}

export const preparationProcessDefinitions: PreparationProcessDefinition[] = [
  {
    processCode: 'PREP_SHRINKING',
    processName: '缩水',
    processStage: 'PREP',
    processStageName: '准备阶段',
    targetObject: 'FABRIC',
    targetObjectName: '面料',
    isAutoGeneratedFromBom: true,
    bomTriggerField: 'shrinkRequirement',
    canGeneratePreparationOrder: false,
    description: '历史准备工序，当前未开放加工单和 PDA 执行闭环。',
  },
  {
    processCode: 'PREP_WASHING',
    processName: '洗水',
    processStage: 'PREP',
    processStageName: '准备阶段',
    targetObject: 'FABRIC',
    targetObjectName: '面料',
    isAutoGeneratedFromBom: true,
    bomTriggerField: 'washRequirement',
    canGeneratePreparationOrder: false,
    description: '历史准备工序，当前未开放加工单和 PDA 执行闭环。',
  },
]

export const modernSpecialCraftDefinitions: ModernSpecialCraftDefinition[] = [
  {
    craftCode: 'AUX_EMBROIDERY',
    craftName: '绣花',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，可在纸样裁片部位上维护。',
  },
  {
    craftCode: 'AUX_STRIP',
    craftName: '打条',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，随裁片部位生成特殊工艺任务。',
  },
  {
    craftCode: 'AUX_PLEATING',
    craftName: '压褶',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，按裁片部位维护。',
  },
  {
    craftCode: 'AUX_DALAN',
    craftName: '打揽',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，按菲票流转。',
  },
  {
    craftCode: 'AUX_HEAT_TRANSFER',
    craftName: '烫画',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'GARMENT_SEMI',
    targetObjectName: '成衣',
    canSelectInPatternPiece: false,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '纯色 T-shirt 成衣烫画，按 SKU 件数执行。',
  },
  {
    craftCode: 'AUX_DIRECT_PRINT',
    craftName: '直喷',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，按裁片部位执行。',
  },
  {
    craftCode: 'AUX_SHELL_EMBROIDERY',
    craftName: '贝壳绣',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，归入辅助工艺管理。',
  },
  {
    craftCode: 'AUX_CURVED_TEETH_EMBROIDERY',
    craftName: '曲牙绣',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，按裁片部位维护。',
  },
  {
    craftCode: 'AUX_STRAIGHT_SHELL_EMBROIDERY',
    craftName: '一字贝绣花',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级辅助工艺，按裁片部位维护。',
  },
  {
    craftCode: 'AUX_BINDING_STRIP',
    craftName: '捆条',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'CUTTING_FACTORY',
    managementDomainName: '裁床厂管理',
    targetObject: 'FABRIC',
    targetObjectName: '面料',
    canSelectInPatternPiece: false,
    canSelectInBindingArea: true,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '捆条跟随纸样维护，不在单个裁片实例特殊工艺列中选择。',
  },
  {
    craftCode: 'AUX_BUTTON_LOOP',
    craftName: '盘扣',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'BINDING_STRIP',
    targetObjectName: '捆条',
    canSelectInPatternPiece: false,
    canSelectInBindingArea: true,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '捆条菲票投入、盘扣成品按个产出的辅助工艺，仅在纸样包捆条行维护。',
  },
  {
    craftCode: 'AUX_FLOWER_MAKING',
    craftName: '花朵',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级花朵辅助工艺，沿用裁片菲票加工闭环。',
  },
  {
    craftCode: 'AUX_GATHERING',
    craftName: '打褶',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级打褶辅助工艺，与压褶保持独立工艺身份。',
  },
  {
    craftCode: 'AUX_HOTFIX_RHINESTONE',
    craftName: '烫钻',
    craftCategory: 'AUXILIARY',
    craftCategoryName: '辅助工艺',
    specialCraftType: 'AUXILIARY',
    specialCraftTypeName: '辅助工艺',
    managementDomain: 'AUXILIARY_CRAFT_FACTORY',
    managementDomainName: '辅助工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级烫钻辅助工艺，沿用裁片菲票加工闭环。',
  },
  {
    craftCode: 'SPECIAL_TEMPLATE_PROCESS',
    craftName: '模板工序',
    craftCategory: 'SPECIAL',
    craftCategoryName: '特种工艺',
    specialCraftType: 'SPECIAL',
    specialCraftTypeName: '特种工艺',
    managementDomain: 'SPECIAL_CRAFT_FACTORY',
    managementDomainName: '特种工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级特种工艺，适用于模板辅助加工。',
  },
  {
    craftCode: 'SPECIAL_LASER_POCKET',
    craftName: '激光开袋',
    craftCategory: 'SPECIAL',
    craftCategoryName: '特种工艺',
    specialCraftType: 'SPECIAL',
    specialCraftTypeName: '特种工艺',
    managementDomain: 'SPECIAL_CRAFT_FACTORY',
    managementDomainName: '特种工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级特种工艺，适用于激光定位开袋。',
  },
  {
    craftCode: 'SPECIAL_PATTERN_MACHINE_SEWING',
    craftName: '特种车缝（花样机）',
    craftCategory: 'SPECIAL',
    craftCategoryName: '特种工艺',
    specialCraftType: 'SPECIAL',
    specialCraftTypeName: '特种工艺',
    managementDomain: 'SPECIAL_CRAFT_FACTORY',
    managementDomainName: '特种工艺工厂管理',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    canSelectInPatternPiece: true,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: false,
    canGenerateSpecialCraftTask: true,
    description: '裁片部位级特种工艺，适用于花样机加工。',
  },
  {
    craftCode: 'SPECIAL_ELASTIC_FIXED_LENGTH_CUTTING',
    craftName: '橡筋定长切割',
    craftCategory: 'SPECIAL',
    craftCategoryName: '特种工艺',
    specialCraftType: 'SPECIAL',
    specialCraftTypeName: '特种工艺',
    managementDomain: 'SPECIAL_CRAFT_FACTORY',
    managementDomainName: '特种工艺工厂管理',
    targetObject: 'ACCESSORY',
    targetObjectName: '辅料',
    canSelectInPatternPiece: false,
    canSelectInBindingArea: false,
    canTriggerFromMaterial: true,
    canGenerateSpecialCraftTask: true,
    description: '橡筋定长切割针对辅料，不在裁片明细逐片特殊工艺中选择。',
  },
]

export const cuttingCraftDefinitions: CuttingCraftDefinition[] = [
  {
    craftCode: 'CUTTING_NORMAL',
    craftName: '普通裁',
    processStage: 'PROD',
    processStageName: '生产阶段',
    processGroup: 'CUTTING',
    processGroupName: '裁床工序',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    description: '常规裁床裁剪工艺。',
  },
  {
    craftCode: 'CUTTING_LASER_POSITIONING',
    craftName: '激光定位裁',
    processStage: 'PROD',
    processStageName: '生产阶段',
    processGroup: 'CUTTING',
    processGroupName: '裁床工序',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    description: '按激光定位要求进行裁剪。',
  },
  {
    craftCode: 'CUTTING_DIRECTIONAL',
    craftName: '定向裁',
    processStage: 'PROD',
    processStageName: '生产阶段',
    processGroup: 'CUTTING',
    processGroupName: '裁床工序',
    targetObject: 'CUT_PIECE_PART',
    targetObjectName: '裁片部位',
    description: '按方向、纹路或图案要求定向裁剪。',
  },
]

function resolveSpecialCraftSupportedTargetObjects(
  item: Pick<LegacyCraftMappingDefinition, 'legacyValue' | 'isSpecialCraft'>,
): SpecialCraftSupportedTargetObject[] {
  if (!item.isSpecialCraft) return []
  return [...(SPECIAL_CRAFT_SUPPORTED_TARGET_OBJECTS_BY_LEGACY_VALUE[item.legacyValue] ?? ['CUT_PIECE'])]
}

function resolveSpecialCraftVisibleFactoryTypes(
  item: Pick<LegacyCraftMappingDefinition, 'legacyValue' | 'isSpecialCraft'>,
): SpecialCraftVisibleFactoryType[] {
  if (!item.isSpecialCraft) return []
  return [...(SPECIAL_CRAFT_VISIBLE_FACTORY_TYPES_BY_LEGACY_VALUE[item.legacyValue] ?? ['CENTRAL_SPECIAL'])]
}

export function getSpecialCraftTargetObjectLabel(
  targetObject: SpecialCraftSupportedTargetObject,
): SpecialCraftTargetObjectLabel {
  return SPECIAL_CRAFT_TARGET_OBJECT_LABEL[targetObject]
}

export function getSpecialCraftSupportedTargetObjectLabels(
  targetObjects: SpecialCraftSupportedTargetObject[],
): SpecialCraftTargetObjectLabel[] {
  return targetObjects.map((item) => SPECIAL_CRAFT_TARGET_OBJECT_LABEL[item])
}

export function isSpecialCraftTargetObjectLabel(value: string | undefined): value is SpecialCraftTargetObjectLabel {
  return value === '已裁部位' || value === '完整面料' || value === '成衣' || value === '捆条'
}

export function normalizeSpecialCraftTargetObjectLabel(
  value: string | undefined,
): SpecialCraftTargetObjectLabel | '' {
  if (value === '裁片') return '已裁部位'
  if (value === '面料') return '完整面料'
  if (value === '半成品' || value === '成衣半成品' || value === '整件成衣') return '成衣'
  if (value === 'BINDING_STRIP') return '捆条'
  return isSpecialCraftTargetObjectLabel(value) ? value : ''
}

export const PROCESS_ROLE_LABEL: Record<ProcessRole, string> = {
  EXTERNAL_TASK: '对外任务',
  PREPARATION_ORDER: '生产准备加工单',
  INTERNAL_CAPACITY_NODE: '产能节点',
}

export const DETAIL_SPLIT_MODE_LABEL: Record<DetailSplitMode, string> = {
  COMPOSITE: '组合维度',
}

export const DETAIL_SPLIT_DIMENSION_LABEL: Record<DetailSplitDimension, string> = {
  PATTERN: '纸样',
  MATERIAL_SKU: '物料SKU',
  GARMENT_COLOR: '成衣颜色',
  GARMENT_SKU: '成衣SKU',
}

export const RULE_SOURCE_LABEL: Record<RuleSource, string> = {
  INHERIT_PROCESS: '继承工序规则',
  OVERRIDE_CRAFT: '工艺覆盖规则',
}

export const PROCESS_DOC_TYPE_LABEL: Record<ProcessDocType, string> = {
  DEMAND: '需求单',
  TASK: '任务单',
  PREPARATION_ORDER: '加工单',
}

function toYesNoLabel(value: boolean): string {
  return value ? '是' : '否'
}

function toStatusLabel(isActive: boolean): string {
  return isActive ? '可用' : '历史停用'
}

export const TASK_TYPE_MODE_LABEL: Record<TaskTypeMode, string> = {
  PROCESS: '按工序',
  CRAFT: '按工艺',
}

const PROCESS_SYSTEM_CODE_MAP: Record<string, string> = {
  PRINT: 'PROC_PRINT',
  WATER_SOLUBLE: 'PROC_WATER_SOLUBLE',
  DYE: 'PROC_DYE',
  CUT_PANEL: 'PROC_CUT',
  EMBROIDERY: 'PROC_EMBROIDER',
  PLEATING: 'PROC_PLEAT',
  WOOL: 'PROC_WOOL',
  SEW: 'PROC_SEW',
  SPECIAL_CRAFT: 'PROC_SPECIAL_CRAFT',
  SHRINKING: 'PROC_SHRINK',
  WASHING: 'PROC_WASH',
  BUTTONHOLE: 'PROC_BUTTONHOLE',
  BUTTON_ATTACH: 'PROC_BUTTON_ATTACH',
  IRONING: 'PROC_IRON',
  PACKAGING: 'PROC_PACK',
  IRON_PACK: 'PROC_IRON_PACK',
}

const CRAFT_SYSTEM_CODE_BY_LEGACY_VALUE: Record<number, string> = {
  1: 'PROC_POSITION_CUT',
  2: 'PROC_EMBROIDER',
  4: 'PROC_PLEAT',
  8: 'PROC_DALAN',
  16: 'PROC_DIRECTION_CUT',
  32: 'PROC_DATIAO',
  64: 'PROC_LASER_CUT',
  128: 'PROC_WASH',
  256: 'PROC_HAND_BUTTON',
  512: 'PROC_MACHINE_BUTTON',
  1024: 'PROC_FOUR_CLAW',
  4096: 'PROC_SHRINK',
  8192: 'PROC_TANHUA',
  16384: 'PROC_DIRECT_PRINT',
  32768: 'PROC_CLOTH_BUTTON',
  131072: 'PROC_KUNTIAO',
  262144: 'PROC_QUYA',
  262145: 'PROC_BASE_CONNECT',
  524288: 'PROC_BUTTONHOLE',
  1048576: 'PROC_SHELL_EMBROIDER',
  2000001: 'PROC_PRINT',
  2000002: 'PROC_PRINT',
  2000003: 'PROC_DYE',
  2000004: 'PROC_DYE',
  2000005: 'PROC_IRON',
  2000006: 'PROC_PACK',
  2000007: 'PROC_WOOL',
  2000008: 'PROC_WOOL',
  2000009: 'PROC_WATER_SOLUBLE',
}

const CARRY_SUGGESTION_BY_PROCESS_CODE: Record<string, string> = {
  PRINT: '印花厂优先',
  WATER_SOLUBLE: '染色厂优先',
  DYE: '染色厂优先',
  CUT_PANEL: '裁片厂优先',
  EMBROIDERY: '绣花厂优先',
  PLEATING: '压褶工艺厂优先',
  WOOL: '周哥毛织厂优先',
  SEW: '车缝厂优先',
  SPECIAL_CRAFT: '特殊工艺厂优先',
  SHRINKING: '缩水工艺厂优先',
  WASHING: '洗水工艺厂优先',
  BUTTONHOLE: '后道产能优先',
  BUTTON_ATTACH: '后道产能优先',
  IRONING: '后道产能优先',
  PACKAGING: '后道产能优先',
}

type ProcessDefaultRule = {
  assignmentGranularity: ProcessAssignmentGranularity
  detailSplitMode: DetailSplitMode
  detailSplitDimensions: DetailSplitDimension[]
}

const PROCESS_DEFAULT_RULES: Record<string, ProcessDefaultRule> = {
  PRINT: {
    assignmentGranularity: 'COLOR',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
  },
  WATER_SOLUBLE: {
    assignmentGranularity: 'ORDER',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['MATERIAL_SKU'],
  },
  DYE: {
    assignmentGranularity: 'COLOR',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_COLOR', 'MATERIAL_SKU'],
  },
  CUT_PANEL: {
    assignmentGranularity: 'ORDER',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_COLOR', 'PATTERN', 'MATERIAL_SKU'],
  },
  EMBROIDERY: {
    assignmentGranularity: 'ORDER',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
  },
  PLEATING: {
    assignmentGranularity: 'ORDER',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
  },
  WOOL: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  SEW: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  SPECIAL_CRAFT: {
    assignmentGranularity: 'ORDER',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
  },
  SHRINKING: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  WASHING: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  BUTTONHOLE: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  BUTTON_ATTACH: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  IRONING: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  PACKAGING: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
  IRON_PACK: {
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
  },
}

function toProcessDocType(documentLabel: string): ProcessDocType {
  if (documentLabel === '需求单') return 'DEMAND'
  if (documentLabel === '加工单') return 'PREPARATION_ORDER'
  return 'TASK'
}

function toTaskTypeMode(isSpecialCraft: boolean): TaskTypeMode {
  return isSpecialCraft ? 'CRAFT' : 'PROCESS'
}

function toCraftCode(legacyValue: number): string {
  return `CRAFT_${String(legacyValue).padStart(6, '0')}`
}

export const processStageDefinitions: ProcessStageDefinition[] = [
  {
    stageCode: 'PREP',
    stageName: '准备阶段',
    sort: 10,
    description: '印花、水溶、染色、缩水、洗水等产前处理阶段',
  },
  {
    stageCode: 'PROD',
    stageName: '生产阶段',
    sort: 20,
    description: '裁片、绣花、压褶、车缝、特殊工艺等主体生产阶段',
  },
  {
    stageCode: 'POST',
    stageName: '后道阶段',
    sort: 30,
    description: '成衣到货确认后执行开扣眼、装扣子、烫包等实际工序；质检和复检为流程节点，不属于工序字典',
  },
]

const processDefinitionSeeds: Array<
  Omit<
    ProcessDefinition,
    | 'systemProcessCode'
    | 'assignmentGranularity'
    | 'detailSplitMode'
    | 'detailSplitDimensions'
    | 'defaultDocType'
    | 'taskTypeMode'
    | 'isSpecialCraftContainer'
    | 'defaultDocLabel'
  > & {
    defaultDocument: string
  }
> = [
  {
    processCode: 'PRINT',
    processName: '印花',
    stageCode: 'PREP',
    processRole: 'PREPARATION_ORDER',
    generatesExternalTask: false,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '加工单',
    description: '由BOM上的印花要求触发',
    triggerSource: 'BOM上存在印花要求',
  },
  {
    processCode: 'WATER_SOLUBLE',
    processName: '水溶',
    stageCode: 'PREP',
    processRole: 'PREPARATION_ORDER',
    generatesExternalTask: false,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '加工单',
    description: '由 BOM 物料上的水溶要求触发',
    triggerSource: 'BOM 物料存在水溶要求',
  },
  {
    processCode: 'DYE',
    processName: '染色',
    stageCode: 'PREP',
    processRole: 'PREPARATION_ORDER',
    generatesExternalTask: false,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '加工单',
    description: '由BOM上的染色要求触发',
    triggerSource: 'BOM上存在染色要求',
  },
  {
    processCode: 'SHRINKING',
    processName: '缩水',
    stageCode: 'PREP',
    processRole: 'PREPARATION_ORDER',
    generatesExternalTask: false,
    requiresTaskQr: false,
    requiresHandoverOrder: false,
    capacityEnabled: false,
    capacityRollupMode: 'NONE',
    factoryMobileExecutionMode: 'NONE',
    isActive: false,
    defaultDocument: '加工单',
    description: '历史准备工序，当前未开放加工单和 PDA 执行闭环。',
  },
  {
    processCode: 'WASHING',
    processName: '洗水',
    stageCode: 'PREP',
    processRole: 'PREPARATION_ORDER',
    generatesExternalTask: false,
    requiresTaskQr: false,
    requiresHandoverOrder: false,
    capacityEnabled: false,
    capacityRollupMode: 'NONE',
    factoryMobileExecutionMode: 'NONE',
    isActive: false,
    defaultDocument: '加工单',
    description: '历史准备工序，当前未开放加工单和 PDA 执行闭环。',
  },
  {
    processCode: 'CUT_PANEL',
    processName: '裁片',
    stageCode: 'PROD',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
  },
  {
    processCode: 'EMBROIDERY',
    processName: '绣花',
    stageCode: 'PROD',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
  },
  {
    processCode: 'PLEATING',
    processName: '压褶',
    stageCode: 'PROD',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
  },
  {
    processCode: 'WOOL',
    processName: '毛织',
    stageCode: 'PROD',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
    description: '周哥毛织厂自有毛织加工，支持整件毛织和部位毛织。',
  },
  {
    processCode: 'SEW',
    processName: '车缝',
    stageCode: 'PROD',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
  },
  {
    processCode: 'SPECIAL_CRAFT',
    processName: '特殊工艺',
    stageCode: 'PROD',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
    description: '用于打揽、打条、捆条、激光切、烫画、直喷等',
  },
  {
    processCode: 'BUTTONHOLE',
    processName: '开扣眼',
    stageCode: 'POST',
    processRole: 'INTERNAL_CAPACITY_NODE',
    generatesExternalTask: false,
    requiresTaskQr: false,
    requiresHandoverOrder: false,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'NONE',
    isActive: true,
    defaultDocument: '任务单',
  },
  {
    processCode: 'BUTTON_ATTACH',
    processName: '装扣子',
    stageCode: 'POST',
    processRole: 'INTERNAL_CAPACITY_NODE',
    generatesExternalTask: false,
    requiresTaskQr: false,
    requiresHandoverOrder: false,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'NONE',
    isActive: true,
    defaultDocument: '任务单',
  },
  {
    processCode: 'IRON_PACK',
    processName: '烫包',
    stageCode: 'POST',
    processRole: 'EXTERNAL_TASK',
    generatesExternalTask: true,
    requiresTaskQr: true,
    requiresHandoverOrder: true,
    capacityEnabled: true,
    capacityRollupMode: 'SELF',
    factoryMobileExecutionMode: 'FULL_TASK',
    isActive: true,
    defaultDocument: '任务单',
    description: '合并原熨烫与包装的当前业务口径；历史 IRONING、PACKAGING 仅通过兼容映射归一到烫包。',
  },
]

function resolveProcessGranularity(processCode: string): ProcessAssignmentGranularity {
  if (processCode === 'PRINT' || processCode === 'DYE') return 'COLOR'
  if (
    processCode === 'SEW'
    || processCode === 'WOOL'
    || processCode === 'SHRINKING'
    || processCode === 'BUTTONHOLE'
    || processCode === 'BUTTON_ATTACH'
    || processCode === 'IRON_PACK'
    || processCode === 'IRONING'
    || processCode === 'PACKAGING'
  ) return 'SKU'
  return 'ORDER'
}

function resolveProcessDefaultRule(processCode: string): ProcessDefaultRule {
  const configured = PROCESS_DEFAULT_RULES[processCode]
  if (configured) return configured

  const assignmentGranularity = resolveProcessGranularity(processCode)
  if (assignmentGranularity === 'SKU') {
    return {
      assignmentGranularity,
      detailSplitMode: 'COMPOSITE',
      detailSplitDimensions: ['GARMENT_SKU'],
    }
  }
  if (assignmentGranularity === 'COLOR') {
    return {
      assignmentGranularity,
      detailSplitMode: 'COMPOSITE',
      detailSplitDimensions: ['GARMENT_COLOR', 'MATERIAL_SKU'],
    }
  }
  return {
    assignmentGranularity,
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
  }
}

function formatDetailSplitDimensions(dimensions: DetailSplitDimension[]): string {
  if (dimensions.length === 0) return '-'
  return dimensions.map((dimension) => DETAIL_SPLIT_DIMENSION_LABEL[dimension]).join(' + ')
}

export const processDefinitions: ProcessDefinition[] = processDefinitionSeeds.map((seed) => {
  const defaultDocType = toProcessDocType(seed.defaultDocument)
  const isSpecialCraftContainer = seed.processCode === 'SPECIAL_CRAFT'
  const defaultRule = resolveProcessDefaultRule(seed.processCode)
  return {
    processCode: seed.processCode,
    systemProcessCode: PROCESS_SYSTEM_CODE_MAP[seed.processCode] ?? `PROC_${seed.processCode}`,
    processName: seed.processName,
    stageCode: seed.stageCode,
    processRole: seed.processRole,
    parentProcessCode: seed.parentProcessCode,
    generatesExternalTask: seed.generatesExternalTask,
    requiresTaskQr: seed.requiresTaskQr,
    requiresHandoverOrder: seed.requiresHandoverOrder,
    capacityEnabled: seed.capacityEnabled,
    capacityRollupMode: seed.capacityRollupMode,
    factoryMobileExecutionMode: seed.factoryMobileExecutionMode,
    isActive: seed.isActive,
    assignmentGranularity: defaultRule.assignmentGranularity,
    detailSplitMode: defaultRule.detailSplitMode,
    detailSplitDimensions: [...defaultRule.detailSplitDimensions],
    defaultDocType,
    taskTypeMode: isSpecialCraftContainer ? 'CRAFT' : 'PROCESS',
    isSpecialCraftContainer,
    description: seed.description,
    triggerSource: seed.triggerSource,
    defaultDocLabel: PROCESS_DOC_TYPE_LABEL[defaultDocType],
  }
})

export const legacyProcessCraftMappings: LegacyCraftMappingDefinition[] = [
  { legacyValue: 1, legacyCraftName: '定位裁', craftName: '定位裁', processCode: 'CUT_PANEL', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 2, legacyCraftName: '绣花', craftName: '绣花', processCode: 'EMBROIDERY', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 4, legacyCraftName: '压褶', craftName: '压褶', processCode: 'PLEATING', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 8, legacyCraftName: '打揽', craftName: '打揽', processCode: 'SPECIAL_CRAFT', isSpecialCraft: true, defaultDocument: '任务单', remark: '已明确按特殊工艺加工单管理' },
  { legacyValue: 16, legacyCraftName: '定向裁', craftName: '定向裁', processCode: 'CUT_PANEL', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 32, legacyCraftName: '打条', craftName: '打条', processCode: 'SPECIAL_CRAFT', isSpecialCraft: true, defaultDocument: '任务单', remark: '已明确按特殊工艺加工单管理' },
  { legacyValue: 64, legacyCraftName: '激光切', craftName: '激光切', processCode: 'SPECIAL_CRAFT', isSpecialCraft: true, defaultDocument: '任务单', remark: '已明确按特殊工艺加工单管理' },
  { legacyValue: 128, legacyCraftName: '洗水', craftName: '洗水', processCode: 'WASHING', isSpecialCraft: false, isActive: false, defaultDocument: '加工单', legacy: true, hiddenInNewDict: true, remark: '仅保留历史兼容映射；当前未开放加工单和 PDA 执行闭环' },
  { legacyValue: 256, legacyCraftName: '手缝扣', craftName: '手缝扣', processCode: 'BUTTON_ATTACH', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 512, legacyCraftName: '机打扣', craftName: '机打扣', processCode: 'BUTTON_ATTACH', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 1024, legacyCraftName: '四爪扣', craftName: '四爪扣', processCode: 'BUTTON_ATTACH', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 4096, legacyCraftName: '缩水', craftName: '缩水', processCode: 'SHRINKING', isSpecialCraft: false, isActive: false, defaultDocument: '加工单', legacy: true, hiddenInNewDict: true, remark: '仅保留历史兼容映射；当前未开放加工单和 PDA 执行闭环' },
  { legacyValue: 8192, legacyCraftName: '烫画', craftName: '烫画', processCode: 'SPECIAL_CRAFT', isSpecialCraft: true, defaultDocument: '任务单', remark: '通常用于纯色T-shirt，已明确按特殊工艺加工单管理' },
  { legacyValue: 16384, legacyCraftName: '直喷', craftName: '直喷', processCode: 'SPECIAL_CRAFT', isSpecialCraft: true, defaultDocument: '任务单', remark: '通常用于纯色T-shirt，已明确按特殊工艺加工单管理' },
  { legacyValue: 32768, legacyCraftName: '布包扣', craftName: '布包扣', processCode: 'BUTTON_ATTACH', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 131072, legacyCraftName: '捆条', craftName: '捆条', processCode: 'SPECIAL_CRAFT', isSpecialCraft: true, defaultDocument: '任务单', remark: '已明确按特殊工艺加工单管理' },
  { legacyValue: 262144, legacyCraftName: '曲牙', craftName: '曲牙', processCode: 'SEW', isSpecialCraft: false, defaultDocument: '任务单', remark: '当前先按车缝归类' },
  { legacyValue: 262145, legacyCraftName: '基础连接', craftName: '基础连接', processCode: 'SEW', isSpecialCraft: false, defaultDocument: '任务单', remark: '当前按普通车缝基线归类' },
  { legacyValue: 524288, legacyCraftName: '开扣眼', craftName: '开扣眼', processCode: 'BUTTONHOLE', isSpecialCraft: false, defaultDocument: '任务单' },
  { legacyValue: 1048576, legacyCraftName: '贝壳绣', craftName: '贝壳绣', processCode: 'EMBROIDERY', isSpecialCraft: false, defaultDocument: '任务单', remark: '当前先按绣花归类' },
]

const supplementalProcessCraftMappings: LegacyCraftMappingDefinition[] = [
  { legacyValue: 2000001, legacyCraftName: '丝网印', craftName: '丝网印', processCode: 'PRINT', isSpecialCraft: false, defaultDocument: '加工单' },
  { legacyValue: 2000002, legacyCraftName: '数码印', craftName: '数码印', processCode: 'PRINT', isSpecialCraft: false, defaultDocument: '加工单' },
  { legacyValue: 2000003, legacyCraftName: '匹染', craftName: '匹染', processCode: 'DYE', isSpecialCraft: false, defaultDocument: '加工单' },
  { legacyValue: 2000004, legacyCraftName: '色织', craftName: '色织', processCode: 'DYE', isSpecialCraft: false, defaultDocument: '加工单' },
  { legacyValue: 2000005, legacyCraftName: '熨烫', craftName: '烫包', processCode: 'IRON_PACK', isSpecialCraft: false, isActive: false, defaultDocument: '任务单', remark: '历史名称，仅用于归一到烫包' },
  { legacyValue: 2000006, legacyCraftName: '包装', craftName: '烫包', processCode: 'IRON_PACK', isSpecialCraft: false, isActive: false, defaultDocument: '任务单', remark: '历史名称，仅用于归一到烫包' },
  { legacyValue: 2000010, legacyCraftName: '烫包', craftName: '烫包', processCode: 'IRON_PACK', isSpecialCraft: false, isActive: true, defaultDocument: '任务单' },
  {
    legacyValue: 2000007,
    legacyCraftName: '整件毛织',
    craftName: '整件毛织',
    processCode: 'WOOL',
    isSpecialCraft: false,
    isActive: true,
    defaultDocument: '任务单',
    ruleSource: 'OVERRIDE_CRAFT',
    assignmentGranularity: 'SKU',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['GARMENT_SKU'],
    remark: '整件毛织加工后对象为成衣 SKU，完成后交既定后道工厂。',
  },
  {
    legacyValue: 2000008,
    legacyCraftName: '部位毛织',
    craftName: '部位毛织',
    processCode: 'WOOL',
    isSpecialCraft: false,
    isActive: true,
    defaultDocument: '任务单',
    ruleSource: 'OVERRIDE_CRAFT',
    assignmentGranularity: 'DETAIL',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: ['PATTERN', 'GARMENT_SKU'],
    remark: '部位毛织加工后对象为毛织部位 SKU，完成后交裁床待交出仓。',
  },
  {
    legacyValue: 2000009,
    legacyCraftName: '水溶',
    craftName: '水溶',
    processCode: 'WATER_SOLUBLE',
    isSpecialCraft: false,
    isActive: true,
    defaultDocument: '加工单',
  },
]

const MODERN_SPECIAL_CRAFT_LEGACY_VALUE_BY_NAME: Record<string, number> = {
  绣花: 3000001,
  压褶: 3000002,
  贝壳绣: 3000003,
  曲牙绣: 3000004,
  一字贝绣花: 3000005,
  模板工序: 3000006,
  激光开袋: 3000007,
  '特种车缝（花样机）': 3000008,
  橡筋定长切割: 3000009,
  盘扣: 3100001,
  花朵: 3100002,
  打褶: 3100003,
  烫钻: 3100004,
}

const modernSpecialCraftProcessMappings: LegacyCraftMappingDefinition[] = modernSpecialCraftDefinitions
  .filter(
    (craft) =>
      !legacyProcessCraftMappings.some(
        (item) => item.processCode === 'SPECIAL_CRAFT' && item.craftName === craft.craftName,
      ),
  )
  .map((craft) => ({
    legacyValue: MODERN_SPECIAL_CRAFT_LEGACY_VALUE_BY_NAME[craft.craftName],
    legacyCraftName: craft.craftName,
    craftName: craft.craftName,
    processCode: 'SPECIAL_CRAFT',
    isSpecialCraft: true,
    defaultDocument: '任务单',
    remark: `${craft.craftCategoryName}，适用对象：${craft.targetObjectName}`,
  }))

const processDefinitionByCode = new Map(processDefinitions.map((item) => [item.processCode, item]))
const processDefinitionBySystemCode = new Map(processDefinitions.map((item) => [item.systemProcessCode, item]))
const stageDefinitionByCode = new Map(processStageDefinitions.map((item) => [item.stageCode, item]))

function resolveProcessCraftManagementDomain(
  item: Pick<LegacyCraftMappingDefinition, 'craftName' | 'processCode'>,
): { managementDomain?: ProcessCraftManagementDomain; managementDomainName?: ProcessCraftManagementDomainName } {
  const modernSpecialCraft = modernSpecialCraftDefinitions.find((craft) => craft.craftName === item.craftName)
  if (modernSpecialCraft) {
    return {
      managementDomain: modernSpecialCraft.managementDomain,
      managementDomainName: modernSpecialCraft.managementDomainName,
    }
  }

  if (CUTTING_FACTORY_CRAFT_NAMES.has(item.craftName)) {
    return {
      managementDomain: 'CUTTING_FACTORY',
      managementDomainName: PROCESS_CRAFT_MANAGEMENT_DOMAIN_NAME.CUTTING_FACTORY,
    }
  }

  if (AUXILIARY_CRAFT_FACTORY_CRAFT_NAMES.has(item.craftName)) {
    return {
      managementDomain: 'AUXILIARY_CRAFT_FACTORY',
      managementDomainName: PROCESS_CRAFT_MANAGEMENT_DOMAIN_NAME.AUXILIARY_CRAFT_FACTORY,
    }
  }

  if (SPECIAL_CRAFT_FACTORY_CRAFT_NAMES.has(item.craftName) || item.processCode === 'SPECIAL_CRAFT') {
    return {
      managementDomain: 'SPECIAL_CRAFT_FACTORY',
      managementDomainName: PROCESS_CRAFT_MANAGEMENT_DOMAIN_NAME.SPECIAL_CRAFT_FACTORY,
    }
  }

  return {}
}

function resolveProcessCraftTargetObject(
  item: Pick<LegacyCraftMappingDefinition, 'craftName' | 'processCode'>,
): { targetObject: ProcessTargetObject; targetObjectName: ProcessTargetObjectName } {
  const modernSpecialCraft = modernSpecialCraftDefinitions.find((craft) => craft.craftName === item.craftName)
  if (modernSpecialCraft) {
    return {
      targetObject: modernSpecialCraft.targetObject,
      targetObjectName: modernSpecialCraft.targetObjectName,
    }
  }

  const preparationProcess = preparationProcessDefinitions.find(
    (process) => process.processName === item.craftName || process.processCode === item.processCode,
  )
  if (preparationProcess) {
    return {
      targetObject: preparationProcess.targetObject,
      targetObjectName: preparationProcess.targetObjectName,
    }
  }

  const cuttingCraft = cuttingCraftDefinitions.find((craft) => craft.craftName === item.craftName)
  if (cuttingCraft) {
    return {
      targetObject: cuttingCraft.targetObject,
      targetObjectName: cuttingCraft.targetObjectName,
    }
  }

  if (item.processCode === 'WATER_SOLUBLE') {
    return { targetObject: 'BOM_MATERIAL', targetObjectName: 'BOM物料' }
  }
  if (item.processCode === 'PRINT' || item.processCode === 'DYE' || item.processCode === 'SHRINKING' || item.processCode === 'WASHING') {
    return { targetObject: 'FABRIC', targetObjectName: '面料' }
  }
  if (item.processCode === 'BUTTON_ATTACH') {
    return { targetObject: 'ACCESSORY', targetObjectName: '辅料' }
  }
  if (item.processCode === 'WOOL') {
    return item.craftName === '部位毛织'
      ? { targetObject: 'CUT_PIECE_PART', targetObjectName: '裁片部位' }
      : { targetObject: 'GARMENT_SEMI', targetObjectName: '成衣' }
  }
  return { targetObject: 'CUT_PIECE_PART', targetObjectName: '裁片部位' }
}

export const allProcessCraftDefinitions: ProcessCraftDefinition[] = [
  ...legacyProcessCraftMappings,
  ...supplementalProcessCraftMappings,
  ...modernSpecialCraftProcessMappings,
]
  .slice()
  .sort((a, b) => a.legacyValue - b.legacyValue)
  .map((item) => {
    const process = processDefinitionByCode.get(item.processCode)
    const targetObjectInfo = resolveProcessCraftTargetObject(item)
    const managementDomainInfo = resolveProcessCraftManagementDomain(item)
    const inheritedRule: ProcessDefaultRule = {
      assignmentGranularity: process?.assignmentGranularity ?? 'ORDER',
      detailSplitMode: process?.detailSplitMode ?? 'COMPOSITE',
      detailSplitDimensions: process?.detailSplitDimensions ?? ['PATTERN', 'MATERIAL_SKU'],
    }
    const forceOverrideBySpecialCraft = item.isSpecialCraft
    const resolvedRuleSource: RuleSource = forceOverrideBySpecialCraft
      ? 'OVERRIDE_CRAFT'
      : item.ruleSource ?? 'INHERIT_PROCESS'
    const resolvedAssignmentGranularity =
      resolvedRuleSource === 'OVERRIDE_CRAFT'
        ? item.assignmentGranularity ?? inheritedRule.assignmentGranularity
        : inheritedRule.assignmentGranularity
    const resolvedDetailSplitMode =
      resolvedRuleSource === 'OVERRIDE_CRAFT'
        ? item.detailSplitMode ?? inheritedRule.detailSplitMode
        : inheritedRule.detailSplitMode
    const resolvedDetailSplitDimensions =
      resolvedRuleSource === 'OVERRIDE_CRAFT'
        ? [...(item.detailSplitDimensions ?? inheritedRule.detailSplitDimensions)]
        : [...inheritedRule.detailSplitDimensions]
    const defaultDocType = process?.processRole === 'PREPARATION_ORDER'
      ? 'PREPARATION_ORDER'
      : toProcessDocType(item.defaultDocument)
    return {
      craftCode: toCraftCode(item.legacyValue),
      craftName: item.craftName,
      legacyValue: item.legacyValue,
      legacyCraftName: item.legacyCraftName,
      processCode: item.processCode,
      systemProcessCode: CRAFT_SYSTEM_CODE_BY_LEGACY_VALUE[item.legacyValue] ?? process?.systemProcessCode ?? `PROC_${item.processCode}`,
      stageCode: process?.stageCode ?? 'PROD',
      processRole: process?.processRole ?? 'EXTERNAL_TASK',
      parentProcessCode: process?.parentProcessCode,
      generatesExternalTask: (item.isActive ?? true) && (process?.generatesExternalTask ?? false),
      requiresTaskQr: (item.isActive ?? true) && (process?.requiresTaskQr ?? false),
      requiresHandoverOrder: (item.isActive ?? true) && (process?.requiresHandoverOrder ?? false),
      capacityEnabled: process?.capacityEnabled ?? true,
      capacityRollupMode: process?.capacityRollupMode ?? 'SELF',
      factoryMobileExecutionMode: process?.factoryMobileExecutionMode ?? 'FULL_TASK',
      isActive: item.isActive ?? true,
      assignmentGranularity: resolvedAssignmentGranularity,
      ruleSource: resolvedRuleSource,
      defaultDocType,
      taskTypeMode: toTaskTypeMode(item.isSpecialCraft),
      detailSplitMode: resolvedDetailSplitMode,
      detailSplitDimensions: resolvedDetailSplitDimensions,
      isSpecialCraft: item.isSpecialCraft,
      targetObject: targetObjectInfo.targetObject,
      targetObjectName: targetObjectInfo.targetObjectName,
      ...managementDomainInfo,
      supportedTargetObjects: resolveSpecialCraftSupportedTargetObjects(item),
      supportedTargetObjectLabels: getSpecialCraftSupportedTargetObjectLabels(
        resolveSpecialCraftSupportedTargetObjects(item),
      ),
      visibleFactoryTypes: resolveSpecialCraftVisibleFactoryTypes(item),
      carrySuggestion: CARRY_SUGGESTION_BY_PROCESS_CODE[item.processCode] ?? '工艺匹配工厂优先',
      remark: item.remark,
    }
  })

export const processCraftDefinitions: ProcessCraftDefinition[] = allProcessCraftDefinitions.filter((item) => item.isActive)

const processCraftByCode = new Map(allProcessCraftDefinitions.map((item) => [item.craftCode, item]))
const processCraftByLegacyValue = new Map(allProcessCraftDefinitions.map((item) => [item.legacyValue, item]))

export const craftStageDict = processStageDefinitions

export function listProcessStages(): ProcessStageDefinition[] {
  return processStageDefinitions.slice().sort((a, b) => a.sort - b.sort)
}

export function getProcessStageByCode(stageCode: CraftStageCode): ProcessStageDefinition | undefined {
  return stageDefinitionByCode.get(stageCode)
}

export function listProcessDefinitions(): ProcessDefinition[] {
  return processDefinitions
    .slice()
    .sort((a, b) => {
      const stageA = stageDefinitionByCode.get(a.stageCode)?.sort ?? 999
      const stageB = stageDefinitionByCode.get(b.stageCode)?.sort ?? 999
      if (stageA !== stageB) return stageA - stageB
      const nameCompare = a.processName.localeCompare(b.processName, 'zh-CN')
      if (nameCompare !== 0) return nameCompare
      return a.processCode.localeCompare(b.processCode)
    })
}

export function getProcessDefinitionByCode(processCode: string): ProcessDefinition | undefined {
  return processDefinitionByCode.get(processCode)
}

export function getProcessDefinitionBySystemCode(systemProcessCode: string): ProcessDefinition | undefined {
  return processDefinitionBySystemCode.get(systemProcessCode)
}

export function isExternalTaskProcess(processCode: string): boolean {
  return getProcessDefinitionByCode(processCode)?.generatesExternalTask ?? false
}

export function isPostCapacityNode(processCode: string): boolean {
  const process = getProcessDefinitionByCode(processCode)
  return process?.stageCode === 'POST' && process.capacityEnabled && process.isActive
}

export function listProcessesByStageCode(stageCode: CraftStageCode): ProcessDefinition[] {
  return listProcessDefinitions().filter((item) => item.stageCode === stageCode)
}

export function listProcessCraftDefinitions(): ProcessCraftDefinition[] {
  return processCraftDefinitions.slice()
}

export function listAllProcessCraftDefinitions(): ProcessCraftDefinition[] {
  return allProcessCraftDefinitions.slice()
}

export function listInactiveProcessCraftDefinitions(): ProcessCraftDefinition[] {
  return allProcessCraftDefinitions.filter((item) => !item.isActive)
}

export function listProcessCraftDefinitionsByStatus(isActive: boolean): ProcessCraftDefinition[] {
  return allProcessCraftDefinitions.filter((item) => item.isActive === isActive)
}

export function listActiveProcessCraftDefinitions(): ProcessCraftDefinition[] {
  return processCraftDefinitions.slice()
}

export function getProcessCraftByCode(craftCode: string): ProcessCraftDefinition | undefined {
  return processCraftByCode.get(craftCode)
}

export function getProcessCraftByLegacyValue(legacyValue: number): ProcessCraftDefinition | undefined {
  return processCraftByLegacyValue.get(legacyValue)
}

export function getSpecialCraftSupportedTargetObjectsByCraftCode(
  craftCode: string,
): SpecialCraftSupportedTargetObject[] {
  return [...(getProcessCraftByCode(craftCode)?.supportedTargetObjects ?? [])]
}

export function getSpecialCraftVisibleFactoryTypesByCraftCode(
  craftCode: string,
): SpecialCraftVisibleFactoryType[] {
  return [...(getProcessCraftByCode(craftCode)?.visibleFactoryTypes ?? [])]
}

export function listCraftsByProcessCode(processCode: string): ProcessCraftDefinition[] {
  return processCraftDefinitions.filter((item) => item.processCode === processCode)
}

export function listCraftsByStageCode(stageCode: CraftStageCode): ProcessCraftDefinition[] {
  return processCraftDefinitions.filter((item) => item.stageCode === stageCode)
}

export function listSelectableSpecialCraftDefinitions(): ProcessCraftDefinition[] {
  return processCraftDefinitions.filter(
    (item) =>
      item.isSpecialCraft
      && item.processCode === 'SPECIAL_CRAFT',
  )
}

function clonePreparationProcess(item: PreparationProcessDefinition): PreparationProcessDefinition {
  return { ...item }
}

function cloneModernSpecialCraft(item: ModernSpecialCraftDefinition): ModernSpecialCraftDefinition {
  return { ...item }
}

function cloneCuttingCraft(item: CuttingCraftDefinition): CuttingCraftDefinition {
  return { ...item }
}

function findModernSpecialCraft(craftCodeOrName: string): ModernSpecialCraftDefinition | undefined {
  return modernSpecialCraftDefinitions.find(
    (item) => item.craftCode === craftCodeOrName || item.craftName === craftCodeOrName,
  )
}

export function listCraftsByManagementDomain(domain: ProcessCraftManagementDomain): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.managementDomain === domain)
    .map((item) => cloneModernSpecialCraft(item))
}

export function getCraftManagementDomain(craftCodeOrName: string): ProcessCraftManagementDomain | undefined {
  return findModernSpecialCraft(craftCodeOrName)?.managementDomain
}

export function getCraftManagementDomainName(craftCodeOrName: string): ProcessCraftManagementDomainName | undefined {
  return findModernSpecialCraft(craftCodeOrName)?.managementDomainName
}

export function listPreparationProcesses(): PreparationProcessDefinition[] {
  return preparationProcessDefinitions.map((item) => clonePreparationProcess(item))
}

export function listSpecialCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions.map((item) => cloneModernSpecialCraft(item))
}

export function listAuxiliaryCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.craftCategory === 'AUXILIARY')
    .map((item) => cloneModernSpecialCraft(item))
}

export function listSpecialTypeCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.craftCategory === 'SPECIAL')
    .map((item) => cloneModernSpecialCraft(item))
}

export function listCutPiecePartCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.targetObject === 'CUT_PIECE_PART' && item.canSelectInPatternPiece)
    .map((item) => cloneModernSpecialCraft(item))
}

export function listBindingAreaCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.canSelectInBindingArea)
    .map((item) => cloneModernSpecialCraft(item))
}

export function listFabricCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.targetObject === 'FABRIC')
    .map((item) => cloneModernSpecialCraft(item))
}

export function listAccessoryCrafts(): ModernSpecialCraftDefinition[] {
  return modernSpecialCraftDefinitions
    .filter((item) => item.targetObject === 'ACCESSORY')
    .map((item) => cloneModernSpecialCraft(item))
}

export function listCuttingCrafts(): CuttingCraftDefinition[] {
  return cuttingCraftDefinitions.map((item) => cloneCuttingCraft(item))
}

export function getCraftTargetObject(craftCodeOrName: string): ProcessTargetObject | undefined {
  const modernCraft = findModernSpecialCraft(craftCodeOrName)
  if (modernCraft) return modernCraft.targetObject
  const cuttingCraft = cuttingCraftDefinitions.find(
    (item) => item.craftCode === craftCodeOrName || item.craftName === craftCodeOrName,
  )
  if (cuttingCraft) return cuttingCraft.targetObject
  const preparationProcess = preparationProcessDefinitions.find(
    (item) => item.processCode === craftCodeOrName || item.processName === craftCodeOrName,
  )
  if (preparationProcess) return preparationProcess.targetObject
  const legacyCraft = getProcessCraftByCode(craftCodeOrName) ?? getProcessCraftByLegacyValue(Number(craftCodeOrName))
  if (legacyCraft) {
    const migratedCraft = findModernSpecialCraft(legacyCraft.craftName)
    if (migratedCraft) return migratedCraft.targetObject
    if (legacyCraft.craftName === '洗水' || legacyCraft.craftName === '缩水') return 'FABRIC'
  }
  return undefined
}

export function canSelectCraftInPatternPiece(craftCodeOrName: string): boolean {
  const modernCraft = findModernSpecialCraft(craftCodeOrName)
  if (modernCraft) return modernCraft.canSelectInPatternPiece
  const legacyCraft = getProcessCraftByCode(craftCodeOrName) ?? getProcessCraftByLegacyValue(Number(craftCodeOrName))
  if (!legacyCraft) return false
  const migratedCraft = findModernSpecialCraft(legacyCraft.craftName)
  return migratedCraft?.canSelectInPatternPiece ?? false
}

export interface ProcessCraftOption {
  processCode: string
  processName: string
  craftCode: string
  craftName: string
  label: string
  processRole: ProcessRole
  stageCode: CraftStageCode
  isCapacityNode: boolean
}

function buildProcessCraftOption(definition: ProcessCraftDefinition): ProcessCraftOption | null {
  const row = getProcessCraftDictRowByCode(definition.craftCode)
  if (!row || !row.isActive) return null

  const process = getProcessDefinitionByCode(definition.processCode)
  const isCapacityNode = process?.processRole === 'INTERNAL_CAPACITY_NODE'

  if (isCapacityNode && process?.parentProcessCode) {
    const parent = getProcessDefinitionByCode(process.parentProcessCode)
    const processCode = parent?.processCode ?? row.processCode
    const processName = parent?.processName ?? row.processName
    const craftCode = process.processCode
    const craftName = process.processName

    return {
      processCode,
      processName,
      craftCode,
      craftName,
      label: `${processName} / ${craftName}`,
      processRole: process.processRole,
      stageCode: parent?.stageCode ?? row.stageCode,
      isCapacityNode: true,
    }
  }

  return {
    processCode: row.processCode,
    processName: row.processName,
    craftCode: row.craftCode,
    craftName: row.craftName,
    label: `${row.processName} / ${row.craftName}`,
    processRole: row.processRole,
    stageCode: row.stageCode,
    isCapacityNode: false,
  }
}

function dedupeProcessCraftOptions(options: ProcessCraftOption[]): ProcessCraftOption[] {
  const optionMap = new Map<string, ProcessCraftOption>()
  for (const option of options) {
    optionMap.set(`${option.processCode}::${option.craftCode}`, option)
  }

  return [...optionMap.values()].sort((left, right) => {
    const stageCompare = listProcessStages().findIndex((item) => item.stageCode === left.stageCode)
      - listProcessStages().findIndex((item) => item.stageCode === right.stageCode)
    if (stageCompare !== 0) return stageCompare
    const processCompare = left.processName.localeCompare(right.processName, 'zh-CN')
    if (processCompare !== 0) return processCompare
    return left.craftName.localeCompare(right.craftName, 'zh-CN')
  })
}

export function getActiveProcessCraftOptions(): ProcessCraftOption[] {
  return dedupeProcessCraftOptions(
    listActiveProcessCraftDefinitions()
      .map((item) => buildProcessCraftOption(item))
      .filter((item): item is ProcessCraftOption => Boolean(item)),
  )
}

export function getCapacityProcessCraftOptions(): ProcessCraftOption[] {
  return getActiveProcessCraftOptions().filter((item) => {
    const process = getProcessDefinitionByCode(item.isCapacityNode ? item.craftCode : item.processCode)
    if (item.isCapacityNode) return true
    return process?.capacityEnabled ?? false
  })
}

export function getExternalTaskProcessCraftOptions(): ProcessCraftOption[] {
  return getActiveProcessCraftOptions().filter((item) => !item.isCapacityNode)
}

export function getCapacityNodeProcessCraftOptions(): ProcessCraftOption[] {
  return getActiveProcessCraftOptions().filter((item) => item.isCapacityNode)
}

export function getAssignmentGranularityByCraftCode(craftCode: string): ProcessAssignmentGranularity {
  return processCraftByCode.get(craftCode)?.assignmentGranularity ?? 'ORDER'
}

export function getDetailSplitModeByCraftCode(craftCode: string): DetailSplitMode {
  return processCraftByCode.get(craftCode)?.detailSplitMode ?? 'COMPOSITE'
}

export function getDetailSplitDimensionsByCraftCode(craftCode: string): DetailSplitDimension[] {
  return [...(processCraftByCode.get(craftCode)?.detailSplitDimensions ?? ['PATTERN', 'MATERIAL_SKU'])]
}

export function getRuleSourceByCraftCode(craftCode: string): RuleSource {
  return processCraftByCode.get(craftCode)?.ruleSource ?? 'INHERIT_PROCESS'
}

export function getDefaultDocTypeByCraftCode(craftCode: string): ProcessDocType {
  return processCraftByCode.get(craftCode)?.defaultDocType ?? 'TASK'
}

export function getTaskTypeModeByCraftCode(craftCode: string): TaskTypeMode {
  return processCraftByCode.get(craftCode)?.taskTypeMode ?? 'PROCESS'
}

export function isSpecialCraftByCraftCode(craftCode: string): boolean {
  return processCraftByCode.get(craftCode)?.isSpecialCraft ?? false
}

export const allProcessCraftDictRows: ProcessCraftDictRow[] = allProcessCraftDefinitions.map((item) => {
  const process = processDefinitionByCode.get(item.processCode)
  const stage = stageDefinitionByCode.get(item.stageCode)
  const processAssignmentGranularity = process?.assignmentGranularity ?? 'ORDER'
  const processDetailSplitMode = process?.detailSplitMode ?? 'COMPOSITE'
  const processDetailSplitDimensions = [...(process?.detailSplitDimensions ?? ['PATTERN', 'MATERIAL_SKU'])]
  const parentProcess = item.parentProcessCode ? processDefinitionByCode.get(item.parentProcessCode) : undefined
  return {
    craftCode: item.craftCode,
    craftName: item.craftName,
    processCode: item.processCode,
    processName: process?.processName ?? item.processCode,
    stageCode: item.stageCode,
    stageName: stage?.stageName ?? item.stageCode,
    isActive: item.isActive,
    statusLabel: toStatusLabel(item.isActive),
    processRole: item.processRole,
    processRoleLabel: PROCESS_ROLE_LABEL[item.processRole],
    taskScopeLabel: PROCESS_ROLE_LABEL[item.processRole],
    parentProcessCode: item.parentProcessCode,
    parentProcessName: parentProcess?.processName,
    generatesExternalTask: item.generatesExternalTask,
    generatesExternalTaskLabel: toYesNoLabel(item.generatesExternalTask),
    requiresTaskQr: item.requiresTaskQr,
    requiresTaskQrLabel: toYesNoLabel(item.requiresTaskQr),
    requiresHandoverOrder: item.requiresHandoverOrder,
    requiresHandoverOrderLabel: toYesNoLabel(item.requiresHandoverOrder),
    capacityEnabled: item.capacityEnabled,
    capacityEnabledLabel: toYesNoLabel(item.capacityEnabled),
    capacityRollupMode: item.capacityRollupMode,
    factoryMobileExecutionMode: item.factoryMobileExecutionMode,
    assignmentGranularity: item.assignmentGranularity,
    assignmentGranularityLabel: PROCESS_ASSIGNMENT_GRANULARITY_LABEL[item.assignmentGranularity],
    ruleSource: item.ruleSource,
    ruleSourceLabel: RULE_SOURCE_LABEL[item.ruleSource],
    detailSplitMode: item.detailSplitMode,
    detailSplitModeLabel: DETAIL_SPLIT_MODE_LABEL[item.detailSplitMode],
    detailSplitDimensions: [...item.detailSplitDimensions],
    detailSplitDimensionsText: formatDetailSplitDimensions(item.detailSplitDimensions),
    handoffAdvice: item.carrySuggestion,
    legacyValue: item.legacyValue,
    legacyCraftName: item.legacyCraftName,
    isSpecialCraft: item.isSpecialCraft,
    targetObject: item.targetObject,
    targetObjectName: item.targetObjectName,
    supportedTargetObjects: [...item.supportedTargetObjects],
    supportedTargetObjectLabels: [...item.supportedTargetObjectLabels],
    supportedTargetObjectText: item.supportedTargetObjectLabels.join('、'),
    visibleFactoryTypes: [...item.visibleFactoryTypes],
    defaultDocument: PROCESS_DOC_TYPE_LABEL[item.defaultDocType],
    defaultDocType: item.defaultDocType,
    taskTypeMode: item.taskTypeMode,
    processAssignmentGranularity,
    processAssignmentGranularityLabel:
      PROCESS_ASSIGNMENT_GRANULARITY_LABEL[processAssignmentGranularity],
    processDetailSplitMode,
    processDetailSplitModeLabel: DETAIL_SPLIT_MODE_LABEL[processDetailSplitMode],
    processDetailSplitDimensions,
    processDetailSplitDimensionsText: formatDetailSplitDimensions(processDetailSplitDimensions),
    remark: item.remark,
    processNote: process?.description,
    triggerSource: process?.triggerSource,
  }
})

export const processCraftDictRows: ProcessCraftDictRow[] = allProcessCraftDictRows.filter((item) => item.isActive)

export function listProcessCraftDictRows(includeHistorical: boolean = false): ProcessCraftDictRow[] {
  return includeHistorical ? allProcessCraftDictRows.slice() : processCraftDictRows.slice()
}

export function getProcessCraftDictRowByCode(craftCode: string): ProcessCraftDictRow | undefined {
  return allProcessCraftDictRows.find((item) => item.craftCode === craftCode)
}

export interface ActiveProcessCraftRow {
  stageCode: CraftStageCode
  stageName: string
  processCode: string
  processName: string
  craftCode: string
  craftName: string
  processCraftKey: string
  processCraftLabel: string
  isExternalTask: boolean
  isCapacityNode: boolean
}

export interface ActiveProcessOption {
  processCode: string
  processName: string
}

export type ResolvedProcessCraft = ActiveProcessCraftRow

function buildActiveProcessCraftRow(definition: ProcessCraftDefinition): ActiveProcessCraftRow | null {
  if (!definition.isActive) return null

  const process = getProcessDefinitionByCode(definition.processCode)
  if (!process || !process.isActive) return null

  if (process.processRole === 'INTERNAL_CAPACITY_NODE' && process.parentProcessCode) {
    const parent = getProcessDefinitionByCode(process.parentProcessCode)
    if (!parent || !parent.isActive) return null

    return {
      stageCode: parent.stageCode,
      stageName: getProcessStageByCode(parent.stageCode)?.stageName ?? parent.stageCode,
      processCode: parent.processCode,
      processName: parent.processName,
      craftCode: process.processCode,
      craftName: process.processName,
      processCraftKey: `${parent.processCode}::${process.processCode}`,
      processCraftLabel: `${parent.processName} / ${process.processName}`,
      isExternalTask: false,
      isCapacityNode: true,
    }
  }

  return {
    stageCode: definition.stageCode,
    stageName: getProcessStageByCode(definition.stageCode)?.stageName ?? definition.stageCode,
    processCode: process.processCode,
    processName: process.processName,
    craftCode: definition.craftCode,
    craftName: definition.craftName,
    processCraftKey: `${process.processCode}::${definition.craftCode}`,
    processCraftLabel: `${process.processName} / ${definition.craftName}`,
    isExternalTask: process.generatesExternalTask,
    isCapacityNode: false,
  }
}

function sortActiveProcessCraftRows(left: ActiveProcessCraftRow, right: ActiveProcessCraftRow): number {
  const leftStageSort = getProcessStageByCode(left.stageCode)?.sort ?? Number.MAX_SAFE_INTEGER
  const rightStageSort = getProcessStageByCode(right.stageCode)?.sort ?? Number.MAX_SAFE_INTEGER
  if (leftStageSort !== rightStageSort) return leftStageSort - rightStageSort
  const processCompare = left.processName.localeCompare(right.processName, 'zh-CN')
  if (processCompare !== 0) return processCompare
  return left.craftName.localeCompare(right.craftName, 'zh-CN')
}

const activeProcessCraftRows = (() => {
  const rowMap = new Map<string, ActiveProcessCraftRow>()
  for (const definition of listActiveProcessCraftDefinitions()) {
    const row = buildActiveProcessCraftRow(definition)
    if (!row) continue
    rowMap.set(row.processCraftKey, row)
  }
  return [...rowMap.values()].sort(sortActiveProcessCraftRows)
})()

const activeProcessCraftRowByKey = new Map(
  activeProcessCraftRows.map((item) => [item.processCraftKey, item] as const),
)

export function getActiveProcessCraftRows(): ActiveProcessCraftRow[] {
  return activeProcessCraftRows.slice()
}

export function getActiveProcessOptions(): ActiveProcessOption[] {
  const optionMap = new Map<string, ActiveProcessOption>()
  for (const row of activeProcessCraftRows) {
    if (!optionMap.has(row.processCode)) {
      optionMap.set(row.processCode, {
        processCode: row.processCode,
        processName: row.processName,
      })
    }
  }

  return [...optionMap.values()].sort((left, right) => left.processName.localeCompare(right.processName, 'zh-CN'))
}

export function getActiveCraftOptionsByProcess(processCode?: string): ActiveProcessCraftRow[] {
  return activeProcessCraftRows.filter((row) => (processCode ? row.processCode === processCode : true))
}

export function resolveProcessCraft(
  processCode: string,
  craftCode: string,
): ResolvedProcessCraft | null {
  const normalized = activeProcessCraftRowByKey.get(`${processCode}::${craftCode}`)
  if (normalized) return { ...normalized }

  const craft = getProcessCraftByCode(craftCode)
  if (craft?.isActive && craft.processCode === processCode) {
    const process = getProcessDefinitionByCode(processCode)
    if (!process || !process.isActive) return null
    return {
      stageCode: craft.stageCode,
      stageName: getProcessStageByCode(craft.stageCode)?.stageName ?? craft.stageCode,
      processCode,
      processName: process.processName,
      craftCode: craft.craftCode,
      craftName: craft.craftName,
      processCraftKey: `${processCode}::${craft.craftCode}`,
      processCraftLabel: `${process.processName} / ${craft.craftName}`,
      isExternalTask: process.generatesExternalTask,
      isCapacityNode: process.processRole === 'INTERNAL_CAPACITY_NODE',
    }
  }

  const process = getProcessDefinitionByCode(processCode)
  if (process?.processRole === 'INTERNAL_CAPACITY_NODE' && process.parentProcessCode && craftCode === process.processCode) {
    const mapped = activeProcessCraftRowByKey.get(`${process.parentProcessCode}::${process.processCode}`)
    return mapped ? { ...mapped } : null
  }

  return null
}

export function assertProcessCraftExists(
  processCode: string,
  craftCode: string,
  context: string = '工序工艺校验',
): ResolvedProcessCraft {
  const resolved = resolveProcessCraft(processCode, craftCode)
  if (!resolved) {
    throw new Error(`${context}：未找到有效工序工艺组合 ${processCode} / ${craftCode}`)
  }
  return resolved
}
