import fs from 'node:fs/promises'

import { expect, test } from '@playwright/test'

const PREFIX = 'pcs-independent-sampling'

test('设计改款列表查询、导出、排序后全选本页和跨页批量复制', async ({ page }) => {
  await page.goto('/pcs/production-preparation/design-revision')
  const table = page.locator('[data-independent-sampling-list="DESIGN_REVISION"] [data-independent-sampling-table]')
  const visibleCheckboxes = table.locator(`input[data-${PREFIX}-select-task]`)
  await expect(visibleCheckboxes).toHaveCount(10)

  await page.locator(`[data-${PREFIX}-field="listKeyword"]`).fill('ES-DR-001')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  await expect(visibleCheckboxes).toHaveCount(1)
  await expect(page.locator('[data-independent-sampling-list="DESIGN_REVISION"]')).toContainText('共 1 条')
  const oneRowDownload = page.waitForEvent('download')
  await page.locator(`[data-${PREFIX}-action="export"]`).click()
  const oneRowCsv = await fs.readFile(await (await oneRowDownload).path(), 'utf8')
  expect(oneRowCsv).toContain('ES-DR-001')
  expect(oneRowCsv).not.toContain('ES-DR-002')

  await page.locator(`[data-${PREFIX}-action="reset"]`).click()
  await expect(visibleCheckboxes).toHaveCount(10)
  const allRowsDownload = page.waitForEvent('download')
  await page.locator(`[data-${PREFIX}-action="export"]`).click()
  const allRowsCsv = await fs.readFile(await (await allRowsDownload).path(), 'utf8')
  expect(allRowsCsv.trim().split('\n')).toHaveLength(25)
  expect(allRowsCsv).toContain('ES-DR-024')
  expect(allRowsCsv.split('\n')[0]).not.toContain('操作')
  await page.locator(`[data-${PREFIX}-field="listStatus"]`).selectOption('DRAFT')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  const resultTitle = page.locator('[data-independent-sampling-list="DESIGN_REVISION"]').getByText(/^共 \d+ 条$/).first()
  const previousDraftCount = Number((await resultTitle.textContent())?.match(/\d+/)?.[0])
  expect(previousDraftCount).toBeGreaterThanOrEqual(0)
  await page.locator(`[data-${PREFIX}-action="reset"]`).click()
  await page.getByText('更多筛选', { exact: true }).click()
  await page.locator(`[data-${PREFIX}-field="listPattern"]`).selectOption('REUSE')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  await expect(resultTitle).toHaveText('共 0 条')
  await page.locator(`[data-${PREFIX}-action="reset"]`).click()
  await page.getByText('更多筛选', { exact: true }).click()
  await page.locator(`[data-${PREFIX}-field="listStartDate"]`).fill('2026-07-01')
  await page.locator(`[data-${PREFIX}-field="listEndDate"]`).fill('2026-07-05')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  await expect(resultTitle).toHaveText('共 5 条')
  await page.locator(`[data-${PREFIX}-action="reset"]`).click()
  await page.locator(`[data-${PREFIX}-action="open-column-settings"]`).click()
  await page.locator('[data-standard-list-column-key="owner"] input[data-pcs-independent-sampling-action="toggle-column-visibility"]').uncheck()
  await expect(table.locator('th').getByText('买手', { exact: true })).toHaveCount(0)
  await page.reload()
  await expect(table.locator('th').getByText('买手', { exact: true })).toHaveCount(0)
  await page.locator(`[data-${PREFIX}-action="open-column-settings"]`).click()
  await page.locator(`[data-${PREFIX}-action="restore-column-settings"]`).click()
  await expect(table.locator('th').getByText('买手', { exact: true })).toHaveCount(1)
  await page.locator(`[data-${PREFIX}-action="close-column-settings"]`).last().click()
  await page.locator(`[data-${PREFIX}-action="sort-column"][data-column-key="code"]`).click()
  await page.locator(`[data-${PREFIX}-action="sort-column"][data-column-key="code"]`).click()

  const firstPageIds = await visibleCheckboxes.evaluateAll((items) => items.map((item) => item.getAttribute('data-pcs-independent-sampling-select-task')))
  await page.locator(`[data-${PREFIX}-action="select-page"]`).click()
  await expect(visibleCheckboxes).toHaveCount(10)
  await expect(table.locator(`input[data-${PREFIX}-select-task]:checked`)).toHaveCount(10)
  await expect(page.locator('[data-design-revision-selected-count]')).toHaveText('已选 10 条')

  await page.locator(`[data-${PREFIX}-action="next-page"]`).click()
  const secondPageFirst = visibleCheckboxes.first()
  const secondPageId = await secondPageFirst.getAttribute(`data-${PREFIX}-select-task`)
  expect(firstPageIds).not.toContain(secondPageId)
  await secondPageFirst.check()
  await expect(page.locator('[data-design-revision-selected-count]')).toHaveText('已选 11 条')

  await page.locator(`[data-${PREFIX}-action="copy-selected"]`).click()
  await expect(page.getByText('已批量生成独立的设计改款草稿。')).toBeVisible()
  await expect(page.locator('[data-independent-sampling-list="DESIGN_REVISION"] .whitespace-pre-line').first()).toContainText(`${firstPageIds[0]}：成功，新草稿`)
  await expect(page.locator('[data-independent-sampling-list="DESIGN_REVISION"] .whitespace-pre-line').first()).toContainText(`${secondPageId}：成功，新草稿`)
  await expect(page.locator('[data-design-revision-selected-count]')).toHaveText('已选 0 条')
  await page.locator(`[data-${PREFIX}-field="listStatus"]`).selectOption('DRAFT')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  await expect(resultTitle).toHaveText(`共 ${previousDraftCount + 11} 条`)
})

test('染印组合筛选读取已保存草稿的目标结果 SKU', async ({ page }) => {
  await page.goto('/pcs/production-preparation/design-revision/ES-ID-DR-001?step=buyer')
  await page.locator('[data-independent-bom-line]').first().locator(`[data-${PREFIX}-field="bomMaterialSkuId"]`).selectOption('dr_cotton_dye_print')
  await page.locator(`[data-${PREFIX}-action="save-draft"]`).click()
  await expect(page.getByText('设计改款草稿已保存。')).toBeVisible()

  await page.goto('/pcs/production-preparation/design-revision')
  await page.getByText('更多筛选', { exact: true }).click()
  await page.locator(`[data-${PREFIX}-field="listProcessing"]`).selectOption('BOTH')
  await page.locator(`[data-${PREFIX}-field="listKeyword"]`).fill('ES-DR-001')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  await expect(page.locator('[data-independent-sampling-list="DESIGN_REVISION"]').getByText(/^共 \d+ 条$/).first()).toHaveText('共 1 条')
  await expect(page.locator(`[data-${PREFIX}-select-task]`)).toHaveCount(1)
  await expect(page.getByRole('button', { name: '收起更多', exact: true })).toBeVisible()
  await page.locator(`[data-${PREFIX}-field="listProcessing"]`).selectOption('NONE')
  await page.locator(`[data-${PREFIX}-action="query"]`).click()
  await expect(page.locator('[data-independent-sampling-list="DESIGN_REVISION"]').getByText(/^共 \d+ 条$/).first()).toHaveText('共 0 条')
})

 test('旧列偏好下勾选仍固定第一列，筛选展开局部更新', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('higood-pcs-design-revision-list-preferences-v2', JSON.stringify({ order: ['code', 'style', 'select'], visibleKeys: ['code', 'style', 'select'], frozenKeys: ['code'], pageSize: 10 })))
  await page.goto('/pcs/production-preparation/design-revision')
  const table = page.locator('[data-independent-sampling-table]')
  await expect(table.locator('thead th').first()).toHaveText('勾选')
  await table.locator('tbody tr').first().locator('td').first().locator('input').check()
  await page.evaluate(() => { document.querySelector('[data-independent-sampling-table]')!.setAttribute('data-retained', 'yes') })
  await page.getByRole('button', { name: '更多筛选', exact: true }).click()
  await expect(page.locator('[data-process-advanced]')).toBeVisible()
  await expect(table).toHaveAttribute('data-retained', 'yes')
  await page.getByRole('button', { name: '收起更多', exact: true }).click()
  await expect(page.locator('[data-process-advanced]')).toBeHidden()
  await expect(table.locator('tbody input:checked')).toHaveCount(1)
  await page.reload()
  await expect(table.locator('thead th').first()).toHaveText('勾选')
  for (const width of [1366, 1280]) {
    await page.setViewportSize({ width, height: 768 })
    await page.getByRole('button', { name: '更多筛选', exact: true }).click()
    await expect(page.locator('[data-process-advanced]')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/design-revision-filters-${width}.png` })
    await page.getByRole('button', { name: '收起更多', exact: true }).click()
  }
})
