import { expect, test } from '@playwright/test'
import { writeFile } from 'node:fs/promises'

test('物料搜索、每行加工互斥、混合物料保存提交', async ({ page }, info) => {
 const samples: Record<string,number[]> = {}
 await page.context().grantPermissions(['clipboard-read','clipboard-write'])
 const action = (name:string) => page.locator(`[data-pcs-independent-sampling-action="${name}"]`)
 const field = (name:string) => page.locator(`[data-pcs-independent-sampling-field="${name}"]`)
 const measure = async (name:string, work:()=>Promise<void>) => {
  const start = await page.evaluate(()=>performance.now())
  await work()
  const end = await page.evaluate(async()=>{await Promise.all([...document.images].filter(img=>{const r=img.getBoundingClientRect();return r.width&&r.height&&r.top<innerHeight&&r.bottom>0}).map(img=>img.decode()));await new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));return performance.now()})
  ;(samples[name] ||= []).push(end-start)
 }
 await page.goto('/pcs/production-preparation/design-revision/new')
 await action('add-bom-line').click()
 const row = page.locator('[data-independent-bom-line]').first()
 const picker = row.locator('[data-design-style-picker="material"]')
 for(let round=0;round<5;round++) {
  await page.setViewportSize({width:round===4?1280:1366,height:768})
  await measure('open',async()=>{await picker.locator('summary').click();await expect(picker.locator('input')).toBeFocused()})
  await page.evaluate(()=>navigator.clipboard.writeText('  dr-cotton-001-white-blue-print  '))
  await measure('paste',async()=>{await picker.locator('input').press('ControlOrMeta+V');await expect(picker.locator('option:not([hidden])')).toHaveCount(1)})
  await measure('select',async()=>{await picker.locator('select').selectOption('dr_cotton_dye_print');await expect(picker).not.toHaveAttribute('open','');await expect(row).toContainText('无需染色；印花')})
  await expect(row.locator('[data-pcs-independent-sampling-field="bomDyeRequirement"]')).toHaveValue('否')
  await expect(row.locator('[data-pcs-independent-sampling-field="bomPrintRequirement"]')).toHaveValue('是')
  await picker.locator('summary').click()
  if(round===0)await page.screenshot({path:info.outputPath('material-search-open.png')})
  await measure('noResult',async()=>{await picker.locator('input').fill('MISSING-987');await expect(picker.locator('[data-design-style-empty]')).toBeVisible()})
  await measure('clear',async()=>{await picker.locator('input').fill('');expect(await picker.locator('option:not([hidden])').count()).toBeGreaterThan(3)})
  await measure('escape',async()=>{await picker.locator('input').press('Escape');await expect(picker).not.toHaveAttribute('open','')})
  await picker.locator('summary').click()
  await measure('outside',async()=>{await page.getByRole('heading',{name:'物料与加工要求'}).click();await expect(picker).not.toHaveAttribute('open','')})
  await measure('previewMaterial',async()=>{await row.locator('[data-pcs-independent-sampling-action="open-image"]').first().click();await expect(page.getByRole('dialog')).toBeVisible()})
  await measure('closePreview',async()=>{await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)})
  if(round===4)await page.screenshot({path:info.outputPath('material-layout.png'),fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
 }
 await action('add-bom-line').click()
 const rows=page.locator('[data-independent-bom-line]')
 await rows.nth(1).locator('summary').click()
 await rows.nth(1).locator('select[aria-label="物料 SKU 搜索结果"]').selectOption('dr_cotton_dyed')
 await expect(rows.nth(1).locator('[data-pcs-independent-sampling-field="bomDyeRequirement"]')).toHaveValue('是')
 await expect(rows.nth(1).locator('[data-pcs-independent-sampling-field="bomPrintRequirement"]')).toHaveValue('否')
 await page.locator('[data-design-style-picker="targetStyleId"] summary').click()
 await field('targetStyleId').selectOption({index:2})
 await page.locator('[data-pcs-independent-sampling-create-design-upload]').setInputFiles('public/dress-sample-1.jpg')
 await expect(page.getByText('dress-sample-1.jpg',{exact:true})).toBeVisible()
 await field('creationReason').fill('每条物料独立加工')
 await action('save-draft').click()
 await expect(page.getByText('设计改款草稿已保存。')).toBeVisible()
 await page.reload()
 await expect(rows).toHaveCount(2)
 await expect(rows.nth(0).locator('[data-pcs-independent-sampling-field="bomDyeRequirement"]')).toHaveValue('否')
 await action('confirm-scheme').click()
 await expect(page.getByRole('heading',{name:'本次需要完成的工作'})).toBeVisible()
 const hrefs=await page.locator('a[href*="/fcs/craft/"]').evaluateAll(links=>links.map(l=>l.getAttribute('href')))
 expect(hrefs.some(h=>h?.includes('/dyeing/'))).toBe(true)
 expect(hrefs.some(h=>h?.includes('/printing/'))).toBe(true)
 await writeFile(info.outputPath('material-search-performance.json'),JSON.stringify(samples,null,2))
 for(const [name,values] of Object.entries(samples))for(const value of values)expect(value,`${name}: ${value}ms`).toBeLessThan(500)
})
