import { test, expect } from '@playwright/test'
for (const width of [360,390]) test(`简易交出 PDA ${width} 输入与成功页`,async({page},info)=>{
  test.setTimeout(120000)
  await page.setViewportSize({width,height:width===360?640:844})
  await page.addInitScript(()=>{
    localStorage.setItem('fcs_pda_factory_id','OWN-CUTTING-001')
    localStorage.setItem('fcs_pda_session',JSON.stringify({userId:'OWN-CUTTING-001_admin',loginId:'OWN-CUTTING-001_admin',userName:'HiGood裁床厂管理员',roleId:'ROLE_ADMIN',factoryId:'OWN-CUTTING-001',factoryName:'HiGood裁床厂',loggedAt:'2026-09-17 09:00:00'}))
  })
  await page.goto('/fcs/pda/cutting/simple-cut-piece-handover')
  const root=page.locator('[data-simple-cut-root="PDA"]')
  const input=root.locator('[data-simple-cut-input]')
  await input.fill('RW-10CIVDB-0IZLA0Q')
  await root.getByRole('button',{name:'扫描',exact:true}).click()
  const confirm=root.locator('[data-simple-cut-action="confirm"]')
  await expect(confirm).toContainText('700 片',{timeout:90000})
  await expect(root).not.toContainText('当前仓管账号')
  await expect(root).not.toContainText('使用扫码枪，或手动输入')
  const ib=await input.boundingBox(),sb=await root.getByRole('button',{name:'扫描',exact:true}).boundingBox()
  expect(Math.abs(ib!.y-sb!.y)).toBeLessThan(5)
  const cb=await confirm.boundingBox(),fb=await root.locator('footer').boundingBox()
  expect(cb!.width).toBeGreaterThan(fb!.width-30)
  expect(cb!.y+cb!.height).toBeLessThan(width===360?640:844)
  await page.screenshot({path:info.outputPath('preview.png'),fullPage:true})
  await confirm.click()
  await expect(root).toContainText('已交出 · 工厂已接收')
  await expect(root.getByRole('link')).toHaveCount(0)
  await expect(root).not.toContainText('查看交出记录')
  await expect(root).toContainText('700')
  await expect(root).toContainText('陈琳')
  expect(await root.locator('svg').count()).toBe(1)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('success.png'),fullPage:true})
  await root.getByRole('button',{name:'继续扫描'}).click()
  await expect(input).toBeFocused()
  await expect(input).toHaveValue('')
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('cuttingRuntimeEventLedger')!).events.filter((e:{eventType:string})=>e.eventType==='简易裁片交出').length)).toBe(1)
})
