import { test, expect } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
const artifact='output/playwright/task-sheet-print'
const pdf='output/pdf/task-sheet-print'
test.use({deviceScaleFactor:2})
fs.writeFileSync('/tmp/decode-task-code.swift','import Foundation\nimport Vision\nimport AppKit\nlet url=URL(fileURLWithPath:CommandLine.arguments[1])\nlet request=VNDetectBarcodesRequest()\nrequest.symbologies=[.qr,.code128]\ntry VNImageRequestHandler(url:url).perform([request])\nlet results=(request.results ?? []).map { ["symbology":$0.symbology.rawValue,"text":$0.payloadStringValue ?? ""] }\nlet data=try JSONSerialization.data(withJSONObject:results)\nprint(String(data:data,encoding:.utf8)!)\n')
const decodeRaster=(file:string)=>JSON.parse(execFileSync('swift',['-module-cache-path','/tmp/task-code-swift-cache','/tmp/decode-task-code.swift',file],{encoding:'utf8'})) as Array<{text:string}>
test('任务单与生产确认单真实图片、打印、码与 A4 验收', async ({page})=>{
  test.setTimeout(600000)
  fs.mkdirSync(artifact,{recursive:true});fs.mkdirSync(pdf,{recursive:true})
  await page.setViewportSize({width:1366,height:768})
  await page.goto('/fcs/print/preview?documentType=PRODUCTION_CONFIRMATION&sourceType=PRODUCTION_ORDER&sourceId=PO-DEMO-SIMPLE-0916')
  await expect(page.locator('.print-preview-root')).toBeVisible({timeout:120000})
  const sheets=await page.evaluate(async()=>{
    const f=await import('/src/data/fcs/cutting/simple-cut-piece-handover-fixtures.ts');f.ensureSimpleCutPieceHandoverFixtures()
    const d=await import('/src/data/fcs/dispatch-task-sheet.ts')
    return d.listDispatchTaskSheetAssignments().filter(a=>a.productionOrderId.startsWith('PO-DEMO-')).map(a=>d.buildDispatchTaskSheetData(a.assignmentId)).filter(s=>['独立车缝','车缝+烫包','裁剪+车缝+烫包'].includes(s.taskTypeLabel)).map(s=>({id:s.assignment.assignmentId,no:s.taskSheetNo,type:s.taskTypeLabel,qr:s.qrValue}))
  })
  expect(sheets).toHaveLength(4)
  await page.evaluate(()=>{(window as any).__printCalls=0;window.print=()=>{(window as any).__printCalls++}})
  await expect(page.getByRole('heading',{name:'生产确认单（Formula Konfirmasi Barang）',exact:true})).toBeVisible()
  await expect(page.getByRole('table',{name:'生产单基本资料'})).toBeVisible()
  for(const title of ['warna & gambar','Kain & aksesoris','Daftar SK','Graf ukura']) await expect(page.getByText(title,{exact:true})).toBeVisible()
  await expect.poll(()=>page.locator('[data-print-image-state="loaded"]').count()).toBeGreaterThan(3)
  await page.getByRole('button',{name:'打印',exact:true}).click()
  await expect.poll(()=>page.evaluate(()=>(window as any).__printCalls),{timeout:20000}).toBe(1)
  await expect(page.getByRole('table',{name:'辅料信息',exact:true})).toContainText('雾霾灰开尾拉链')
  await expect(page.getByRole('table',{name:'辅料信息',exact:true})).toContainText('雾霾灰罗纹')
  for(const kind of ['DXF','RUL','PRJ']) await expect(page.getByRole('link',{name:kind,exact:true}).first()).toBeVisible()
  await page.screenshot({path:`${artifact}/production-confirmation.png`,fullPage:true})
  await page.pdf({path:`${pdf}/production-confirmation.pdf`,format:'A4',printBackground:true,preferCSSPageSize:true})
  execFileSync('pdftoppm',['-png','-r','300','-f','1','-singlefile',`${pdf}/production-confirmation.pdf`,`${artifact}/production-confirmation-printed-page-1`])
  const productionCodes=decodeRaster(`${artifact}/production-confirmation-printed-page-1.png`)
  expect(productionCodes.some(code=>code.text==='PO-DEMO-SIMPLE-0916')).toBe(true)
  const decodedResults: Array<unknown> = [{productionCodes}]
  for(const [index,sheet] of sheets.entries()){
    await page.goto(`/fcs/print/preview?documentType=DISPATCH_TASK_SHEET&sourceType=EFFECTIVE_TASK_ASSIGNMENT&sourceId=${encodeURIComponent(sheet.id)}`)
    await expect(page.locator('[data-real-qr] svg')).toBeVisible({timeout:30000})
    await expect(page.getByText(sheet.no,{exact:true}).first()).toBeVisible()
    await expect.poll(()=>page.locator('img[data-print-image]').evaluateAll(imgs=>imgs.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true)
    await page.locator('[data-print-image-url]').first().click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.locator('[data-print-image-url]').first().click()
    await page.getByRole('dialog').click({position:{x:2,y:2}});await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.locator('[data-print-image-url]').first().click()
    await page.getByRole('button',{name:'关闭',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.screenshot({path:`${artifact}/task-${index}.png`,fullPage:true})
    await page.locator('[data-real-barcode]').screenshot({path:`${artifact}/barcode-${index}.png`})
    await page.locator('[data-real-qr]').screenshot({path:`${artifact}/qr-${index}.png`})
    await page.pdf({path:`${pdf}/task-${index}.pdf`,format:'A4',printBackground:true,preferCSSPageSize:true})
    execFileSync('pdftoppm',['-png','-r','300','-f','1','-singlefile',`${pdf}/task-${index}.pdf`,`${artifact}/task-${index}-printed-page-1`])
    const printedCodes=decodeRaster(`${artifact}/task-${index}-printed-page-1.png`)
    const barcodeDecoded=printedCodes.filter(r=>r.text===sheet.no)
    const qrDecoded=printedCodes.filter(r=>r.text===sheet.qr)
    expect(barcodeDecoded.some(r=>r.text===sheet.no)).toBe(true)
    expect(qrDecoded.some(r=>r.text===sheet.qr)).toBe(true)
    decodedResults.push({taskSheetNo:sheet.no,barcodeDecoded,qrDecoded})
    const before=await page.evaluate(()=>localStorage.getItem('cuttingRuntimeEventLedger'))
    await page.evaluate(()=>{(window as any).__printCalls=0;window.print=()=>{(window as any).__printCalls++}})
    await page.getByRole('button',{name:'打印',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__printCalls),{timeout:20000}).toBe(1)
    await page.getByRole('button',{name:'打印',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__printCalls),{timeout:20000}).toBe(2)
    expect(await page.evaluate(()=>localStorage.getItem('cuttingRuntimeEventLedger'))).toBe(before)
    if(index===0){
      await page.route('**/production-confirmation-demo/grey-zip-hoodie.png',route=>route.abort())
      await page.reload();await expect(page.locator('[data-print-image-state="error"]').first()).toBeVisible()
      await page.evaluate(()=>{(window as any).__printCalls=0;window.print=()=>{(window as any).__printCalls++}})
      await page.getByRole('button',{name:'打印',exact:true}).click()
      await expect(page.locator('[data-print-ready-feedback]')).toContainText('打印未开始')
      expect(await page.evaluate(()=>(window as any).__printCalls)).toBe(0)
      await page.unroute('**/production-confirmation-demo/grey-zip-hoodie.png')
      await page.locator('[data-print-image-state="error"] [data-print-image-retry]').first().click()
      await expect(page.locator('[data-print-image-state="error"]')).toHaveCount(0)
      await page.getByRole('button',{name:'打印',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).__printCalls),{timeout:20000}).toBe(1)
    }
  }
  const pdfInfo=fs.readdirSync(pdf).filter(name=>name.endsWith('.pdf')).map(name=>({name,info:execFileSync('pdfinfo',[`${pdf}/${name}`],{encoding:'utf8'})}))
  expect(pdfInfo.some(row=>Number(row.info.match(/Pages:\s+(\d+)/)?.[1])>=2)).toBe(true)
  fs.writeFileSync(`${artifact}/codes.json`,JSON.stringify({sheets,decodedResults,pdfInfo},null,2))
})

test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus){const state=await page.evaluate(()=>({feedback:document.querySelector('[data-print-ready-feedback]')?.textContent,images:Array.from(document.querySelectorAll<HTMLImageElement>('img[data-print-image]')).map(i=>({src:i.src,complete:i.complete,width:i.naturalWidth,state:i.closest('[data-print-image-frame]')?.getAttribute('data-print-image-state')}))})).catch(()=>null);fs.writeFileSync(`${artifact}/failure-state.json`,JSON.stringify(state,null,2))}})
