import { test, expect } from '@playwright/test'
import fs from 'node:fs/promises'

test('PPIC 同一真实交出事实的任务打印与欠片页面', async ({page}) => {
  test.setTimeout(300000)
  await fs.mkdir('output/playwright/task-sheet-ppic',{recursive:true})
  await page.addInitScript(() => {
    localStorage.setItem('fcs_pda_factory_id','OWN-CUTTING-001')
    localStorage.setItem('fcs_pda_session',JSON.stringify({userId:'OWN-CUTTING-001_admin',loginId:'OWN-CUTTING-001_admin',userName:'验收仓管',roleId:'ROLE_ADMIN',factoryId:'OWN-CUTTING-001',factoryName:'自营裁床',loggedAt:'2026-09-16 09:00:00'}))
  })
  await page.setViewportSize({width:1366,height:768})
  await page.goto('/fcs/craft/cutting/warehouse-management/wait-handover')
  await page.locator('[data-simple-cut-open]').click({timeout:120000})
  await page.locator('[data-simple-cut-input]').fill('RW-10CIVDB-0IZLA0Q')
  await page.locator('[data-simple-cut-input]').press('Enter')
  await expect(page.locator('[data-simple-cut-action="confirm"]')).toContainText('700 片',{timeout:120000})
  await page.locator('[data-simple-cut-action="confirm"]').click()
  await expect(page.locator('[data-simple-cut-root]')).toContainText('已交出 · 工厂已接收',{timeout:120000})
  await page.goto('/fcs/sewing-outsourcing/cut-piece-handover?tab=HANDED_WITH_DEBT')
  await page.locator('[data-sewing-cut-piece-filter="keyword"]').fill('PO-DEMO-SIMPLE-0916')
  await page.locator('[data-sewing-cut-piece-action="query"]').click()
  await expect(page.locator('[data-sewing-cut-piece-action="open-detail"]')).toHaveCount(1)
  await page.locator('[data-sewing-cut-piece-action="open-detail"]').click()
  const detail=page.getByRole('dialog',{name:'交出与欠片详情',exact:true})
  await expect(detail).toContainText('700片')
  await expect(detail).toContainText('200／0片')
  await expect(detail).toContainText('0件')
  await expect(detail).toContainText('SKU-SIMPLE-M-GRY')
  await page.screenshot({path:'output/playwright/task-sheet-ppic/debt-700-of-900.png',fullPage:true})
  await page.goto('/fcs/sewing-outsourcing/tasks')
  await page.locator('[data-ppic-task-field="keyword"]').fill('PO-DEMO-SIMPLE-0916')
  await page.locator('[data-ppic-task-action="query"]').click()
  await expect(page.locator('[data-ppic-task-action="print-task-sheet"]')).toHaveCount(1)
  await expect(page.locator('[data-pickup-kind="CUT_PIECE"]')).toHaveCount(0)
  await page.locator('[data-pda-image-preview-url]').first().click()
  await expect(page.locator('[data-pda-image-preview-root] img')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.locator('[data-pda-image-preview-root]')).toHaveCount(0)
  await page.screenshot({path:'output/playwright/task-sheet-ppic/task-actions.png',fullPage:true})
  await page.locator('[data-ppic-task-action="print-task-sheet"]').click()
  await expect(page).toHaveURL(/documentType=DISPATCH_TASK_SHEET/)
  await expect(page.locator('body')).toContainText('RW-10CIVDB-0IZLA0Q',{timeout:120000})
  expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('cuttingRuntimeEventLedger')||'{"events":[]}').events.filter((e:{eventType:string})=>e.eventType==='简易裁片交出').length)).toBe(1)
})

test('PPIC款图失败有提示并可恢复大图',async({page})=>{
  test.setTimeout(180000)
  await page.route('**/production-confirmation-demo/grey-zip-hoodie.png',route=>route.abort())
  await page.goto('/fcs/sewing-outsourcing/tasks')
  await page.locator('[data-ppic-task-field="keyword"]').fill('PO-DEMO-SIMPLE-0916')
  await page.locator('[data-ppic-task-action="query"]').click()
  await expect(page.locator('[data-ppic-task-action="print-task-sheet"]')).toHaveCount(1,{timeout:120000})
  const failed=page.locator('[data-pda-image-preview-url="/production-confirmation-demo/grey-zip-hoodie.png"] span')
  await expect(failed).toBeVisible({timeout:120000})
  await page.unroute('**/production-confirmation-demo/grey-zip-hoodie.png')
  await failed.click()
  const img=page.locator('[data-pda-image-preview-root] img')
  await expect.poll(()=>img.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true)
  await page.locator('[data-pda-image-preview-close]').last().click()
  await expect(page.locator('[data-pda-image-preview-root]')).toHaveCount(0)
})

test('历史裁片旧码即使原责任上下文已缺失也仅显示历史提示',async({page})=>{
  await page.addInitScript(()=>{
    localStorage.setItem('fcs_pda_factory_id','OWN-CUTTING-001')
    localStorage.setItem('fcs_pda_session',JSON.stringify({userId:'OWN-CUTTING-001_admin',loginId:'OWN-CUTTING-001_admin',userName:'验收仓管',roleId:'ROLE_ADMIN',factoryId:'OWN-CUTTING-001',factoryName:'自营裁床',loggedAt:'2026-09-16 09:00:00'}))
    localStorage.setItem('higood:ppic:sewing-pickup-slips:v1',JSON.stringify({version:1,versions:[{versionId:'LEGACY-RETIRED-CUT',slipId:'PPIC-PICKUP-RETIRED-CUT_PIECE',assignmentId:'RETIRED',objectKind:'CUT_PIECE',status:'VOIDED',versionNo:1,lines:[]}],handoverResults:[]}))
  })
  await page.setViewportSize({width:360,height:640})
  await page.goto('/fcs/pda/handover?sewingPickupVersionId=LEGACY-RETIRED-CUT')
  await expect(page.getByRole('heading',{name:'旧裁片领料单仅供历史查询'})).toBeVisible({timeout:120000})
  await expect(page.locator('[data-pda-handover-action="confirm-sewing-pickup"]')).toHaveCount(0)
  await expect(page.locator('[data-sewing-pickup-line-id]')).toHaveCount(0)
  await fs.mkdir('output/playwright/task-sheet-ppic',{recursive:true})
  await page.screenshot({path:'output/playwright/task-sheet-ppic/legacy-code-blocked.png',fullPage:true})
})
