import { expect, test, type Page } from '@playwright/test'

// Dedicated functional regression; cold-load and interaction performance are measured separately.
async function readFacts(page: Page, taskId: string) {
  return page.evaluate(async (id) => {
    const { getSpecialCraftTaskOrderById } = await import('/src/data/fcs/special-craft-task-orders.ts')
    const { readWoolStore } = await import('/src/data/fcs/wool-domain/store.ts')
    const task = getSpecialCraftTaskOrderById(id)
    const store = readWoolStore()
    return { receivedQty: task?.receivedQty, pieceKey: task?.woolPieceKey, receipts: task?.woolFinalReceipts, pieces: store.pieceReceipts, craftRecords: store.craftRecords, handovers: store.handovers.filter((row: any) => task?.woolFinalInputOrderIds?.includes(row.woolOrderId)) }
  }, taskId)
}

for (const viewport of [{ width: 360, height: 800 }, { width: 400, height: 806 }]) {
  test(`最终成衣工艺 PDA ${viewport.width}x${viewport.height} 按实际批次接收、刷新与工厂隔离`, async ({ page }, testInfo) => {
    test.setTimeout(90_000)
    await page.setViewportSize(viewport)
    await page.goto('/fcs/craft/wool/knitting-orders')
    await expect(page.locator('[data-wool-work-orders-root]')).toBeVisible()
    const scene = await page.evaluate(async () => {
      const { prepareWoolFinalDownstreamReviewScenario } = await import('/scripts/fixtures/wool-final-downstream-review.ts')
      const { setPdaSession, listFactoryPdaUsers, createPdaSessionFromUser } = await import('/src/data/fcs/store-domain-pda.ts')
      const scene = prepareWoolFinalDownstreamReviewScenario()
      const user = listFactoryPdaUsers(scene.factoryId).find((user: any) => user.roleId === 'ROLE_MANAGER') || listFactoryPdaUsers(scene.factoryId)[0]
      if (!user) throw Error('验收接收厂没有实际 PDA 用户')
      const session = createPdaSessionFromUser(user)
      setPdaSession(session)
      return { ...scene, session }
    })
    await page.goto(`/fcs/pda/exec/${encodeURIComponent(scene.taskId)}`)
    const receive = page.locator('[data-pda-execd-action="special-confirm-receive"]')
    await expect(receive).toBeVisible()
    await expect(page.locator('[data-special-craft-garment-sku-list]')).toContainText('应收：20 件')
    await expect(page.locator('[data-special-craft-garment-sku-list]')).not.toContainText('来自成衣仓实出')
    await receive.click()
    await expect(page).toHaveURL(new RegExp(`/fcs/pda/handover\\?tab=pickup&woolFinalCraftOrderId=${scene.taskId}$`))
    await expect(page.getByRole('heading', { name: '接收缝盘成衣' })).toBeVisible()
    await expect(page.getByRole('button', { name: '接收本批' })).toHaveCount(2)
    await expect(page.locator('main')).toContainText('交出 12 件')
    await expect(page.locator('main')).toContainText('交出 8 件')
    const image = page.locator('main img').first()
    await expect(image).toHaveAttribute('src', scene.styleImageUrl)
    await image.evaluate((image: HTMLImageElement) => image.decode())
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('pending-two-batches.png'), fullPage: true })
    const before = await readFacts(page, scene.taskId)
    expect(before.pieceKey).toBeUndefined()
    expect(before.receivedQty).toBe(0)
    expect(before.handovers).toHaveLength(2)
    expect(before.handovers.every((row: any) => !row.pieceKey && row.qtyUnit === '件')).toBe(true)
    await page.locator('article').filter({ hasText: scene.handovers[0].handoverId }).getByRole('button', { name: '接收本批' }).click()
    await expect(page.locator('[data-pda-handoverd-action="open-receiver-writeback"]')).toBeVisible()
    await page.locator('[data-pda-handoverd-action="open-receiver-writeback"]').click()
    const qty = page.locator('[data-pda-handoverd-field="writebackQty"]')
    await expect(qty).toHaveValue('12')
    await qty.fill('12')
    await page.locator('[data-pda-handoverd-action="submit-receiver-writeback"]').click()
    await expect(qty).toHaveCount(0)
    await page.reload()
    await expect(page.locator('[data-pda-handoverd-action="open-receiver-writeback"]')).toHaveCount(0)
    const actual = await readFacts(page, scene.taskId)
    expect(actual.receivedQty).toBe(12)
    expect(actual.receipts?.find((row: any) => row.handoverId === scene.handovers[0].handoverId)?.receivedQty).toBe(12)
    expect(actual.receipts?.find((row: any) => row.handoverId === scene.handovers[1].handoverId)?.receivedQty).toBeUndefined()
    expect(actual.pieces).toEqual(before.pieces)
    expect(actual.craftRecords).toEqual(before.craftRecords)
    await page.goto(`/fcs/pda/exec/${encodeURIComponent(scene.taskId)}`)
    await expect(receive).toBeVisible()
    await expect(page.locator('[data-special-craft-garment-sku-list]')).toContainText('累计实收：12 件')
    await expect(page.locator('[data-special-craft-garment-sku-list]')).toContainText('可加工：12 件')
    await receive.click()
    await expect(page.getByRole('button', { name: '接收本批' })).toHaveCount(1)
    await expect(page.locator('main')).toContainText('交出 8 件')
    await expect(page.locator('main')).not.toContainText(scene.handovers[0].handoverId)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath('remaining-eight-after-refresh.png'), fullPage: true })
    const pendingUrl = page.url()
    const secondBatchPath = await page.getByRole('button', { name: '接收本批' }).getAttribute('data-nav')
    expect(secondBatchPath).toBeTruthy()
    await page.evaluate(async () => {
      const { setPdaSession, listFactoryPdaUsers, createPdaSessionFromUser } = await import('/src/data/fcs/store-domain-pda.ts')
      setPdaSession(createPdaSessionFromUser(listFactoryPdaUsers('OWN_WOOL_FACTORY')[0]))
    })
    await page.goto(pendingUrl)
    await expect(page.getByText('此成衣加工单不属于当前工厂，请返回核对。')).toBeVisible()
    await expect(page.getByRole('button', { name: '接收本批' })).toHaveCount(0)
    await page.goto(secondBatchPath!)
    await expect(page.getByText('该毛织交出不属于当前登录工厂，不能查看或确认接收。')).toBeVisible()
    await expect(page.locator('[data-pda-handoverd-action="open-receiver-writeback"]')).toHaveCount(0)
    expect(await readFacts(page, scene.taskId)).toEqual(actual)
  })
}
