import type { TechnicalProcessObjectType } from '../../data/pcs-technical-data-version-types.ts'

export type BomRequirementFlag = '是' | '否'
export type BomDrivenPrepProcessCode = 'PRINT' | 'WATER_SOLUBLE' | 'DYE' | 'EMBROIDERY'
export type BomTriggerField =
  | 'printRequirement'
  | 'waterSolubleRequirement'
  | 'dyeRequirement'
  | 'embroideryRequirement'

export const bomRequirementOptions: BomRequirementFlag[] = ['否', '是']

export const bomTriggerFieldLabel: Record<BomTriggerField, string> = {
  printRequirement: '印花需求',
  waterSolubleRequirement: '水溶要求',
  dyeRequirement: '染色需求',
  embroideryRequirement: '绣花需求',
}

export interface BomProcessLinkageBomRow {
  id?: string
  type?: '面料' | '纱线' | '辅料' | '包装材料' | '成衣' | '其他'
  materialCode?: string
  materialName?: string
  usageProcessCodes?: string[]
  printRequirement?: string
  waterSolubleRequirement?: string
  dyeRequirement?: string
  embroideryRequirement?: string
}

export interface BomDrivenPrepTechnique {
  id: string
  entryType: 'PROCESS_BASELINE' | 'CRAFT'
  stageCode: 'PREP' | 'PROD'
  stage: string
  processCode: string
  process: string
  craftCode: string
  technique: string
  assignmentGranularity: 'ORDER' | 'COLOR' | 'SKU' | 'DETAIL'
  ruleSource: string
  detailSplitMode: string
  detailSplitDimensions: string[]
  defaultDocType: 'DEMAND' | 'TASK' | 'PREPARATION_ORDER'
  taskTypeMode: 'PROCESS' | 'CRAFT'
  isSpecialCraft: boolean
  selectedTargetObject?: string
  targetObject?: 'FABRIC' | 'BOM_MATERIAL' | 'ACCESSORY' | 'GARMENT_SEMI'
  targetObjectName?: '面料' | 'BOM物料' | '辅料' | '成衣'
  supportedTargetObjects?: string[]
  supportedTargetObjectLabels?: string[]
  triggerSource: string
  difficulty: '简单' | '中等' | '困难'
  remark: string
  source: '字典引用'
  sourceType?: 'BOM' | 'PATTERN' | 'MANUAL' | 'DICT'
  triggerField?: BomTriggerField
  linkedBomItemIds?: string[]
  routeObjectKey?: string
  inputObjectType?: TechnicalProcessObjectType
  outputObjectType?: TechnicalProcessObjectType
  consumedBomItemIds?: string[]
  predecessorEntryIds?: string[]
  isAutoGenerated?: boolean
  canRemoveAutomatically?: boolean
  hasManualOverride?: boolean
  manualNotes?: string
  manualFieldsTouched?: boolean
  requiresRemovalConfirmation?: boolean
  linkageStatus?: '已生成' | '待确认'
}

export interface BomDrivenPrepTechniqueCandidate {
  id: string
  stageCode: string
  processCode: string
  detailSplitDimensions: readonly string[]
  linkedBomItemIds?: readonly string[]
  routeObjectKey?: string
  inputObjectType?: TechnicalProcessObjectType
  outputObjectType?: TechnicalProcessObjectType
  consumedBomItemIds?: readonly string[]
  predecessorEntryIds?: readonly string[]
  sourceType?: 'BOM' | 'PATTERN' | 'MANUAL' | 'DICT'
  isAutoGenerated?: boolean
  hasManualOverride?: boolean
  manualFieldsTouched?: boolean
  manualNotes?: string
  remark?: string
  requiresRemovalConfirmation?: boolean
  linkageStatus?: '已生成' | '待确认'
}

export interface SyncPreparationProcessesFromBomResult<T extends BomDrivenPrepTechniqueCandidate> {
  techniques: T[]
  generatedProcessCodes: BomDrivenPrepProcessCode[]
  removedProcessCodes: BomDrivenPrepProcessCode[]
  pendingConfirmationProcessCodes: BomDrivenPrepProcessCode[]
  generatedOccurrenceIds: string[]
  removedOccurrenceIds: string[]
  pendingConfirmationOccurrenceIds: string[]
}

type BomRouteOccurrenceSpec = {
  id: string
  bomItemId: string
  routeObjectKey: string
  processCode: string
  processName: string
  entryType: 'PROCESS_BASELINE' | 'CRAFT'
  stageCode: 'PREP' | 'PROD'
  stageName: string
  craftCode: string
  craftName: string
  isSpecialCraft: boolean
  selectedTargetObject?: '成衣' | '完整面料' | '辅料'
  inputObjectType: TechnicalProcessObjectType
  outputObjectType: TechnicalProcessObjectType
  triggerField?: BomTriggerField
  triggerSource: string
  assignmentGranularity: 'ORDER' | 'COLOR' | 'SKU'
  detailSplitDimensions: string[]
  defaultDocType: 'TASK' | 'PREPARATION_ORDER'
  taskTypeMode: 'PROCESS' | 'CRAFT'
  consumesBomItem?: boolean
}

const GARMENT_HEAT_TRANSFER_CODES = new Set(['AUX_HEAT_TRANSFER', 'HEAT_TRANSFER', 'PROC_HEAT_TRANSFER'])
const GARMENT_DIRECT_PRINT_CODES = new Set(['AUX_DIRECT_PRINT', 'DIRECT_PRINT', 'PROC_DIRECT_PRINT'])
const BINDING_STRIP_CODES = new Set(['CRAFT_131072', 'AUX_BINDING_STRIP'])
const ELASTIC_FIXED_LENGTH_CODES = new Set(['CRAFT_3000009', 'SPECIAL_ELASTIC_FIXED_LENGTH_CUTTING'])

export function normalizeBomRequirement(value: unknown): BomRequirementFlag {
  return value === '是' || value === true ? '是' : '否'
}

function toSafeId(value: string): string {
  return value.trim().replace(/[^A-Za-z0-9_-]/g, '_') || 'UNKNOWN'
}

function toBomObjectType(type: BomProcessLinkageBomRow['type']): TechnicalProcessObjectType {
  if (type === '面料') return 'FABRIC'
  if (type === '纱线') return 'YARN'
  if (type === '辅料') return 'ACCESSORY'
  if (type === '包装材料') return 'PACKAGING_MATERIAL'
  if (type === '成衣') return 'GARMENT'
  return 'BOM_MATERIAL'
}

function getRequiredPrepProcessCodesForRow(row: BomProcessLinkageBomRow): BomDrivenPrepProcessCode[] {
  if (row.type === '成衣') return []
  const codes: BomDrivenPrepProcessCode[] = []
  if (normalizeBomRequirement(row.waterSolubleRequirement) === '是') codes.push('WATER_SOLUBLE')
  if (String(row.dyeRequirement || '无') !== '无') codes.push('DYE')
  if (String(row.printRequirement || '无') !== '无') codes.push('PRINT')
  if (String(row.embroideryRequirement || '无') !== '无') codes.push('EMBROIDERY')
  return codes
}

function getBomDrivenProcessMeta(processCode: BomDrivenPrepProcessCode): {
  processName: string
  triggerField: BomTriggerField
  assignmentGranularity: 'COLOR' | 'ORDER'
  detailSplitDimensions: string[]
} {
  if (processCode === 'PRINT') {
    return {
      processName: '印花',
      triggerField: 'printRequirement',
      assignmentGranularity: 'COLOR',
      detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
    }
  }
  if (processCode === 'WATER_SOLUBLE') {
    return {
      processName: '水溶',
      triggerField: 'waterSolubleRequirement',
      assignmentGranularity: 'ORDER',
      detailSplitDimensions: ['MATERIAL_SKU'],
    }
  }
  if (processCode === 'EMBROIDERY') {
    return {
      processName: '绣花',
      triggerField: 'embroideryRequirement',
      assignmentGranularity: 'COLOR',
      detailSplitDimensions: ['MATERIAL_SKU'],
    }
  }
  return {
    processName: '染色',
    triggerField: 'dyeRequirement',
    assignmentGranularity: 'COLOR',
    detailSplitDimensions: ['MATERIAL_SKU'],
  }
}

function buildBoundMaterialCraftOccurrenceSpec(
  row: BomProcessLinkageBomRow,
  bomItemId: string,
  craftCode: 'CRAFT_131072' | 'CRAFT_3000009',
): BomRouteOccurrenceSpec {
  const isBindingStrip = craftCode === 'CRAFT_131072'
  const craftName = isBindingStrip ? '捆条' : '橡筋定长切割'
  return {
    id: `tech-prod-${toSafeId(bomItemId)}-${craftCode.toLowerCase().replace(/_/g, '-')}`,
    bomItemId,
    routeObjectKey: `BOM:${bomItemId}`,
    processCode: 'SPECIAL_CRAFT',
    processName: isBindingStrip ? '辅助工艺' : '特种工艺',
    entryType: 'CRAFT',
    stageCode: 'PROD',
    stageName: '生产阶段',
    craftCode,
    craftName,
    isSpecialCraft: true,
    selectedTargetObject: isBindingStrip ? '完整面料' : '辅料',
    inputObjectType: isBindingStrip ? 'FABRIC' : 'ACCESSORY',
    outputObjectType: isBindingStrip ? 'BINDING_STRIP' : 'ACCESSORY',
    triggerSource: `物料清单绑定工艺：${describeBomRow(row, bomItemId)} / ${craftName}`,
    assignmentGranularity: 'SKU',
    detailSplitDimensions: ['MATERIAL_SKU', 'GARMENT_SKU'],
    defaultDocType: 'TASK',
    taskTypeMode: 'CRAFT',
    consumesBomItem: true,
  }
}

function describeBomRow(row: BomProcessLinkageBomRow, bomItemId: string): string {
  const name = String(row.materialName || row.materialCode || bomItemId).trim()
  const type = row.type || '物料'
  return `${type}：${name}`
}

function buildPrepOccurrenceSpec(
  row: BomProcessLinkageBomRow,
  bomItemId: string,
  processCode: BomDrivenPrepProcessCode,
): BomRouteOccurrenceSpec {
  const meta = getBomDrivenProcessMeta(processCode)
  const objectType = toBomObjectType(row.type)
  return {
    id: `tech-prep-${toSafeId(bomItemId)}-${processCode.toLowerCase().replace(/_/g, '-')}`,
    bomItemId,
    routeObjectKey: `BOM:${bomItemId}`,
    processCode,
    processName: meta.processName,
    entryType: 'PROCESS_BASELINE',
    stageCode: 'PREP',
    stageName: '准备阶段',
    craftCode: '',
    craftName: meta.processName,
    isSpecialCraft: false,
    inputObjectType: objectType,
    outputObjectType: objectType,
    triggerField: meta.triggerField,
    triggerSource: `物料清单自动生成：${describeBomRow(row, bomItemId)} / ${bomTriggerFieldLabel[meta.triggerField]}`,
    assignmentGranularity: meta.assignmentGranularity,
    detailSplitDimensions: meta.detailSplitDimensions,
    defaultDocType: 'PREPARATION_ORDER',
    taskTypeMode: 'PROCESS',
  }
}

function buildCutOccurrenceSpec(row: BomProcessLinkageBomRow, bomItemId: string): BomRouteOccurrenceSpec {
  return {
    id: `tech-prod-${toSafeId(bomItemId)}-cut-panel`,
    bomItemId,
    routeObjectKey: `BOM:${bomItemId}`,
    processCode: 'CUT_PANEL',
    processName: '裁剪',
    entryType: 'PROCESS_BASELINE',
    stageCode: 'PROD',
    stageName: '生产阶段',
    craftCode: '',
    craftName: '裁剪',
    isSpecialCraft: false,
    inputObjectType: 'FABRIC',
    outputObjectType: 'CUT_PIECE',
    triggerSource: `物料清单自动生成：${describeBomRow(row, bomItemId)} / 布料默认裁剪`,
    assignmentGranularity: 'SKU',
    detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU', 'GARMENT_SKU'],
    defaultDocType: 'TASK',
    taskTypeMode: 'PROCESS',
  }
}

function buildGarmentCraftOccurrenceSpec(
  row: BomProcessLinkageBomRow,
  bomItemId: string,
  craftCode: 'AUX_HEAT_TRANSFER' | 'AUX_DIRECT_PRINT',
  craftName: '烫画' | '直喷',
): BomRouteOccurrenceSpec {
  return {
    id: `tech-prod-${toSafeId(bomItemId)}-${craftCode.toLowerCase().replace(/_/g, '-')}`,
    bomItemId,
    routeObjectKey: `BOM:${bomItemId}`,
    processCode: 'SPECIAL_CRAFT',
    processName: '辅助工艺',
    entryType: 'CRAFT',
    stageCode: 'PROD',
    stageName: '生产阶段',
    craftCode,
    craftName,
    isSpecialCraft: true,
    selectedTargetObject: '成衣',
    inputObjectType: 'GARMENT',
    outputObjectType: 'GARMENT',
    triggerSource: `物料清单自动生成：${describeBomRow(row, bomItemId)} / ${craftName}`,
    assignmentGranularity: 'SKU',
    detailSplitDimensions: ['GARMENT_SKU'],
    defaultDocType: 'TASK',
    taskTypeMode: 'CRAFT',
  }
}

function listRequiredOccurrenceSpecs(bomRows: BomProcessLinkageBomRow[]): BomRouteOccurrenceSpec[] {
  return bomRows.flatMap((row, index) => {
    const bomItemId = String(row.id || `BOM-${index + 1}`).trim()
    const prepSpecs = getRequiredPrepProcessCodesForRow(row)
      .map((processCode) => buildPrepOccurrenceSpec(row, bomItemId, processCode))
    const productionSpecs: BomRouteOccurrenceSpec[] = []
    if (row.type === '面料') productionSpecs.push(buildCutOccurrenceSpec(row, bomItemId))
    const usageCodes = new Set(row.usageProcessCodes ?? [])
    if (row.type === '面料' && [...BINDING_STRIP_CODES].some((code) => usageCodes.has(code))) {
      productionSpecs.push(buildBoundMaterialCraftOccurrenceSpec(row, bomItemId, 'CRAFT_131072'))
    }
    if (row.type === '辅料' && [...ELASTIC_FIXED_LENGTH_CODES].some((code) => usageCodes.has(code))) {
      productionSpecs.push(buildBoundMaterialCraftOccurrenceSpec(row, bomItemId, 'CRAFT_3000009'))
    }
    if (row.type === '成衣') {
      if ([...GARMENT_HEAT_TRANSFER_CODES].some((code) => usageCodes.has(code))) {
        productionSpecs.push(buildGarmentCraftOccurrenceSpec(row, bomItemId, 'AUX_HEAT_TRANSFER', '烫画'))
      }
      if ([...GARMENT_DIRECT_PRINT_CODES].some((code) => usageCodes.has(code))) {
        productionSpecs.push(buildGarmentCraftOccurrenceSpec(row, bomItemId, 'AUX_DIRECT_PRINT', '直喷'))
      }
    }
    return [...prepSpecs, ...productionSpecs]
  })
}

function buildAutoGeneratedOccurrence(spec: BomRouteOccurrenceSpec): BomDrivenPrepTechnique {
  return {
    id: spec.id,
    entryType: spec.entryType,
    stageCode: spec.stageCode,
    stage: spec.stageName,
    processCode: spec.processCode,
    process: spec.processName,
    craftCode: spec.craftCode,
    technique: spec.craftName,
    assignmentGranularity: spec.assignmentGranularity,
    ruleSource: 'INHERIT_PROCESS',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: [...spec.detailSplitDimensions],
    defaultDocType: spec.defaultDocType,
    taskTypeMode: spec.taskTypeMode,
    isSpecialCraft: spec.isSpecialCraft,
    selectedTargetObject: spec.selectedTargetObject,
    targetObject: spec.selectedTargetObject === '成衣'
      ? 'GARMENT_SEMI'
      : spec.selectedTargetObject === '完整面料'
        ? 'FABRIC'
        : spec.selectedTargetObject === '辅料'
          ? 'ACCESSORY'
          : spec.inputObjectType === 'FABRIC' ? 'FABRIC' : 'BOM_MATERIAL',
    targetObjectName: spec.selectedTargetObject === '成衣'
      ? '成衣'
      : spec.selectedTargetObject === '完整面料'
        ? '面料'
        : spec.selectedTargetObject === '辅料'
          ? '辅料'
          : spec.inputObjectType === 'FABRIC' ? '面料' : 'BOM物料',
    supportedTargetObjects: spec.selectedTargetObject === '成衣'
      ? ['SEMI_FINISHED_GARMENT']
      : spec.selectedTargetObject === '完整面料'
        ? ['FULL_FABRIC']
        : spec.selectedTargetObject === '辅料'
          ? ['ACCESSORY']
          : undefined,
    supportedTargetObjectLabels: spec.selectedTargetObject === '成衣'
      ? ['成衣']
      : spec.selectedTargetObject === '完整面料'
        ? ['完整面料']
        : spec.selectedTargetObject === '辅料'
          ? ['辅料']
          : undefined,
    triggerSource: spec.triggerSource,
    difficulty: '中等',
    remark: '',
    source: '字典引用',
    sourceType: 'BOM',
    triggerField: spec.triggerField,
    linkedBomItemIds: [spec.bomItemId],
    routeObjectKey: spec.routeObjectKey,
    inputObjectType: spec.inputObjectType,
    outputObjectType: spec.outputObjectType,
    consumedBomItemIds: spec.consumesBomItem ? [spec.bomItemId] : [],
    predecessorEntryIds: [],
    isAutoGenerated: true,
    canRemoveAutomatically: true,
    hasManualOverride: false,
    manualNotes: '',
    manualFieldsTouched: false,
    requiresRemovalConfirmation: false,
    linkageStatus: '已生成',
  }
}

export function buildAutoGeneratedProcessForCode(processCode: BomDrivenPrepProcessCode): BomDrivenPrepTechnique {
  return buildAutoGeneratedOccurrence(buildPrepOccurrenceSpec({
    id: `legacy-${processCode.toLowerCase()}`,
    type: '其他',
    materialName: '待关联 BOM 物料',
  }, `legacy-${processCode.toLowerCase()}`, processCode))
}

export function isBomDrivenPrepProcessCode(processCode: string): processCode is BomDrivenPrepProcessCode {
  return processCode === 'PRINT'
    || processCode === 'WATER_SOLUBLE'
    || processCode === 'DYE'
    || processCode === 'EMBROIDERY'
}

export function getCanonicalBomDrivenPrepProcessCode(processCode: string): BomDrivenPrepProcessCode | null {
  if (isBomDrivenPrepProcessCode(processCode)) return processCode
  return null
}

export function isBomDrivenPrepTechnique(
  item: Pick<BomDrivenPrepTechniqueCandidate, 'stageCode' | 'processCode'> & Partial<BomDrivenPrepTechniqueCandidate>,
): boolean {
  if (item.stageCode !== 'PREP') return false
  if (!getCanonicalBomDrivenPrepProcessCode(item.processCode)) return false
  if (item.sourceType === 'MANUAL') return false
  return item.sourceType === 'BOM' || item.isAutoGenerated === true || item.sourceType === undefined
}

export function hasManualPrepProcessContent(item: Partial<BomDrivenPrepTechniqueCandidate>): boolean {
  if (
    item.hasManualOverride
      || item.manualFieldsTouched
      || String(item.manualNotes || '').trim()
  ) {
    return true
  }
  if (item.sourceType === 'BOM' || item.isAutoGenerated === true) return false
  return Boolean(String(item.remark || '').trim())
}

function isBomDrivenOccurrence(item: BomDrivenPrepTechniqueCandidate): boolean {
  return item.sourceType === 'BOM'
    || (item.sourceType === undefined && (
      item.isAutoGenerated === true || isBomDrivenPrepTechnique(item)
    ))
}

function getLegacyOccurrenceMatchKey(item: BomDrivenPrepTechniqueCandidate): string {
  const linkedBomItemIds = [...(item.linkedBomItemIds ?? [])]
  if (linkedBomItemIds.length !== 1) return ''
  if (item.processCode === 'SPECIAL_CRAFT') {
    const craftCode = String((item as BomDrivenPrepTechniqueCandidate & { craftCode?: string }).craftCode || '')
    return `BOM:${linkedBomItemIds[0]}:${craftCode}`
  }
  return `BOM:${linkedBomItemIds[0]}:${item.processCode}`
}

function getOccurrenceMatchKey(spec: BomRouteOccurrenceSpec): string {
  return `BOM:${spec.bomItemId}:${spec.entryType === 'CRAFT' ? spec.craftCode : spec.processCode}`
}

// 仅同步技术包内的工艺路线；本函数不创建工程任务，也不写入生产准备时效。
export function syncTechPackProcessesFromBom<T extends BomDrivenPrepTechniqueCandidate>(
  techniques: T[],
  bomRows: BomProcessLinkageBomRow[],
): SyncPreparationProcessesFromBomResult<T> {
  const requiredSpecs = listRequiredOccurrenceSpecs(bomRows)
  const requiredByKey = new Map(requiredSpecs.map((spec) => [getOccurrenceMatchKey(spec), spec]))
  const existingByKey = new Map<string, T>()
  const keptItems: T[] = []
  const removedProcessCodes: BomDrivenPrepProcessCode[] = []
  const pendingConfirmationProcessCodes: BomDrivenPrepProcessCode[] = []
  const removedOccurrenceIds: string[] = []
  const pendingConfirmationOccurrenceIds: string[] = []
  const migratedIds = new Map<string, string>()

  techniques.forEach((item) => {
    const normalizedItem = {
      ...item,
      detailSplitDimensions: [...item.detailSplitDimensions],
      linkedBomItemIds: [...(item.linkedBomItemIds ?? [])],
      consumedBomItemIds: [...(item.consumedBomItemIds ?? [])],
      predecessorEntryIds: item.predecessorEntryIds ? [...item.predecessorEntryIds] : undefined,
    } as unknown as T
    // 旧版按 BOM 记录的裁剪节点就是当前自动裁剪节点，保留其内容并迁移引用。
    const legacyBomCut = normalizedItem.processCode === 'CUT_PANEL'
      && normalizedItem.sourceType === undefined
      && (normalizedItem.linkedBomItemIds ?? []).length === 1
    if (!isBomDrivenOccurrence(normalizedItem) && !legacyBomCut) {
      keptItems.push(normalizedItem)
      return
    }

    const matchKey = getLegacyOccurrenceMatchKey(normalizedItem)
    const spec = requiredByKey.get(matchKey)
    if (spec && !existingByKey.has(matchKey)) {
      existingByKey.set(matchKey, normalizedItem)
      migratedIds.set(normalizedItem.id, spec.id)
      return
    }
    if (hasManualPrepProcessContent(normalizedItem)) {
      keptItems.push({
        ...normalizedItem,
        requiresRemovalConfirmation: true,
        linkageStatus: '待确认',
      })
      pendingConfirmationOccurrenceIds.push(normalizedItem.id)
      const prepCode = getCanonicalBomDrivenPrepProcessCode(normalizedItem.processCode)
      if (prepCode) pendingConfirmationProcessCodes.push(prepCode)
      return
    }
    removedOccurrenceIds.push(normalizedItem.id)
    const prepCode = getCanonicalBomDrivenPrepProcessCode(normalizedItem.processCode)
    if (prepCode) removedProcessCodes.push(prepCode)
  })

  const generatedOccurrenceIds: string[] = []
  const generatedProcessCodes: BomDrivenPrepProcessCode[] = []
  const generatedItems = requiredSpecs.map((spec) => {
    const matchKey = getOccurrenceMatchKey(spec)
    const existing = existingByKey.get(matchKey)
    const generated = buildAutoGeneratedOccurrence(spec)
    generatedOccurrenceIds.push(spec.id)
    const prepCode = getCanonicalBomDrivenPrepProcessCode(spec.processCode)
    if (prepCode) generatedProcessCodes.push(prepCode)
    return {
      ...generated,
      ...(existing ?? {}),
      id: spec.id,
      entryType: spec.entryType,
      stageCode: spec.stageCode,
      stage: spec.stageName,
      processCode: spec.processCode,
      process: spec.processName,
      craftCode: spec.craftCode,
      technique: spec.craftName,
      isSpecialCraft: spec.isSpecialCraft,
      selectedTargetObject: spec.selectedTargetObject,
      linkedBomItemIds: [spec.bomItemId],
      routeObjectKey: spec.routeObjectKey,
      inputObjectType: spec.inputObjectType,
      outputObjectType: spec.outputObjectType,
      consumedBomItemIds: spec.consumesBomItem ? [spec.bomItemId] : [],
      sourceType: 'BOM',
      triggerField: spec.triggerField,
      triggerSource: spec.triggerSource,
      isAutoGenerated: true,
      canRemoveAutomatically: true,
      requiresRemovalConfirmation: false,
      linkageStatus: '已生成',
      predecessorEntryIds: existing?.predecessorEntryIds ? [...existing.predecessorEntryIds] : [],
    } as unknown as T
  })

  const uniquePrepCodes = (codes: BomDrivenPrepProcessCode[]) => [...new Set(codes)]
  return {
    techniques: [...keptItems, ...generatedItems].map((item) => ({
      ...item,
      predecessorEntryIds: item.predecessorEntryIds?.map((id) => migratedIds.get(id) ?? id),
    })),
    generatedProcessCodes: uniquePrepCodes(generatedProcessCodes),
    removedProcessCodes: uniquePrepCodes(removedProcessCodes),
    pendingConfirmationProcessCodes: uniquePrepCodes(pendingConfirmationProcessCodes),
    generatedOccurrenceIds,
    removedOccurrenceIds,
    pendingConfirmationOccurrenceIds,
  }
}
