import {
  listPreparationProcesses,
  type PreparationProcessDefinition,
} from '../../data/fcs/process-craft-dict.ts'

export type BomRequirementFlag = '是' | '否'
export type BomDrivenPrepProcessCode = 'PRINT' | 'WATER_SOLUBLE' | 'DYE' | 'PREP_SHRINKING' | 'PREP_WASHING'
export type BomTriggerField =
  | 'printRequirement'
  | 'waterSolubleRequirement'
  | 'dyeRequirement'
  | 'shrinkRequirement'
  | 'washRequirement'

export const bomRequirementOptions: BomRequirementFlag[] = ['否', '是']

export const bomTriggerFieldLabel: Record<BomTriggerField, string> = {
  printRequirement: '印花需求',
  waterSolubleRequirement: '水溶要求',
  dyeRequirement: '染色需求',
  shrinkRequirement: '缩水需求',
  washRequirement: '洗水需求',
}

export interface BomProcessLinkageBomRow {
  id?: string
  printRequirement?: string
  waterSolubleRequirement?: string
  dyeRequirement?: string
  shrinkRequirement?: string
  washRequirement?: string
}

export interface BomDrivenPrepTechnique {
  id: string
  entryType: 'PROCESS_BASELINE'
  stageCode: 'PREP'
  stage: string
  processCode: string
  process: string
  craftCode: string
  technique: string
  assignmentGranularity: 'ORDER' | 'COLOR' | 'SKU' | 'DETAIL'
  ruleSource: string
  detailSplitMode: string
  detailSplitDimensions: string[]
  defaultDocType: 'DEMAND' | 'TASK'
  taskTypeMode: 'PROCESS' | 'CRAFT'
  isSpecialCraft: false
  selectedTargetObject?: string
  targetObject?: 'FABRIC' | 'BOM_MATERIAL'
  targetObjectName?: '面料' | 'BOM物料'
  supportedTargetObjects?: string[]
  supportedTargetObjectLabels?: string[]
  triggerSource: string
  outputValue: number
  outputValueUnit: string
  referenceOutputValueValue: number | null
  referenceOutputValueUnit: string
  referenceOutputValueUnitLabel: string
  referenceOutputValueNote: string
  difficulty: '简单' | '中等' | '困难'
  remark: string
  source: '字典引用'
  sourceType?: 'BOM' | 'MANUAL' | 'DICT'
  triggerField?: BomTriggerField
  linkedBomItemIds?: string[]
  isAutoGenerated?: boolean
  canRemoveAutomatically?: boolean
  hasManualOverride?: boolean
  manualNotes?: string
  manualFieldsTouched?: boolean
  requiresRemovalConfirmation?: boolean
  linkageStatus?: '已生成' | '待确认'
}

export interface SyncPreparationProcessesFromBomResult<T extends BomDrivenPrepTechnique> {
  techniques: T[]
  generatedProcessCodes: BomDrivenPrepProcessCode[]
  removedProcessCodes: BomDrivenPrepProcessCode[]
  pendingConfirmationProcessCodes: BomDrivenPrepProcessCode[]
}

const prepDefinitions = listPreparationProcesses()

function getPreparationDefinition(processCode: 'PREP_SHRINKING' | 'PREP_WASHING'): PreparationProcessDefinition {
  const definition = prepDefinitions.find((item) => item.processCode === processCode)
  if (!definition) {
    throw new Error(`缺少准备阶段工序字典：${processCode}`)
  }
  return definition
}

export function normalizeBomRequirement(value: unknown): BomRequirementFlag {
  return value === '是' || value === true ? '是' : '否'
}

export function shouldGenerateShrinkProcess(bomRows: BomProcessLinkageBomRow[]): boolean {
  return bomRows.some((item) => normalizeBomRequirement(item.shrinkRequirement) === '是')
}

export function shouldGenerateWashProcess(bomRows: BomProcessLinkageBomRow[]): boolean {
  return bomRows.some((item) => normalizeBomRequirement(item.washRequirement) === '是')
}

function shouldGeneratePrintProcess(bomRows: BomProcessLinkageBomRow[]): boolean {
  return bomRows.some((item) => String(item.printRequirement || '无') !== '无')
}

function shouldGenerateWaterSolubleProcess(bomRows: BomProcessLinkageBomRow[]): boolean {
  return bomRows.some((item) => normalizeBomRequirement(item.waterSolubleRequirement) === '是')
}

function shouldGenerateDyeProcess(bomRows: BomProcessLinkageBomRow[]): boolean {
  return bomRows.some((item) => String(item.dyeRequirement || '无') !== '无')
}

function getRequiredPrepProcessCodes(bomRows: BomProcessLinkageBomRow[]): BomDrivenPrepProcessCode[] {
  const codes: BomDrivenPrepProcessCode[] = []
  if (shouldGenerateWaterSolubleProcess(bomRows)) codes.push('WATER_SOLUBLE')
  if (shouldGenerateDyeProcess(bomRows)) codes.push('DYE')
  if (shouldGeneratePrintProcess(bomRows)) codes.push('PRINT')
  if (shouldGenerateShrinkProcess(bomRows)) codes.push('PREP_SHRINKING')
  if (shouldGenerateWashProcess(bomRows)) codes.push('PREP_WASHING')
  return codes
}

function getBomDrivenProcessMeta(processCode: BomDrivenPrepProcessCode): {
  processCode: BomDrivenPrepProcessCode
  processName: string
  processStage: 'PREP'
  processStageName: string
  targetObject: 'FABRIC' | 'BOM_MATERIAL'
  targetObjectName: '面料' | 'BOM物料'
  triggerField: BomTriggerField
  defaultDocument: 'DEMAND' | 'TASK'
  taskTypeMode: 'PROCESS'
  assignmentGranularity: 'COLOR' | 'ORDER'
  detailSplitDimensions: string[]
  defaultOutputValue: number
  outputValueUnit: string
  description: string
} {
  if (processCode === 'PRINT') {
    return {
      processCode,
      processName: '印花',
      processStage: 'PREP',
      processStageName: '准备阶段',
      targetObject: 'FABRIC',
      targetObjectName: '面料',
      triggerField: 'printRequirement',
      defaultDocument: 'TASK',
      taskTypeMode: 'PROCESS',
      assignmentGranularity: 'COLOR',
      detailSplitDimensions: ['PATTERN', 'MATERIAL_SKU'],
      defaultOutputValue: 12,
      outputValueUnit: '产值/件',
      description: '由BOM上的印花要求触发。',
    }
  }

  if (processCode === 'WATER_SOLUBLE') {
    return {
      processCode,
      processName: '水溶',
      processStage: 'PREP',
      processStageName: '准备阶段',
      targetObject: 'BOM_MATERIAL',
      targetObjectName: 'BOM物料',
      triggerField: 'waterSolubleRequirement',
      defaultDocument: 'TASK',
      taskTypeMode: 'PROCESS',
      assignmentGranularity: 'ORDER',
      detailSplitDimensions: ['MATERIAL_SKU'],
      defaultOutputValue: 70,
      outputValueUnit: '产值/批',
      description: '由 BOM 水溶要求触发。',
    }
  }

  if (processCode === 'DYE') {
    return {
      processCode,
      processName: '染色',
      processStage: 'PREP',
      processStageName: '准备阶段',
      targetObject: 'FABRIC',
      targetObjectName: '面料',
      triggerField: 'dyeRequirement',
      defaultDocument: 'TASK',
      taskTypeMode: 'PROCESS',
      assignmentGranularity: 'COLOR',
      detailSplitDimensions: ['MATERIAL_SKU'],
      defaultOutputValue: 10,
      outputValueUnit: '产值/件',
      description: '由BOM上的染色要求触发。',
    }
  }

  const definition = getPreparationDefinition(processCode)
  return {
    processCode,
    processName: definition.processName,
    processStage: definition.processStage,
    processStageName: definition.processStageName,
    targetObject: 'FABRIC',
    targetObjectName: '面料',
    triggerField: definition.bomTriggerField as BomTriggerField,
    defaultDocument: 'TASK',
    taskTypeMode: 'PROCESS',
    assignmentGranularity: 'ORDER',
    detailSplitDimensions: ['MATERIAL_SKU'],
    defaultOutputValue: processCode === 'PREP_WASHING' ? 75 : 65,
    outputValueUnit: '产值/批',
    description: definition.description,
  }
}

function buildAutoGeneratedPrepProcess(processCode: BomDrivenPrepProcessCode): BomDrivenPrepTechnique {
  const meta = getBomDrivenProcessMeta(processCode)
  return {
    id: `tech-prep-${processCode.toLowerCase().replace(/_/g, '-')}`,
    entryType: 'PROCESS_BASELINE',
    stageCode: 'PREP',
    stage: meta.processStageName,
    processCode: meta.processCode,
    process: meta.processName,
    craftCode: '',
    technique: meta.processName,
    assignmentGranularity: meta.assignmentGranularity,
    ruleSource: 'INHERIT_PROCESS',
    detailSplitMode: 'COMPOSITE',
    detailSplitDimensions: [...meta.detailSplitDimensions],
    defaultDocType: meta.defaultDocument,
    taskTypeMode: meta.taskTypeMode,
    isSpecialCraft: false,
    targetObject: meta.targetObject,
    targetObjectName: meta.targetObjectName,
    triggerSource: `物料清单自动生成：${bomTriggerFieldLabel[meta.triggerField]}`,
    outputValue: meta.defaultOutputValue,
    outputValueUnit: meta.outputValueUnit,
    referenceOutputValueValue: null,
    referenceOutputValueUnit: '',
    referenceOutputValueUnitLabel: '',
    referenceOutputValueNote: meta.description,
    difficulty: '中等',
    remark: '',
    source: '字典引用',
    sourceType: 'BOM',
    triggerField: meta.triggerField,
    isAutoGenerated: true,
    canRemoveAutomatically: true,
    hasManualOverride: false,
    manualNotes: '',
    manualFieldsTouched: false,
    requiresRemovalConfirmation: false,
    linkageStatus: '已生成',
  }
}

export function buildAutoGeneratedShrinkProcess(): BomDrivenPrepTechnique {
  return buildAutoGeneratedPrepProcess('PREP_SHRINKING')
}

export function buildAutoGeneratedWashProcess(): BomDrivenPrepTechnique {
  return buildAutoGeneratedPrepProcess('PREP_WASHING')
}

export function buildAutoGeneratedProcessForCode(processCode: BomDrivenPrepProcessCode): BomDrivenPrepTechnique {
  return buildAutoGeneratedPrepProcess(processCode)
}

export function isBomDrivenPrepProcessCode(processCode: string): processCode is BomDrivenPrepProcessCode {
  return processCode === 'PRINT'
    || processCode === 'WATER_SOLUBLE'
    || processCode === 'DYE'
    || processCode === 'PREP_SHRINKING'
    || processCode === 'PREP_WASHING'
}

function getLinkedBomItemIds(
  processCode: BomDrivenPrepProcessCode,
  bomRows: BomProcessLinkageBomRow[],
): string[] {
  return bomRows
    .filter((item) => {
      if (processCode === 'PRINT') return String(item.printRequirement || '无') !== '无'
      if (processCode === 'WATER_SOLUBLE') return normalizeBomRequirement(item.waterSolubleRequirement) === '是'
      if (processCode === 'DYE') return String(item.dyeRequirement || '无') !== '无'
      if (processCode === 'PREP_SHRINKING') return normalizeBomRequirement(item.shrinkRequirement) === '是'
      return normalizeBomRequirement(item.washRequirement) === '是'
    })
    .map((item) => String(item.id || '').trim())
    .filter(Boolean)
}

export function getCanonicalBomDrivenPrepProcessCode(processCode: string): BomDrivenPrepProcessCode | null {
  if (isBomDrivenPrepProcessCode(processCode)) return processCode
  if (processCode === 'SHRINKING') return 'PREP_SHRINKING'
  if (processCode === 'WASHING') return 'PREP_WASHING'
  return null
}

export function isBomDrivenPrepTechnique(
  item: Pick<BomDrivenPrepTechnique, 'stageCode' | 'processCode'> & Partial<BomDrivenPrepTechnique>,
): boolean {
  if (item.stageCode !== 'PREP') return false
  if (!getCanonicalBomDrivenPrepProcessCode(item.processCode)) return false
  if (item.sourceType === 'MANUAL') return false
  return item.sourceType === 'BOM' || item.isAutoGenerated === true || item.sourceType === undefined
}

export function hasManualPrepProcessContent(item: Partial<BomDrivenPrepTechnique>): boolean {
  return Boolean(
    item.hasManualOverride
      || item.manualFieldsTouched
      || String(item.manualNotes || '').trim()
      || String(item.remark || '').trim(),
  )
}

export function syncPreparationProcessesFromBom<T extends BomDrivenPrepTechnique>(
  techniques: T[],
  bomRows: BomProcessLinkageBomRow[],
): SyncPreparationProcessesFromBomResult<T> {
  const requiredCodes = getRequiredPrepProcessCodes(bomRows)
  const requiredCodeSet = new Set<BomDrivenPrepProcessCode>(requiredCodes)
  const existingAutoByCode = new Map<BomDrivenPrepProcessCode, T>()
  const manualPrepProcessCodes = new Set<BomDrivenPrepProcessCode>()
  const keptItems: T[] = []
  const removedProcessCodes: BomDrivenPrepProcessCode[] = []
  const pendingConfirmationProcessCodes: BomDrivenPrepProcessCode[] = []

  techniques.forEach((item) => {
    const normalizedItem = {
      ...item,
      detailSplitDimensions: [...item.detailSplitDimensions],
      linkedBomItemIds: [...(item.linkedBomItemIds ?? [])],
    } as T
    const canonicalCode = getCanonicalBomDrivenPrepProcessCode(normalizedItem.processCode)

    if (canonicalCode && isBomDrivenPrepTechnique(normalizedItem)) {
      if (requiredCodeSet.has(canonicalCode)) {
        existingAutoByCode.set(canonicalCode, normalizedItem)
        return
      }

      if (hasManualPrepProcessContent(normalizedItem)) {
        keptItems.push({
          ...normalizedItem,
          requiresRemovalConfirmation: true,
          linkageStatus: '待确认',
        })
        pendingConfirmationProcessCodes.push(canonicalCode)
        return
      }

      removedProcessCodes.push(canonicalCode)
      return
    }

    keptItems.push(normalizedItem)
    if (normalizedItem.stageCode === 'PREP' && canonicalCode) {
      manualPrepProcessCodes.add(canonicalCode)
    }
  })

  const generatedProcessCodes: BomDrivenPrepProcessCode[] = []
  const generatedItems = requiredCodes
    .filter((code) => !manualPrepProcessCodes.has(code))
    .map((code) => {
      const existing = existingAutoByCode.get(code)
      generatedProcessCodes.push(code)
      return {
        ...buildAutoGeneratedProcessForCode(code),
        ...(existing ?? {}),
        processCode: code,
        sourceType: 'BOM',
        triggerField: getBomDrivenProcessMeta(code).triggerField,
        linkedBomItemIds: getLinkedBomItemIds(code, bomRows),
        isAutoGenerated: true,
        canRemoveAutomatically: true,
        requiresRemovalConfirmation: false,
        linkageStatus: '已生成',
      } as T
    })

  return {
    techniques: [...keptItems, ...generatedItems],
    generatedProcessCodes,
    removedProcessCodes,
    pendingConfirmationProcessCodes,
  }
}
