import {
  canEditTechnique,
  difficultyOptions,
  bomTriggerFieldLabel,
  escapeHtml,
  getTechniqueCraftOptions,
  getTechniqueProcessOptions,
  getTechniqueReferenceMetaByCraftCode,
  getSelectedDraftMeta,
  isBomDrivenPrepTechnique,
  isPrepStage,
  isTechPackModuleReadOnly,
  stageCodeToName,
  stageOptions,
  state,
} from './context.ts'
import type { TechniqueItem } from './context.ts'
import { sortProcessRouteEntries } from '../../data/tech-pack-process-route.ts'

const routeSourceKindLabel: Record<TechniqueItem['routeSourceKind'], string> = {
  DICT_DEFAULT: '字典基础路线',
  GARMENT_CATEGORY: '品类默认路线',
  BOM_REQUIREMENT: '物料要求推导',
  PATTERN_PACKAGE: '纸样资料推导',
  PIECE_CRAFT: '裁片部位工艺',
  MANUAL: '人工调整',
}

const routeParallelAcceptanceModeLabel: Record<TechniqueItem['routeParallelAcceptanceMode'], string> = {
  INDEPENDENT_ONLY: '分别承接',
  WHOLE_GROUP_ALLOWED: '并行组整体承接',
}

type ProcessRouteGroup = {
  stepNo: number
  items: TechniqueItem[]
}

function getProcessRouteGroups(): ProcessRouteGroup[] {
  const groups = new Map<number, TechniqueItem[]>()
  sortProcessRouteEntries(state.techniques).forEach((item) => {
    groups.set(item.routeStepNo, [...(groups.get(item.routeStepNo) ?? []), item])
  })
  return Array.from(groups.entries()).map(([stepNo, items]) => ({
    stepNo,
    items: items.slice().sort((left, right) => left.routeLaneNo - right.routeLaneNo),
  }))
}

function renderRouteActionButtons(item: TechniqueItem, readonly: boolean): string {
  if (readonly) return ''
  const isParallel = Boolean(item.routeParallelGroupId)
  return `
    <button
      class="inline-flex h-7 w-7 items-center justify-center rounded border bg-background hover:bg-muted"
      title="上移"
      data-tech-action="move-technique-route-up"
      data-tech-id="${escapeHtml(item.id)}"
    >
      <i data-lucide="arrow-up" class="h-3.5 w-3.5"></i>
    </button>
    <button
      class="inline-flex h-7 w-7 items-center justify-center rounded border bg-background hover:bg-muted"
      title="下移"
      data-tech-action="move-technique-route-down"
      data-tech-id="${escapeHtml(item.id)}"
    >
      <i data-lucide="arrow-down" class="h-3.5 w-3.5"></i>
    </button>
    ${
      isParallel
        ? `<button
            class="inline-flex h-7 items-center rounded border bg-background px-2 text-xs hover:bg-muted"
            data-tech-action="remove-technique-from-parallel"
            data-tech-id="${escapeHtml(item.id)}"
          >移出并行</button>`
        : `<button
            class="inline-flex h-7 items-center rounded border bg-background px-2 text-xs hover:bg-muted"
            data-tech-action="make-techniques-parallel"
            data-tech-id="${escapeHtml(item.id)}"
            data-route-direction="previous"
          >与上一步并行</button>
          <button
            class="inline-flex h-7 items-center rounded border bg-background px-2 text-xs hover:bg-muted"
            data-tech-action="make-techniques-parallel"
            data-tech-id="${escapeHtml(item.id)}"
            data-route-direction="next"
          >与下一步并行</button>`
    }
  `
}

export function renderProcessTechniqueCard(item: TechniqueItem): string {
  const readonly = isTechPackModuleReadOnly('PROCESS')
  const canEdit = canEditTechnique(item)
  const canDelete = !isBomDrivenPrepTechnique(item)
  const isBomGenerated = item.sourceType === 'BOM' || item.isAutoGenerated === true
  const woolText = `${item.processCode || ''} ${item.process || ''} ${item.technique || ''}`
  const isWoolTechnique = item.processCode === 'WOOL' || item.woolTaskType === 'WHOLE_GARMENT' || item.woolTaskType === 'PART_PANEL' || woolText.includes('毛织')
  const isWholeWool = item.woolTaskType === 'WHOLE_GARMENT' || item.technique === '整件毛织'
  const isPartWool = item.woolTaskType === 'PART_PANEL' || item.technique === '部位毛织'
  const woolDownstream = item.downstreamTarget || (isPartWool ? '裁床待交出仓' : '后道工厂')
  const woolPackagingText = isWholeWool
    ? item.packagingRequired
      ? '需要包装节点'
      : '不需要包装节点'
    : '不需要包装节点'
  const triggerFieldText = item.triggerField ? bomTriggerFieldLabel[item.triggerField] : ''
  const autoSourceText = isBomGenerated
    ? `
      <div class="mt-2 flex flex-wrap items-center gap-2 text-xs">
        <span class="rounded border border-blue-200 bg-blue-50 px-2 py-0.5 font-medium text-blue-700">来源：物料清单自动生成</span>
        ${triggerFieldText ? `<span class="rounded border border-slate-200 bg-background px-2 py-0.5 text-slate-700">触发字段：${escapeHtml(triggerFieldText)}</span>` : ''}
        <span class="rounded border ${
          item.linkageStatus === '待确认'
            ? 'border-amber-200 bg-amber-50 text-amber-700'
            : 'border-emerald-200 bg-emerald-50 text-emerald-700'
        } px-2 py-0.5 font-medium">状态：${escapeHtml(item.linkageStatus || '已生成')}</span>
      </div>
    `
    : ''
  const removalConfirm = item.requiresRemovalConfirmation
    ? `
      <div class="mt-3 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
        <div class="font-medium">当前物料清单已无${escapeHtml(item.process)}需求，但准备阶段“${escapeHtml(item.process)}”已存在人工维护内容。是否保留该工序？</div>
        ${
          readonly
            ? ''
            : `<div class="mt-2 flex flex-wrap gap-2">
                <button type="button" class="rounded border border-amber-300 bg-white px-2 py-1 hover:bg-amber-100" data-tech-action="keep-bom-prep-process" data-tech-id="${escapeHtml(item.id)}">保留${escapeHtml(item.process)}</button>
                <button type="button" class="rounded bg-amber-600 px-2 py-1 font-medium text-white hover:bg-amber-700" data-tech-action="remove-bom-prep-process" data-tech-id="${escapeHtml(item.id)}">移除${escapeHtml(item.process)}</button>
              </div>`
        }
      </div>
    `
    : ''
  const woolRuleBlock = isWoolTechnique
    ? `
      <div class="rounded-md border border-emerald-100 bg-emerald-50/60 px-3 py-2">
        <div class="grid gap-2 text-xs text-slate-700 md:grid-cols-4">
          <div>
            <span class="text-muted-foreground">任务类型</span>
            <p class="mt-1 font-medium text-slate-800">${escapeHtml(item.technique || item.woolTaskType || '-')}</p>
          </div>
          <div>
            <span class="text-muted-foreground">完成交出</span>
            <p class="mt-1 font-medium text-slate-800">${escapeHtml(woolDownstream)}</p>
          </div>
          <div>
            <span class="text-muted-foreground">菲票规则</span>
            <p class="mt-1 font-medium text-slate-800">${item.requiresFeiTicket ? '打印毛织菲票' : '不打印毛织菲票'}</p>
          </div>
          <div>
            <span class="text-muted-foreground">是否需要包装节点</span>
            ${
              !readonly && isWholeWool
                ? `<label class="mt-1 flex items-center gap-2 font-medium text-slate-800">
                    <input type="checkbox" data-tech-field="tech-packaging-required" data-tech-id="${escapeHtml(item.id)}" ${item.packagingRequired ? 'checked' : ''} />
                    需要
                  </label>`
                : `<p class="mt-1 font-medium text-slate-800">${escapeHtml(woolPackagingText)}</p>`
            }
          </div>
        </div>
      </div>
    `
    : ''
  const referenceValueText =
    item.referenceOutputValueValue !== null && item.referenceOutputValueUnitLabel
      ? `${item.referenceOutputValueValue} ${item.referenceOutputValueUnitLabel}`
      : '暂无平台参考'
  const targetObjectText =
    item.isSpecialCraft && item.selectedTargetObject
      ? `<span class="rounded border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[11px] font-medium text-emerald-700">作用对象：${escapeHtml(item.selectedTargetObject)}</span>`
      : item.targetObjectName
        ? `<span class="rounded border border-emerald-200 bg-emerald-50 px-2 py-0.5 text-[11px] font-medium text-emerald-700">对象：${escapeHtml(item.targetObjectName)}</span>`
      : ''
  return `
    <article class="space-y-3 rounded-lg border bg-muted/20 p-3" data-tech-process-card="${escapeHtml(item.processCode)}">
      <div class="flex items-start justify-between gap-3">
        <div class="space-y-1">
          <div class="flex flex-wrap items-center gap-2">
            <span class="text-sm font-semibold">${escapeHtml(item.technique)}</span>
            <span class="rounded border border-slate-200 bg-background px-2 py-0.5 text-[11px] font-medium text-slate-700">${escapeHtml(item.process)}</span>
            ${targetObjectText}
            <span class="rounded border border-blue-200 bg-blue-50 px-2 py-0.5 text-[11px] font-medium text-blue-700">当前款产值 基线</span>
          </div>
          ${autoSourceText}
          ${removalConfirm}
        </div>
        <div class="flex flex-wrap items-center justify-end gap-1">
          ${renderRouteActionButtons(item, readonly)}
          ${
            canEdit && !readonly
              ? `<button class="inline-flex h-7 w-7 items-center justify-center rounded hover:bg-muted" data-tech-action="edit-technique" data-tech-id="${escapeHtml(item.id)}">
                  <i data-lucide="edit-2" class="h-3.5 w-3.5"></i>
                </button>`
              : ''
          }
          ${
            canDelete && !readonly
              ? `<button class="inline-flex h-7 w-7 items-center justify-center rounded text-red-600 hover:bg-red-50" data-tech-action="delete-technique" data-tech-id="${escapeHtml(item.id)}">
                  <i data-lucide="trash-2" class="h-3.5 w-3.5"></i>
                </button>`
              : ''
          }
        </div>
      </div>
      ${woolRuleBlock}
      <div class="rounded-md border border-blue-100 bg-blue-50/60 px-3 py-2">
        <div class="grid gap-2 text-xs md:grid-cols-3">
          <div>
            <span class="text-muted-foreground">平台参考</span>
            <p class="mt-1 font-medium text-slate-800">${escapeHtml(referenceValueText)}</p>
          </div>
          <div>
            <span class="text-muted-foreground">默认推荐单位</span>
            <p class="mt-1 font-medium text-slate-800">${escapeHtml(item.referenceOutputValueUnitLabel || item.outputValueUnit || '-')}</p>
          </div>
          <div>
            <span class="text-muted-foreground">参考说明</span>
            <p class="mt-1 leading-5 text-slate-700">${escapeHtml(item.referenceOutputValueNote)}</p>
          </div>
        </div>
      </div>
      <div class="grid grid-cols-1 gap-3 text-sm md:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]">
        ${
          readonly
            ? `
              <div class="space-y-1">
                <span class="text-xs text-muted-foreground">当前款产值 基线</span>
                <p class="font-medium text-slate-800">${escapeHtml(String(item.outputValue || '-'))} ${escapeHtml(item.outputValueUnit || item.referenceOutputValueUnitLabel || '')}</p>
              </div>
              <div class="space-y-1">
                <span class="text-xs text-muted-foreground">难度辅助说明</span>
                <p class="font-medium text-slate-800">${escapeHtml(item.difficulty || '-')}</p>
              </div>
              <div class="space-y-1 md:col-span-2">
                <span class="text-xs text-muted-foreground">基线备注</span>
                <p class="text-slate-700">${escapeHtml(item.remark || '-')}</p>
              </div>
            `
            : `
              <label class="space-y-1">
                <span class="text-xs text-muted-foreground">当前款产值 基线</span>
                <div class="flex items-center gap-2">
                  <input
                    type="number"
                    class="h-8 w-28 rounded-md border px-2 text-sm"
                    value="${item.outputValue}"
                    data-tech-field="tech-output-value"
                    data-tech-id="${item.id}"
                  />
                  <span class="inline-flex h-8 items-center rounded-md border bg-background px-3 text-xs font-medium text-slate-700">
                    ${escapeHtml(item.outputValueUnit || item.referenceOutputValueUnitLabel || '-')}
                  </span>
                </div>
              </label>
              <label class="space-y-1">
                <span class="text-xs text-muted-foreground">难度辅助说明</span>
                <select class="mt-1 h-8 w-full rounded-md border px-2 text-sm" data-tech-field="tech-difficulty" data-tech-id="${item.id}">
                  ${difficultyOptions.map((option) => `<option value="${option}" ${item.difficulty === option ? 'selected' : ''}>${option}</option>`).join('')}
                </select>
              </label>
              <label class="md:col-span-2">
                <span class="text-xs text-muted-foreground">基线备注</span>
                <input
                  class="mt-1 h-8 w-full rounded-md border px-2 text-sm"
                  value="${escapeHtml(item.remark)}"
                  data-tech-field="tech-remark"
                  data-tech-id="${item.id}"
                  placeholder="基线备注"
                />
              </label>
            `
        }
      </div>
    </article>
  `
}

function renderProcessRouteEditor(readonly: boolean): string {
  const routeGroups = getProcessRouteGroups()
  if (routeGroups.length === 0) {
    return `
      <section class="rounded-lg border bg-card px-4 py-8 text-center text-sm text-muted-foreground">
        暂无工序工艺，请先新增生产阶段或后道阶段工序。
      </section>
    `
  }

  return `
    <section class="space-y-3">
      ${routeGroups
        .map((group) => {
          const isParallel = group.items.length > 1
          const acceptanceMode = group.items[0]?.routeParallelAcceptanceMode ?? 'INDEPENDENT_ONLY'
          return `
            <article class="rounded-lg border bg-card">
              <header class="flex flex-wrap items-center justify-between gap-3 border-b px-4 py-3">
                <div class="flex flex-wrap items-center gap-2">
                  <span class="text-sm font-semibold">第 ${group.stepNo} 步</span>
                  ${
                    isParallel
                      ? '<span class="rounded border border-blue-200 bg-blue-50 px-2 py-0.5 text-xs font-medium text-blue-700">并行处理</span>'
                      : '<span class="rounded border border-slate-200 bg-slate-50 px-2 py-0.5 text-xs font-medium text-slate-600">串行处理</span>'
                  }
                  ${
                    isParallel
                      ? `<span class="text-xs text-muted-foreground">${escapeHtml(routeParallelAcceptanceModeLabel[acceptanceMode])}</span>`
                      : ''
                  }
                </div>
                ${
                  isParallel && !readonly
                    ? `<button
                        type="button"
                        class="inline-flex items-center rounded border px-2 py-1 text-xs hover:bg-muted"
                        data-tech-action="toggle-parallel-group-acceptance"
                        data-tech-id="${escapeHtml(group.items[0].id)}"
                      >
                        ${escapeHtml(
                          acceptanceMode === 'WHOLE_GROUP_ALLOWED'
                            ? '切换为分别承接'
                            : '允许并行组整体承接',
                        )}
                      </button>`
                    : ''
                }
              </header>
              <div class="grid gap-3 p-4 ${isParallel ? 'md:grid-cols-2 xl:grid-cols-3' : ''}">
                ${group.items.map((item) => renderProcessTechniqueCard(item)).join('')}
              </div>
            </article>
          `
        })
        .join('')}
    </section>
  `
}

function renderProcessRouteBatchTable(): string {
  const items = sortProcessRouteEntries(state.techniques)
  return `
    <section class="rounded-lg border bg-card">
      <header class="border-b px-4 py-3">
        <h4 class="text-sm font-semibold">批量辅助</h4>
      </header>
      <div class="overflow-x-auto">
        <table class="w-full min-w-[760px] text-left text-sm">
          <thead class="bg-muted/40 text-xs text-muted-foreground">
            <tr>
              <th class="px-4 py-2 font-medium">工序</th>
              <th class="px-4 py-2 font-medium">来源</th>
              <th class="px-4 py-2 font-medium">步骤</th>
              <th class="px-4 py-2 font-medium">并行组</th>
              <th class="px-4 py-2 font-medium">承接口径</th>
            </tr>
          </thead>
          <tbody class="divide-y">
            ${
              items.length === 0
                ? `<tr><td colspan="5" class="px-4 py-6 text-center text-muted-foreground">暂无工序路线</td></tr>`
                : items
                    .map((item) => `
                      <tr>
                        <td class="px-4 py-3">
                          <div class="font-medium text-slate-800">${escapeHtml(item.technique)}</div>
                          <div class="mt-0.5 text-xs text-muted-foreground">${escapeHtml(item.stage)} / ${escapeHtml(item.process)}</div>
                        </td>
                        <td class="px-4 py-3">${escapeHtml(routeSourceKindLabel[item.routeSourceKind])}</td>
                        <td class="px-4 py-3">第 ${item.routeStepNo} 步</td>
                        <td class="px-4 py-3">${item.routeParallelGroupId ? `并行处理：第 ${item.routeStepNo} 步` : '无'}</td>
                        <td class="px-4 py-3">${escapeHtml(routeParallelAcceptanceModeLabel[item.routeParallelAcceptanceMode])}</td>
                      </tr>
                    `)
                    .join('')
            }
          </tbody>
        </table>
      </div>
    </section>
  `
}

function renderProcessRouteRelations(): string {
  const bomById = new Map(state.bomItems.map((item) => [item.id, item]))
  const patternById = new Map(state.patternItems.map((item) => [item.id, item]))
  const rows = state.techniques.flatMap((item) => {
    const itemRows: Array<{ process: string; source: string; detail: string }> = []
    const bomNames = (item.linkedBomItemIds ?? [])
      .map((id) => {
        const bom = bomById.get(id)
        return bom ? `${bom.materialName}（${bom.materialCode || id}）` : id
      })
      .filter((text) => text.trim().length > 0)
    if (bomNames.length > 0) {
      itemRows.push({ process: item.technique, source: '物料清单', detail: bomNames.join('、') })
    }

    const patternNames = (item.linkedPatternIds ?? [])
      .map((id) => patternById.get(id)?.name || id)
      .filter((text) => text.trim().length > 0)
    if (patternNames.length > 0) {
      itemRows.push({ process: item.technique, source: '纸样资料', detail: patternNames.join('、') })
    }

    if (item.isSpecialCraft || item.selectedTargetObject || item.targetObjectName) {
      itemRows.push({
        process: item.technique,
        source: '裁片部位工艺',
        detail: item.selectedTargetObject || item.targetObjectName || '按工序对象承接',
      })
    }

    if (item.triggerSource) {
      itemRows.push({ process: item.technique, source: '触发条件', detail: item.triggerSource })
    }

    return itemRows
  })

  return `
    <section class="rounded-lg border bg-card">
      <header class="border-b px-4 py-3">
        <h4 class="text-sm font-semibold">来源关系查看</h4>
      </header>
      <div class="divide-y">
        ${
          rows.length === 0
            ? '<div class="px-4 py-6 text-center text-sm text-muted-foreground">暂无物料、纸样或裁片部位推导关系。</div>'
            : rows
                .map((row) => `
                  <div class="grid gap-2 px-4 py-3 text-sm md:grid-cols-[160px_140px_minmax(0,1fr)]">
                    <div class="font-medium text-slate-800">${escapeHtml(row.process)}</div>
                    <div class="text-slate-700">${escapeHtml(row.source)}</div>
                    <div class="text-muted-foreground">${escapeHtml(row.detail)}</div>
                  </div>
                `)
                .join('')
        }
      </div>
    </section>
  `
}

export function renderProcessTab(): string {
  const readonly = isTechPackModuleReadOnly('PROCESS')
  const routeConfirmed = state.processRouteStatus === 'CONFIRMED'
  const confirmMeta = routeConfirmed
    ? `确认人：${state.processRouteConfirmedBy || '-'}　确认时间：${state.processRouteConfirmedAt || '-'}`
    : state.processRouteUpdatedAt
      ? `最近调整：${state.processRouteUpdatedBy || '-'}　${state.processRouteUpdatedAt}`
      : '路线待跟单确认'
  return `
    <section class="space-y-4">
      <header class="rounded-lg border bg-card px-4 py-3">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <div>
            <div class="flex flex-wrap items-center gap-2">
              <h3 class="text-base font-semibold">工序工艺</h3>
              <span class="rounded border px-2 py-0.5 text-xs font-medium ${
                routeConfirmed
                  ? 'border-emerald-200 bg-emerald-50 text-emerald-700'
                  : 'border-amber-200 bg-amber-50 text-amber-700'
              }">${routeConfirmed ? '路线已确认' : '路线待确认'}</span>
            </div>
            <p class="mt-1 text-xs text-muted-foreground">${escapeHtml(confirmMeta)}</p>
          </div>
          <div class="flex flex-wrap items-center gap-2">
            ${stageOptions
              .filter((stage) => !isPrepStage(stage))
              .map((stage) =>
                readonly
                  ? ''
                  : `<button
                      class="inline-flex items-center rounded border px-2 py-1 text-xs hover:bg-muted"
                      data-tech-action="open-add-technique"
                      data-stage="${escapeHtml(stage)}"
                    >
                      <i data-lucide="plus" class="mr-1 h-3.5 w-3.5"></i>
                      新增${escapeHtml(stage)}工序
                    </button>`,
              )
              .join('')}
            ${
              readonly || state.techniques.length === 0
                ? ''
                : `<button
                    class="inline-flex items-center rounded bg-blue-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-blue-700"
                    data-tech-action="confirm-process-route"
                  >
                    <i data-lucide="check-circle-2" class="mr-1 h-3.5 w-3.5"></i>
                    确认工艺路线
                  </button>`
            }
          </div>
        </div>
      </header>
      ${renderProcessRouteEditor(readonly)}
      ${renderProcessRouteBatchTable()}
      ${renderProcessRouteRelations()}
    </section>
  `
}


export function renderAddTechniqueDialog(): string {
  if (!state.addTechniqueDialogOpen) return ''
  if (isTechPackModuleReadOnly('PROCESS')) return ''
  const selectedMeta = getSelectedDraftMeta()
  const isEdit = Boolean(state.editTechniqueId)
  const editingTechnique = state.editTechniqueId
    ? state.techniques.find((item) => item.id === state.editTechniqueId) ?? null
    : null
  const isLockedPrepTechnique = editingTechnique ? isBomDrivenPrepTechnique(editingTechnique) : false
  const currentStageName = state.newTechnique.stageCode
    ? stageCodeToName.get(state.newTechnique.stageCode) || state.newTechnique.stageCode
    : ''
  const processOptions = getTechniqueProcessOptions(state.newTechnique.stageCode)
  const availableCraftOptions = getTechniqueCraftOptions(
    state.newTechnique.stageCode,
    state.newTechnique.processCode,
  )
  const selectedCraft = availableCraftOptions.find((item) => item.craftCode === state.newTechnique.craftCode) ?? null
  const targetOptions = selectedCraft?.isSpecialCraft ? selectedCraft.supportedTargetObjectLabels ?? [] : []
  const isWoolCraft = selectedCraft?.processCode === 'WOOL'
  const isWholeWool = selectedCraft?.craftName === '整件毛织'
  const woolDownstream = selectedCraft?.craftName === '部位毛织' ? '裁床待交出仓' : '后道工厂'
  const draftReferenceMeta = getTechniqueReferenceMetaByCraftCode(state.newTechnique.craftCode)
  const draftReferenceText =
    draftReferenceMeta.referenceOutputValueValue !== null && draftReferenceMeta.referenceOutputValueUnitLabel
      ? `${draftReferenceMeta.referenceOutputValueValue} ${draftReferenceMeta.referenceOutputValueUnitLabel}`
      : '暂无平台参考'

  return `
    <div class="fixed inset-0 z-[60] flex items-center justify-center bg-black/45 p-4" data-dialog-backdrop="true">
      <section class="w-full max-w-lg rounded-xl border bg-background shadow-2xl" data-dialog-panel="true">
        <header class="border-b px-6 py-4">
          <h3 class="text-lg font-semibold">${isEdit ? '编辑工序配置' : '新增工序配置'}</h3>
        </header>
        <div class="space-y-4 px-6 py-4">
          <label class="space-y-1">
            <span class="text-sm">所属阶段</span>
            <div class="w-full rounded-md border bg-muted/20 px-3 py-2 text-sm text-muted-foreground">
              ${escapeHtml(currentStageName || '-')}
            </div>
          </label>

          <label class="space-y-1">
            <span class="text-sm">所属工序 <span class="text-red-500">*</span></span>
            <select class="w-full rounded-md border px-3 py-2 text-sm" data-tech-field="new-technique-process-code" ${isLockedPrepTechnique ? 'disabled' : ''}>
              <option value="">选择工序</option>
              ${processOptions
                .map(
                  (item) =>
                    `<option value="${item.processCode}" ${state.newTechnique.processCode === item.processCode ? 'selected' : ''}>${item.processName}</option>`,
                )
                .join('')}
            </select>
          </label>

          <label class="space-y-1">
            <span class="text-sm">工艺 <span class="text-red-500">*</span></span>
            <select class="w-full rounded-md border px-3 py-2 text-sm" data-tech-field="new-technique-craft-code" ${isLockedPrepTechnique ? 'disabled' : ''}>
              <option value="">选择工艺</option>
              ${availableCraftOptions
                .map(
                  (item) =>
                    `<option value="${item.craftCode}" ${state.newTechnique.craftCode === item.craftCode ? 'selected' : ''}>${item.craftName}</option>`,
                )
                .join('')}
            </select>
          </label>

          ${
            selectedCraft?.isSpecialCraft
              ? `
                <label class="space-y-1">
                  <span class="text-sm">作用对象 <span class="text-red-500">*</span></span>
                  ${
                    targetOptions.length <= 1
                      ? `<div class="w-full rounded-md border bg-muted/20 px-3 py-2 text-sm text-slate-700">${escapeHtml(targetOptions[0] || '请选择')}</div>`
                      : `<select class="w-full rounded-md border px-3 py-2 text-sm" data-tech-field="new-technique-target-object">
                          <option value="">请选择作用对象</option>
                          ${targetOptions
                            .map((item) => `<option value="${item}" ${state.newTechnique.selectedTargetObject === item ? 'selected' : ''}>${item}</option>`)
                            .join('')}
                        </select>`
                  }
                </label>
              `
              : ''
          }

          ${
            isWoolCraft
              ? `
                <div class="rounded-md border border-emerald-100 bg-emerald-50/60 px-3 py-3 text-sm">
                  <div class="font-medium text-emerald-800">毛织任务规则</div>
                  <div class="mt-2 grid gap-2 text-xs text-slate-700 md:grid-cols-2">
                    <div>任务类型：${escapeHtml(selectedCraft?.craftName || '-')}</div>
                    <div>领料方式：染厂/面料仓送料到厂</div>
                    <div>完成交出：${escapeHtml(woolDownstream)}</div>
                    <div>菲票规则：${selectedCraft?.craftName === '部位毛织' ? '按毛织部位打印菲票' : '整件毛织不打印菲票'}</div>
                  </div>
                  ${
                    isWholeWool
                      ? `<label class="mt-3 flex items-center gap-2 text-xs text-slate-700">
                          <input type="checkbox" data-tech-field="new-technique-packaging-required" value="是" ${state.newTechnique.packagingRequired ? 'checked' : ''} />
                          本单整件毛织需要包装节点
                        </label>`
                      : ''
                  }
                </div>
              `
              : ''
          }

          <div class="rounded-md border border-blue-100 bg-blue-50/60 px-3 py-3">
            <p class="text-xs font-medium text-blue-700">工艺理论标准（参考）</p>
            <div class="mt-2 grid gap-2 text-xs md:grid-cols-3">
              <div>
                <span class="text-muted-foreground">平台参考</span>
                <p class="mt-1 font-medium text-slate-800">${escapeHtml(draftReferenceText)}</p>
              </div>
              <div>
                <span class="text-muted-foreground">默认推荐单位</span>
                <p class="mt-1 font-medium text-slate-800">${escapeHtml(draftReferenceMeta.referenceOutputValueUnitLabel || '-')}</p>
              </div>
              <div>
                <span class="text-muted-foreground">说明</span>
                <p class="mt-1 leading-5 text-slate-700">${escapeHtml(draftReferenceMeta.referenceOutputValueNote)}</p>
              </div>
            </div>
          </div>

          <div class="grid grid-cols-2 gap-4">
            <label class="space-y-1">
              <span class="text-sm">当前款产值 基线</span>
              <input type="number" class="w-full rounded-md border px-3 py-2 text-sm" data-tech-field="new-technique-output-value" value="${escapeHtml(state.newTechnique.outputValue)}" placeholder="0" />
            </label>
            <label class="space-y-1">
              <span class="text-sm">默认推荐产值单位</span>
              <div class="w-full rounded-md border bg-muted/20 px-3 py-2 text-sm text-slate-700">
                ${escapeHtml(state.newTechnique.outputValueUnit || draftReferenceMeta.referenceOutputValueUnitLabel || '-')}
              </div>
            </label>
          </div>

          <label class="space-y-1">
            <span class="text-sm">难度辅助说明</span>
            <select class="w-full rounded-md border px-3 py-2 text-sm" data-tech-field="new-technique-difficulty">
              ${difficultyOptions
                .map((option) => `<option value="${option}" ${state.newTechnique.difficulty === option ? 'selected' : ''}>${option}</option>`)
                .join('')}
            </select>
          </label>

          <label class="space-y-1">
            <span class="text-sm">基线备注</span>
            <textarea rows="2" class="w-full rounded-md border px-3 py-2 text-sm" data-tech-field="new-technique-remark" placeholder="备注信息">${escapeHtml(state.newTechnique.remark)}</textarea>
          </label>
        </div>

        <footer class="flex items-center justify-end gap-2 border-t px-6 py-4">
          <button class="rounded-md border px-4 py-2 text-sm hover:bg-muted" data-tech-action="close-add-technique">取消</button>
          <button class="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 ${
            selectedMeta ? '' : 'pointer-events-none opacity-50'
          }" data-tech-action="save-technique">${isEdit ? '保存' : '确认新增'}</button>
        </footer>
      </section>
    </div>
  `
}
