import LogicFlow from '@logicflow/core'
import { Dagre } from '@logicflow/layout'
import { materializeLegacyProcessRoutePredecessors } from '../../data/tech-pack-process-route.ts'
import type { TechnicalProcessObjectType } from '../../data/pcs-technical-data-version-types.ts'
import { isTechPackModuleReadOnly, state } from './context.ts'

const objectTypeLabel: Record<TechnicalProcessObjectType, string> = {
  BOM_MATERIAL: 'BOM 物料',
  FABRIC: '布料',
  YARN: '纱线',
  ACCESSORY: '辅料',
  PACKAGING_MATERIAL: '包装材料',
  CUT_PIECE: '裁片',
  KNITTED_PANEL: '毛织衣片',
  GARMENT: '成衣',
  PACKED_GARMENT: '已包装成衣',
}

const stageStyle: Record<string, { fill: string; stroke: string }> = {
  PREP: { fill: '#eff6ff', stroke: '#2563eb' },
  PROD: { fill: '#ecfdf5', stroke: '#059669' },
  POST: { fill: '#fff7ed', stroke: '#ea580c' },
}

let activeGraph: LogicFlow | null = null
let mountSerial = 0

function dispatchRouteCommand(
  type: 'add-edge' | 'remove-edge' | 'undo' | 'redo',
  sourceEntryId = '',
  targetEntryId = '',
): void {
  window.dispatchEvent(new CustomEvent('higood:process-route-command', {
    detail: { type, sourceEntryId, targetEntryId },
  }))
}

function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function branchLabel(entry: (typeof state.techniques)[number]): string {
  const keys = [...new Set(state.techniques.map((item) => item.routeObjectKey).filter(Boolean))]
  const index = entry.routeObjectKey ? keys.indexOf(entry.routeObjectKey) + 1 : 0
  const bom = state.bomItems.find((item) => entry.linkedBomItemIds?.includes(item.id))
  const object = bom?.type || (entry.routeObjectKey?.startsWith('GARMENT:') ? '成衣' : '对象')
  return index ? `${object}分支 ${index}` : '来源待确认'
}

function renderNodeInspector(entryId: string): void {
  const inspector = document.querySelector<HTMLElement>('[data-tech-process-route-inspector]')
  const entry = state.techniques.find((item) => item.id === entryId)
  if (!inspector || !entry) return
  const readonly = isTechPackModuleReadOnly('PROCESS')
  const source = entry.triggerSource || entry.source || '按工艺字典及当前技术包配置'
  const canDelete = !readonly && !(entry.sourceType === 'BOM' || entry.isAutoGenerated)
  inspector.innerHTML = `
    <div class="flex flex-wrap items-start justify-between gap-3">
      <div>
        <div class="font-medium text-slate-800">${escapeHtml(entry.technique)} · ${escapeHtml(entry.stage)}</div>
        <div class="mt-1">来源：${escapeHtml(source)}</div>
        <div class="mt-1">${escapeHtml(branchLabel(entry))}　${escapeHtml(formatObjectType(entry.inputObjectType))} → ${escapeHtml(formatObjectType(entry.outputObjectType))}</div>
      </div>
      ${readonly ? '' : `<div class="flex gap-2"><button type="button" class="rounded border bg-white px-2 py-1 text-slate-700 hover:bg-muted" data-tech-action="edit-technique" data-tech-id="${escapeHtml(entry.id)}">编辑工艺</button>${canDelete ? `<button type="button" class="rounded border border-red-200 bg-white px-2 py-1 text-red-700 hover:bg-red-50" data-tech-action="delete-technique" data-tech-id="${escapeHtml(entry.id)}">删除节点</button>` : ''}</div>`}
    </div>
  `
}

function formatObjectType(type: TechnicalProcessObjectType | undefined): string {
  return type ? objectTypeLabel[type] : '待确认'
}

function buildGraphData(): LogicFlow.GraphConfigData {
  const entries = materializeLegacyProcessRoutePredecessors(state.techniques)
  const entryById = new Map(entries.map((entry) => [entry.id, entry]))
  return {
    nodes: entries.map((entry, index) => {
      const style = stageStyle[entry.stageCode] ?? stageStyle.PROD
      return {
        id: entry.id,
        type: 'rect',
        x: 140 + ((entry.routeStepNo ?? index + 1) - 1) * 280,
        y: 90 + ((entry.routeLaneNo ?? 1) - 1) * 150,
        text: `${entry.technique} · ${branchLabel(entry)}\n${formatObjectType(entry.inputObjectType)} → ${formatObjectType(entry.outputObjectType)}`,
        draggable: false,
        resizable: false,
        rotatable: false,
        properties: {
          width: 220,
          height: 86,
          radius: 10,
          style: {
            fill: style.fill,
            stroke: style.stroke,
            strokeWidth: 1.5,
          },
          textStyle: {
            color: '#0f172a',
            fontSize: 13,
            lineHeight: 1.45,
          },
        },
      }
    }),
    edges: entries.flatMap((entry) => (entry.predecessorEntryIds ?? [])
      .filter((predecessorId) => entryById.has(predecessorId))
      .map((predecessorId) => ({
        id: `route-edge:${predecessorId}:${entry.id}`,
        type: 'polyline',
        sourceNodeId: predecessorId,
        targetNodeId: entry.id,
      }))),
  }
}

function mountProcessRouteGraph(container: HTMLElement): void {
  activeGraph?.destroy()
  activeGraph = null
  container.replaceChildren()

  const readonly = isTechPackModuleReadOnly('PROCESS')
  const lf = new LogicFlow({
    container,
    plugins: [Dagre],
    grid: false,
    edgeType: 'polyline',
    background: { backgroundColor: '#ffffff' },
    keyboard: { enabled: false },
    history: false,
    textEdit: false,
    allowResize: false,
    allowRotate: false,
    stopMoveGraph: false,
    stopScrollGraph: true,
    stopZoomGraph: false,
    snapline: false,
    isSilentMode: readonly,
  })
  activeGraph = lf
  lf.render(buildGraphData())
  const dagre = (lf.extension as unknown as { dagre?: { layout: (option: Record<string, unknown>) => void } }).dagre
  const applyAutoLayout = (): void => dagre?.layout({
    rankdir: 'LR',
    align: 'UL',
    nodesep: 70,
    ranksep: 100,
    isDefaultAnchor: true,
  })
  applyAutoLayout()
  lf.fitView(34, 34)

  const panel = container.closest<HTMLElement>('[data-testid="tech-pack-process-route-graph-panel"]')
  panel?.addEventListener('click', (event) => {
    const actionNode = (event.target as HTMLElement).closest<HTMLElement>('[data-tech-route-graph-action]')
    const action = actionNode?.dataset.techRouteGraphAction
    if (action === 'auto-layout') {
      applyAutoLayout()
      lf.fitView(34, 34)
    } else if (action === 'fit-view') {
      lf.fitView(34, 34)
    } else if (action === 'undo' || action === 'redo') {
      dispatchRouteCommand(action)
    }
  })
  lf.on('node:click', ({ data }) => renderNodeInspector(data.id))
  if (!readonly) {
    lf.on('node:dbclick', ({ data }) => {
      renderNodeInspector(data.id)
      document.querySelector<HTMLElement>(`[data-tech-process-route-inspector] [data-tech-action="edit-technique"][data-tech-id="${CSS.escape(data.id)}"]`)?.click()
    })
  }

  if (!readonly) {
    lf.on('edge:add', ({ data }) => {
      dispatchRouteCommand('add-edge', data.sourceNodeId, data.targetNodeId)
    })
    lf.on('edge:dbclick', ({ data }) => {
      lf.deleteEdge(data.id)
    })
    lf.on('edge:delete', ({ data }) => {
      dispatchRouteCommand('remove-edge', data.sourceNodeId, data.targetNodeId)
    })
  }
}

export function scheduleProcessRouteLogicFlowMount(): void {
  if (typeof window === 'undefined') return
  const serial = ++mountSerial
  window.setTimeout(() => {
    if (serial !== mountSerial) return
    const container = document.querySelector<HTMLElement>('[data-tech-process-route-graph]')
    if (!container) {
      activeGraph?.destroy()
      activeGraph = null
      return
    }
    mountProcessRouteGraph(container)
  }, 0)
}
