// 生产需求 Mock 数据

export type LegacyType = 'ID_PURCHASE' | 'GOODS_PURCHASE'
export type SourceSystem = 'LEGACY' | 'NEW'
export type Priority = 'URGENT' | 'HIGH' | 'NORMAL'
export type DemandStatus = 'PENDING_CONVERT' | 'CONVERTED' | 'HOLD' | 'CANCELLED'
export type TechPackStatus = 'INCOMPLETE' | 'RELEASED'

export interface SkuLine {
  skuCode: string
  size: string
  color: string
  qty: number
}

export interface ProductionDemand {
  demandId: string
  legacyType: LegacyType
  legacyOrderNo: string
  sourceSystem: SourceSystem
  spuCode: string
  spuName: string
  imageUrl: string
  category?: string
  marketScopes: string[]
  priority: Priority
  demandStatus: DemandStatus
  techPackStatus: TechPackStatus
  techPackVersionLabel: string
  requiredDeliveryDate: string | null
  requiredQtyTotal: number
  constraintsNote: string
  skuLines: SkuLine[]
  hasProductionOrder: boolean
  productionOrderId: string | null
  createdAt: string
  updatedAt: string
}

// Mock 数据 - 覆盖所有状态组合
export const productionDemands: ProductionDemand[] = [
  // PENDING_CONVERT + INCOMPLETE + 未生成
  {
    demandId: 'DEM-202603-0001',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240776',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-001',
    spuName: 'Kemeja Batik Pria Modern',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Shirt',
    marketScopes: ['ID'],
    priority: 'URGENT',
    demandStatus: 'PENDING_CONVERT',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: '-',
    requiredDeliveryDate: '2026-04-15',
    requiredQtyTotal: 1500,
    constraintsNote: 'Bahan harus 100% katun. Warna tidak boleh luntur setelah 5x cuci.',
    skuLines: [
      { skuCode: 'SKU-001-S-BLK', size: 'S', color: 'Black', qty: 300 },
      { skuCode: 'SKU-001-M-BLK', size: 'M', color: 'Black', qty: 400 },
      { skuCode: 'SKU-001-L-BLK', size: 'L', color: 'Black', qty: 500 },
      { skuCode: 'SKU-001-XL-BLK', size: 'XL', color: 'Black', qty: 300 },
    ],
    hasProductionOrder: false,
    productionOrderId: null,
    createdAt: '2026-03-01 09:00:00',
    updatedAt: '2026-03-01 09:00:00',
  },
  // PENDING_CONVERT + INCOMPLETE + 未生成
  {
    demandId: 'DEM-202603-0002',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240777',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-002',
    spuName: 'Dress Wanita Casual',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Womens Dress',
    marketScopes: ['ID', 'TH'],
    priority: 'HIGH',
    demandStatus: 'PENDING_CONVERT',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: 'beta',
    requiredDeliveryDate: '2026-04-20',
    requiredQtyTotal: 2000,
    constraintsNote: 'Jahitan harus rapi. Label harus terpasang dengan benar.',
    skuLines: [
      { skuCode: 'SKU-002-S-RED', size: 'S', color: 'Red', qty: 500 },
      { skuCode: 'SKU-002-M-RED', size: 'M', color: 'Red', qty: 600 },
      { skuCode: 'SKU-002-L-RED', size: 'L', color: 'Red', qty: 500 },
      { skuCode: 'SKU-002-XL-RED', size: 'XL', color: 'Red', qty: 400 },
    ],
    hasProductionOrder: false,
    productionOrderId: null,
    createdAt: '2026-03-01 10:30:00',
    updatedAt: '2026-03-01 10:30:00',
  },
  // PENDING_CONVERT + RELEASED + 未生成
  {
    demandId: 'DEM-202603-0003',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240778',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-003',
    spuName: 'Celana Panjang Formal',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Pants',
    marketScopes: ['ID'],
    priority: 'URGENT',
    demandStatus: 'PENDING_CONVERT',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.0',
    requiredDeliveryDate: '2026-04-10',
    requiredQtyTotal: 3000,
    constraintsNote: 'Wajib ada label ukuran. Resleting YKK.',
    skuLines: [
      { skuCode: 'SKU-003-30-NVY', size: '30', color: 'Navy', qty: 600 },
      { skuCode: 'SKU-003-32-NVY', size: '32', color: 'Navy', qty: 800 },
      { skuCode: 'SKU-003-34-NVY', size: '34', color: 'Navy', qty: 900 },
      { skuCode: 'SKU-003-36-NVY', size: '36', color: 'Navy', qty: 700 },
    ],
    hasProductionOrder: false,
    productionOrderId: null,
    createdAt: '2026-03-02 08:00:00',
    updatedAt: '2026-03-02 14:00:00',
  },
  // CONVERTED + INCOMPLETE + 已生成
  {
    demandId: 'DEM-202603-0004',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240779',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-004',
    spuName: 'Kaos Polos Premium',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens T-Shirt',
    marketScopes: ['ID', 'VN'],
    priority: 'HIGH',
    demandStatus: 'CONVERTED',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: 'beta-v2',
    requiredDeliveryDate: '2026-04-25',
    requiredQtyTotal: 5000,
    constraintsNote: 'Cotton combed 30s. Warna harus sesuai Pantone.',
    skuLines: [
      { skuCode: 'SKU-004-S-WHT', size: 'S', color: 'White', qty: 1000 },
      { skuCode: 'SKU-004-M-WHT', size: 'M', color: 'White', qty: 1500 },
      { skuCode: 'SKU-004-L-WHT', size: 'L', color: 'White', qty: 1500 },
      { skuCode: 'SKU-004-XL-WHT', size: 'XL', color: 'White', qty: 1000 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0001',
    createdAt: '2026-03-02 09:00:00',
    updatedAt: '2026-03-02 16:00:00',
  },
  // CONVERTED + RELEASED + 已生成
  {
    demandId: 'DEM-202603-0005',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240780',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-005',
    spuName: 'Jaket Hoodie Unisex',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Outerwear',
    marketScopes: ['ID'],
    priority: 'NORMAL',
    demandStatus: 'CONVERTED',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v2.1',
    requiredDeliveryDate: '2026-05-01',
    requiredQtyTotal: 2500,
    constraintsNote: 'Fleece 280gsm. Resleting harus kuat.',
    skuLines: [
      { skuCode: 'SKU-005-S-GRY', size: 'S', color: 'Grey', qty: 500 },
      { skuCode: 'SKU-005-M-GRY', size: 'M', color: 'Grey', qty: 700 },
      { skuCode: 'SKU-005-L-GRY', size: 'L', color: 'Grey', qty: 800 },
      { skuCode: 'SKU-005-XL-GRY', size: 'XL', color: 'Grey', qty: 500 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0002',
    createdAt: '2026-03-03 08:00:00',
    updatedAt: '2026-03-03 15:00:00',
  },
  // HOLD + INCOMPLETE + 未生成
  {
    demandId: 'DEM-202603-0006',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240781',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-006',
    spuName: 'Rok Mini Plisket',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Womens Skirt',
    marketScopes: ['ID', 'TH', 'VN'],
    priority: 'NORMAL',
    demandStatus: 'HOLD',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: '-',
    requiredDeliveryDate: null,
    requiredQtyTotal: 1800,
    constraintsNote: 'Menunggu konfirmasi warna dari buyer.',
    skuLines: [
      { skuCode: 'SKU-006-S-PNK', size: 'S', color: 'Pink', qty: 400 },
      { skuCode: 'SKU-006-M-PNK', size: 'M', color: 'Pink', qty: 500 },
      { skuCode: 'SKU-006-L-PNK', size: 'L', color: 'Pink', qty: 500 },
      { skuCode: 'SKU-006-XL-PNK', size: 'XL', color: 'Pink', qty: 400 },
    ],
    hasProductionOrder: false,
    productionOrderId: null,
    createdAt: '2026-03-03 10:00:00',
    updatedAt: '2026-03-03 10:00:00',
  },
  // CANCELLED + INCOMPLETE + 未生成
  {
    demandId: 'DEM-202603-0007',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240782',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-007',
    spuName: 'Blazer Wanita Formal',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Womens Blazer',
    marketScopes: ['ID'],
    priority: 'HIGH',
    demandStatus: 'CANCELLED',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: 'beta',
    requiredDeliveryDate: '2026-04-30',
    requiredQtyTotal: 1200,
    constraintsNote: 'Dibatalkan karena perubahan koleksi.',
    skuLines: [
      { skuCode: 'SKU-007-S-BLK', size: 'S', color: 'Black', qty: 300 },
      { skuCode: 'SKU-007-M-BLK', size: 'M', color: 'Black', qty: 400 },
      { skuCode: 'SKU-007-L-BLK', size: 'L', color: 'Black', qty: 300 },
      { skuCode: 'SKU-007-XL-BLK', size: 'XL', color: 'Black', qty: 200 },
    ],
    hasProductionOrder: false,
    productionOrderId: null,
    createdAt: '2026-03-04 09:00:00',
    updatedAt: '2026-03-04 14:00:00',
  },
  // PENDING_CONVERT + RELEASED + 未生成
  {
    demandId: 'DEM-202603-0008',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240783',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-008',
    spuName: 'Kemeja Flanel Pria',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Shirt',
    marketScopes: ['ID'],
    priority: 'URGENT',
    demandStatus: 'PENDING_CONVERT',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.0',
    requiredDeliveryDate: '2026-04-08',
    requiredQtyTotal: 4000,
    constraintsNote: 'Pattern harus align di bagian depan. Kancing kayu.',
    skuLines: [
      { skuCode: 'SKU-008-S-PLB', size: 'S', color: 'Plaid Blue', qty: 800 },
      { skuCode: 'SKU-008-M-PLB', size: 'M', color: 'Plaid Blue', qty: 1200 },
      { skuCode: 'SKU-008-L-PLB', size: 'L', color: 'Plaid Blue', qty: 1200 },
      { skuCode: 'SKU-008-XL-PLB', size: 'XL', color: 'Plaid Blue', qty: 800 },
    ],
    hasProductionOrder: false,
    productionOrderId: null,
    createdAt: '2026-03-04 11:00:00',
    updatedAt: '2026-03-04 11:00:00',
  },
  // CONVERTED + RELEASED + 已生成
  {
    demandId: 'DEM-202603-0009',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240784',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-009',
    spuName: 'Polo Shirt Pique',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Polo',
    marketScopes: ['ID', 'TH'],
    priority: 'HIGH',
    demandStatus: 'CONVERTED',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.2',
    requiredDeliveryDate: '2026-03-25',
    requiredQtyTotal: 6000,
    constraintsNote: 'Logo bordir dada kiri. Kerah harus kaku.',
    skuLines: [
      { skuCode: 'SKU-009-S-WHT', size: 'S', color: 'White', qty: 1200 },
      { skuCode: 'SKU-009-M-WHT', size: 'M', color: 'White', qty: 1800 },
      { skuCode: 'SKU-009-L-WHT', size: 'L', color: 'White', qty: 1800 },
      { skuCode: 'SKU-009-XL-WHT', size: 'XL', color: 'White', qty: 1200 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0003',
    createdAt: '2026-02-20 08:00:00',
    updatedAt: '2026-03-01 10:00:00',
  },
  // CONVERTED + RELEASED + 已生成
  {
    demandId: 'DEM-202603-0010',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240785',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-010',
    spuName: 'Celana Jogger Pria',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Pants',
    marketScopes: ['ID'],
    priority: 'NORMAL',
    demandStatus: 'CONVERTED',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.0',
    requiredDeliveryDate: '2026-03-10',
    requiredQtyTotal: 3500,
    constraintsNote: 'Elastis pinggang harus kuat. Saku samping resleting.',
    skuLines: [
      { skuCode: 'SKU-010-S-BLK', size: 'S', color: 'Black', qty: 700 },
      { skuCode: 'SKU-010-M-BLK', size: 'M', color: 'Black', qty: 1000 },
      { skuCode: 'SKU-010-L-BLK', size: 'L', color: 'Black', qty: 1100 },
      { skuCode: 'SKU-010-XL-BLK', size: 'XL', color: 'Black', qty: 700 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0004',
    createdAt: '2026-02-15 09:00:00',
    updatedAt: '2026-03-02 16:00:00',
  },
  // CONVERTED + INCOMPLETE + 已生成
  {
    demandId: 'DEM-202603-0011',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240786',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-011',
    spuName: 'Sweater Rajut Wanita',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Womens Knitwear',
    marketScopes: ['ID', 'VN'],
    priority: 'URGENT',
    demandStatus: 'CONVERTED',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: '-',
    requiredDeliveryDate: '2026-04-18',
    requiredQtyTotal: 2200,
    constraintsNote: 'Rajutan harus rapat. Tidak boleh melar.',
    skuLines: [
      { skuCode: 'SKU-011-S-CRM', size: 'S', color: 'Cream', qty: 500 },
      { skuCode: 'SKU-011-M-CRM', size: 'M', color: 'Cream', qty: 600 },
      { skuCode: 'SKU-011-L-CRM', size: 'L', color: 'Cream', qty: 600 },
      { skuCode: 'SKU-011-XL-CRM', size: 'XL', color: 'Cream', qty: 500 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0005',
    createdAt: '2026-03-01 08:00:00',
    updatedAt: '2026-03-01 14:00:00',
  },
  // CONVERTED + INCOMPLETE + 已生成
  {
    demandId: 'DEM-202603-0012',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240787',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-012',
    spuName: 'Cardigan Wanita',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Womens Knitwear',
    marketScopes: ['ID'],
    priority: 'HIGH',
    demandStatus: 'CONVERTED',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: 'beta',
    requiredDeliveryDate: '2026-04-22',
    requiredQtyTotal: 1600,
    constraintsNote: 'Kancing mutiara. Rajutan halus.',
    skuLines: [
      { skuCode: 'SKU-012-S-BEG', size: 'S', color: 'Beige', qty: 400 },
      { skuCode: 'SKU-012-M-BEG', size: 'M', color: 'Beige', qty: 400 },
      { skuCode: 'SKU-012-L-BEG', size: 'L', color: 'Beige', qty: 400 },
      { skuCode: 'SKU-012-XL-BEG', size: 'XL', color: 'Beige', qty: 400 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0006',
    createdAt: '2026-03-02 10:00:00',
    updatedAt: '2026-03-02 15:00:00',
  },
  // CONVERTED + RELEASED + 已生成
  {
    demandId: 'DEM-202603-0013',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240788',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-013',
    spuName: 'Jas Pria Formal',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Suit',
    marketScopes: ['ID'],
    priority: 'URGENT',
    demandStatus: 'CONVERTED',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.5',
    requiredDeliveryDate: '2026-05-10',
    requiredQtyTotal: 800,
    constraintsNote: 'Wool blend. Lapel harus tajam.',
    skuLines: [
      { skuCode: 'SKU-013-S-NVY', size: 'S', color: 'Navy', qty: 150 },
      { skuCode: 'SKU-013-M-NVY', size: 'M', color: 'Navy', qty: 250 },
      { skuCode: 'SKU-013-L-NVY', size: 'L', color: 'Navy', qty: 250 },
      { skuCode: 'SKU-013-XL-NVY', size: 'XL', color: 'Navy', qty: 150 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0007',
    createdAt: '2026-02-28 09:00:00',
    updatedAt: '2026-03-03 11:00:00',
  },
  // CONVERTED + RELEASED + 已生成
  {
    demandId: 'DEM-202603-0014',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240789',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-014',
    spuName: 'Rompi Pria Casual',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Vest',
    marketScopes: ['ID', 'TH'],
    priority: 'NORMAL',
    demandStatus: 'CONVERTED',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.0',
    requiredDeliveryDate: '2026-04-28',
    requiredQtyTotal: 1000,
    constraintsNote: 'Dibatalkan oleh buyer.',
    skuLines: [
      { skuCode: 'SKU-014-S-GRN', size: 'S', color: 'Green', qty: 200 },
      { skuCode: 'SKU-014-M-GRN', size: 'M', color: 'Green', qty: 300 },
      { skuCode: 'SKU-014-L-GRN', size: 'L', color: 'Green', qty: 300 },
      { skuCode: 'SKU-014-XL-GRN', size: 'XL', color: 'Green', qty: 200 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0008',
    createdAt: '2026-02-25 10:00:00',
    updatedAt: '2026-03-04 09:00:00',
  },
  // CONVERTED + INCOMPLETE + 已生成
  {
    demandId: 'DEM-202603-0015',
    legacyType: 'ID_PURCHASE',
    legacyOrderNo: '240790',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-015',
    spuName: 'Kemeja Linen Pria',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Mens Shirt',
    marketScopes: ['ID'],
    priority: 'HIGH',
    demandStatus: 'CONVERTED',
    techPackStatus: 'INCOMPLETE',
    techPackVersionLabel: '-',
    requiredDeliveryDate: '2026-05-05',
    requiredQtyTotal: 2800,
    constraintsNote: 'Linen premium. Jahitan Perancis.',
    skuLines: [
      { skuCode: 'SKU-015-S-WHT', size: 'S', color: 'White', qty: 600 },
      { skuCode: 'SKU-015-M-WHT', size: 'M', color: 'White', qty: 800 },
      { skuCode: 'SKU-015-L-WHT', size: 'L', color: 'White', qty: 800 },
      { skuCode: 'SKU-015-XL-WHT', size: 'XL', color: 'White', qty: 600 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0009',
    createdAt: '2026-03-04 14:00:00',
    updatedAt: '2026-03-04 14:30:00',
  },
  // CONVERTED + RELEASED + 已生成
  {
    demandId: 'DEM-202603-0016',
    legacyType: 'GOODS_PURCHASE',
    legacyOrderNo: '240791',
    sourceSystem: 'LEGACY',
    spuCode: 'SPU-2024-016',
    spuName: 'Blus Wanita Satin',
    imageUrl: '/placeholder.svg?height=80&width=80',
    category: 'Womens Blouse',
    marketScopes: ['ID', 'VN'],
    priority: 'URGENT',
    demandStatus: 'CONVERTED',
    techPackStatus: 'RELEASED',
    techPackVersionLabel: 'v1.1',
    requiredDeliveryDate: '2026-03-28',
    requiredQtyTotal: 3200,
    constraintsNote: 'Satin silk blend. Tidak boleh kusut.',
    skuLines: [
      { skuCode: 'SKU-016-S-CHP', size: 'S', color: 'Champagne', qty: 700 },
      { skuCode: 'SKU-016-M-CHP', size: 'M', color: 'Champagne', qty: 900 },
      { skuCode: 'SKU-016-L-CHP', size: 'L', color: 'Champagne', qty: 900 },
      { skuCode: 'SKU-016-XL-CHP', size: 'XL', color: 'Champagne', qty: 700 },
    ],
    hasProductionOrder: true,
    productionOrderId: 'PO-202603-0010',
    createdAt: '2026-02-22 09:00:00',
    updatedAt: '2026-03-01 16:00:00',
  },
]

// 需求状态配置
export const demandStatusConfig: Record<DemandStatus, { label: string; color: string }> = {
  PENDING_CONVERT: { label: '待转单', color: 'bg-blue-100 text-blue-700' },
  CONVERTED:       { label: '已转单', color: 'bg-green-100 text-green-700' },
  HOLD:            { label: '暂停', color: 'bg-yellow-100 text-yellow-700' },
  CANCELLED:       { label: '已取消', color: 'bg-red-100 text-red-700' },
}

// 技术包状态配置
export const techPackStatusConfig: Record<TechPackStatus, { label: string; color: string }> = {
  INCOMPLETE: { label: '未完成', color: 'bg-orange-100 text-orange-700' },
  RELEASED:   { label: '已发布', color: 'bg-green-100 text-green-700' },
}

// 优先级配置
export const priorityConfig: Record<Priority, { label: string; color: string }> = {
  URGENT: { label: '紧急', color: 'bg-red-100 text-red-700' },
  HIGH:   { label: '高', color: 'bg-orange-100 text-orange-700' },
  NORMAL: { label: '普通', color: 'bg-blue-100 text-blue-700' },
}
