// @page-pattern: list
import { openTmfVersionReplanDialog } from './version-replan-dialog.ts'
import { getTmfDemandVersionChange } from '../../../../data/pms/tmf-material-purchases.ts'
import { openTmfProductionControlDialog } from './production-control-dialog.ts'
import { openTmfProductionDemandDialog } from './production-demand-dialog.ts'
import { renderStandardListPage, renderStandardListStats } from '../../../../components/ui/list-page.ts'
import { createProcessOrderListController, type ProcessOrderListControllerState } from '../../../../components/ui/process-order-list-controller.ts'
import type { StandardListColumn } from '../../../../components/ui/list-table.ts'
import { exportStandardListRows } from '../../../../components/ui/list-export.ts'
import { escapeHtml as e } from '../../../../utils.ts'
import { listTmfWorkOrders } from '../../../../data/fcs/tmf-work-order-view.ts'

const prefix='tmf-work-orders', selector='[data-tmf-work-orders]'
const state:ProcessOrderListControllerState&{keyword:string}={currentPage:1,sort:null,preferences:{order:[],visibleKeys:[],frozenKeys:[],pageSize:10},preferencesLoaded:false,showColumnSettings:false,keyword:''}
const action=(name:string,label:string)=>`<button class="rounded border px-3 py-2 text-sm" data-${prefix}-action="${name}" data-skip-page-rerender="true">${label}</button>`
const rows=()=>listTmfWorkOrders().filter(o=>!state.keyword||[o.productionOrderNo,o.versionId,...o.demands.map(d=>d.materialSkuId)].join(' ').toLowerCase().includes(state.keyword.toLowerCase()))
type Row=ReturnType<typeof listTmfWorkOrders>[number]
const columns:StandardListColumn<Row>[]=[
 {key:'source',title:'生产单 / 技术包版本',width:245,required:true,freezeable:true,sortable:true,sortValue:o=>o.productionOrderNo,render:o=>`<strong>${e(o.productionOrderNo)}</strong><div class="text-xs break-all">${e(o.versionId)}</div><div class="text-xs">路线节点 ${e(o.routeEntryId)}</div>`},
 {key:'material',title:'加工物料',width:260,required:true,render:o=>`<div class="flex gap-2">${o.material?.materialImageUrl?`<button data-tmf-work-orders-action="image" data-id="${e(o.id)}" data-skip-page-rerender="true"><img class="h-12 w-12 object-cover rounded" src="${e(o.material.materialImageUrl)}" alt="${e(o.material.materialName)}真实实拍替代图"></button>`:''}<div>${e(o.material?.materialName??o.demands[0].materialSkuId)}<div class="text-xs text-amber-700">用户提供真实实拍替代图；规格按技术包核对</div></div></div>`},
 {key:'requirements',title:'加工需求',width:230,required:true,render:o=>`<div>${o.demands.length} 条规格明细 · 合计 ${o.requiredPieces} ${o.material?.accessoryType==='绳子'?'根':'条'}</div><div class="text-xs">${o.demands.map(d=>`${e(d.garmentSize)} ${d.specification.cutLengthMm}mm × ${d.requiredPieces}`).join('；')}</div>`},
 {key:'receipt',title:'投入接收',width:135,render:o=>o.receiptStatus},
 {key:'process',title:'加工进度',width:150,render:o=>`${o.processingStatus}${o.control&&o.control.status!=='ACTIVE'?`<div class="text-amber-700 text-xs">${o.demands[0].supersededBySnapshotId?'已换版保留':o.control.pendingCancellationDisposition?'主单取消待处置':o.control.status==='CANCELLED'?'取消处置已确认':'生产单受限'}</div>`:''}`},
 {key:'handover',title:'产出交出',width:160,render:o=>o.handoverStatus},
 {key:'actions',title:'操作',width:230,required:true,actionColumn:true,render:o=>`<button class="rounded bg-blue-600 text-white px-3 py-2 text-xs" data-nav="/fcs/craft/accessory/webbing/work-orders/${encodeURIComponent(o.id)}">进入加工单</button><button class="border rounded px-3 py-2 text-xs mt-1" data-tmf-work-orders-action="control" data-id="${e(o.demands[0].productionOrderId)}" data-skip-page-rerender="true">生产限制与处置</button>${!o.demands[0].supersededBySnapshotId&&getTmfDemandVersionChange(o.demands[0])?`<button class="border rounded px-3 py-2 text-xs mt-1" data-tmf-work-orders-action="version" data-id="${e(o.productionOrderId)}" data-skip-page-rerender="true">采用版本变更</button>`:''}`},
]
const controller=createProcessOrderListController({state,columns,eventPrefix:prefix,rootSelector:selector,preferenceKey:'higood:list:/fcs/craft/accessory/webbing/work-orders',tableSurfaceSelector:'[data-tmf-work-table]',paginationSurfaceSelector:'[data-tmf-work-pagination]',overlaysSurfaceSelector:'[data-tmf-work-columns]',getRows:rows,locallyManagedEvents:true,pageSizeOptions:[10,20,50],defaultFrozenKeys:['source'],columnSettingsTitle:'织带加工单列设置',emptyText:'暂无已从生产单技术包快照生成的织带加工需求。'})
const stats=()=>renderStandardListStats([{label:'当前查询',value:`${rows().length} 单`},{label:'待接收/部分接收',value:`${rows().filter(o=>['待接收','部分接收'].includes(o.receiptStatus)).length} 单`},{label:'加工中',value:`${rows().filter(o=>o.processingStatus==='加工中').length} 单`}])
const refresh=()=>{controller.refresh({overlays:true});const root=document.querySelector(selector);if(root){root.querySelector('[data-tmf-work-stats]')!.innerHTML=stats();const heading=root.querySelector('[data-standard-list-table-section] > header h2');if(heading)heading.textContent=`加工单 · ${rows().length} 单`}}
function bind(){const root=document.querySelector<HTMLElement>(selector);if(!root||root.dataset.bound)return;root.dataset.bound='true';controller.installColumnDragEvents()
 root.addEventListener('error',event=>{if(event.target instanceof HTMLImageElement){const span=document.createElement('span');span.textContent='图片加载失败';event.target.replaceWith(span)}},true)
 root.addEventListener('keydown',event=>{if(event.key==='Escape'){root.querySelector('[data-tmf-work-image]')!.innerHTML='';root.querySelector('[data-tmf-work-generate]')!.replaceChildren();root.querySelector('[data-tmf-work-control]')!.replaceChildren();state.showColumnSettings=false;controller.refresh({table:false,pagination:false,overlays:true})}})
 root.addEventListener('change',event=>{const field=event.target as HTMLSelectElement;if(field.getAttribute(`data-${prefix}-field`)==='pageSize'){controller.setPageSize(Number(field.value));refresh()}})
 root.addEventListener('click',event=>{const target=(event.target as HTMLElement).closest<HTMLElement>(`[data-${prefix}-action]`);if(!target)return;event.stopPropagation();const name=target.getAttribute(`data-${prefix}-action`)
 if(name==='version'){try{openTmfVersionReplanDialog(root.querySelector<HTMLElement>('[data-tmf-work-control]')!,target.dataset.id!,(frozen)=>{refresh();root.querySelector('[data-tmf-work-feedback]')!.textContent=frozen?'旧占用已释放，未发分配已释放，旧实物按原规格冻结；已生成当前版本需求，请重新备料。':'旧占用已释放，已生成当前采用版本需求；请按新版重新备料。'})}catch(error){root.querySelector('[data-tmf-work-feedback]')!.textContent=error instanceof Error?error.message:'无法核对采用变更。'}}
 else if(name==='control'){try{openTmfProductionControlDialog(root.querySelector<HTMLElement>('[data-tmf-work-control]')!,target.dataset.id!,()=>{refresh();root.querySelector('[data-tmf-work-feedback]')!.textContent='处理已保存。已执行实物保留，仓库和加工页面按同一限制处理。'})}catch(error){root.querySelector('[data-tmf-work-feedback]')!.textContent=error instanceof Error?error.message:'无法读取处置数量。'}}
 else if(name==='generate')openTmfProductionDemandDialog(root.querySelector<HTMLElement>('[data-tmf-work-generate]')!,()=>{refresh();root.querySelector('[data-tmf-work-feedback]')!.textContent='已按生产单采用的技术包生成加工需求；同来源不重复生成。'})
 else if(name==='query'){state.keyword=root.querySelector<HTMLInputElement>('[name="keyword"]')!.value.trim();state.currentPage=1;refresh()}
 else if(name==='reset'){state.keyword='';root.querySelector<HTMLInputElement>('[name="keyword"]')!.value='';state.currentPage=1;state.sort=null;refresh()}
 else if(name==='close-image')root.querySelector('[data-tmf-work-image]')!.innerHTML=''
 else if(name==='image'){const order=listTmfWorkOrders().find(o=>o.id===target.dataset.id);if(order?.material?.materialImageUrl)root.querySelector('[data-tmf-work-image]')!.innerHTML=`<div class="fixed inset-0 z-[80] bg-black/60 flex items-center justify-center p-4"><button class="absolute inset-0" data-${prefix}-action="close-image" data-skip-page-rerender="true" aria-label="关闭大图"></button><div class="relative rounded bg-white p-3"><p>半成品参考图 ${action('close-image','关闭')}</p><img class="max-h-[70vh] max-w-[85vw] object-contain" src="${e(order.material.materialImageUrl)}" alt="${e(order.material.materialName)}半成品参考图"></div></div>`}
 else if(name==='export')exportStandardListRows({fileName:'织带生产加工单',columns,rows:rows()})
 else if(name==='prev-page'||name==='next-page'){controller.stepPage(name==='prev-page'?-1:1);refresh()}
 else if(name==='sort-column'){controller.cycleSort(target.dataset.columnKey||'');refresh()}
 else if(name==='open-column-settings'||name==='close-column-settings'){state.showColumnSettings=name==='open-column-settings';controller.refresh({table:false,pagination:false,overlays:true})}
 else if(name==='restore-column-settings'){controller.restorePreferences();refresh()}
 else if(name==='toggle-column-visibility'||name==='toggle-column-freeze'){controller.updateColumnPreference(name,target.getAttribute(`data-${prefix}-column-key`)||target.closest(`[data-${prefix}-column-key]`)?.getAttribute(`data-${prefix}-column-key`)||'',target instanceof HTMLInputElement?target.checked:undefined);refresh()}
 })
}
export function renderTmfWorkOrdersPage(){state.currentPage=1;state.sort=null;controller.ensurePreferencesLoaded();const view=controller.getView();if(typeof window!=='undefined')requestAnimationFrame(bind);return `<div data-tmf-work-orders>${renderStandardListPage({title:'织带／绳子生产加工单',primaryActionsHtml:action('generate','从生产单生成'),feedbackHtml:'<p role="status" data-tmf-work-feedback class="text-sm text-blue-700"></p>',filtersHtml:`<div class="rounded border bg-white p-3"><label class="text-xs">生产单 / 技术包 / SKU<input name="keyword" value="${e(state.keyword)}" class="block w-80 max-w-full border rounded p-2 mt-1 text-sm"></label><div class="flex gap-2 mt-3">${action('query','查询')}${action('reset','重置')}${action('export','导出')}</div></div>`,statsHtml:`<div data-tmf-work-stats>${stats()}</div>`,listTitle:`加工单 · ${rows().length} 单`,listActionsHtml:action('open-column-settings','列设置'),tableHtml:`<div data-tmf-work-table>${view.tableHtml}</div>`,paginationHtml:`<div data-tmf-work-pagination>${view.paginationHtml}</div>`,overlaysHtml:`<div data-tmf-work-columns>${controller.renderColumnSettings()}</div><div data-tmf-work-image></div><div data-tmf-work-generate></div><div data-tmf-work-control></div>`})}</div>`}
