import type { RouteRegistry } from './route-types.ts'
import {
  renderPmsBomDetailPage,
  renderPmsBomTemplatesPage,
  renderPmsDictionariesPage,
  renderPmsFirstLegCarriersPage,
  renderPmsFirstLegShipmentsPage,
  renderPmsGarmentSkusPage,
  renderPmsKolDemandsPage,
  renderPmsLogisticsPaymentRequestsPage,
  renderPmsLogisticsReconciliationsPage,
  renderPmsMaterialArchivesPage,
  renderPmsMaterialInventoryPage,
  renderPmsMaterialPaymentRequestsPage,
  renderPmsMaterialPurchaseOrdersPage,
  renderPmsMaterialPurchaseTrackingPage,
  renderPmsMaterialReconciliationsPage,
  renderPmsMaterialRequirementsPage,
  renderPmsProductPurchaseOrdersPage,
  renderPmsPurchaseOrderPage,
  renderPmsPurchaseSuggestionsPage,
  renderPmsRolesPage,
  renderPmsSampleSkusPage,
  renderPmsSubjectOperationsPage,
  renderPmsSupplierConfirmationsPage,
  renderPmsSuppliersPage,
  renderPmsSupplyArchivesPage,
  renderPmsTradeSubjectsPage,
  renderPmsTransitDashboardPage,
  renderPmsTransitOrderChecksPage,
  renderPmsTransitPreparationTasksPage,
  renderPmsTransitReceiptsPage,
  renderPmsUnitsPage,
  renderPmsUsersPage,
  renderPmsWarehousesPage,
  renderPmsWorkbenchPage,
} from './route-renderers-pms.ts'

export const routes: RouteRegistry = {
  exactRoutes: {
    '/pms/workbench/overview': () => renderPmsWorkbenchPage(),
    '/pms/purchase-suggestions': () => renderPmsPurchaseSuggestionsPage(),
    '/pms/kol-demands': () => renderPmsKolDemandsPage(),
    '/pms/product-purchase-orders': () => renderPmsProductPurchaseOrdersPage(),
    '/pms/material-requirements': () => renderPmsMaterialRequirementsPage(),
    '/pms/material-purchase-orders': () => renderPmsMaterialPurchaseOrdersPage(),
    '/pms/material-purchase-tracking': () => renderPmsMaterialPurchaseTrackingPage(),
    '/pms/material-supplier-confirmations': () => renderPmsSupplierConfirmationsPage(),
    '/pms/first-leg-shipments': () => renderPmsFirstLegShipmentsPage(),
    '/pms/first-leg-carriers': () => renderPmsFirstLegCarriersPage(),
    '/pms/trade-subjects': () => renderPmsTradeSubjectsPage(),
    '/pms/suppliers': () => renderPmsSuppliersPage(),
    '/pms/supplier-supply-archives': () => renderPmsSupplyArchivesPage(),
    '/pms/material-archives': () => renderPmsMaterialArchivesPage(),
    '/pms/garment-skus': () => renderPmsGarmentSkusPage(),
    '/pms/sample-skus': () => renderPmsSampleSkusPage(),
    '/pms/warehouses': () => renderPmsWarehousesPage(),
    '/pms/units': () => renderPmsUnitsPage(),
    '/pms/bom-templates': () => renderPmsBomTemplatesPage(),
    '/pms/subject-operations': () => renderPmsSubjectOperationsPage(),
    '/pms/material-reconciliations': () => renderPmsMaterialReconciliationsPage(),
    '/pms/logistics-reconciliations': () => renderPmsLogisticsReconciliationsPage(),
    '/pms/material-payment-requests': () => renderPmsMaterialPaymentRequestsPage(),
    '/pms/logistics-payment-requests': () => renderPmsLogisticsPaymentRequestsPage(),
    '/pms/material-inventory': () => renderPmsMaterialInventoryPage(),
    '/pms/transit/dashboard': () => renderPmsTransitDashboardPage(),
    '/pms/transit/receipts': () => renderPmsTransitReceiptsPage(),
    '/pms/transit/order-checks': () => renderPmsTransitOrderChecksPage(),
    '/pms/transit/preparation-tasks': () => renderPmsTransitPreparationTasksPage(),
    '/pms/users': () => renderPmsUsersPage(),
    '/pms/roles': () => renderPmsRolesPage(),
    '/pms/dictionaries': () => renderPmsDictionariesPage(),
    '/pms/purchase-order': () => renderPmsPurchaseOrderPage(),
  },
  dynamicRoutes: [
    {
      pattern: /^\/pms\/bom-templates\/([^/]+)$/,
      render: (match) => renderPmsBomDetailPage(match[1]),
    },
  ],
}
