import type { RouteRegistry } from './route-types'
import {
  buildSpecialCraftDomainWaitHandoverWarehousePath,
  buildSpecialCraftDomainWaitProcessWarehousePath,
  buildSpecialCraftOperationSlug,
  buildSpecialCraftTaskOrdersPath,
  listEnabledSpecialCraftOperationDefinitions,
} from '../data/fcs/special-craft-operations'
import { buildDeductionEntryHrefByBasisId } from '../data/fcs/quality-chain-adapter'
import { renderRouteRedirect } from './route-utils'
import {
  renderTaskBreakdownPage,
  renderCapabilityPage,
  renderFactoryCapacityProfilePage,
  renderFactoryOnboardingPage,
  renderFactoryPerformancePage,
  renderFactoryProfilePage,
  renderFactoryStatusPage,
  renderOverviewPage,
  renderTodosPage,
  renderCapacityBottleneckPage,
  renderCapacityConstraintsPage,
  renderCapacityOverviewPage,
  renderCapacityPoliciesPage,
  renderCapacityRiskPage,
  renderProductionChangeEditPage,
  renderProductionChangeNewPage,
  renderProductionChangeOrderDetailPage,
  renderProductionChangeRelationDetailPage,
  renderProductionChangesPage,
  renderProductionCraftDictPage,
  renderProductionDemandInboxPage,
  renderProductionTaskGenerationRuleCreatePage,
  renderProductionTaskGenerationRuleDetailPage,
  renderProductionTaskGenerationRuleEditPage,
  renderProductionTaskGenerationRulesPage,
  renderProductionConfirmationPrintPage,
  renderTaskDeliveryCardPrintPage,
  renderTaskRouteCardPrintPage,
  renderPrintPreviewPage,
  renderProductionOrderDetailPage,
  renderProductionOrdersPage,
  renderProductionPreparationTimingPage,
  renderProductionPreparationTimingStatisticsPage,
  renderProcessDyeOrdersPage,
  renderProcessWaterSolubleOrdersPage,
  renderProcessPrintOrdersPage,
  renderMaterialIssuePage,
  renderQcRecordDetailPage,
  renderQcRecordsPage,
  renderDeductionAnalysisPage,
  renderBatchesPage,
  renderSettlementListPage,
  renderSettlementDetailPage,
  renderSettlementInitPage,
  renderFcsProductionTechPackSnapshotPage,
  renderMaterialStatementsPage,
  renderHistoryPage,
  renderPaymentSyncPage,
  renderStatementsPage,
  renderAdjustmentsPage,
  renderDispatchBoardPage,
  renderSewingDispatchWorkbenchPage,
  renderContinuousDispatchPage,
  renderDispatchAcceptanceSlaPage,
  renderDispatchTendersPage,
  renderFcsMaterialPrepListPage,
  renderFcsDyeingPrepPage,
  renderFcsPrintingPrepPage,
  renderFcsCuttingPrepPage,
  renderFcsSewingPrepPage,
  renderFcsOtherPrepPage,
  renderProgressBoardPage,
  renderProgressTaskDetailPage,
  renderProgressCuttingDetailPage,
  renderProgressCuttingExceptionCenterPage,
  renderProgressCuttingOverviewPage,
  renderProgressExceptionsPage,
  renderProgressHandoverOrderPage,
  renderProgressHandoverPage,
  renderProgressMaterialPage,
  renderProgressMilestoneConfigPage,
  renderProductionOrderProgressTrackingPage,
  renderProgressUrgePage,
  renderCraftWorkbenchOverviewPage,
  renderCraftCuttingFeiTicketDetailPage,
  renderCraftCuttingFeiTicketPrintedPage,
  renderCraftCuttingFeiTicketPrintPage,
  renderCraftCuttingFeiTicketReprintPage,
  renderCraftCuttingFeiTicketNumberingPage,
  renderCraftCuttingFeiTicketNumberingSummaryPage,
  renderCraftCuttingFeiTicketsPage,
  renderCraftCuttingBindingFeiTicketsPage,
  renderCraftCuttingCutOrdersPage,
  renderCraftCuttingCutOrderDetailPage,
  renderCraftCuttingCutOrderClosePage,
  renderCraftCuttingPickupManagementDetailPage,
  renderCraftCuttingPickupManagementPage,
  renderCraftCuttingProductionProgressPage,
  renderCraftCuttingProductionProgressDetailPage,
  renderPlaceholderPage,
  renderCraftCuttingMarkerCreatePage,
  renderCraftCuttingMarkerListPage,
  renderCraftCuttingMarkerPlanDetailPage,
  renderCraftCuttingMarkerPlanEditPage,
  renderCraftCuttingMarkerSpreadingPage,
  renderCraftCuttingSampleWarehouseDetailPage,
  renderCraftCuttingSampleWarehousePage,
  renderCraftCuttingSpecialProcessDetailPage,
  renderCraftCuttingSpecialProcessesPage,
  renderCraftCuttingSpreadingCreatePage,
  renderCraftCuttingSpreadingDetailPage,
  renderCraftCuttingSpreadingEditPage,
  renderCraftCuttingSpreadingListPage,
  renderCraftCuttingCutPieceReleasePage,
  renderCraftCuttingSupplementManagementPage,
  renderCraftCuttingAbMaterialStatisticsPage,
  renderCraftCuttingDailyProductionReportPage,
  renderCraftCuttingSummaryPage,
  renderCraftCuttingTransferBagDetailPage,
  renderCraftCuttingTransferBagsPage,
  renderCraftCuttingHandoverOrdersPage,
  renderCraftCuttingHandoverOrderDetailPage,
  renderCraftCuttingHandoverOrderRecordsPage,
  renderCraftCuttingHandoverRecordDetailPage,
  renderCraftCuttingWarehouseManagementWaitHandoverPage,
  renderCraftCuttingWarehouseManagementWaitProcessPage,
  renderCraftPrintingDashboardsPage,
  renderCraftPrintingPendingReviewPage,
  renderCraftPrintingProgressPage,
  renderCraftPrintingStatisticsPage,
  renderCraftPrintingWaitHandoverWarehousePage,
  renderCraftPrintingWaitProcessWarehousePage,
  renderCraftPrintingWorkOrderDetailPage,
  renderCraftPrintingWorkOrdersPage,
  renderCraftDyeingDyeOrdersPage,
  renderCraftDyeingReportsPage,
  renderCraftDyeingWaitHandoverWarehousePage,
  renderCraftDyeingWaitProcessWarehousePage,
  renderCraftDyeingWorkOrdersPage,
  renderCraftCombinedDyeingPage,
  renderCraftDyeingWaterSolubleOrdersPage,
  renderCraftWoolFeiTicketsPage,
  renderCraftWoolMachineSchedulePage,
  renderCraftWoolMachinesPage,
  renderCraftWoolStatisticsPage,
  renderCraftWoolWorkOrderDetailPage,
  renderCraftWoolWorkOrdersPage,
  renderCraftWoolWaitHandoverWarehousePage,
  renderCraftWoolWaitProcessWarehousePage,
  renderPostFinishingQcOrdersPage,
  renderPostFinishingRecheckOrdersPage,
  renderPostFinishingRecheckOrderDetailPage,
  renderPostFinishingStatisticsPage,
  renderPostFinishingTasksPage,
  renderPostFinishingWaitHandoverWarehousePage,
  renderPostFinishingWaitProcessWarehousePage,
  renderPostFinishingWorkOrderDetailPage,
  renderPostFinishingWorkOrdersPage,
  renderSpecialCraftDomainWaitHandoverWarehousePage,
  renderSpecialCraftDomainWaitProcessWarehousePage,
  renderSpecialCraftTaskDetailPage,
  renderSpecialCraftTaskOrdersPage,
  renderSpecialCraftWorkOrderDetailPage,
  renderTraceMappingPage,
  renderTraceParentCodesPage,
  renderTraceUniqueCodesPage,
  renderTraceUnitPricePage,
  renderCuttingSettlementInputPage,
} from './route-renderers-fcs'

const specialCraftExactRoutes = Object.fromEntries(
  [
    ...listEnabledSpecialCraftOperationDefinitions().map((operation) => {
      const operationSlug = buildSpecialCraftOperationSlug(operation)
      return [buildSpecialCraftTaskOrdersPath(operation), () => renderSpecialCraftTaskOrdersPage(operationSlug)]
    }),
    [
      buildSpecialCraftDomainWaitProcessWarehousePath('AUXILIARY_CRAFT_FACTORY'),
      () => renderSpecialCraftDomainWaitProcessWarehousePage('auxiliary'),
    ],
    [
      buildSpecialCraftDomainWaitHandoverWarehousePath('AUXILIARY_CRAFT_FACTORY'),
      () => renderSpecialCraftDomainWaitHandoverWarehousePage('auxiliary'),
    ],
    [
      buildSpecialCraftDomainWaitProcessWarehousePath('SPECIAL_CRAFT_FACTORY'),
      () => renderSpecialCraftDomainWaitProcessWarehousePage('special-type'),
    ],
    [
      buildSpecialCraftDomainWaitHandoverWarehousePath('SPECIAL_CRAFT_FACTORY'),
      () => renderSpecialCraftDomainWaitHandoverWarehousePage('special-type'),
    ],
  ],
)

export const routes: RouteRegistry = {
  exactRoutes: {
    '/fcs/factories/onboarding': () => renderFactoryOnboardingPage(),
    '/fcs/factories/profile': () => renderFactoryProfilePage(),
    '/fcs/factories/capacity-profile': () => renderFactoryCapacityProfilePage(),
    '/fcs/factories/capability': () => renderCapabilityPage(),
    '/fcs/factories/status': () => renderFactoryStatusPage(),
    '/fcs/factories/performance': () => renderFactoryPerformancePage(),
    '/fcs/factories/settlement': () => renderSettlementListPage(),
    '/fcs/factories/settlement/new': () => renderSettlementListPage(),
    '/fcs/workbench/overview': () => renderOverviewPage(),
    '/fcs/workbench/todos': () => renderTodosPage(),
    '/fcs/capacity/overview': () => renderCapacityOverviewPage(),
    '/fcs/capacity/risk': () => renderCapacityRiskPage(),
    '/fcs/capacity/bottleneck': () => renderCapacityBottleneckPage(),
    '/fcs/capacity/constraints': () => renderCapacityConstraintsPage(),
    '/fcs/capacity/policies': () => renderCapacityPoliciesPage(),
    '/fcs/production/task-generation-rules': () => renderProductionTaskGenerationRulesPage(),
    '/fcs/production/task-generation-rules/new': () => renderProductionTaskGenerationRuleCreatePage(),
    '/fcs/production/demand-inbox': () => renderProductionDemandInboxPage(),
    '/fcs/production/orders': () => renderProductionOrdersPage(),
    '/fcs/production/preparation-timing': () => renderProductionPreparationTimingPage(),
    '/fcs/production/preparation-timing-statistics': () => renderProductionPreparationTimingStatisticsPage(),
    '/fcs/production/changes': () => renderProductionChangesPage(),
    '/fcs/production/changes/new': () => renderProductionChangeNewPage(),
    '/fcs/production/craft-dict': () => renderProductionCraftDictPage(),
    '/fcs/process/task-breakdown': () => renderTaskBreakdownPage(),
    '/fcs/process/dye-orders': () => renderProcessDyeOrdersPage(),
    '/fcs/process/water-soluble-orders': () => renderProcessWaterSolubleOrdersPage(),
    '/fcs/process/print-orders': () => renderProcessPrintOrdersPage(),
    '/fcs/process/material-issue': () => renderMaterialIssuePage(),
    '/fcs/quality/qc-records': () => renderQcRecordsPage(),
    '/fcs/quality/deduction-analysis': () => renderDeductionAnalysisPage(),
    '/fcs/quality/deduction-calc': () =>
      renderRouteRedirect('/fcs/quality/deduction-analysis', '正在跳转到扣款记录'),
    '/fcs/quality/arbitration': () =>
      renderRouteRedirect('/fcs/quality/qc-records?view=WAIT_PLATFORM_REVIEW', '正在跳转到质检记录'),
    '/fcs/quality/penalty-output': () => renderDeductionAnalysisPage(),
    '/fcs/settlement/statements': () => renderStatementsPage(),
    '/fcs/settlement/adjustments': () => renderAdjustmentsPage(),
    '/fcs/settlement/batches': () => renderBatchesPage(),
    '/fcs/settlement/material-statements': () => renderMaterialStatementsPage(),
    '/fcs/settlement/payment-sync': () => renderPaymentSyncPage(),
    '/fcs/settlement/history': () => renderHistoryPage(),
    '/fcs/settlement/cutting-input': () =>
      renderRouteRedirect('/fcs/craft/cutting/settlement-scoring', '正在跳转到裁片结算评分'),
    '/fcs/dispatch/board': () => renderRouteRedirect('/fcs/dispatch/non-sewing', '正在跳转到非车缝任务分配'),
    '/fcs/dispatch/non-sewing': () => renderDispatchBoardPage(),
    '/fcs/dispatch/sewing': () => renderSewingDispatchWorkbenchPage(),
    '/fcs/dispatch/continuous': () => renderContinuousDispatchPage(),
    '/fcs/dispatch/acceptance-sla': () => renderDispatchAcceptanceSlaPage(),
    '/fcs/dispatch/tenders': () => renderDispatchTendersPage(),
    '/fcs/dispatch/exceptions': () => renderProgressExceptionsPage(),
    '/fcs/material-prep/list': () => renderFcsMaterialPrepListPage(),
    '/fcs/material-prep/dyeing': () => renderFcsDyeingPrepPage(),
    '/fcs/material-prep/printing': () => renderFcsPrintingPrepPage(),
    '/fcs/material-prep/cutting': () => renderFcsCuttingPrepPage(),
    '/fcs/material-prep/sewing': () => renderFcsSewingPrepPage(),
    '/fcs/material-prep/other': () => renderFcsOtherPrepPage(),
    '/fcs/progress/board': () => renderProgressBoardPage(),
    '/fcs/progress/exceptions': () => renderProgressExceptionsPage(),
    '/fcs/progress/handover': () => renderProgressHandoverPage(),
    '/fcs/progress/urge': () => renderProgressUrgePage(),
    '/fcs/progress/milestone-config': () => renderProgressMilestoneConfigPage(),
    '/fcs/progress/material': () => renderProgressMaterialPage(),
    '/fcs/progress/production-orders': () => renderProductionOrderProgressTrackingPage(),
    '/fcs/progress/production-orders/detail': () => renderProductionOrderProgressTrackingPage(),
    '/fcs/print/preview': () => renderPrintPreviewPage(),
    '/fcs/print/task-route-card': () => renderTaskRouteCardPrintPage(),
    '/fcs/print/task-delivery-card': () => renderTaskDeliveryCardPrintPage(),
    '/fcs/progress/cutting-overview': () => renderProgressCuttingOverviewPage(),
    '/fcs/progress/cutting-exception-center': () => renderProgressCuttingExceptionCenterPage(),
    '/fcs/craft/workbench/overview': () => renderCraftWorkbenchOverviewPage(),
    '/fcs/craft/workbench/todos': () => renderCraftWorkbenchOverviewPage(),
    '/fcs/craft/workbench/risks': () => renderCraftWorkbenchOverviewPage(),
    '/fcs/craft/cutting': () =>
      renderRouteRedirect('/fcs/craft/cutting/production-progress', '正在跳转到生产单总览'),
    '/fcs/craft/cutting/production-order-progress': () => renderCraftCuttingProductionProgressPage(),
    '/fcs/craft/cutting/production-progress': () => renderCraftCuttingProductionProgressPage(),
    '/fcs/craft/cutting/cut-orders': () => renderCraftCuttingCutOrdersPage(),
    '/fcs/craft/cutting/cut-order-close': () => renderCraftCuttingCutOrderClosePage(),
    '/fcs/craft/cutting/pickup-management': () => renderCraftCuttingPickupManagementPage(),
    '/fcs/craft/cutting/pickup-management-detail': () => renderCraftCuttingPickupManagementDetailPage(),
    '/fcs/craft/cutting/marker-list': () => renderCraftCuttingMarkerListPage(),
    '/fcs/craft/cutting/marker-create': () => renderCraftCuttingMarkerCreatePage(),
    '/fcs/craft/cutting/spreading-list': () => renderCraftCuttingSpreadingListPage(),
    '/fcs/craft/cutting/spreading-create': () => renderCraftCuttingSpreadingCreatePage(),
    '/fcs/craft/cutting/marker-spreading': () => renderCraftCuttingMarkerSpreadingPage(),
    '/fcs/craft/cutting/settlement-scoring': () => renderCuttingSettlementInputPage(),
    '/fcs/craft/cutting/marker-detail': () =>
      renderRouteRedirect('/fcs/craft/cutting/marker-list', '正在跳转到唛架方案'),
    '/fcs/craft/cutting/marker-edit': () =>
      renderRouteRedirect('/fcs/craft/cutting/marker-list', '正在跳转到唛架方案'),
    '/fcs/craft/cutting/spreading-detail': () => renderCraftCuttingSpreadingDetailPage(),
    '/fcs/craft/cutting/spreading-edit': () => renderCraftCuttingSpreadingEditPage(),
    '/fcs/craft/cutting/fei-tickets': () => renderCraftCuttingFeiTicketsPage(),
    '/fcs/craft/cutting/binding-fei-tickets': () => renderCraftCuttingBindingFeiTicketsPage(),
    '/fcs/craft/cutting/fei-ticket-detail': () => renderCraftCuttingFeiTicketDetailPage(),
    '/fcs/craft/cutting/fei-ticket-printed': () => renderCraftCuttingFeiTicketPrintedPage(),
    '/fcs/craft/cutting/fei-ticket-print': () => renderCraftCuttingFeiTicketPrintPage(),
    '/fcs/craft/cutting/fei-ticket-reprint': () => renderCraftCuttingFeiTicketReprintPage(),
    '/fcs/craft/cutting/fei-ticket-numbering': () => renderCraftCuttingFeiTicketNumberingPage(),
    '/fcs/craft/cutting/fei-ticket-numbering/summary': () => renderCraftCuttingFeiTicketNumberingSummaryPage(),
    '/fcs/craft/cutting/sample-warehouse': () => renderCraftCuttingSampleWarehousePage(),
    '/fcs/craft/cutting/warehouse': () =>
      renderRouteRedirect('/fcs/craft/cutting/warehouse-management/wait-process', '正在跳转到待加工仓'),
    '/fcs/craft/cutting/warehouse-management': () =>
      renderRouteRedirect('/fcs/craft/cutting/warehouse-management/wait-process', '正在跳转到待加工仓'),
    '/fcs/craft/cutting/warehouse-management/wait-process': () => renderCraftCuttingWarehouseManagementWaitProcessPage(),
    '/fcs/craft/cutting/warehouse-management/wait-handover': () => renderCraftCuttingWarehouseManagementWaitHandoverPage(),
    '/fcs/craft/cutting/handover-orders': () => renderCraftCuttingHandoverOrdersPage(),
    '/fcs/craft/cutting/warehouse-management/sample-warehouse': () =>
      renderRouteRedirect('/fcs/craft/cutting/sample-warehouse', '正在跳转到裁床样衣仓'),
    '/fcs/craft/cutting/transfer-bags': () => renderCraftCuttingTransferBagsPage(),
    '/fcs/craft/cutting/transfer-bag-detail': () => renderCraftCuttingTransferBagDetailPage(),
    '/fcs/craft/cutting/special-processes': () => renderCraftCuttingSpecialProcessesPage(),
    '/fcs/craft/cutting/cut-piece-release': () => renderCraftCuttingCutPieceReleasePage(),
    '/fcs/craft/cutting/supplement-management': () => renderCraftCuttingSupplementManagementPage(),
    '/fcs/craft/cutting/statistics/daily-production': () => renderCraftCuttingDailyProductionReportPage(),
    '/fcs/craft/cutting/statistics/ab-material': () => renderCraftCuttingAbMaterialStatisticsPage(),
    '/fcs/craft/cutting/summary': () => renderCraftCuttingSummaryPage(),
    '/fcs/craft/printing': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/work-orders': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/tasks': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/orders': () => renderCraftPrintingWorkOrdersPage(),
    '/fcs/craft/printing/wait-process-warehouse': () => renderCraftPrintingWaitProcessWarehousePage(),
    '/fcs/craft/printing/wait-handover-warehouse': () => renderCraftPrintingWaitHandoverWarehousePage(),
    '/fcs/craft/printing/warehouse': () =>
      renderRouteRedirect('/fcs/craft/printing/wait-process-warehouse', '正在跳转到印花待加工仓'),
    '/fcs/craft/printing/warehouse-management': () =>
      renderRouteRedirect('/fcs/craft/printing/wait-process-warehouse', '正在跳转到印花待加工仓'),
    '/fcs/craft/printing/pending-review': () => renderCraftPrintingPendingReviewPage(),
    '/fcs/craft/printing/batches': () => renderCraftPrintingPendingReviewPage(),
    '/fcs/craft/printing/progress': () =>
      renderRouteRedirect('/fcs/craft/printing/work-orders?tab=progress', '正在跳转到印花加工单进度视图'),
    '/fcs/craft/printing/stats': () => renderCraftPrintingStatisticsPage(),
    '/fcs/craft/printing/statistics': () => renderCraftPrintingStatisticsPage(),
    '/fcs/craft/printing/dashboards': () => renderCraftPrintingDashboardsPage(),
    '/fcs/craft/dyeing': () => renderCraftDyeingWorkOrdersPage(),
    '/fcs/craft/dyeing/work-orders': () => renderCraftDyeingWorkOrdersPage(),
    '/fcs/craft/dyeing/combined-dyeing': () => renderCraftCombinedDyeingPage(),
    '/fcs/craft/dyeing/water-soluble-orders': () => renderCraftDyeingWaterSolubleOrdersPage(),
    '/fcs/craft/dyeing/tasks': () => renderCraftDyeingWorkOrdersPage(),
    '/fcs/craft/dyeing/wait-process-warehouse': () => renderCraftDyeingWaitProcessWarehousePage(),
    '/fcs/craft/dyeing/wait-handover-warehouse': () => renderCraftDyeingWaitHandoverWarehousePage(),
    '/fcs/craft/dyeing/warehouse': () =>
      renderRouteRedirect('/fcs/craft/dyeing/wait-process-warehouse', '正在跳转到染色待加工仓'),
    '/fcs/craft/dyeing/warehouse-management': () =>
      renderRouteRedirect('/fcs/craft/dyeing/wait-process-warehouse', '正在跳转到染色待加工仓'),
    '/fcs/craft/dyeing/orders': () =>
      renderRouteRedirect('/fcs/craft/dyeing/work-orders?tab=formula', '正在跳转到染色加工单配方视图'),
    '/fcs/craft/dyeing/dye-orders': () =>
      renderRouteRedirect('/fcs/craft/dyeing/work-orders?tab=formula', '正在跳转到染色加工单配方视图'),
    '/fcs/craft/dyeing/batches': () =>
      renderRouteRedirect('/fcs/craft/dyeing/work-orders?tab=formula', '正在跳转到染色加工单配方视图'),
    '/fcs/craft/dyeing/stats': () => renderCraftDyeingReportsPage(),
    '/fcs/craft/dyeing/reports': () => renderCraftDyeingReportsPage(),
    '/fcs/craft/wool': () =>
      renderRouteRedirect('/fcs/craft/wool/work-orders', '正在跳转到毛织加工单'),
    '/fcs/craft/wool/work-orders': () => renderCraftWoolWorkOrdersPage(),
    '/fcs/craft/wool/wait-process-warehouse': () => renderCraftWoolWaitProcessWarehousePage(),
    '/fcs/craft/wool/wait-handover-warehouse': () => renderCraftWoolWaitHandoverWarehousePage(),
    '/fcs/craft/wool/fei-tickets': () => renderCraftWoolFeiTicketsPage(),
    '/fcs/craft/wool/machine-schedule': () => renderCraftWoolMachineSchedulePage(),
    '/fcs/craft/wool/machines': () => renderCraftWoolMachinesPage(),
    '/fcs/craft/wool/statistics': () => renderCraftWoolStatisticsPage(),
    '/fcs/craft/wool/stats': () => renderCraftWoolStatisticsPage(),
    '/fcs/craft/wool/warehouse': () =>
      renderRouteRedirect('/fcs/craft/wool/wait-process-warehouse', '正在跳转到毛织待加工仓'),
    '/fcs/craft/wool/warehouse-management': () =>
      renderRouteRedirect('/fcs/craft/wool/wait-process-warehouse', '正在跳转到毛织待加工仓'),
    '/fcs/craft/wool/tasks': () =>
      renderRouteRedirect('/fcs/craft/wool/work-orders', '正在跳转到毛织加工单'),
    '/fcs/craft/wool/orders': () =>
      renderRouteRedirect('/fcs/craft/wool/work-orders', '正在跳转到毛织加工单'),
    '/fcs/craft/post-finishing': () =>
      renderRouteRedirect('/fcs/craft/post-finishing/tasks', '正在跳转到后道任务'),
    '/fcs/craft/post-finishing/tasks': () => renderPostFinishingTasksPage(),
    '/fcs/craft/post-finishing/work-orders': () => renderPostFinishingWorkOrdersPage(),
    '/fcs/craft/post-finishing/qc-orders': () => renderPostFinishingQcOrdersPage(),
    '/fcs/craft/post-finishing/recheck-orders': () => renderPostFinishingRecheckOrdersPage(),
    '/fcs/craft/post-finishing/wait-process-warehouse': () => renderPostFinishingWaitProcessWarehousePage(),
    '/fcs/craft/post-finishing/wait-handover-warehouse': () => renderPostFinishingWaitHandoverWarehousePage(),
    '/fcs/craft/post-finishing/statistics': () => renderPostFinishingStatisticsPage(),
    ...specialCraftExactRoutes,
    '/fcs/production/create': () =>
      renderPlaceholderPage(
        '生成生产单',
        '根据生产需求创建生产单，包括拆单规则配置、批次划分、工艺路线选择等。',
        '生产单管理',
      ),
    '/fcs/trace/mapping': () => renderTraceMappingPage(),
    '/fcs/trace/parent-codes': () => renderTraceParentCodesPage(),
    '/fcs/trace/unique-codes': () => renderTraceUniqueCodesPage(),
    '/fcs/trace/unit-price': () => renderTraceUnitPricePage(),
  },
  dynamicRoutes: [
    {
      pattern: /^\/fcs\/progress\/board\/tasks\/([^/?]+)(?:\?.*)?$/,
      render: (match) => renderProgressTaskDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/production-progress-detail\/([^/]+)$/,
      render: (match) => renderCraftCuttingProductionProgressDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/cut-orders\/([^/]+)$/,
      render: (match) => renderCraftCuttingCutOrderDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/sample-warehouse\/([^/?]+)(?:\?.*)?$/,
      render: (match) => renderCraftCuttingSampleWarehouseDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/fei-tickets\/([^/]+)\/print$/,
      render: () => renderCraftCuttingFeiTicketPrintPage(),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/fei-tickets\/([^/]+)\/reprint$/,
      render: () => renderCraftCuttingFeiTicketReprintPage(),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/fei-tickets\/([^/]+)$/,
      render: () => renderCraftCuttingFeiTicketDetailPage(),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/marker-edit\/([^/]+)$/,
      render: (match) => renderCraftCuttingMarkerPlanEditPage(match[1]),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/marker-detail\/([^/]+)$/,
      render: (match) => renderCraftCuttingMarkerPlanDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/orders\/([^/]+)\/tech-pack$/,
      render: (match) => renderFcsProductionTechPackSnapshotPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/orders\/([^/]+)\/confirmation-print$/,
      render: (match) => renderProductionConfirmationPrintPage(match[1]),
    },
    {
      pattern: /^\/fcs\/task-print\/delivery-card\/([^/]+)\/([^/]+)$/,
      render: (match) => renderTaskDeliveryCardPrintPage(match[1], match[2]),
    },
    {
      pattern: /^\/fcs\/task-print\/route-card\/([^/]+)\/([^/]+)$/,
      render: (match) => renderTaskRouteCardPrintPage(match[1], match[2]),
    },
    {
      pattern: /^\/fcs\/factories\/settlement\/new\/([^/]+)$/,
      render: (match) => renderSettlementInitPage(match[1]),
    },
    {
      pattern: /^\/fcs\/factories\/settlement\/([^/]+)$/,
      render: (match) => renderSettlementDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/quality\/qc-records\/([^/]+)$/,
      render: (match) => renderQcRecordDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/quality\/deduction-calc\/([^/]+)$/,
      render: (match) =>
        renderRouteRedirect(
          buildDeductionEntryHrefByBasisId(decodeURIComponent(match[1])),
          '正在跳转到关联质检记录',
        ),
    },
    {
      pattern: /^\/fcs\/production\/changes\/orders\/([^/]+)$/,
      render: (match) => renderProductionChangeRelationDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/changes\/([^/]+)\/edit$/,
      render: (match) => renderProductionChangeEditPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/changes\/([^/]+)$/,
      render: (match) => renderProductionChangeOrderDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/orders\/([^/]+)$/,
      render: (match) => renderProductionOrderDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/production\/task-generation-rules\/([^/]+)\/edit$/,
      render: (match) => renderProductionTaskGenerationRuleEditPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/production\/task-generation-rules\/([^/]+)$/,
      render: (match) => renderProductionTaskGenerationRuleDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/progress\/cutting-overview\/([^/]+)$/,
      render: (match) => renderProgressCuttingDetailPage(match[1]),
    },
    {
      pattern: /^\/fcs\/progress\/handover\/order\/([^/]+)$/,
      render: (match) => renderProgressHandoverOrderPage(match[1]),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/handover-orders\/([^/]+)$/,
      render: (match) => renderCraftCuttingHandoverOrderDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/handover-orders\/([^/]+)\/records$/,
      render: (match) => renderCraftCuttingHandoverOrderRecordsPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/handover-records\/([^/]+)$/,
      render: (match) => renderCraftCuttingHandoverRecordDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/cutting\/special-processes\/([^/]+)$/,
      render: (match) => renderCraftCuttingSpecialProcessDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/process-factory\/special-craft\/([^/]+)\/tasks\/([^/]+)$/,
      render: (match) => renderSpecialCraftTaskDetailPage(match[1], decodeURIComponent(match[2])),
    },
    {
      pattern: /^\/fcs\/process-factory\/special-craft\/([^/]+)\/work-orders\/([^/]+)$/,
      render: (match) => renderSpecialCraftWorkOrderDetailPage(match[1], decodeURIComponent(match[2])),
    },
    {
      pattern: /^\/fcs\/craft\/printing\/work-orders\/([^/]+)$/,
      render: (match) => renderCraftPrintingWorkOrderDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/dyeing\/work-orders\/([^/]+)$/,
      render: (match) => renderRouteRedirect(
        `/fcs/craft/dyeing/work-orders?dyeOrderId=${encodeURIComponent(decodeURIComponent(match[1]))}`,
        '正在跳转到染色加工单',
      ),
    },
    {
      pattern: /^\/fcs\/craft\/wool\/work-orders\/([^/]+)$/,
      render: (match) => renderCraftWoolWorkOrderDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/post-finishing\/recheck-orders\/([^/]+)$/,
      render: (match) => renderPostFinishingRecheckOrderDetailPage(decodeURIComponent(match[1])),
    },
    {
      pattern: /^\/fcs\/craft\/post-finishing\/work-orders\/([^/]+)$/,
      render: (match) => renderPostFinishingWorkOrderDetailPage(decodeURIComponent(match[1])),
    },
  ],
}
