import assert from 'node:assert/strict'
import { test } from 'node:test'
import { mkdir,writeFile } from 'node:fs/promises'
import { chromium } from '@playwright/test'
const base=process.env.ROOM_TEST_URL||'http://127.0.0.1:4206',out='output/playwright/sample-label-style',route='/los/live-room',samples:Array<{round:number;name:string;ms:number}>=[]
const ready=async(p:any)=>{await p.waitForSelector('[data-los-room-root]');await p.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))))}
const action=(p:any,s:string)=>p.locator(`[data-los-room-action="${s}"]`).first(),field=(p:any,s:string)=>p.locator(`[data-los-room-field="${s}"]`).first()
const act=async(p:any,round:number,name:string,fn:()=>Promise<unknown>,wait?:()=>Promise<unknown>)=>{await p.evaluate(()=>(window as any).__roomStart=performance.now());await fn();if(wait)await wait();await ready(p);const ms=await p.evaluate(()=>performance.now()-(window as any).__roomStart);samples.push({round,name,ms});assert.ok(ms<=1000,`${name}: ${ms}ms > 1s`)}
test('ROOM all remaining controls, parent enable/disable, pagination, failures and navigation repeated 5 times',{timeout:300000},async()=>{
 await mkdir(out,{recursive:true});const b=await chromium.launch();try{for(let round=1;round<=5;round++){
 const c=await b.newContext({viewport:{width:round===5?1280:1366,height:768}});await c.addInitScript(()=>{(window as any).__name=(v:unknown)=>v;for(const ev of ['pointerdown','input','change','click'])document.addEventListener(ev,()=>(window as any).__roomStart=performance.now(),true)});const p=await c.newPage();await p.goto(base+route);await ready(p)
 await act(p,round,'sites-open',()=>action(p,'sites').click());await act(p,round,'edit-site',()=>p.locator('[data-los-room-action="edit-site"][data-id="JKT-A"]').click());await act(p,round,'site-name-edit',()=>field(p,'site.name').fill('雅加达 A 验证地点'));await act(p,round,'site-disable-input',()=>field(p,'site.enabled').uncheck());await act(p,round,'site-disable-dialog',()=>action(p,'save-site').click(),()=>p.locator('[data-dialog-confirm]').waitFor());await act(p,round,'site-disable-confirm',()=>p.locator('[data-dialog-confirm]').click(),()=>p.locator('[aria-label="维护直播地点"]').waitFor({state:'hidden'}));assert.match(await p.locator('tbody').textContent(),/地点已停用/)
 await act(p,round,'site-disabled-filter',()=>field(p,'query.enabled').selectOption('no'));await act(p,round,'site-filter-input',()=>field(p,'query.site').selectOption('JKT-A'));await act(p,round,'site-filter-query',()=>action(p,'query').click());assert.equal(await p.locator('tbody tr').count(),1)
 await act(p,round,'sites-reopen',()=>action(p,'sites').click());await act(p,round,'site-edit-again',()=>p.locator('[data-los-room-action="edit-site"][data-id="JKT-A"]').click());await act(p,round,'site-enable-input',()=>field(p,'site.enabled').check());await act(p,round,'site-enable-save',()=>action(p,'save-site').click(),()=>p.locator('[aria-label="维护直播地点"]').waitFor({state:'hidden'}));await act(p,round,'filter-reset',()=>action(p,'reset').click())
 await action(p,'sites').click();await act(p,round,'new-site-reset',()=>action(p,'new-site').click());await field(p,'site.name').fill('不能丢失的地点');p.once('dialog',(d:any)=>d.dismiss());await act(p,round,'site-close-rejected',()=>action(p,'close-sites').click());assert.equal(await field(p,'site.name').inputValue(),'不能丢失的地点');p.once('dialog',(d:any)=>d.accept());await act(p,round,'site-close-confirmed',()=>action(p,'close-sites').click(),()=>p.locator('[aria-label="维护直播地点"]').waitFor({state:'hidden'}))
 await p.evaluate(async()=>{const los=await import('/src/data/los-live-room-master.ts');const categories=los.getLiveRoom('loc-live-01')!.categoryNumberIds;for(let i=10;i<35;i++){const roomId=los.liveRoomCode('JKT-A',6,i);await los.saveLiveRoom({roomId,siteId:'JKT-A',floor:6,sequence:i,name:`分页房间 ${i}`,categoryNumberIds:categories,opm:'A',so:'B',enabled:true},0)}});await p.reload();await ready(p);assert.equal(await p.locator('tbody tr').count(),20);await act(p,round,'next-page',()=>action(p,'next-page').click());assert.equal(await p.locator('tbody tr').count(),7);await act(p,round,'prev-page',()=>action(p,'prev-page').click());assert.equal(await p.locator('tbody tr').count(),20)
 await p.getByText('新增房间',{exact:true}).click();await field(p,'name').fill('取消必须保留');await act(p,round,'category-search-extra',()=>p.locator('[data-los-room-category-search]').fill('11'));await act(p,round,'category-search-clear-extra',()=>p.locator('[data-los-room-category-search]').fill(''));p.once('dialog',(d:any)=>d.dismiss());await act(p,round,'cancel-edit-rejected',()=>action(p,'cancel-edit').click());assert.equal(await field(p,'name').inputValue(),'取消必须保留');p.once('dialog',(d:any)=>d.dismiss());await act(p,round,'browser-back-rejected',()=>p.evaluate(()=>history.back()));await field(p,'name').waitFor();assert.equal(await field(p,'name').inputValue(),'取消必须保留');p.once('dialog',(d:any)=>d.accept());await act(p,round,'cancel-edit-confirmed',()=>action(p,'cancel-edit').click(),()=>p.getByText('直播房间列表',{exact:true}).waitFor())
 // Fail a real UI save, verify original state and recoverable input.
 await p.getByText('新增房间',{exact:true}).click();await field(p,'siteId').selectOption('JKT-A');await field(p,'floor').fill('9');await field(p,'sequence').fill('99');await field(p,'name').fill('故障后保留');await field(p,'opm').fill('A');await field(p,'so').fill('B');await p.locator('[data-los-room-field="categoryNumberIds"]').first().check();await p.evaluate(()=>{(window as any).__originalRoomPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...a:any[]){if(this.name==='records')throw new DOMException('injected','QuotaExceededError');return(window as any).__originalRoomPut.apply(this,a)}});await act(p,round,'save-quota-failure',()=>action(p,'save').click(),()=>p.getByRole('alert').waitFor());assert.equal(await field(p,'name').inputValue(),'故障后保留');await act(p,round,'dismiss-error',()=>action(p,'dismiss').click());await p.evaluate(()=>IDBObjectStore.prototype.put=(window as any).__originalRoomPut);await act(p,round,'retry-save',()=>action(p,'save').click(),()=>p.getByText('直播房间详情',{exact:true}).waitFor());await act(p,round,'logs-open-extra',()=>p.locator('summary').click());await act(p,round,'logs-close-extra',()=>p.locator('summary').click());await act(p,round,'return-list-extra',()=>p.getByText('返回列表',{exact:true}).click(),()=>p.getByText('直播房间列表',{exact:true}).waitFor());for(const key of ['site','categories','owners','enabled'])for(let i=0;i<3;i++)await act(p,round,`sort-${key}-${i}`,()=>p.locator(`[data-los-room-action="sort-column"][data-column-key="${key}"]`).click());await c.close()
 for(const path of [route+'/new',route+'/loc-live-01/edit']){const recovery=await b.newContext();await recovery.addInitScript(()=>{(window as any).__name=(v:unknown)=>v;const open=indexedDB.open.bind(indexedDB);(window as any).__fail=true;indexedDB.open=((...a:any[])=>{if(a[0]==='higood-pcs-records'&&(window as any).__fail)throw new DOMException('injected','InvalidStateError');return(open as any)(...a)}) as any;document.addEventListener('pointerdown',()=>(window as any).__roomStart=performance.now(),true)});const q=await recovery.newPage();await q.goto(base+path);await q.getByText('直播房间资料暂时无法读取',{exact:true}).waitFor();await q.evaluate(()=>(window as any).__fail=false);await act(q,round,path+':recover-read',()=>action(q,'reload').click(),()=>field(q,'name').waitFor());await recovery.close()}
 }
 await writeFile(out+'/room-extra-performance.json',JSON.stringify({samples,maximum:Math.max(...samples.map(s=>s.ms))},null,2))
 }finally{await b.close()}
})
