import assert from 'node:assert/strict'
import { test } from 'node:test'
import { mkdir,writeFile } from 'node:fs/promises'
import { chromium } from '@playwright/test'
const base=process.env.ROOM_TEST_URL||'http://127.0.0.1:4206',out='output/playwright/sample-label-style',route='/los/live-room'
const samples:Array<{name:string;ms:number;round:number}>=[],errors:string[]=[]
const ready=async(p:any)=>{await p.waitForSelector('[data-los-room-root]');await p.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))))}
const finish=async(p:any,name:string,round:number,nav=false)=>{await ready(p);const ms=await p.evaluate((nav:boolean)=>performance.now()-(nav?0:(window as any).__roomStart),nav);samples.push({name,ms,round});if(ms>1000)await writeFile(out+'/room-failed-samples.json',JSON.stringify({samples,failed:{name,ms,round}},null,2));assert.ok(ms<=1000,`${name}: ${ms}ms > 1s`)}
const act=async(p:any,name:string,round:number,action:()=>Promise<unknown>,wait?:()=>Promise<unknown>)=>{await p.evaluate(()=>(window as any).__roomStart=performance.now());await action();if(wait)await wait();await finish(p,name,round)}
const action=(p:any,s:string)=>p.locator(`[data-los-room-action="${s}"]`).first(),field=(p:any,s:string)=>p.locator(`[data-los-room-field="${s}"]`).first()
const init=()=>{(window as any).__name=(v:unknown)=>v;for(const ev of ['pointerdown','input','change','click'])document.addEventListener(ev,()=>(window as any).__roomStart=performance.now(),true);window.print=()=>{if(window.parent!==window)(window.parent as any).__roomPrinted=document.documentElement.outerHTML;window.dispatchEvent(new Event('afterprint'))}}
const rows=async(p:any)=>p.evaluate(async()=>JSON.stringify((await(await import('/src/data/pcs-record-db.ts')).readPcsRecords()).records))

test('ROOM unique identity, maintenance, refreshed print, atomic guards and 1s gate', {timeout:300000},async()=>{
 await mkdir(out,{recursive:true});const b=await chromium.launch({headless:true})
 try{for(let round=1;round<=5;round++){
  const c=await b.newContext({viewport:{width:round===5?1280:1366,height:round===5?720:768},acceptDownloads:true});await c.addInitScript(init);const p=await c.newPage();p.on('pageerror',(e:any)=>errors.push(e.message));const cd=await c.newCDPSession(p);await cd.send('Network.enable');await cd.send('Network.setCacheDisabled',{cacheDisabled:true})
  for(const path of [route,route+'/new',route+'/loc-live-01',route+'/loc-live-01/edit',route+'/loc-live-01/label']){
   await p.goto(base+path);await finish(p,path+':cold',round,true);await p.reload();await finish(p,path+':reload',round,true)
   await p.goto(base+route);await ready(p);await act(p,path+':SPA',round,()=>p.evaluate((path:string)=>{const a=document.createElement('a');a.dataset.nav=path;document.querySelector('main')!.append(a);(window as any).__oldRoom=document.querySelector('[data-los-room-root]');a.click();a.remove()},path),()=>p.waitForFunction(()=>!(window as any).__oldRoom?.isConnected))
  }
  assert.equal(await rows(p),'[]','fresh reads persist no seed copies')
  await p.goto(base+route);await ready(p);await act(p,'open-sites',round,()=>action(p,'sites').click());await act(p,'site-code',round,()=>field(p,'site.code').fill('TEST-JKT'));await act(p,'site-name',round,()=>field(p,'site.name').fill('验证直播地点'))
  await act(p,'save-site',round,()=>action(p,'save-site').click(),()=>p.waitForSelector('[aria-label="维护直播地点"]',{state:'hidden'}))
  await act(p,'new-room',round,()=>p.getByText('新增房间',{exact:true}).click(),()=>field(p,'floor').waitFor());await act(p,'site-select',round,()=>field(p,'siteId').selectOption('TEST-JKT'));await act(p,'floor',round,()=>field(p,'floor').fill('4'));await act(p,'sequence',round,()=>field(p,'sequence').fill('2'))
  assert.equal(await p.locator('[data-room-code-preview]').textContent(),'TEST-JKT-04-002')
  await act(p,'room-name',round,()=>field(p,'name').fill('402 直播房间'));await act(p,'opm',round,()=>field(p,'opm').fill('SELVI'));await act(p,'so',round,()=>field(p,'so').fill('LUSI'))
  await act(p,'category-search',round,()=>p.locator('[data-los-room-category-search]').fill('11 ·'));await act(p,'category-select-11',round,()=>p.locator('[data-room-category-option]').filter({hasText:'11 · knit top-18-30'}).locator('input').check());await p.locator('[data-los-room-category-search]').fill('54 ·');await act(p,'category-select-54',round,()=>p.locator('[data-room-category-option]').filter({hasText:'54 · knit cardigan-18-30'}).locator('input').check())
  await act(p,'save-room',round,()=>action(p,'save').click(),()=>p.getByText('直播房间详情',{exact:true}).waitFor());assert.ok((await rows(p)).includes('TEST-JKT-04-002'));await p.reload();await finish(p,'saved-room-refresh',round,true)
  await act(p,'edit-room',round,()=>p.getByText('编辑',{exact:true}).first().click(),()=>field(p,'name').waitFor());for(const k of ['siteId','floor','sequence'])assert.equal(await field(p,k).isDisabled(),true)
  await act(p,'update-room-name',round,()=>field(p,'name').fill('402 已维护房间'));await act(p,'update-room',round,()=>action(p,'save').click(),()=>p.getByText('直播房间详情',{exact:true}).waitFor())
  await act(p,'label-preview',round,()=>p.getByText('打印标签',{exact:true}).click(),()=>p.locator('[data-room-label]').first().waitFor());assert.equal(await p.locator('[data-room-label]').count(),2);assert.deepEqual(await p.locator('.room-door-code').allTextContents(),['TEST-JKT-04-002','TEST-JKT-04-002']);assert.match(await p.locator('[data-room-label-preview]').textContent(),/11-knit top-18-30.*针织上衣.*OPM = SELVI.*S.O = LUSI/s)
  const beforePrint=await rows(p);await act(p,'print',round,()=>action(p,'print').click(),()=>p.waitForFunction(()=>!!(window as any).__roomPrinted));assert.equal(await rows(p),beforePrint)
  const html=await p.evaluate(()=>(window as any).__roomPrinted);assert.match(html,/@page\{size:A4 portrait/);assert.ok(!html.includes('data-los-room-root'))
  if(round===1){await p.screenshot({path:out+'/room-label.png',fullPage:true});const printPage=await c.newPage();await printPage.setContent(html);await printPage.pdf({path:out+'/room-door-label.pdf',preferCSSPageSize:true,printBackground:true});await printPage.close();await writeFile(out+'/room-door-label.html',html)}
  // Duplicate identity is rejected without adding a record.
  await p.goto(base+route+'/new');await ready(p);await field(p,'siteId').selectOption('TEST-JKT');await field(p,'floor').fill('4');await field(p,'sequence').fill('2');await field(p,'name').fill('重复房间');await field(p,'opm').fill('A');await field(p,'so').fill('B');await p.locator('[data-los-room-field="categoryNumberIds"]').first().check();const beforeDuplicate=await rows(p);await act(p,'duplicate-room-rejected',round,()=>action(p,'save').click(),()=>p.getByRole('alert').waitFor());assert.match(await p.getByRole('alert').textContent(),/已存在/);assert.equal(await rows(p),beforeDuplicate)
  // Leave protection preserves the current input on cancellation.
  p.once('dialog',(d:any)=>d.dismiss());await act(p,'leave-rejected',round,()=>p.getByText('返回列表',{exact:true}).click());assert.equal(await field(p,'name').inputValue(),'重复房间');p.once('dialog',(d:any)=>d.accept());await act(p,'leave-confirmed',round,()=>p.getByText('返回列表',{exact:true}).click(),()=>p.getByText('直播房间列表',{exact:true}).waitFor())
  // Cross-tab updates, quota abort and disabled parent guard share the real record adapter.
  const checks=await p.evaluate(async()=>{
   const los=await import('/src/data/los-live-room-master.ts'),db=await import('/src/data/pcs-record-db.ts');await los.ensureLosLiveRoomState();const r=los.getLiveRoom('TEST-JKT-04-002')!,v=los.losRecordVersion('rooms',r.roomId),guard=los.liveRoomTransferGuards(r.roomId),before=JSON.stringify((await db.readPcsRecords()).records)
   const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:any[]){if(this.name==='records')throw new DOMException('injected quota','QuotaExceededError');return put.apply(this,args as any)};let quota=false;try{await los.saveLiveRoom({...r,name:'不得保存'},v)}catch{quota=true}finally{IDBObjectStore.prototype.put=put}const rolledBack=JSON.stringify((await db.readPcsRecords()).records)===before
   await los.saveLiveRoom({...r,name:'其他标签保存'},v);let stale=false;try{await los.saveLiveRoom({...r,name:'旧版不能覆盖'},v)}catch{stale=true}
   let race=false;try{await db.commitPcsRecords({puts:[{id:'room-test/sample-guard',collection:'test',value:{sample:'unchanged'},expectedVersion:0}],guards:guard,deletes:[],operationId:crypto.randomUUID(),intent:'room guard race'})}catch{race=true}
   const parentGuards=los.liveRoomTransferGuards(r.roomId);const site=los.listLiveSites().find(s=>s.siteId===r.siteId)!;await los.saveLiveSite({...site,enabled:false},los.losRecordVersion('sites',site.siteId));let parentRace=false;try{await db.commitPcsRecords({puts:[{id:'room-test/site-guard',collection:'test',value:{sample:'unchanged'},expectedVersion:0}],guards:parentGuards,deletes:[],operationId:crypto.randomUUID(),intent:'parent guard race'})}catch{parentRace=true}await los.ensureLosLiveRoomState();const parentDisabled=!los.liveRoomAvailable(los.getLiveRoom(r.roomId)!);await los.saveLiveSite({...site,enabled:true},los.losRecordVersion('sites',site.siteId));const noPartial=!(await db.readPcsRecords()).records.some(r=>r.id==='room-test/sample-guard');await los.ensureLosLiveRoomState();await los.setLiveRoomEnabled(r.roomId,false,los.losRecordVersion('rooms',r.roomId));const projection=await import('/src/data/pcs-sample-location-master.ts');const location=projection.getPcsSampleLocationById(r.roomId);let disabled=false;try{los.liveRoomTransferGuards(r.roomId)}catch{disabled=true}
   return {quota,rolledBack,stale,race,parentRace,parentDisabled,noPartial,disabled,historical:!!location&&location.enabled===false}
  });assert.deepEqual(checks,{quota:true,rolledBack:true,stale:true,race:true,parentRace:true,parentDisabled:true,noPartial:true,disabled:true,historical:true})
  await p.goto(base+route+'/TEST-JKT-04-002');await ready(p);await act(p,'open-enable-dialog',round,()=>action(p,'enabled').click(),()=>p.locator('[data-dialog-confirm]').waitFor());await act(p,'confirm-enable',round,()=>p.locator('[data-dialog-confirm]').click(),()=>p.getByText('使用状态已保存',{exact:false}).waitFor());await act(p,'open-disable-dialog',round,()=>action(p,'enabled').click(),()=>p.locator('[data-dialog-confirm]').waitFor());await act(p,'confirm-disable',round,()=>p.locator('[data-dialog-confirm]').click(),()=>p.getByText('启用房间',{exact:true}).waitFor());await act(p,'log-expand',round,()=>p.locator('summary').click());assert.match(await p.locator('details').textContent(),/启用房间.*停用房间/s);
  await p.goto(base+route);await ready(p);await act(p,'query-input',round,()=>field(p,'query.keyword').fill('TEST-JKT'));await act(p,'query',round,()=>action(p,'query').click());assert.equal(await p.locator('tbody tr').count(),1);const download=p.waitForEvent('download');await act(p,'export',round,()=>action(p,'export').click());await(await download).saveAs(out+`/room-${round}.csv`)
  await act(p,'reset',round,()=>action(p,'reset').click());for(let i=0;i<3;i++)await act(p,'sort-'+i,round,()=>action(p,'sort-column').first().click());await act(p,'columns',round,()=>action(p,'columns').click());await act(p,'hide-category-column',round,()=>p.locator('[data-los-room-action="toggle-column-visibility"][data-los-room-column-key="categories"]').click());await act(p,'freeze-code',round,()=>p.locator('[data-los-room-action="toggle-column-freeze"][data-los-room-column-key="code"]').click());await act(p,'column-drag',round,()=>p.locator('[data-drag-source="owners"]').dragTo(p.locator('[data-drop-target="site"]')));await act(p,'close-columns',round,()=>action(p,'close-column-settings').click());const header=await p.locator('thead th').allTextContents();assert.ok(header.findIndex((s:string)=>s.includes('标签责任人'))<header.findIndex((s:string)=>s.includes('地点 / 楼层')));assert.ok(!header.some((s:string)=>s==='品类编号'))
  await p.reload();await finish(p,'column-preference-refresh',round,true);assert.ok(!(await p.locator('thead th').allTextContents()).some((s:string)=>s==='品类编号'));await action(p,'columns').click();await act(p,'restore-columns',round,()=>action(p,'restore-column-settings').click());await action(p,'close-column-settings').click();await act(p,'page-size',round,()=>field(p,'pageSize').selectOption('50'))
  if(round===1)await p.screenshot({path:out+'/room-list.png',fullPage:true});await c.close()
 }
 assert.deepEqual(errors,[]);await writeFile(out+'/room-performance.json',JSON.stringify({samples,maximum:Math.max(...samples.map(s=>s.ms)),errors},null,2))
 }finally{await b.close()}
})

test('ROOM initial read failure recovers both new and edit direct routes without losing draft',{timeout:60000},async()=>{
 const b=await chromium.launch({headless:true});try{for(const path of [route+'/new',route+'/loc-live-01/edit']){const c=await b.newContext();await c.addInitScript(init);await c.addInitScript(()=>{const open=indexedDB.open.bind(indexedDB);(window as any).__failRoom=true;indexedDB.open=((...a:any[])=>{if((window as any).__failRoom&&a[0]==='higood-pcs-records')throw new DOMException('injected','InvalidStateError');return(open as any)(...a)}) as any});const p=await c.newPage();await p.goto(base+path);await p.getByText('直播房间资料暂时无法读取',{exact:true}).waitFor();await p.evaluate(()=>(window as any).__failRoom=false);await action(p,'reload').click();await field(p,'name').waitFor();assert.equal(await p.locator('[data-los-room-root]').count(),1);await c.close()}}finally{await b.close()}
})

test('ROOM two tabs cannot create the same unique identity; browser back preserves unsaved room', {timeout:60000},async()=>{
 const b=await chromium.launch();const c=await b.newContext();await c.addInitScript(init);try{const p=await c.newPage(),q=await c.newPage();for(const page of [p,q]){await page.goto(base+route);await ready(page)}
 const create=(page:any)=>page.evaluate(async()=>{const los=await import('/src/data/los-live-room-master.ts');const id=los.liveRoomCode('JKT-A',5,7),categoryNumberIds=los.getLiveRoom('loc-live-01')!.categoryNumberIds;try{await los.saveLiveRoom({roomId:id,siteId:'JKT-A',floor:5,sequence:7,name:'并发房间',opm:'A',so:'B',enabled:true,categoryNumberIds},0);return true}catch{return false}});const outcomes=await Promise.all([create(p),create(q)]);assert.equal(outcomes.filter(Boolean).length,1);
 await p.goto(base+route);await ready(p);await p.getByText('新增房间',{exact:true}).click();await field(p,'name').fill('后退必须保留');p.once('dialog',(d:any)=>d.dismiss());await p.evaluate(()=>history.back());await ready(p);assert.equal(await field(p,'name').inputValue(),'后退必须保留');assert.equal(new URL(p.url()).pathname,route+'/new');
 }finally{await c.close();await b.close()}
})
