import assert from 'node:assert/strict'
import test from 'node:test'
import { chromium, type Page } from '@playwright/test'
import { mkdir, writeFile, readFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
const dev=process.env.SIMPLE_DEV_URL||'http://127.0.0.1:43219',production=process.env.SIMPLE_PROD_URL||'http://127.0.0.1:43220'
const out='output/playwright/pcs-simple-materials/copy-identity',rounds=Number(process.env.SIMPLE_ADVERSARIAL_ROUNDS||5)
const act=(a:string)=>`[data-pcs-material-archive-action="${a}"]`,fld=(f:string)=>`[data-pcs-material-archive-field="${f}"]`
const samples:Array<{name:string;ms:number;repeat:number}>=[],errors:string[]=[],checks:string[]=[]
const init=()=>{(globalThis as any).__name=(x:unknown)=>x;(globalThis as any).__adversarialStart=0;(globalThis as any).__pcsWriteCount=0;(globalThis as any).__failPcsWrite=false;(globalThis as any).__blockPreferences=false;const get=Storage.prototype.getItem,set=Storage.prototype.setItem;Storage.prototype.getItem=function(k:string){if((globalThis as any).__blockPreferences)throw new DOMException('Preference denied','SecurityError');return get.call(this,k)};Storage.prototype.setItem=function(k:string,v:string){if((globalThis as any).__blockPreferences)throw new DOMException('Preference full','QuotaExceededError');set.call(this,k,v)}
 const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:any[]){if(this.name==='records'){(globalThis as any).__pcsWriteCount++;if((globalThis as any).__failPcsWrite)throw new DOMException('Injected isolated quota failure','QuotaExceededError')}return put.apply(this,args as any)}
}
async function settled(page:Page){await page.waitForSelector('main');await page.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('main img')].filter(i=>{const r=i.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth}).every(i=>i.complete&&i.naturalWidth>0));await page.evaluate(async()=>{await document.fonts.ready;const frames=()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r())));await frames();await Promise.all(document.getAnimations().filter(a=>a.playState!=='finished'&&Number.isFinite(a.effect?.getComputedTiming().iterations)).map(a=>a.finished.catch(()=>undefined)));await frames()})}
async function finish(page:Page,name:string,repeat:number,nav=false){await settled(page);samples.push({name,repeat,ms:await page.evaluate(nav=>performance.now()-(nav?0:(globalThis as any).__adversarialStart),nav)})}
async function action(page:Page,name:string,repeat:number,run:()=>Promise<unknown>,done?:()=>Promise<unknown>){await page.evaluate(()=>(globalThis as any).__adversarialStart=performance.now());await run();if(done)await done();await finish(page,name,repeat)}
async function go(page:Page,route:string,selector:string){await page.goto(production+route,{waitUntil:'domcontentloaded'});await page.waitForSelector(selector);await settled(page)}
async function rows(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((r,j)=>{const q=indexedDB.open('higood-pcs-records');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});const values=await new Promise<any[]>((r,j)=>{const q=db.transaction('records','readonly').objectStore('records').getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});db.close();return values.sort((a,b)=>a.id.localeCompare(b.id))})}
async function files(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((r,j)=>{const q=indexedDB.open('higood-pcs-records');q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});const list=await new Promise<any[]>((r,j)=>{const q=db.transaction('files','readonly').objectStore('files').getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});db.close();return Promise.all(list.map(async f=>({id:f.id,size:f.blob.size,type:f.blob.type,text:await f.blob.text()})))})}
async function install(page:Page,fixture:any){await page.evaluate(async data=>{const db=await new Promise<IDBDatabase>((r,j)=>{const q=indexedDB.open('higood-pcs-records',2);q.onupgradeneeded=()=>{for(const k of ['records','files','operations','meta'])if(!q.result.objectStoreNames.contains(k))q.result.createObjectStore(k,{keyPath:'id'})};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});await new Promise<void>((r,j)=>{const tx=db.transaction(['records','files'],'readwrite');data.records.forEach((v:any)=>tx.objectStore('records').put(v));data.files.forEach((v:any)=>tx.objectStore('files').put({id:v.id,blob:new Blob([v.text],{type:v.type})}));tx.oncomplete=()=>r();tx.onabort=()=>j(tx.error)});db.close()},fixture)}

async function prepareCopy(browser:Awaited<ReturnType<typeof chromium.launch>>){const c=await browser.newContext();await c.addInitScript(init);const p=await c.newPage();await p.goto(dev+'/pcs/materials/parts');await p.waitForSelector('[data-pcs-material-archive-page]');const result=await p.evaluate(async()=>{
 const m=await import('/src/data/pcs-material-archive-repository.ts'),runtime=await import('/src/data/pcs-record-runtime.ts'),db=await import('/src/data/pcs-record-db.ts');await runtime.ensurePcsRecordState(runtime.PCS_LEGACY_KEYS);const all=m.listMaterialArchives(),items:any[]=[];
 await runtime.runPcsRecordCommand(()=>{for(const kind of ['parts','consumable'] as const){const source=all.find((x:any)=>x.kind===kind)!,root=m.createMaterialArchive({kind,materialName:'复制身份补验-'+kind,materialNameEn:'',categoryName:source.categoryName,remark:'隔离原型测试',specSummary:'',composition:'',processTags:[],widthText:'',gramWeightText:'',pricingUnit:'PCS',mainImageUrl:source.mainImageUrl,firstSku:{colorName:'',sizeName:'',specName:'原规格-'+kind,mainUnit:'PCS',pricingUnit:'PCS',skuImageUrl:source.mainImageUrl,costPrice:0,freightCost:0,weightKg:0,lengthCm:0,widthCm:0,heightCm:0,barcode:''}}),sku=m.listMaterialSkuRecordsByMaterialId(root.materialId)[0],blob=new Blob(['copy-original-'+kind+'-do-not-modify'],{type:'text/plain'}),file=runtime.registerPcsFile(blob,'copy-identity-'+kind);m.addMaterialAsset({materialId:root.materialId,materialSkuId:sku.materialSkuId,name:'原规格说明.txt',role:'SPECIFICATION',url:file.url,fileId:file.fileId,fileName:'原规格说明.txt',mimeType:'text/plain',sizeBytes:blob.size,createdBy:'原型隔离验收'});items.push({kind,rootId:root.materialId,skuId:sku.materialSkuId,code:sku.materialSkuCode,alias:'原型补验别名-'+kind})}});
 const saved=await db.readPcsRecords();return{items,records:saved.records,files:await Promise.all(saved.files.map(async(f:any)=>({id:f.id,type:f.blob.type,text:await f.blob.text()})))}
 });await c.close();return result}

test('SIMPLE-019: copied identity never transfers aliases or rewrites source SKU / attachment entities',{timeout:300000},async()=>{
 await mkdir(out,{recursive:true});const browser=await chromium.launch();let page:Page|undefined,failure:unknown;const facts:any[]=[]
 try{const fixture=await prepareCopy(browser);for(let repeat=0;repeat<5;repeat++){const c=await browser.newContext({viewport:repeat===4?{width:1280,height:720}:{width:1366,height:768}});await c.addInitScript(init);page=await c.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await go(page,'/pcs/materials/parts','[data-pcs-material-archive-page]');await install(page,fixture)
 for(const item of fixture.items){const sourcePath=`/pcs/materials/${item.kind}/${item.rootId}/skus/${item.skuId}`;await go(page,sourcePath+'/edit','[data-pcs-material-sku-edit]');await action(page,item.kind+':maintain-source-alias',repeat,()=>page!.locator(fld('barcodeAliases')).fill(item.alias));await action(page,item.kind+':save-source-alias',repeat,()=>page!.locator(act('save-form')).click(),()=>page!.waitForSelector('[data-pcs-material-sku-detail]'));await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-pcs-material-sku-detail]');await finish(page,item.kind+':source-alias-refresh',repeat,true);assert.ok((await page.locator('main').innerText()).includes(item.alias));
 const originalRows=await rows(page),sourceId=`higood-pcs-material-archive-store-v2/skuRecords/${item.skuId}`,sourceBefore=originalRows.find(r=>r.id===sourceId)!,sourceAssetsBefore=originalRows.filter(r=>!r.deleted&&r.collection.endsWith('/assets')&&(r.value as any).data.materialSkuId===item.skuId),filesBefore=await files(page);assert.ok(sourceBefore);assert.deepEqual((sourceBefore.value as any).data.barcodeAliases,[item.alias]);
 await action(page,item.kind+':source-more',repeat,()=>page!.locator(act('simple-actions')).click());await action(page,item.kind+':copy-unsaved',repeat,()=>page!.locator(act('copy-sku')).click(),()=>page!.waitForSelector('[data-pcs-material-sku-edit]'));assert.equal(await page.locator(fld('barcodeAliases')).inputValue(),'');assert.equal(await page.locator(fld('copyCost')).isChecked(),false);const copiedSpec='复制身份独立规格-'+item.kind;await action(page,item.kind+':new-copied-spec',repeat,()=>page!.locator(fld('specName')).fill(copiedSpec));await action(page,item.kind+':save-independent-copy',repeat,()=>page!.locator(act('save-form')).click(),()=>page!.waitForSelector('[data-pcs-material-sku-detail]'));
 const persisted=await rows(page),sourceAfter=persisted.find(r=>r.id===sourceId)!;assert.deepEqual(sourceAfter,sourceBefore,'source SKU data and actual persistent version must be byte-for-byte unchanged');const sourceAssetsAfter=persisted.filter(r=>!r.deleted&&r.collection.endsWith('/assets')&&(r.value as any).data.materialSkuId===item.skuId);assert.deepEqual(sourceAssetsAfter,sourceAssetsBefore);assert.deepEqual(await files(page),filesBefore,'copy must reuse the source file entity, preserving count and bytes');const copyRow=persisted.find(r=>!r.deleted&&r.collection.endsWith('/skuRecords')&&(r.value as any).data.materialId===item.rootId&&(r.value as any).data.specName===copiedSpec)!,copy=(copyRow.value as any).data;assert.notEqual(copy.materialSkuCode,item.code);assert.notEqual(copy.materialSkuId,item.skuId);assert.deepEqual(copy.barcodeAliases,[]);const copyAssets=persisted.filter(r=>!r.deleted&&r.collection.endsWith('/assets')&&(r.value as any).data.materialSkuId===copy.materialSkuId);assert.equal(copyAssets.length,1);assert.equal((copyAssets[0].value as any).data.fileId,'copy-identity-'+item.kind);
 await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('[data-pcs-material-sku-detail]');await finish(page,item.kind+':copy-refresh',repeat,true);await action(page,item.kind+':copied-file-details',repeat,()=>page!.locator('summary').filter({hasText:'识别图片与补充资料'}).click());const href=await page.getByRole('link',{name:'查看资料',exact:true}).getAttribute('href');assert.ok(href);const fileText=await page.evaluate(async href=>(await fetch(href!)).text(),href);assert.equal(fileText,'copy-original-'+item.kind+'-do-not-modify');
 await action(page,item.kind+':return-list-after-copy-refresh',repeat,()=>page!.locator('[data-pcs-material-sku-detail] header [data-nav]').first().click(),()=>page!.waitForSelector('[data-pcs-material-archive-page]'));await action(page,item.kind+':query-source-alias-input',repeat,()=>page!.locator(fld('search')).fill(item.alias));await action(page,item.kind+':query-source-alias-after-copy',repeat,()=>page!.getByRole('button',{name:'查询',exact:true}).click());assert.equal(await page.locator('tbody input[type="checkbox"]').count(),1);assert.ok((await page.locator('tbody').innerText()).includes(item.code));assert.equal(await page.locator(`tbody [data-nav$="/${copy.materialSkuId}"]`).count(),0);assert.ok(await page.locator(`tbody [data-nav="${sourcePath}"]`).count());if(repeat===0||repeat===4)await page.screenshot({path:`${out}/${item.kind}-source-alias-resolved-${repeat===4?'1280':'1366'}.png`,fullPage:true});await action(page,item.kind+':source-identity-open-after-copy',repeat,()=>page!.locator(`tbody [data-nav="${sourcePath}"]`).first().click(),()=>page!.waitForSelector('[data-pcs-material-sku-detail]'));assert.ok((await page.locator('main').innerText()).includes(item.alias));assert.deepEqual((await rows(page)).find(r=>r.id===sourceId),sourceBefore);assert.deepEqual(await files(page),filesBefore);
 facts.push({repeat,kind:item.kind,sourceSkuId:item.skuId,sourceSkuCode:item.code,sourcePersistentVersionBefore:sourceBefore.version,sourcePersistentVersionAfter:sourceAfter.version,sourceRowUnchanged:true,sourceAssetRowsUnchanged:true,filesUnchanged:true,fileCount:filesBefore.length,copySkuId:copy.materialSkuId,copySkuCode:copy.materialSkuCode,copyAliases:copy.barcodeAliases,alias:item.alias,scope:'通过实际编辑保存的隔离 Mock 别名；不是线上历史别名',resolvedSkuId:item.skuId,wrongCopiedAliasMatches:0})
 }await c.close()}
 }catch(e){failure=e;if(page&&!page.isClosed()){await page.screenshot({path:out+'/failed.png',fullPage:true}).catch(()=>{});await writeFile(out+'/failed-page.txt',await page.locator('body').innerText().catch(()=>''))}}
 finally{const html=await(await fetch(production)).text(),path=html.match(/<script[^>]+src="([^"]+\.js)"/)?.[1]||'',bytes=path?Buffer.from(await(await fetch(production+path)).arrayBuffer()):Buffer.alloc(0),hash=createHash('sha256').update(bytes).digest('hex'),local=path?createHash('sha256').update(await readFile('dist'+path)).digest('hex'):'';const groups=[...new Set(samples.map(s=>s.name))].map(name=>{const values=samples.filter(s=>s.name===name).map(s=>s.ms);return{name,values,max:Math.max(...values),passed:values.length===5&&values.every(ms=>ms<=1000)}});await writeFile(out+'/report.json',JSON.stringify({passed:!failure&&!errors.length&&groups.every(g=>g.passed)&&hash===local,requirements:['SIMPLE-019'],functionalFailure:failure?String(failure):'',errors,facts,groups,samples,measurement:'Five rounds: four 1366x768 and one 1280x720; before action / navigation start through persistence, visible images, fonts, finite animations and two frames; no exemptions',branch:execFileSync('git',['branch','--show-current']).toString().trim(),head:execFileSync('git',['rev-parse','HEAD']).toString().trim(),worktree:process.cwd(),servedBundle:{path,sha256:hash,matchesLocalDist:hash===local},browser:browser.version()},null,2));await browser.close()}
 assert.ifError(failure);assert.deepEqual(errors,[]);assert.equal(facts.length,10);assert.ok(samples.every(s=>s.ms<=1000));assert.ok([...new Set(samples.map(s=>s.name))].every(name=>samples.filter(s=>s.name===name).length===5))
})
