import assert from 'node:assert/strict'
import test from 'node:test'
import {chromium,type Page} from '@playwright/test'
import {mkdir,writeFile} from 'node:fs/promises'
const base=process.env.SIMPLE_TEST_URL||'http://127.0.0.1:43220',out='output/playwright/pcs-simple-materials/long-label'
const A=(a:string)=>`[data-pcs-material-archive-action="${a}"]`,F=(f:string)=>`[data-pcs-material-archive-field="${f}"]`
async function settled(p:Page){await p.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('main img, body img')].filter(x=>x.getBoundingClientRect().width>0&&x.getBoundingClientRect().height>0).every(x=>x.complete&&x.naturalWidth>0));await p.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));});}
test('SIMPLE-020/060: 120 character Chinese model and 100 labels retain text, QR and pagination',{timeout:180000},async()=>{
 await mkdir(out,{recursive:true});const b=await chromium.launch(),samples:any[]=[],errors:string[]=[]
 try{for(let r=0;r<5;r++)for(const kind of ['parts','consumable']){
 const c=await b.newContext({viewport:r===4?{width:1280,height:720}:{width:1366,height:768}});await c.addInitScript(()=>{(globalThis as any).__name=(v:any)=>v;document.addEventListener('pointerdown',()=>{(window as any).__start=performance.now()},true);window.print=()=>{(window as any).__printed=true}});const p=await c.newPage();const cacheSession=await c.newCDPSession(p);await cacheSession.send('Network.enable');await cacheSession.send('Network.setCacheDisabled',{cacheDisabled:true});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+`/pcs/materials/${kind}/new`);await p.waitForSelector(F('firstSpec'));const model='中文超长规格型号适配不同设备及包装尺寸说明'.repeat(6).slice(0,120);assert.equal(model.length,120);await p.locator(F('materialName')).fill('长型号标签测试');await p.locator(F('firstSpec')).fill(model+'中');await p.locator(A('save-form')).click();await p.getByRole('status').filter({hasText:'120'}).first().waitFor();await settled(p);const rejectMs=await p.evaluate(()=>performance.now()-(window as any).__start);samples.push({name:kind+':121-character-block',round:r,ms:rejectMs});assert.ok(rejectMs<=1000);assert.equal(await p.locator(F('firstSpec')).inputValue(),model+'中');await p.locator(F('firstSpec')).fill(model);await p.locator('input[type=file][data-image-target="mainImageUrl"]').setInputFiles(kind==='parts'?'public/materials/pcs-reviewed/knife.jpg':'public/materials/packing-bag.jpg');await p.locator(A('save-form')).click();await p.waitForSelector('[data-pcs-material-detail]');await p.locator(A('root-tab')+'[data-value="skus"]').click();await p.locator('[data-nav*="/skus/"]').filter({hasText:'详情'}).first().click();await p.waitForSelector('[data-pcs-material-sku-detail]');await p.locator(A('simple-actions')).first().click();await p.locator(A('print-label')).click();await p.locator('#pcs-material-labels svg').waitFor();await p.locator(F('printQuantity')).fill('100');await p.locator('#pcs-material-labels svg').waitFor();const promise=p.waitForEvent('popup');await p.locator(A('print-now')).click();const w=await promise;await w.waitForFunction(()=>(window as any).__printed);await settled(w);const ms=await p.evaluate(()=>performance.now()-(window as any).__start);samples.push({name:kind+':long-100-print',round:r,ms});assert.ok(ms<=1000,`${kind} ${ms}ms`);assert.equal(await w.locator('svg').count(),100);assert.ok((await w.locator('body').innerText()).includes(model));const clipped=await w.evaluate(()=>[...document.querySelectorAll<HTMLElement>('[style]')].filter(x=>['hidden','clip'].includes(getComputedStyle(x).overflowY)&&x.scrollHeight>x.clientHeight+1).map(x=>({text:x.innerText,height:x.clientHeight,scroll:x.scrollHeight})));assert.deepEqual(clipped,[]);if(r===0){await w.pdf({path:out+'/'+kind+'-100.pdf',format:'A4'});await w.screenshot({path:out+'/'+kind+'.png'});await writeFile(out+'/'+kind+'-model.txt',model)}await c.close()
 }}finally{await writeFile(out+'/performance.json',JSON.stringify({base,samples,errors},null,2));await b.close()}assert.deepEqual(errors,[])
})
