import assert from 'node:assert/strict'
import test from 'node:test'
import {mkdir,writeFile} from 'node:fs/promises'
import {execFileSync} from 'node:child_process'
import {chromium,type Page} from '@playwright/test'
const base=process.env.SIMPLE_TEST_URL||'http://127.0.0.1:43220',out='output/playwright/pcs-simple-materials'
const rounds=Number(process.env.SIMPLE_TEST_ROUNDS||5),gate=process.env.SIMPLE_FUNCTION_ONLY!=='true'
const act=(a:string)=>`[data-pcs-material-archive-action="${a}"]`,fld=(f:string)=>`[data-pcs-material-archive-field="${f}"]`
test('SIMPLE: isolated real page lifecycle, files, review, units, import, print and five performance samples',{timeout:360000},async()=>{
 await mkdir(out,{recursive:true});const browser=await chromium.launch(),samples:Array<{name:string;ms:number;round:number}>=[],errors:string[]=[];let round=0
 const ready=async(p:Page)=>{await p.waitForSelector('[data-pcs-material-archive-page], [data-pcs-material-detail], [data-pcs-material-sku-detail], [data-pcs-material-edit], [data-pcs-material-sku-edit]');await p.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('main img')].filter(i=>{const r=i.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight}).every(i=>i.complete&&i.naturalWidth>0));await p.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>Number.isFinite(Number(a.effect?.getComputedTiming().iterations))).map(a=>a.finished.catch(()=>{})))});await p.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))))}
 const measure=async(p:Page,name:string,nav=false)=>{await ready(p);const ms=await p.evaluate(nav=>nav?performance.now():performance.now()-(window as any).__simpleStart,nav);samples.push({name,ms,round});if(gate)assert.ok(ms<=1000,`${name} ${ms.toFixed(1)}ms >1000ms`)}
 const action=async(p:Page,name:string,fn:()=>Promise<unknown>,done?:()=>Promise<unknown>)=>{await fn();if(done){try{await done()}catch(e){await writeFile(out+'/failure-page.html',await p.content());await p.screenshot({path:out+'/failure-page.png'});console.log(name,await p.locator('main').innerText());throw e}}await measure(p,name)}
 try{for(round=0;round<rounds;round++){
 const c=await browser.newContext({viewport:round===4?{width:1280,height:720}:{width:1366,height:768}});await c.addInitScript(()=>{(globalThis as any).__name=(v:any)=>v;for(const e of ['pointerdown','input','change'])document.addEventListener(e,()=>{(window as any).__simpleStart=performance.now()},true);window.print=()=>{(window as any).__simplePrintReady=performance.now()}});const p=await c.newPage();p.setDefaultTimeout(8000);p.on('pageerror',e=>errors.push(e.message));const cd=await c.newCDPSession(p);await cd.send('Network.enable');await cd.send('Network.setCacheDisabled',{cacheDisabled:true})
 for(const kind of ['parts','consumable']){
 await p.goto(base+`/pcs/materials/${kind}`);await measure(p,kind+':cold',true);await p.reload();await measure(p,kind+':reload',true)
 assert.equal(await p.locator(act('list-view')).count(),0);assert.equal(await p.locator(fld('stage')).count(),0);for(const title of ['分类','规格型号','主单位','综合标准成本','时间'])assert.ok((await p.locator('main').innerText()).includes(title),title)
 await action(p,kind+':search-input',()=>p.locator(fld('search')).fill(kind==='parts'?'10英寸':'30×25'))
 await action(p,kind+':query',()=>p.locator(act('query')).click());await action(p,kind+':reset',()=>p.locator(act('reset')).click())
 await action(p,kind+':columns-open',()=>p.locator(act('columns')).click());
 await action(p,kind+':column-hide',()=>p.locator(act('toggle-column-visibility')+':not([disabled])').first().uncheck());await action(p,kind+':column-show',()=>p.locator(act('toggle-column-visibility')+':not([disabled])').first().check());await action(p,kind+':column-freeze',()=>p.locator(act('toggle-column-freeze')+':not([disabled])').last().check());await action(p,kind+':column-unfreeze',()=>p.locator(act('toggle-column-freeze')+':not([disabled])').last().uncheck());await p.locator(act('toggle-column-visibility')+':not([disabled])').last().uncheck();await action(p,kind+':column-restore',()=>p.locator(act('restore-column-settings')).click());assert.equal(await p.locator(act('toggle-column-visibility')+':not([disabled]):not(:checked)').count(),0);await action(p,kind+':columns-close',()=>p.locator('button'+act('close-column-settings')).last().click())
 for(const [field,v] of [['category',kind==='parts'?'裁床配件':'包装袋'],['approval','DRAFT'],['status','NOT_ENABLED'],['cost','missing']]){await action(p,kind+':filter-'+field,()=>p.locator(fld(field)).selectOption(v));await action(p,kind+':filter-query-'+field,()=>p.locator(act('query')).click());await action(p,kind+':filter-reset-'+field,()=>p.locator(act('reset')).click())}
 await action(p,kind+':page-size',()=>p.locator(fld('pageSize')).selectOption('50'));assert.ok(await p.locator(act('prev-page')).isDisabled());assert.ok(await p.locator(act('next-page')).isDisabled())

 await action(p,kind+':empty-batch-block',()=>p.locator(act('batch-submit')).click(),()=>p.getByRole('status').filter({hasText:'选择'}).first().waitFor());await action(p,kind+':sort',()=>p.locator(act('sort-column')).first().click())
 await action(p,kind+':new-SPA',()=>p.locator(`[data-nav="/pcs/materials/${kind}/new"]`).click(),()=>p.waitForSelector('[data-pcs-material-edit]'))
 assert.equal(await p.locator(act('form-tab')).count(),0)
 await action(p,kind+':name-input',()=>p.locator(fld('materialName')).fill(`实测${kind}-${round}`));await action(p,kind+':field-remark',()=>p.locator(fld('remark')).fill('通用说明：设备A'));await action(p,kind+':field-firstDescription',()=>p.locator(fld('firstDescription')).fill('规格补充：同一实物'))
 await action(p,kind+':missing-spec-block',()=>p.locator(act('save-form')).click(),()=>p.getByRole('status').filter({hasText:'规格型号'}).waitFor())
 await action(p,kind+':field-firstSpec',()=>p.locator(fld('firstSpec')).fill(kind==='parts'?'10英寸 长型号中文验证 样品附件':'30×25cm 中文验证'));await p.locator('input[type=file][data-image-target="mainImageUrl"]').setInputFiles(kind==='parts'?'public/materials/pcs-reviewed/knife.jpg':'public/materials/packing-bag.jpg')
 await action(p,kind+':atomic-create-Blob',()=>p.locator(act('save-form')).click(),()=>p.waitForSelector('[data-pcs-material-detail]'));const rootURL=p.url()
 assert.equal(await p.locator(act('root-tab')).count(),2);await action(p,kind+':root-SKU-tab',()=>p.locator(act('root-tab')+'[data-value="skus"]').click())
 const skuNav=p.locator('[data-nav*="/skus/"]').filter({hasText:'详情'}).first(),skuURL=await skuNav.getAttribute('data-nav');assert.ok(skuURL)
 await action(p,kind+':SKU-SPA',()=>skuNav.click(),()=>p.waitForSelector('[data-pcs-material-sku-detail]'));assert.equal(await p.locator(act('sku-tab')).count(),3)
 await action(p,kind+':more',()=>p.locator(act('simple-actions')).first().click());await p.locator(act('submit')).click();if(await p.locator('[data-dialog-confirm]').count())await p.locator('[data-dialog-confirm]').click();await p.getByRole('status').filter({hasText:'审核状态已保存'}).first().waitFor();await measure(p,kind+':submit')
 await p.locator(act('approve')).click();if(await p.locator('[data-dialog-confirm]').count())await p.locator('[data-dialog-confirm]').click();await p.getByRole('status').filter({hasText:'审核状态已保存'}).first().waitFor();await measure(p,kind+':approve')
 await p.locator(act('use-status')+'[data-status="ACTIVE"]').click();await p.locator('[data-dialog-confirm]').click();await p.getByRole('status').filter({hasText:'使用状态已保存'}).first().waitFor();await measure(p,kind+':enable-parent-and-SKU');await p.locator(act('close-simple-popup')).click()
 await action(p,kind+':units-tab',()=>p.locator(act('sku-tab')+'[data-value="units"]').click())
 await action(p,kind+':new-package',()=>p.locator(act('edit-section')+'[data-package-id="new"]').click(),()=>p.waitForSelector('[data-pcs-material-sku-edit]'));await action(p,kind+':field-packageType',()=>p.locator(fld('packageType')).selectOption('箱'));await action(p,kind+':field-packageContent',()=>p.locator(fld('packageContent')).fill('10'));await action(p,kind+':field-packageContentUnit',()=>p.locator(fld('packageContentUnit')).selectOption('PCS'));await action(p,kind+':field-packageBasis',()=>p.locator(fld('packageBasis')).fill('确认每箱10个'))
 await action(p,kind+':package-save',async()=>{await p.locator(act('save-form')).click();await p.locator('[data-dialog-confirm]').click()},()=>p.waitForSelector('[data-pcs-material-sku-detail]'));await p.locator(act('sku-tab')+'[data-value="units"]').click();assert.ok((await p.locator('main').innerText()).includes('10 PCS'))
 await p.locator('[data-nav$="/edit"]').filter({hasText:'编辑资料'}).click();await p.waitForSelector('[data-pcs-material-sku-edit]');await action(p,kind+':edit-cost-tab',()=>p.locator(act('form-tab')+'[data-value="cost"]').click());await action(p,kind+':field-purchaseStandardCny',()=>p.locator(fld('purchaseStandardCny')).fill('20'));await action(p,kind+':field-transportStandardCny',()=>p.locator(fld('transportStandardCny')).fill('1'));await action(p,kind+':field-pricingUnit',()=>p.locator(fld('pricingUnit')).selectOption('箱'));await action(p,kind+':field-costReason',()=>p.locator(fld('costReason')).fill('含税每箱报价21'))
 await action(p,kind+':cost-preview',()=>p.locator(act('preview-cost')).click(),()=>p.locator(act('confirm-cost')).waitFor());await action(p,kind+':cost-save',()=>p.locator(act('confirm-cost')).click(),()=>p.waitForSelector('[data-pcs-material-sku-detail]'));await p.locator(act('sku-tab')+'[data-value="cost"]').click();await ready(p);assert.ok((await p.locator('main').innerText()).includes('21.0000'));await p.reload();await measure(p,kind+':persisted-SKU-reload',true);assert.ok((await p.locator('main').innerText()).includes(kind==='parts'?'10英寸':'30×25cm'))

 await p.locator(act('sku-tab')+'[data-value="cost"]').click();for(const currency of ['IDR','USD','CNY'])await action(p,kind+':currency-'+currency,()=>p.locator(act('cost-currency')+'[data-value="'+currency+'"]').click())
 await action(p,kind+':cost-history',()=>p.locator('summary').filter({hasText:'本道标准版本'}).click());await action(p,kind+':cost-history-close',()=>p.locator('summary').filter({hasText:'本道标准版本'}).click())
 await p.locator(act('sku-tab')+'[data-value="units"]').click();await p.locator(act('edit-section')+'[data-package-id]').filter({hasText:'编辑包装'}).first().click();await p.waitForSelector('[data-pcs-material-sku-edit]');await action(p,kind+':package-revision-input',()=>p.locator(fld('packageContent')).fill('20'));assert.match(await p.locator('main').innerText(),/当前.*10|沿用/);await p.locator(fld('packageBasis')).fill('新版20个装');await p.locator(act('save-form')).click();assert.match(await p.locator('dialog').innerText(),/10|沿用/);await p.locator('[data-dialog-confirm]').click();await p.waitForSelector('[data-pcs-material-sku-detail]');await measure(p,kind+':package-revision-save');await p.locator(act('sku-tab')+'[data-value="cost"]').click();await ready(p);assert.ok((await p.locator('main').innerText()).includes('21.0000'))
 await p.locator(act('sku-tab')+'[data-value="spec"]').click();await action(p,kind+':image-preview',()=>p.locator(act('image')).first().click());await action(p,kind+':image-close',()=>p.locator('div'+act('close-overlay')+' button').click())
 // Attach a real Blob and reopen its independently readable URL.
 await p.locator('summary').filter({hasText:'识别图片与补充资料'}).click();await action(p,kind+':field-assetName',()=>p.locator(fld('assetName')).fill('独立读取附件'));await action(p,kind+':field-assetRole',()=>p.locator(fld('assetRole')).selectOption('SPECIFICATION'));await p.locator(fld('assetFile')).setInputFiles({name:'说明.txt',mimeType:'text/plain',buffer:Buffer.from('说明文件：同一实物')});await action(p,kind+':attachment-save',()=>p.locator(act('save-asset')).click(),()=>p.getByRole('status').filter({hasText:'资料已保存'}).waitFor());await p.reload();await measure(p,kind+':attachment-reload',true);await p.locator('summary').filter({hasText:'识别图片与补充资料'}).click();const fileURL=await p.getByRole('link',{name:'查看资料'}).getAttribute('href');assert.ok(fileURL);assert.equal(await p.evaluate(async u=>await(await fetch(u!)).text(),fileURL),'说明文件：同一实物')
 await action(p,kind+':usage-popup',()=>p.locator(act('simple-popup')+'[data-popup="usage"]').first().click());assert.ok((await p.getByRole('dialog',{name:'使用情况'}).innerText()).includes('采购引用'));await action(p,kind+':usage-close',()=>p.locator(act('close-simple-popup')).click())
 await action(p,kind+':logs-popup',()=>p.locator(act('simple-popup')+'[data-popup="logs"]').first().click());assert.ok((await p.getByRole('dialog',{name:'操作日志'}).innerText()).includes('操作人'));await action(p,kind+':logs-close',()=>p.locator(act('close-simple-popup')).click())
 await p.locator(act('simple-actions')).first().click();await action(p,kind+':copy-unsaved',()=>p.locator(act('copy-sku')).click(),()=>p.waitForSelector('[data-pcs-material-sku-edit]'));assert.equal(await p.locator(fld('specName')).inputValue(),'');assert.equal(await p.locator(fld('copyCost')).isChecked(),false);await action(p,kind+':copy-missing-block',()=>p.locator(act('save-form')).click(),()=>p.getByRole('status').filter({hasText:'规格型号'}).waitFor());await action(p,kind+':field-specName',()=>p.locator(fld('specName')).fill('12英寸 新规格'));await action(p,kind+':copy-save',()=>p.locator(act('save-form')).click(),()=>p.waitForSelector('[data-pcs-material-sku-detail]'));assert.ok((await p.locator('main').innerText()).includes('草稿'));await p.locator(act('sku-tab')+'[data-value="cost"]').click();await ready(p);assert.match(await p.locator('main').innerText(),/未维护 RMB/);assert.match(await p.locator('main').innerText(),/缺采购价、缺基础运输/);assert.ok(!(await p.locator('main').innerText()).includes('0.0000'))
 await p.goto(base+`/pcs/materials/${kind}`);await ready(p);await p.locator(fld('search')).fill(`实测${kind}-${round}`);await p.locator(act('query')).click();await ready(p);await action(p,kind+':batch-selection',()=>p.locator(fld('selection')).last().check());await p.locator(act('batch-submit')).click();await p.locator('[data-dialog-confirm]').click();await p.locator(act('close-batch-results')).first().waitFor();await measure(p,kind+':batch-submit');await action(p,kind+':batch-close',()=>p.locator(act('close-batch-results')).first().click());await p.locator(fld('selection')).last().check();await p.locator(act('batch-approve')).click();await p.locator('[data-dialog-confirm]').click();await p.locator(act('close-batch-results')).first().waitFor();await measure(p,kind+':batch-approve');await action(p,kind+':batch-approve-close',()=>p.locator(act('close-batch-results')).first().click());
 await p.goto(base+skuURL);await ready(p);await p.locator(act('simple-actions')).first().click();await action(p,kind+':print-preview',()=>p.locator(act('print-label')).click(),()=>p.locator('#pcs-material-labels svg').waitFor());assert.ok((await p.locator('#pcs-material-labels').innerText()).includes(kind==='parts'?'10英寸':'30×25cm'))
 const popupPromise=p.waitForEvent('popup');await p.locator(act('print-now')).click();const w=await popupPromise;await w.waitForFunction(()=>(window as any).__simplePrintReady);const elapsed=await p.evaluate(()=>performance.now()-(window as any).__simpleStart);samples.push({name:kind+':print-complete',ms:elapsed,round});if(gate)assert.ok(elapsed<=1000,`print ${elapsed}ms`);assert.equal(await w.locator('svg').count(),1);assert.equal(await w.locator('img').evaluateAll(imgs=>imgs.every((i:any)=>i.complete&&i.naturalWidth>0)),true);if(round===0){await w.screenshot({path:out+'/'+kind+'-print.png'});await w.locator('svg').screenshot({path:out+'/'+kind+'-qr.png'});await writeFile(out+'/'+kind+'-qr-expected.txt',skuURL.split('/').at(-1)!);await w.pdf({path:out+'/'+kind+'-print.pdf',format:'A4'});await writeFile(out+'/'+kind+'-print.html',await w.content())}await w.close();await action(p,kind+':print-quantity-100',()=>p.locator(fld('printQuantity')).fill('100'));await p.locator('#pcs-material-labels svg').waitFor();const manyPromise=p.waitForEvent('popup');await p.locator(act('print-now')).click();const many=await manyPromise;await many.waitForFunction(()=>(window as any).__simplePrintReady);const manyMs=await p.evaluate(()=>performance.now()-(window as any).__simpleStart);samples.push({name:kind+':print-100-complete',ms:manyMs,round});if(gate)assert.ok(manyMs<=1000,`print100 ${manyMs}`);assert.equal(await many.locator('svg').count(),100);if(round===0)await many.pdf({path:out+'/'+kind+'-print-100.pdf',format:'A4'});await many.close();await p.locator(act('close-overlay')).click()
 await p.goto(rootURL);await ready(p);await p.locator(act('root-tab')+'[data-value="skus"]').click();await ready(p);assert.equal(await p.locator('[data-nav*="/skus/"]').filter({hasText:'详情'}).count(),2)

 await action(p,kind+':root-basic-tab',()=>p.locator(act('root-tab')+'[data-value="basic"]').click());await p.locator(act('simple-actions')).first().click();await action(p,kind+':copy-root-unsaved',()=>p.locator(act('copy-root')).click(),()=>p.waitForSelector('[data-pcs-material-edit]'));assert.equal(await p.locator(fld('firstSpec')).inputValue(),'');assert.equal(await p.locator(fld('copyCost')).isChecked(),false);await p.locator(fld('materialName')).fill(`复制-${kind}-${round}`);await p.locator(fld('firstSpec')).fill('新的实物规格');await p.locator(fld('copyCost')).check();await action(p,kind+':copy-root-explicit-cost-save',()=>p.locator(act('save-form')).click(),()=>p.waitForSelector('[data-pcs-material-detail]'));assert.ok((await p.locator('main').innerText()).includes('草稿'))
 await p.goto(base+skuURL);await ready(p);await p.locator(act('simple-actions')).first().click();await p.locator(act('correct-simple-spec')).click();await p.locator('dialog textarea').fill((kind==='parts'?'10英寸':'30×25cm')+' 补齐文字');await p.locator('dialog button[type="submit"]').click();await p.locator('dialog textarea').fill('仅补齐文字，实物不变');await action(p,kind+':approved-wording-correction',()=>p.locator('dialog button[type="submit"]').click(),()=>p.getByRole('status').filter({hasText:'规格文字已更正'}).first().waitFor());assert.equal(p.url(),base+skuURL);await p.locator(act('close-simple-popup')).click()
 const directRoutes=[['root-detail',rootURL],['root-edit',rootURL+'/edit'],['sku-detail',base+skuURL],['sku-edit',base+skuURL+'/edit'],['new-sku',rootURL+'/skus/new']];for(const [name,route] of directRoutes){await p.goto(route);await measure(p,kind+':direct-'+name,true);await p.reload();await measure(p,kind+':reload-'+name,true)}
 await p.goto(base+`/pcs/materials/${kind}`);await ready(p);if(round===0||round===4)await p.screenshot({path:out+`/${kind}-${round===0?'1366':'1280'}-list.png`})
 }
 await c.close()
 }
 }finally{await writeFile(out+'/pages-performance.json',JSON.stringify({base,head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),browser:browser.version(),cache:'disabled',rounds,samples,errors,gate},null,2));await browser.close()}
 assert.deepEqual(errors,[]);if(gate)for(const name of new Set(samples.map(s=>s.name)))assert.ok(samples.filter(s=>s.name===name).length>=5,`${name} needs five complete samples`);console.log('samples',samples.length,'max',Math.max(...samples.map(s=>s.ms)))
})
