import assert from 'node:assert/strict'
import test from 'node:test'
import {chromium,type Page} from '@playwright/test'
import {mkdir,writeFile,readFile} from 'node:fs/promises'
const base=process.env.SIMPLE_TEST_URL||'http://127.0.0.1:43220',out='output/playwright/pcs-simple-materials'
const samples:any[]=[],rounds=Number(process.env.SIMPLE_IMPORT_ROUNDS||5),sizes=(process.env.SIMPLE_IMPORT_SIZES||'5,100,500').split(',').map(Number)
const headers=['模式','物料编码','物料名称','分类编码','SKU编码','规格型号','主计量单位','识别图','主档说明','规格说明','版本时间']
const A=(a:string)=>`[data-pcs-material-archive-action="${a}"]`,F=(f:string)=>`[data-pcs-material-archive-field="${f}"]`
async function settled(p:Page){await p.waitForFunction(()=>[...document.querySelectorAll<HTMLImageElement>('main img')].filter(i=>{const r=i.getBoundingClientRect();return r.bottom>0&&r.top<innerHeight}).every(i=>i.complete&&i.naturalWidth>0));await p.evaluate(async()=>{await document.fonts.ready;await Promise.all(document.getAnimations().filter(a=>Number.isFinite(Number(a.effect?.getComputedTiming().iterations))).map(a=>a.finished.catch(()=>{})));await new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done())))})}
test('SIMPLE-051/052/060: actual CSV templates, grouped errors, retry and supported maximum full save',{timeout:360000},async()=>{
 await mkdir(out,{recursive:true});const b=await chromium.launch(),errors:string[]=[]
 try{for(let r=0;r<rounds;r++)for(const n of sizes){const c=await b.newContext({viewport:r===4?{width:1280,height:720}:{width:1366,height:768}});await c.addInitScript(()=>{(globalThis as any).__name=(v:any)=>v;for(const event of ['pointerdown','change'])document.addEventListener(event,()=>{(window as any).__start=performance.now()},true)});const p=await c.newPage();const cacheSession=await c.newCDPSession(p);await cacheSession.send('Network.enable');await cacheSession.send('Network.setCacheDisabled',{cacheDisabled:true});p.setDefaultTimeout(10000);p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/pcs/materials/parts');await p.waitForSelector(A('transfer-open'));await p.locator(A('transfer-open')).click()
 for(const mode of ['archives','units','costs']){await p.locator(F('transferMode')).selectOption(mode);const wait=p.waitForEvent('download');await p.locator(A('transfer-template')).click();const d=await wait,file=await d.path(),text=await readFile(file!,'utf8');assert.ok(!/技术属性JSON|模板ID|加工类型|关系ID/.test(text));if(r===0&&n===sizes[0])await writeFile(out+'/template-'+mode+'.csv',text)}await p.locator(F('transferMode')).selectOption('archives')
 await p.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));const rows=Array.from({length:n},(_,i)=>['新增','',`导入-${r}-${n}-${i}`,'MC-PARTS-27','',`型号-${i}`,'PCS','/materials/pcs-reviewed/knife.jpg','主档说明A','规格说明B',''].join(','));const text=[headers.join(','),...rows].join('\n')
 await p.locator(F('transferFile')).setInputFiles({name:'导入.csv',mimeType:'text/csv',buffer:Buffer.from(text)});try{await p.getByText('已读取业务文件', {exact:false}).waitFor()}catch(e){await writeFile(out+'/import-failure.html',await p.content());console.log(await p.locator('main').innerText());throw e};await settled(p);const fileMs=await p.evaluate(()=>performance.now()-(window as any).__start);samples.push({name:'file-read',n,round:r,ms:fileMs});if(process.env.SIMPLE_FUNCTION_ONLY!=='true')assert.ok(fileMs<=1000);await p.locator(A('transfer-preview')).click();await p.locator(A('transfer-confirm')).waitFor();await settled(p);const previewMs=await p.evaluate(()=>performance.now()-(window as any).__start);samples.push({name:'preview',n,round:r,ms:previewMs})
 const cd=process.env.SIMPLE_PROFILE?await c.newCDPSession(p):null;if(cd){await cd.send('Profiler.enable');await cd.send('Profiler.start')}await p.locator(A('transfer-confirm')).click();await p.getByRole('status').filter({hasText:`导入完成：${n} 组已保存`}).first().waitFor();await settled(p);if(cd){const prof=await cd.send('Profiler.stop');await writeFile('/tmp/import-browser.cpuprofile',JSON.stringify(prof.profile))}const ms=await p.evaluate(()=>performance.now()-(window as any).__start);samples.push({name:'save',n,round:r,ms});console.log('import',n,'preview',previewMs,'save',ms);if(process.env.SIMPLE_FUNCTION_ONLY!=='true'){assert.ok(previewMs<=1000,`preview ${n} ${previewMs}`);assert.ok(ms<=1000,`save ${n} ${ms}`)}
 assert.equal(await p.locator(A('transfer-confirm')).count(),0);await p.locator('button'+A('transfer-close')).first().click();await p.reload();await p.waitForSelector('[data-pcs-material-archive-page]');await p.locator(F('search')).fill(`导入-${r}-${n}-${n-1}`);await p.locator(A('query')).click();await p.getByRole('button',{name:new RegExp('MAT-EP-.*-B')}).first().waitFor();assert.ok((await p.locator('main').innerText()).includes('型号-'+(n-1)))
 await c.close()
 }}finally{await writeFile(out+'/import-performance.json',JSON.stringify({base,rounds,sizes,samples,errors},null,2));await b.close()}assert.deepEqual(errors,[])
})

test('SIMPLE-051/052/060: over-limit rejection, atomic failed group retry, units and cost complete maximum batches',{timeout:360000},async()=>{
 const b=await chromium.launch(),record:any[]=[],errors:string[]=[]
 const parse=(text:string)=>{const lines:string[][]=[];let row:string[]=[],cell='',quote=false;for(let i=0;i<text.length;i++){let ch=text[i];if(ch==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++}else quote=!quote}else if(!quote&&(ch===','||ch==='\n')){row.push(cell.replace(/^\uFEFF/,''));cell='';if(ch==='\n'){lines.push(row);row=[]}}else if(ch!=='\r')cell+=ch}if(cell||row.length){row.push(cell);lines.push(row)}return lines}
 try{for(let r=0;r<5;r++){
 const c=await b.newContext({viewport:r===4?{width:1280,height:720}:{width:1366,height:768}});await c.addInitScript(()=>{(globalThis as any).__name=(v:any)=>v;for(const e of ['pointerdown','change'])document.addEventListener(e,()=>{(window as any).__start=performance.now()},true);const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args:any[]){if((window as any).__rejectImport&&this.name==='records'&&args[0]?.value?.data?.materialName==='边界导入-1')throw new DOMException('Isolated failed root','QuotaExceededError');return add.apply(this,args as any)}});const p=await c.newPage();const cacheSession=await c.newCDPSession(p);await cacheSession.send('Network.enable');await cacheSession.send('Network.setCacheDisabled',{cacheDisabled:true});p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/pcs/materials/parts');await p.waitForSelector(A('transfer-open'));await p.locator(A('transfer-open')).click()
 const finish=async(name:string)=>{await settled(p);const ms=await p.evaluate(()=>performance.now()-(window as any).__start);record.push({name,round:r,ms});if(process.env.SIMPLE_FUNCTION_ONLY!=='true')assert.ok(ms<=1000,`${name} ${ms}ms`)}
 const upload=async(text:string)=>{await p.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));await p.locator(F('transferFile')).setInputFiles({name:'边界.csv',mimeType:'text/csv',buffer:Buffer.from(text)});await p.getByText('已读取业务文件',{exact:false}).waitFor();await finish('boundary:file-read')}
 const rows=Array.from({length:501},(_,i)=>['新增','',`边界导入-${i}`,'MC-PARTS-27','',`型号-${i}`,'PCS','/materials/pcs-reviewed/knife.jpg','通用说明','规格说明',''].join(','));await upload([headers.join(','),...rows].join('\n'));await p.locator(A('transfer-preview')).click();await p.getByRole('status').filter({hasText:'最多 500 行'}).first().waitFor();await finish('limit:archives');assert.equal(await p.locator(A('transfer-confirm')).count(),0)
 await upload([headers.join(','),...rows.slice(0,20)].join('\n'));await p.locator(A('transfer-preview')).click();await p.locator(A('transfer-confirm')).waitFor();await finish('boundary:archives-preview');await p.evaluate(()=>(window as any).__rejectImport=true);await p.locator(A('transfer-confirm')).click();await p.getByRole('status').filter({hasText:'19 组已保存，1 组未保存'}).first().waitFor();await finish('boundary:failure-isolation');assert.ok((await p.locator('main').innerText()).includes('未保存'));await p.evaluate(()=>(window as any).__rejectImport=false);await p.locator(A('transfer-confirm')).click();await p.getByRole('status').filter({hasText:'20 组已保存，0 组未保存'}).first().waitFor();await finish('boundary:retry');assert.equal(await p.locator(A('transfer-confirm')).count(),0)
 await p.locator('button'+A('transfer-close')).first().click();await p.reload();await p.waitForSelector(F('search'));await p.locator(F('search')).fill('边界导入');await p.locator(A('query')).click();await p.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));await p.locator(A('transfer-open')).click();const download=p.waitForEvent('download');await p.locator(A('transfer-export')).click();const d=await download;const table=parse(await readFile((await d.path())!,'utf8'));assert.equal(table.length,21);const skuIndex=table[0].indexOf('SKU编码'),codes=table.slice(1).map(x=>x[skuIndex]);assert.equal(new Set(codes).size,20)
 for(const mode of ['units','costs']){await p.locator(F('transferMode')).selectOption(mode);await p.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));const dl=p.waitForEvent('download');await p.locator(A('transfer-template')).click();const f=await dl,cols=parse(await readFile((await f.path())!,'utf8'))[0];const body=codes.map(code=>{const v:Record<string,string>=mode==='units'?{'SKU编码':code,'辅助单位':'箱','每辅助单位主数量':'10','包装含量':'10','含量单位':'PCS','计量依据':'确认每箱10个','用途':'采购|计价|领用','默认用途':'采购','调整原因':'导入确认'}:{'SKU编码':code,'标准采购成本RMB':'2','基础运输成本RMB':'0.1','采购已含运输':'否','计价单位':'PCS','调整原因':'含税标准人工维护'};return cols.map(x=>v[x]||'').join(',')});await upload([cols.join(','),...body,body[0]].join('\n'));await p.locator(A('transfer-preview')).click();await p.getByRole('status').filter({hasText:'最多 20 行'}).first().waitFor();await finish('limit:'+mode);await upload([cols.join(','),...body].join('\n'));await p.locator(A('transfer-preview')).click();await p.locator(A('transfer-confirm')).waitFor();await finish(mode+':maximum-preview');await p.locator(A('transfer-confirm')).click();await p.getByRole('status').filter({hasText:'20 组已保存，0 组未保存'}).first().waitFor();await finish(mode+':maximum-save');assert.equal(await p.locator(A('transfer-confirm')).count(),0)}
 await c.close()
 }}finally{await writeFile(out+'/import-boundaries-performance.json',JSON.stringify({base,samples:record,errors},null,2));await b.close()}assert.deepEqual(errors,[])
})

test('SIMPLE-051/060: template and export downloads completely available within one second in five rounds',{timeout:120000},async()=>{
 const b=await chromium.launch(),record:any[]=[],errors:string[]=[];await mkdir(out,{recursive:true})
 try{for(let r=0;r<5;r++){const c=await b.newContext({viewport:r===4?{width:1280,height:720}:{width:1366,height:768}});await c.addInitScript(()=>{for(const e of ['pointerdown','change'])document.addEventListener(e,()=>{(window as any).__start=performance.now()},true)});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));const cacheSession=await c.newCDPSession(p);await cacheSession.send('Network.enable');await cacheSession.send('Network.setCacheDisabled',{cacheDisabled:true});await p.goto(base+'/pcs/materials/parts');await p.waitForSelector(A('transfer-open'));await p.locator(A('transfer-open')).click();for(const mode of ['archives','units','costs']){await p.locator(F('transferMode')).selectOption(mode);await p.evaluate(()=>new Promise<void>(done=>requestAnimationFrame(()=>requestAnimationFrame(()=>done()))));for(const action of ['transfer-template','transfer-export']){const download=p.waitForEvent('download');await p.locator(A(action)).click();const d=await download;const content=await readFile((await d.path())!,'utf8');assert.ok(content.length>30);await settled(p);const ms=await p.evaluate(()=>performance.now()-(window as any).__start);record.push({name:mode+':'+action,round:r,ms});assert.ok(ms<=1000,`${mode} ${action} ${ms}ms`)}}await c.close()}}finally{await writeFile(out+'/downloads-performance.json',JSON.stringify({base,samples:record,errors},null,2));await b.close()}assert.deepEqual(errors,[])
})
