// @page-pattern: list
import { escapeHtml as e } from '../utils.ts'
import { hydrateIcons } from '../components/shell.ts'
import { renderStandardListPage, renderStandardListFilters, renderStandardListStats } from '../components/ui/list-page.ts'
import { renderStandardListTable, renderStandardListColumnSettings, type StandardListColumn } from '../components/ui/list-table.ts'
import { loadListColumnPreferences, saveListColumnPreferences, paginateStandardListRows, sortStandardListRows, type StandardListColumnPreferences, type StandardListSortState } from '../components/ui/list-table-model.ts'
import { renderTablePagination } from '../components/ui/pagination.ts'
import { confirmPcsAction } from './pcs-action-dialog.ts'
import { ensurePcsRecordState } from '../data/pcs-record-runtime.ts'
import { listConfigDimensionOptions } from '../data/pcs-config-workspace-repository.ts'
import { ensureLosLiveRoomState, listLiveSites, listLiveRooms, getLiveRoom, liveRoomCode, liveRoomAvailable, liveRoomCategories, losRecordVersion, saveLiveRoom, saveLiveSite, setLiveRoomEnabled, type LiveRoom } from '../data/los-live-room-master.ts'
const PATH='/los/live-room', PREFIX='los-room'
const state={view:'list',id:'',error:'',notice:'',query:{keyword:'',site:'',enabled:''},filter:{keyword:'',site:'',enabled:''},page:1,sort:null as StandardListSortState|null,prefs:null as StandardListColumnPreferences|null,columns:false,siteModal:false,siteEditId:'',siteVersion:0,siteDraft:{code:'',name:'',enabled:true},draft:null as Omit<LiveRoom,'code'|'updatedAt'|'logs'>|null,version:0,saving:false,dirty:false,siteDirty:false}
const cls='h-9 w-full rounded border border-slate-300 bg-white px-3 text-sm'
const btn=(label:string,action:string,attrs='')=>`<button type="button" data-los-room-action="${action}" data-skip-page-rerender="true" class="rounded border border-slate-300 bg-white px-3 py-2 text-sm hover:bg-slate-50" ${attrs}>${e(label)}</button>`
const link=(label:string,href:string)=>`<a href="${e(href)}" data-nav="${e(href)}" class="text-sm text-blue-600 hover:underline">${e(label)}</a>`
const input=(key:string,value:unknown,type='text',disabled=false)=>`<input class="${cls}" data-los-room-field="${key}" type="${type}" value="${e(String(value??''))}" ${type==='number'?'step="1" min="1"':''} ${disabled?'disabled':''}>`
const field=(label:string,control:string)=>`<label class="block min-w-0 space-y-2 text-sm"><span class="font-medium">${e(label)}</span>${control}</label>`
const select=(key:string,value:string,options:Array<[string,string]>,empty='全部')=>`<select class="${cls}" data-los-room-field="${key}"><option value="">${e(empty)}</option>${options.map(([v,n])=>`<option value="${e(v)}" ${v===value?'selected':''}>${e(n)}</option>`).join('')}</select>`
const feedback=()=>state.error||state.notice?`<div role="${state.error?'alert':'status'}" class="rounded border p-3 text-sm ${state.error?'border-red-200 bg-red-50 text-red-700':'border-blue-200 bg-blue-50 text-blue-700'}">${e(state.error||state.notice)} ${btn('关闭提示','dismiss')}</div>`:''
const wrap=(body:string)=>`<div data-los-room-root data-skip-page-rerender="true">${body}${overlays()}</div>`
function columns():StandardListColumn<LiveRoom>[] {return [
  {key:'code',title:'房间标号 / 名称',width:240,required:true,freezeable:true,sortable:true,sortValue:r=>r.code,render:r=>`${link(r.code,`${PATH}/${r.roomId}`)}<p class="mt-1 text-xs text-slate-500">${e(r.name)}</p>`},
  {key:'site',title:'地点 / 楼层',width:210,sortable:true,sortValue:r=>r.siteId,render:r=>`<p>${e(listLiveSites().find(s=>s.siteId===r.siteId)?.name||'地点不可用')}</p><p class="mt-1 text-xs text-slate-500">${r.floor} 楼 · 序列号 ${r.sequence}</p>`},
  {key:'categories',title:'品类编号',width:290,sortable:true,sortValue:r=>liveRoomCategories(r).map(c=>c.code).join('、'),render:r=>liveRoomCategories(r).map(c=>`<p class="text-xs leading-5">${e([c.code,c.nameEn,c.nameZh].filter(Boolean).join(' · '))}</p>`).join('')},
  {key:'owners',title:'标签责任人',width:130,sortable:true,sortValue:r=>r.opm,render:r=>`<p>OPM：${e(r.opm)}</p><p>S.O：${e(r.so)}</p>`},
  {key:'enabled',title:'使用状态',width:110,sortable:true,sortValue:r=>r.enabled?1:0,render:r=>liveRoomAvailable(r)?'启用':r.enabled?'地点已停用':'停用'},
  {key:'actions',title:'操作',width:140,required:true,actionColumn:true,render:r=>`<div class="flex flex-wrap gap-x-3 gap-y-2">${link('详情',`${PATH}/${r.roomId}`)}${link('编辑',`${PATH}/${r.roomId}/edit`)}${link('打印标签',`${PATH}/${r.roomId}/label`)}</div>`},
]}
function prefs(){if(!state.prefs){const cols=columns();let storage:{getItem:(k:string)=>string|null}={getItem:()=>null};try{storage=localStorage}catch{}
 state.prefs=loadListColumnPreferences(storage,'higood-los-room-list-v1',cols,{order:cols.map(c=>c.key),visibleKeys:cols.map(c=>c.key),frozenKeys:['code'],pageSize:20},[20,50,100])}return state.prefs}
function savePrefs(){try{saveListColumnPreferences(localStorage,'higood-los-room-list-v1',prefs())}catch{}}
function matching(){return listLiveRooms().filter(r=>(!state.filter.site||r.siteId===state.filter.site)&&(!state.filter.enabled||(liveRoomAvailable(r)?'yes':'no')===state.filter.enabled)&&(!state.filter.keyword||[r.code,r.name,...liveRoomCategories(r).map(c=>[c.code,c.nameEn,c.nameZh].join(' '))].join(' ').toLowerCase().includes(state.filter.keyword.toLowerCase())))}
function list(){const cols=columns(),rows=sortStandardListRows(matching(),state.sort,(r,k)=>cols.find(c=>c.key===k)?.sortValue?.(r)),page=paginateStandardListRows(rows,state.page,prefs().pageSize);state.page=page.currentPage
return wrap(renderStandardListPage({title:'直播房间管理',primaryActionsHtml:`<div class="flex gap-4">${btn('维护直播地点','sites')}${link('新增房间',`${PATH}/new`)}</div>`,feedbackHtml:feedback(),filtersHtml:renderStandardListFilters({fieldsHtml:`<div class="grid w-full gap-3 md:grid-cols-3">${field('房间标号 / 名称 / 品类编号',input('query.keyword',state.query.keyword))}${field('直播地点',select('query.site',state.query.site,listLiveSites().map(s=>[s.siteId,s.name])))}${field('使用状态',select('query.enabled',state.query.enabled,[['yes','启用'],['no','停用']]))}</div>`,actionPrefix:PREFIX,extraActionsHtml:btn('导出','export')}),statsHtml:renderStandardListStats([{label:'当前结果',value:rows.length},{label:'启用房间',value:rows.filter(liveRoomAvailable).length},{label:'停用 / 地点停用',value:rows.filter(r=>!liveRoomAvailable(r)).length}],{compact:true}),listTitle:'直播房间列表',listActionsHtml:btn('列设置','columns'),tableHtml:renderStandardListTable({columns:cols,rows:page.rows,preferences:prefs(),sort:state.sort,eventPrefix:PREFIX,skipPageRerender:true}),paginationHtml:renderTablePagination({...page,actionPrefix:PREFIX,pageSizeOptions:[20,50,100],skipPageRerender:true})}))}
function roomLabel(room:LiveRoom):string { const categories=liveRoomCategories(room);if(!categories.length||categories.some(c=>!c.code))throw new Error('请先维护完整的品类编号后再打印。')
return `<style>@media print{@page{size:A4 portrait;margin:10mm}.room-door-label{break-inside:avoid}}.room-door-label{box-sizing:border-box;width:170mm;min-height:75mm;margin:0 auto 5mm;padding:5mm;border:1px solid #333;color:#111;background:#fff;text-align:center;font-family:Arial,sans-serif}.room-door-code{font-size:13pt;font-weight:bold;margin-bottom:3mm}.room-door-category{border:1px solid #777;border-radius:8mm;padding:6mm 3mm;font-size:21pt;font-weight:bold}.room-door-zh{font-size:19pt;font-weight:normal;margin-top:2mm}.room-door-owner{border:1px solid #777;border-radius:3mm;margin:3mm 9mm 0;padding:2mm;font-size:17pt;font-weight:bold}</style>${categories.map(c=>`<article class="room-door-label" data-room-label><div class="room-door-code">${e(room.code)}</div><div class="room-door-category">${e(c.nameEn?`${c.code}-${c.nameEn}`:c.code)}<div class="room-door-zh">${e(c.nameZh)}</div></div><div class="room-door-owner">OPM = ${e(room.opm)}</div><div class="room-door-owner">S.O = ${e(room.so)}</div></article>`).join('')}`}
function detail(room:LiveRoom,print=false){return wrap(`<div class="space-y-4 p-5"><div class="flex items-center justify-between"><div><h1 class="text-xl font-semibold">${print?'直播房间标签':'直播房间详情'}</h1><p class="mt-1 text-sm text-slate-500">${e(room.code)} · ${e(room.name)}</p></div><div class="flex items-center gap-4">${link('返回列表',PATH)}${print?btn('打印','print'):link('编辑',`${PATH}/${room.roomId}/edit`)}${!print?link('打印标签',`${PATH}/${room.roomId}/label`):''}</div></div>${feedback()}${print?`<p class="text-sm text-slate-500">A4 纵向打印；每个关联品类编号生成一张门牌，房间标号保持相同。打印不改变房间或样衣状态。</p><div class="overflow-x-auto rounded border bg-slate-100 p-5" data-room-label-preview>${roomLabel(room)}</div>`:`<section class="rounded border bg-white p-5"><dl class="grid gap-5 md:grid-cols-3">${[['地点',listLiveSites().find(s=>s.siteId===room.siteId)?.name],['楼层',room.floor],['序列号',room.sequence],['OPM',room.opm],['S.O',room.so],['状态',liveRoomAvailable(room)?'启用':'停用']].map(([k,v])=>`<div><dt class="text-xs text-slate-500">${e(String(k))}</dt><dd class="mt-2">${e(String(v??''))}</dd></div>`).join('')}</dl><div class="mt-5">${btn(room.enabled?'停用房间':'启用房间','enabled')}</div></section><section class="rounded border bg-white p-5"><h2 class="mb-3 font-semibold">关联品类编号</h2>${liveRoomCategories(room).map(c=>`<p class="py-2 text-sm">${e([c.code,c.nameEn,c.nameZh].filter(Boolean).join(' · '))}</p>`).join('')}</section><details class="rounded border bg-white p-5"><summary>操作记录</summary>${room.logs.map(l=>`<p class="mt-2 text-sm">${e(l.time)} · ${e(l.action)} · ${e(l.actor)}</p>`).join('')||'<p class="mt-2 text-sm text-slate-500">暂无操作记录</p>'}</details>`}</div>`)}
function editor(){const d=state.draft!,old=!!state.id;const sites=listLiveSites().filter(s=>s.enabled||s.siteId===d.siteId);let code='补全地点、楼层和序列号后生成';try{code=liveRoomCode(sites.find(s=>s.siteId===d.siteId)?.code||'',d.floor,d.sequence)}catch{}
 return wrap(`<div class="space-y-4 p-5"><header class="flex justify-between"><h1 class="text-xl font-semibold">${old?'编辑':'新增'}直播房间</h1>${link('返回列表',PATH)}</header>${feedback()}<p class="text-sm text-amber-700" data-room-unsaved ${state.dirty?'':'hidden'}>当前修改尚未保存</p><section class="rounded border bg-white p-5"><h2 class="mb-4 font-semibold">房间身份</h2><div class="grid gap-5 md:grid-cols-3">${field('直播地点',old?input('siteId',sites.find(s=>s.siteId===d.siteId)?.name,'text',true):select('siteId',d.siteId,sites.map(s=>[s.siteId,s.name]),'请选择地点'))}${field('楼层',input('floor',d.floor,'number',old))}${field('序列号',input('sequence',d.sequence,'number',old))}</div><p class="mt-4 text-sm">房间标号：<strong data-room-code-preview>${e(code)}</strong></p><p class="mt-2 text-xs text-slate-500">地点编码 + 两位楼层 + 三位序列号；已有标号固定，停用后也不会分配给其他房间。</p></section><section class="rounded border bg-white p-5"><div class="grid gap-5 md:grid-cols-3">${field('房间名称',input('name',d.name))}${field('OPM',input('opm',d.opm))}${field('S.O',input('so',d.so))}</div></section><section class="rounded border bg-white p-5"><h2 class="mb-3 font-semibold">关联品类编号（可多选）</h2><input type="search" data-los-room-category-search placeholder="搜索编号或名称" class="${cls}"><div class="mt-4 grid max-h-80 gap-2 overflow-auto md:grid-cols-2">${listConfigDimensionOptions('categoryNumbers').filter(o=>o.status==='ENABLED'||d.categoryNumberIds.includes(o.id)).map(o=>`<label class="flex items-start gap-2 py-1 text-sm" data-room-category-option><input type="checkbox" data-los-room-field="categoryNumberIds" value="${e(o.id)}" ${d.categoryNumberIds.includes(o.id)?'checked':''}><span>${e([o.code,o.name_en,o.name_zh].filter(Boolean).join(' · '))}</span></label>`).join('')}</div></section><footer class="sticky bottom-0 flex justify-end gap-4 rounded border bg-white p-4">${btn('取消','cancel-edit')}${btn(state.saving?'保存中…':'保存房间','save',state.saving?'disabled':'')}</footer></div>`)}
function overlays(){if(state.columns)return renderStandardListColumnSettings({title:'列设置',columns:columns(),preferences:prefs(),eventPrefix:PREFIX,maxFrozenWidth:450,skipPageRerender:true})
 if(!state.siteModal)return '';return `<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-5" role="dialog" aria-modal="true" aria-label="维护直播地点"><section class="max-h-[90vh] w-full max-w-2xl overflow-auto rounded bg-white p-5"><header class="flex justify-between"><h2 class="font-semibold">维护直播地点</h2>${btn('关闭','close-sites')}</header><p class="my-3 text-xs text-slate-500">地点编码唯一且固定，用于生成房间标号。新增地点请填写真实名称；当前两处为演示名称。</p>${listLiveSites().map(s=>`<div class="flex items-center justify-between border-b py-2 text-sm"><span>${e(s.code)} · ${e(s.name)} · ${s.enabled?'启用':'停用'}</span>${btn('编辑','edit-site',`data-id="${e(s.siteId)}"`)}</div>`).join('')}<div class="mt-4 grid gap-4 md:grid-cols-2">${field('地点编码',input('site.code',state.siteDraft.code,'text',!!state.siteEditId))}${field('地点名称',input('site.name',state.siteDraft.name))}</div><label class="mt-4 block text-sm"><input type="checkbox" data-los-room-field="site.enabled" ${state.siteDraft.enabled?'checked':''}> 启用地点</label><div class="mt-4 flex justify-end gap-3">${btn('清空 / 新增地点','new-site')}${btn(state.saving?'保存中…':'保存地点','save-site',state.saving?'disabled':'')}</div><div class="mt-3 text-sm text-red-600" data-room-site-error>${e(state.error|| (state.siteDirty?'当前修改尚未保存':''))}</div></section></div>`}
function update(){const root=document.querySelector<HTMLElement>('[data-los-room-root]');if(!root)return;const scroll=root.parentElement?.scrollTop||0;const room=getLiveRoom(state.id);const body=state.view==='list'?list():state.view==='edit'?(state.draft?editor():wrap(`<section class="m-5 rounded border p-5"><h1 class="mb-3 font-semibold">直播房间资料暂时无法读取</h1>${feedback()}${btn('重新读取','reload')}</section>`)):room?detail(room,state.view==='label'):wrap('<p class="p-5">房间不存在。</p>');const shell=document.createElement('div');shell.innerHTML=body;root.replaceChildren(...Array.from(shell.firstElementChild!.childNodes));hydrateIcons(root);if(root.parentElement)root.parentElement.scrollTop=scroll}
function navigate(path:string){const a=document.createElement('a');a.dataset.nav=path;document.querySelector('[data-los-room-root]')!.append(a);a.click();a.remove()}
async function printRoom(){const room=getLiveRoom(state.id);if(!room)throw new Error('房间不存在。');const html=roomLabel(room),frame=document.createElement('iframe');frame.title='直播房间标签打印';frame.style.cssText='position:fixed;left:-9999px;width:210mm;height:297mm;border:0';document.body.append(frame)
 try{await new Promise<void>((resolve,reject)=>{frame.onload=()=>resolve();frame.onerror=()=>reject(Error('打印内容生成失败，请重试。'));frame.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><title>${e(room.code)}</title></head><body>${html}</body></html>`});await frame.contentDocument!.fonts.ready;await new Promise<void>(r=>frame.contentWindow!.requestAnimationFrame(()=>frame.contentWindow!.requestAnimationFrame(()=>r())));frame.contentWindow!.addEventListener('afterprint',()=>frame.remove(),{once:true});window.addEventListener('pagehide',()=>frame.remove(),{once:true});frame.contentWindow!.focus();frame.contentWindow!.print()}catch(error){frame.remove();throw error}}
document.addEventListener('click',async event=>{const n=(event.target as Element)?.closest<HTMLElement>('[data-los-room-action]');if(!n)return;event.preventDefault();event.stopPropagation();if(state.saving)return;const action=n.dataset.losRoomAction!
 try{state.error='';if(action==='query'){state.filter={...state.query};state.page=1}else if(action==='reset'){state.query={keyword:'',site:'',enabled:''};state.filter={...state.query};state.page=1;state.sort=null}else if(action==='columns')state.columns=true;else if(action==='close-column-settings')state.columns=false;else if(action==='prev-page')state.page--;else if(action==='next-page')state.page++;else if(action==='sort-column'){const key=n.dataset.columnKey!;state.sort=state.sort?.key!==key?{key,direction:'asc'}:state.sort.direction==='asc'?{key,direction:'desc'}:null}
 else if(action==='toggle-column-visibility'||action==='toggle-column-freeze'){const key=n.dataset.losRoomColumnKey!,p=prefs(),keys=action==='toggle-column-visibility'?p.visibleKeys:p.frozenKeys;if(keys.includes(key))keys.splice(keys.indexOf(key),1);else keys.push(key);savePrefs()}else if(action==='restore-column-settings'){try{localStorage.removeItem('higood-los-room-list-v1')}catch{}state.prefs=null}
 else if(action==='sites'){state.siteModal=true;state.siteEditId='';state.siteDraft={code:'',name:'',enabled:true};state.siteVersion=0}else if(action==='close-sites'){if(state.siteDirty&&!confirm('地点修改尚未保存，是否放弃修改？'))return;state.siteModal=false;state.siteDirty=false;}else if(action==='edit-site'){if(state.siteDirty&&!confirm('地点修改尚未保存，是否放弃修改？'))return;state.siteDirty=false;const s=listLiveSites().find(s=>s.siteId===n.dataset.id)!;state.siteEditId=s.siteId;state.siteDraft={...s};state.siteVersion=losRecordVersion('sites',s.siteId)}else if(action==='new-site'){if(state.siteDirty&&!confirm('地点修改尚未保存，是否放弃修改？'))return;state.siteDirty=false;state.siteEditId='';state.siteDraft={code:'',name:'',enabled:true};state.siteVersion=0}
 else if(action==='save-site'){if(!state.siteDraft.enabled&&!(await confirmPcsAction('停用地点后，其下房间不能作为新的样衣接收位置。已有流转记录保留。是否停用？')))return;state.saving=true;update();await saveLiveSite({...state.siteDraft,siteId:state.siteEditId||undefined},state.siteVersion);state.siteModal=false;state.siteDirty=false;state.notice='地点已保存'}
 else if(action==='save'){state.saving=true;update();const d=state.draft!;if(!state.id){const site=listLiveSites().find(s=>s.siteId===d.siteId);d.roomId=liveRoomCode(site?.code||'',d.floor,d.sequence)}const r=await saveLiveRoom(d,state.version);state.saving=false;state.dirty=false;state.draft=null;navigate(`${PATH}/${r.roomId}`);return}
 else if(action==='cancel-edit'){if(state.dirty&&!confirm('房间修改尚未保存，是否放弃修改？'))return;state.dirty=false;navigate(PATH);return}else if(action==='enabled'){const r=getLiveRoom(state.id)!;if(!(await confirmPcsAction(r.enabled?'停用房间后不能新增样衣流入；已有记录保留。是否停用？':'是否启用此房间？')))return;state.saving=true;update();await setLiveRoomEnabled(r.roomId,!r.enabled,state.version);state.version=losRecordVersion('rooms',r.roomId);state.notice='使用状态已保存'}
 else if(action==='print'){await printRoom();return}else if(action==='dismiss'){state.notice='';state.error=''}else if(action==='reload'){await ensurePcsRecordState(['higood-pcs-config-workspace-store-v1']);await ensureLosLiveRoomState();if(state.view==='edit'&&!state.draft)initializeDraft()}
 else if(action==='export'){const csv=(s:string)=>`"${s.replace(/"/g,'""')}"`;const lines=[['房间标号','地点','楼层','序列号','房间名称','品类编号','OPM','S.O','状态'],...matching().map(r=>[r.code,listLiveSites().find(s=>s.siteId===r.siteId)?.name||'',String(r.floor),String(r.sequence),r.name,liveRoomCategories(r).map(c=>[c.code,c.nameEn,c.nameZh].filter(Boolean).join(' · ')).join('；'),r.opm,r.so,liveRoomAvailable(r)?'启用':'停用'])];const url=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(row=>row.map(csv).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='直播房间.csv';a.click();URL.revokeObjectURL(url);state.notice=`已导出 ${lines.length-1} 个房间`}
 }catch(e){state.error=e instanceof Error?e.message:'未保存，请重试。'}finally{state.saving=false;update()}
},true)
document.addEventListener('input',event=>{const el=event.target as HTMLInputElement;const search=el.closest<HTMLInputElement>('[data-los-room-category-search]');if(search){search.parentElement?.querySelectorAll<HTMLElement>('[data-room-category-option]').forEach(n=>n.hidden=!(n.textContent||'').toLowerCase().includes(search.value.toLowerCase()));return}const key=el.dataset.losRoomField;if(!key)return;event.stopPropagation();if(key.startsWith('query.'))Object.assign(state.query,{[key.slice(6)]:el.value});else if(key.startsWith('site.')){state.siteDirty=true;const note=document.querySelector('[data-room-site-error]');if(note)note.textContent='当前修改尚未保存';Object.assign(state.siteDraft,{[key.slice(5)]:el.type==='checkbox'?el.checked:el.value});}else if(key==='pageSize'){prefs().pageSize=Number(el.value);state.page=1;savePrefs();update()}else if(state.draft){state.dirty=true;const unsaved=document.querySelector<HTMLElement>('[data-room-unsaved]');if(unsaved)unsaved.hidden=false;if(key==='categoryNumberIds'){const ids=new Set(state.draft.categoryNumberIds);el.checked?ids.add(el.value):ids.delete(el.value);state.draft.categoryNumberIds=[...ids]}else Object.assign(state.draft,{[key]:['floor','sequence'].includes(key)?Number(el.value):el.value});const preview=document.querySelector('[data-room-code-preview]');if(preview){try{preview.textContent=liveRoomCode(listLiveSites().find(s=>s.siteId===state.draft!.siteId)?.code||'',state.draft.floor,state.draft.sequence)}catch{preview.textContent='补全地点、楼层和序列号后生成'}}}},true)
export async function renderLosLiveRoomPage(id='',view='list'):Promise<string>{
 state.view=view;state.id=id;state.dirty=false;state.siteDirty=false;state.draft=null;
 try{await ensurePcsRecordState(['higood-pcs-config-workspace-store-v1']);await ensureLosLiveRoomState();state.error='';state.notice='';state.columns=false;state.siteModal=false
 if(view==='edit'){if(id&&!getLiveRoom(id))return wrap('<p class="p-5">房间不存在。</p>');initializeDraft();return editor()}
 if(view==='list')return list();const room=getLiveRoom(id);state.version=losRecordVersion('rooms',id);return room?detail(room,view==='label'):wrap('<p class="p-5">房间不存在。</p>')
 }catch(error){state.error=error instanceof Error?error.message:'读取失败';return wrap(`<section class="m-5 rounded border p-5"><h1 class="mb-3 font-semibold">直播房间资料暂时无法读取</h1>${feedback()}${btn('重新读取','reload')}</section>`)}
}

function initializeDraft(){const old=state.id?getLiveRoom(state.id):null;state.version=state.id?losRecordVersion('rooms',state.id):0;state.draft=old?structuredClone(old):{roomId:'',siteId:'',floor:1,sequence:1,name:'',categoryNumberIds:[],opm:'',so:'',enabled:true}}
let draggedColumn=''
document.addEventListener('dragstart',event=>{const n=(event.target as Element)?.closest<HTMLElement>('[data-standard-list-column-drag]');if(!n?.closest('[data-los-room-root]'))return;draggedColumn=n.dataset.dragSource||'';event.dataTransfer?.setData('text/plain',draggedColumn)},true)
document.addEventListener('dragover',event=>{const n=(event.target as Element)?.closest<HTMLElement>('[data-drop-target]');if(n?.closest('[data-los-room-root]')){event.preventDefault();event.stopPropagation()}},true)
document.addEventListener('drop',event=>{const n=(event.target as Element)?.closest<HTMLElement>('[data-drop-target]');if(!n?.closest('[data-los-room-root]'))return;event.preventDefault();event.stopPropagation();const order=prefs().order,target=n.dataset.dropTarget||'',from=order.indexOf(draggedColumn),to=order.indexOf(target);if(from>=0&&to>=0&&from!==to){order.splice(from,1);order.splice(order.indexOf(target),0,draggedColumn);savePrefs();update()}draggedColumn=''},true)
document.addEventListener('click',event=>{if(!document.querySelector('[data-los-room-root]'))return;const nav=(event.target as Element)?.closest('[data-nav], [data-action="close-tab"], [data-action="close-all-tabs"]');if(!nav||(!state.dirty&&!state.siteDirty))return;if(!confirm('当前修改尚未保存，是否放弃修改并离开？')){event.preventDefault();event.stopImmediatePropagation()}else{state.dirty=false;state.siteDirty=false}},true)
window.addEventListener('beforeunload',event=>{if(document.querySelector('[data-los-room-root]')&&(state.dirty||state.siteDirty)){event.preventDefault();event.returnValue=''}})
window.addEventListener('higood:before-history-navigation',event=>{
 if(!document.querySelector('[data-los-room-root]')||(!state.dirty&&!state.siteDirty))return
 if(!confirm('当前修改尚未保存，是否放弃修改并离开？')){
  event.preventDefault()
  const current=state.view==='list'?PATH:state.view==='edit'?(state.id?`${PATH}/${state.id}/edit`:`${PATH}/new`):`${PATH}/${state.id}${state.view==='label'?'/label':''}`
  history.pushState(null,'',current)
 }else{state.dirty=false;state.siteDirty=false}
},true)
