import { escapeHtml as e } from '../utils.ts'
export const channelInputClass = 'h-9 w-full rounded-md border bg-white px-3 text-sm focus:border-blue-500 focus:outline-none'
export function channelButton(label: string, action: string, attrs = '', primary = false, prefix = 'pcs-channel-product-list'): string { return `<button type="button" class="inline-flex h-9 items-center justify-center gap-1 rounded-md ${primary ? 'bg-blue-600 text-white hover:bg-blue-700' : 'border bg-white text-slate-700 hover:bg-slate-50'} px-3 text-sm font-medium disabled:opacity-50" data-${prefix}-action="${e(action)}" ${attrs}>${e(label)}</button>` }
export function channelLink(label: string, path: string, primary = false): string { return `<button type="button" class="inline-flex h-9 items-center rounded-md ${primary ? 'bg-blue-600 text-white' : 'border bg-white text-slate-700'} px-3 text-sm" data-nav="${e(path)}">${e(label)}</button>` }
export function channelBadge(value: string): string { const tone = ['审核通过','在售','一致','成功','启用'].includes(value) ? 'bg-green-50 text-green-700' : ['失败','平台限制','同时变更待处理'].includes(value) ? 'bg-red-50 text-red-700' : ['待审核','待同步','结果待核实','部分成功','未发布'].includes(value) ? 'bg-amber-50 text-amber-700' : 'bg-slate-100 text-slate-600'; return `<span class="inline-flex whitespace-nowrap rounded px-2 py-1 text-xs ${tone}">${e(value)}</span>` }
export function channelField(label: string, value: unknown): string { return `<div class="min-w-0"><dt class="mb-1 text-xs text-slate-500">${e(label)}</dt><dd class="break-words text-sm text-slate-900">${e(value == null || value === '' ? '—' : String(value))}</dd></div>` }
export function channelCard(title: string, body: string, action = ''): string { return `<section class="overflow-hidden rounded-lg border bg-white"><header class="flex min-h-12 flex-wrap items-center justify-between gap-3 border-b px-5 py-3"><h2 class="text-sm font-semibold">${e(title)}</h2>${action}</header><div class="p-5">${body}</div></section>` }
export function channelTabs(tabs: Array<[string,string]>, current: string, prefix = 'pcs-channel-product-list', action = 'tab'): string { return `<nav class="flex flex-wrap gap-1 border-b bg-white px-4" aria-label="详情视图">${tabs.map(([key,label]) => `<button type="button" class="border-b-2 px-4 py-3 text-sm ${current === key ? 'border-blue-600 font-semibold text-blue-600' : 'border-transparent text-slate-600 hover:text-blue-600'}" data-${prefix}-action="${action}" data-tab="${key}" aria-selected="${current === key}">${e(label)}</button>`).join('')}</nav>` }
export function channelInput(label: string, key: string, value: unknown, options: { type?: string; required?: boolean; readOnly?: boolean; prefix?: string; help?: string; min?: string } = {}): string { const prefix = options.prefix || 'pcs-channel-product-list'; return `<label class="block text-sm"><span class="mb-1.5 block font-medium text-slate-700">${e(label)}${options.required ? '<span class="ml-1 text-red-500">*</span>' : ''}</span><input class="${channelInputClass} ${options.readOnly ? 'bg-slate-50' : ''}" type="${options.type || 'text'}" value="${e(value == null ? '' : String(value))}" data-${prefix}-field="${e(key)}" ${options.readOnly ? 'readonly' : ''} ${options.min ? `min="${options.min}"` : ''}>${options.help ? `<span class="mt-1 block text-xs text-slate-500">${e(options.help)}</span>` : ''}</label>` }
export function channelSelect(label: string, key: string, value: string, values: Array<[string,string]>, prefix = 'pcs-channel-product-list', disabled = false): string { return `<label class="block text-sm"><span class="mb-1.5 block font-medium text-slate-700">${e(label)}</span><select class="${channelInputClass}" data-${prefix}-field="${e(key)}" ${disabled ? 'disabled' : ''}>${values.map(([v,l]) => `<option value="${e(v)}" ${v === value ? 'selected' : ''}>${e(l)}</option>`).join('')}</select></label>` }
export function channelTextArea(label: string, key: string, value: string, rows = 5, prefix = 'pcs-channel-product-list'): string { return `<label class="block text-sm"><span class="mb-1.5 block font-medium text-slate-700">${e(label)}</span><textarea rows="${rows}" class="w-full rounded-md border p-3 text-sm focus:border-blue-500 focus:outline-none" data-${prefix}-field="${e(key)}">${e(value)}</textarea></label>` }
/** 保存原描述，预览只输出销售说明使用的结构标签，不接收脚本、事件、样式或业务事件属性。 */
export function renderChannelDescription(value: string): string {
  const allowed=new Set(['p','br','strong','b','em','i','u','s','ul','ol','li','h1','h2','h3','h4','blockquote','table','thead','tbody','tfoot','tr','th','td','caption','hr','img','a','div','span'])
  const input=value.replace(/<!--[^]*?-->/g,'').replace(/<(script|style|iframe|object|embed|svg|math|form)\b[^>]*>[^]*?<\/\1\s*>/gi,'')
  const safeText=(text:string)=>e(text).replace(/&amp;(#[xX][0-9a-fA-F]+|#\d+|amp|lt|gt|quot|apos|nbsp);/g,'&$1;')
  const parts:string[]=[];let position=0
  for(const match of input.matchAll(/<\s*(\/?)\s*([a-z][a-z0-9]*)\b([^>]*)>/gi)){
    parts.push(safeText(input.slice(position,match.index)));position=match.index!+match[0].length
    const [,closing,rawName,attributes]=match,name=rawName.toLowerCase();if(!allowed.has(name))continue
    if(closing){if(!['br','hr','img'].includes(name))parts.push(`</${name}>`);continue}
    const values=new Map<string,string>()
    for(const attribute of attributes.matchAll(/([a-z][a-z0-9-]*)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s"'=<>`]+))/gi))values.set(attribute[1].toLowerCase(),attribute[2]??attribute[3]??attribute[4]??'')
    const extras:string[]=[]
    if(name==='img'||name==='a'){
      const key=name==='img'?'src':'href',url=values.get(key)||''
      if(/^(https?:\/\/|\/[^/])/i.test(url)&&!/[\u0000-\u0020\u007f]/.test(url))extras.push(`${key}="${e(url)}"`)
      if(name==='a')extras.push('target="_blank"','rel="noopener noreferrer"')
      if(name==='img')extras.push(`alt="${e(values.get('alt')||'商品描述图片')}"`,'loading="lazy"')
    }
    if(name==='th'||name==='td')for(const key of ['colspan','rowspan'])if(/^\d{1,2}$/.test(values.get(key)||''))extras.push(`${key}="${values.get(key)}"`)
    parts.push(`<${name}${extras.length?' '+extras.join(' '):''}>`)
  }
  parts.push(safeText(input.slice(position)))
  return `<div class="prose prose-sm max-w-none overflow-x-auto whitespace-pre-wrap break-words [&_img]:max-w-full [&_table]:border-collapse [&_td]:border [&_td]:p-2 [&_th]:border [&_th]:p-2">${parts.join('')||'未填写'}</div>`
}
export function channelTable(headers: string[], rows: string[][], empty = '暂无记录'): string { return `<div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr>${headers.map(h => `<th class="whitespace-nowrap border-b px-3 py-3 font-medium">${e(h)}</th>`).join('')}</tr></thead><tbody>${rows.length ? rows.map(row => `<tr class="border-b last:border-0 hover:bg-slate-50/60">${row.map(cell => `<td class="px-3 py-3 align-top">${cell}</td>`).join('')}</tr>`).join('') : `<tr><td colspan="${headers.length}" class="p-8 text-center text-slate-400">${e(empty)}</td></tr>`}</tbody></table></div>` }
export function channelImage(url: string, title: string, size = 'h-12 w-12', prefix = 'pcs-channel-product-list'): string { return url ? `<button type="button" class="shrink-0 overflow-hidden rounded-md border bg-slate-50 ${size}" data-${prefix}-action="image" data-url="${e(url)}" data-title="${e(title)}" aria-label="查看${e(title)}大图"><img src="${e(url)}" alt="${e(title)}" class="h-full w-full object-cover" loading="lazy"></button>` : '<span class="text-xs text-slate-400">未配置识别图</span>' }
export function channelNotice(message: string, error = false): string { return message ? `<div role="status" class="rounded-lg border ${error ? 'border-red-200 bg-red-50 text-red-700' : 'border-blue-100 bg-blue-50 text-blue-700'} px-4 py-3 text-sm">${e(message)}</div>` : '' }
export function channelImageOverlay(url: string, title: string, prefix = 'pcs-channel-product-list'): string { return url ? `<div class="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-8" role="dialog" aria-modal="true" aria-label="图片预览"><section class="max-h-full max-w-4xl overflow-auto rounded-lg bg-white p-4"><header class="mb-3 flex items-center justify-between gap-6"><h2 class="font-semibold">${e(title)}</h2>${channelButton('关闭','close-image','',false,prefix)}</header><img src="${e(url)}" alt="${e(title)}" class="max-h-[75vh] max-w-full object-contain"></section></div>` : '' }
export function channelDownload(name: string, content: string, mime = 'text/csv;charset=utf-8'): void { const url = URL.createObjectURL(new Blob([mime.startsWith('text/csv') ? '\uFEFF' : '', content], { type: mime })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
export function channelCsv(rows: unknown[][]): string { return rows.map(row => row.map(value => `"${String(value ?? '').replaceAll('"','""')}"`).join(',')).join('\r\n') }
