import assert from 'node:assert/strict'
import { listDyeWorkOrders, getDyeOutputRolls, saveDyeOutputRolls, deleteDyeOutputRolls, markDyeOutputRolls, listDyeDispatchDocuments, createDyeDispatchDocument, finishDyeDispatchDocument, getDyeDispatchAvailableQty, getDyeOrderHandoverSummary, submitDyeHandover } from '../src/data/fcs/dyeing-task-domain.ts'
const order = listDyeWorkOrders().find(order => order.status === 'WAIT_HANDOVER' && getDyeDispatchAvailableQty(order.dyeOrderId) > 2)!
assert(order, '必须有包装完成的演示单')
const id = order.dyeOrderId
const initial = JSON.stringify(getDyeOrderHandoverSummary(id))
saveDyeOutputRolls(id, [{qty:0},{qty:1,vatNo:'TEST-01'},{qty:1}])
let rolls = getDyeOutputRolls(id).slice(-3)
assert.throws(()=>createDyeDispatchDocument([{orderId:id,rollIds:[rolls[0].id]}],'测试'),/未维护/)
const doc = createDyeDispatchDocument([{orderId:id,rollIds:[rolls[1].id]}],'测试')
assert.equal(JSON.stringify(getDyeOrderHandoverSummary(id)), initial)
assert.throws(()=>deleteDyeOutputRolls(id,[rolls[1].id]),/占用/)
assert.throws(()=>saveDyeOutputRolls(id,[{id:rolls[1].id,qty:2}]),/占用/)
assert.throws(()=>createDyeDispatchDocument([{orderId:id,rollIds:[rolls[1].id]}],'测试'),/占用/)
createDyeDispatchDocument([{orderId:id,rollIds:[rolls[2].id]}],'测试',doc.id)
assert.equal(listDyeDispatchDocuments()[0].lines[0].rolls.length,2)
assert.throws(()=>submitDyeHandover(id,{handoverQty:getDyeDispatchAvailableQty(id)}),/不能超过/)
finishDyeDispatchDocument(doc.id,'confirm')
assert.equal(listDyeDispatchDocuments()[0].status,'已交出')
assert.throws(()=>finishDyeDispatchDocument(doc.id,'confirm'),/草稿/)
assert(getDyeOutputRolls(id).find(roll=>roll.id===rolls[1].id)?.dispatchId)
markDyeOutputRolls(id,[rolls[1].id],'print')
assert(getDyeOutputRolls(id).find(roll=>roll.id===rolls[1].id)?.dispatchId, '补打不改变交出状态')
const before = JSON.stringify(getDyeOutputRolls(id))
assert.throws(()=>saveDyeOutputRolls(id,[{qty:3},{qty:NaN}]),/非负/)
assert.equal(JSON.stringify(getDyeOutputRolls(id)), before, '批量导入整体回滚')
saveDyeOutputRolls(id,[{qty:1}]); rolls=getDyeOutputRolls(id)
const next = createDyeDispatchDocument([{orderId:id,rollIds:[rolls.at(-1)!.id]}],'测试')
finishDyeDispatchDocument(next.id,'void')
assert.equal(listDyeDispatchDocuments().find(doc=>doc.id===next.id)!.lines[0].rolls[0].qty,1)
const next2 = createDyeDispatchDocument([{orderId:id,rollIds:[rolls.at(-1)!.id]}],'测试')
finishDyeDispatchDocument(next2.id,'confirm')
console.log('PASS 草稿不交出、零卷阻断、占用保护、合单、直接交出预留保护、重复确认、部分分批、导入回滚、作废快照、补打保护',id,getDyeOrderHandoverSummary(id))
