import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

import {
  canSelectCraftInPatternPiece,
  listCutPiecePartCrafts,
  listSpecialCrafts,
} from '../src/data/fcs/process-craft-dict.ts'
import { techPacks } from '../src/data/fcs/tech-packs.ts'
import {
  buildBomItemsFromTechPack,
  buildTechniquesFromTechPack,
} from '../src/pages/tech-pack/context.ts'
import {
  buildAutoGeneratedShrinkProcess,
  buildAutoGeneratedWashProcess,
  shouldGenerateShrinkProcess,
  shouldGenerateWashProcess,
  syncPreparationProcessesFromBom,
} from '../src/pages/tech-pack/bom-process-linkage.ts'

const root = process.cwd()

function read(path: string): string {
  return readFileSync(resolve(root, path), 'utf8')
}

function assert(condition: unknown, message: string): void {
  if (!condition) {
    throw new Error(`BOM 缩水/洗水联动检查失败：${message}`)
  }
}

function assertIncludes(path: string, expected: string, message: string): void {
  assert(read(path).includes(expected), `${message}：${path} 缺少 ${expected}`)
}

function assertNotIncludes(path: string, forbidden: string, message: string): void {
  assert(!read(path).includes(forbidden), `${message}：${path} 不应出现 ${forbidden}`)
}

const contextSource = read('src/pages/tech-pack/context.ts')
const bomDomainSource = read('src/pages/tech-pack/bom-domain.ts')
const processDomainSource = read('src/pages/tech-pack/process-domain.ts')
const linkageSource = read('src/pages/tech-pack/bom-process-linkage.ts')
const versionTypesSource = read('src/data/pcs-technical-data-version-types.ts')
const techPacksSource = read('src/data/fcs/tech-packs.ts')

assert(contextSource.includes('shrinkRequirement: BomRequirementFlag'), 'BomItemRow 必须包含 shrinkRequirement')
assert(contextSource.includes('washRequirement: BomRequirementFlag'), 'BomItemRow 必须包含 washRequirement')
assert(versionTypesSource.includes('shrinkRequirement?:') && techPacksSource.includes('shrinkRequirement?:'), '技术包和版本快照类型必须包含 shrinkRequirement')
assert(versionTypesSource.includes('washRequirement?:') && techPacksSource.includes('washRequirement?:'), '技术包和版本快照类型必须包含 washRequirement')
assert(bomDomainSource.includes('缩水需求'), '物料清单页面必须显示“缩水需求”列')
assert(bomDomainSource.includes('洗水需求'), '物料清单页面必须显示“洗水需求”列')
assert(linkageSource.includes("export const bomRequirementOptions: BomRequirementFlag[] = ['否', '是']"), '缩水/洗水需求必须可选“是 / 否”')
assert(contextSource.includes("shrinkRequirement: '否'") && contextSource.includes("washRequirement: '否'"), '缩水/洗水需求默认值必须为“否”')

for (const expected of [
  'shouldGenerateShrinkProcess',
  'shouldGenerateWashProcess',
  'syncPreparationProcessesFromBom',
  'buildAutoGeneratedShrinkProcess',
  'buildAutoGeneratedWashProcess',
]) {
  assert(linkageSource.includes(expected), `缺少 ${expected} 联动函数`)
}

assert(shouldGenerateShrinkProcess([{ shrinkRequirement: '是' }]), '任一 BOM 行缩水需求为“是”时必须生成缩水')
assert(!shouldGenerateShrinkProcess([{ shrinkRequirement: '否' }, { shrinkRequirement: '否' }]), '全部缩水需求为“否”时不得继续要求缩水')
assert(shouldGenerateWashProcess([{ washRequirement: '是' }]), '任一 BOM 行洗水需求为“是”时必须生成洗水')
assert(!shouldGenerateWashProcess([{ washRequirement: '否' }, { washRequirement: '否' }]), '全部洗水需求为“否”时不得继续要求洗水')

const shrinkProcess = buildAutoGeneratedShrinkProcess()
const washProcess = buildAutoGeneratedWashProcess()
assert(shrinkProcess.processCode === 'PREP_SHRINKING', '自动生成缩水工序编码必须为 PREP_SHRINKING')
assert(washProcess.processCode === 'PREP_WASHING', '自动生成洗水工序编码必须为 PREP_WASHING')
assert(shrinkProcess.sourceType === 'BOM' && shrinkProcess.triggerField === 'shrinkRequirement' && shrinkProcess.isAutoGenerated === true, '自动生成缩水工序必须标记 BOM 来源和 shrinkRequirement')
assert(washProcess.sourceType === 'BOM' && washProcess.triggerField === 'washRequirement' && washProcess.isAutoGenerated === true, '自动生成洗水工序必须标记 BOM 来源和 washRequirement')
assert(shrinkProcess.targetObject === 'FABRIC' && washProcess.targetObject === 'FABRIC', '缩水/洗水准备工序对象必须为面料')

const generated = syncPreparationProcessesFromBom([], [{ shrinkRequirement: '是', washRequirement: '是' }])
assert(generated.techniques.some((item) => item.processCode === 'PREP_SHRINKING'), 'BOM 触发后必须生成 PREP_SHRINKING')
assert(generated.techniques.some((item) => item.processCode === 'PREP_WASHING'), 'BOM 触发后必须生成 PREP_WASHING')

const removed = syncPreparationProcessesFromBom([shrinkProcess, washProcess], [{ shrinkRequirement: '否', washRequirement: '否' }])
assert(!removed.techniques.some((item) => item.processCode === 'PREP_SHRINKING'), '全部缩水需求取消时应移除无人工内容的自动缩水工序')
assert(!removed.techniques.some((item) => item.processCode === 'PREP_WASHING'), '全部洗水需求取消时应移除无人工内容的自动洗水工序')
assert(removed.removedProcessCodes.includes('PREP_SHRINKING') && removed.removedProcessCodes.includes('PREP_WASHING'), '取消需求后应记录被移除的准备工序')

const manualShrink = { ...shrinkProcess, remark: '人工确认保留缩水参数' }
const pending = syncPreparationProcessesFromBom([manualShrink], [{ shrinkRequirement: '否' }])
assert(pending.techniques.some((item) => item.processCode === 'PREP_SHRINKING' && item.requiresRemovalConfirmation === true), '有人工维护内容时不得静默删除缩水')
assert(pending.pendingConfirmationProcessCodes.includes('PREP_SHRINKING'), '有人工内容时缩水必须进入待确认')
const manualWash = { ...washProcess, manualNotes: '人工洗水说明' }
const pendingWash = syncPreparationProcessesFromBom([manualWash], [{ washRequirement: '否' }])
assert(pendingWash.techniques.some((item) => item.processCode === 'PREP_WASHING' && item.requiresRemovalConfirmation === true), '有人工维护内容时不得静默删除洗水')
assert(pendingWash.pendingConfirmationProcessCodes.includes('PREP_WASHING'), '有人工内容时洗水必须进入待确认')

assert(processDomainSource.includes('物料清单自动生成'), '工序工艺页面必须展示自动生成来源')
assert(processDomainSource.includes('触发字段'), '工序工艺页面必须展示触发字段')
assert(processDomainSource.includes('待确认'), '工序工艺页面必须展示人工内容冲突待确认状态')
assert(contextSource.includes('sourceType: item.sourceType') && contextSource.includes('triggerField: item.triggerField'), '技术包保存必须保留自动生成工序来源信息')
assert(contextSource.includes('shrinkRequirement: item.shrinkRequirement') && contextSource.includes('washRequirement: item.washRequirement'), '技术包保存必须保留 BOM 缩水/洗水需求')

const bothTechPack = techPacks.find((techPack) =>
  techPack.bomItems.some((item) => item.shrinkRequirement === '是')
  && techPack.bomItems.some((item) => item.washRequirement === '是'),
)
assert(bothTechPack, 'mock 数据必须至少有一个技术包同时触发缩水和洗水')
const shrinkOnlyTechPack = techPacks.find((techPack) =>
  techPack.bomItems.some((item) => item.shrinkRequirement === '是')
  && techPack.bomItems.every((item) => item.washRequirement !== '是'),
)
assert(shrinkOnlyTechPack, 'mock 数据必须至少有一个技术包只触发缩水')
const washOnlyTechPack = techPacks.find((techPack) =>
  techPack.bomItems.some((item) => item.washRequirement === '是')
  && techPack.bomItems.every((item) => item.shrinkRequirement !== '是'),
)
assert(washOnlyTechPack, 'mock 数据必须至少有一个技术包只触发洗水')
const neitherTechPack = techPacks.find((techPack) =>
  techPack.bomItems.length > 0
  && techPack.bomItems.every((item) => item.shrinkRequirement !== '是' && item.washRequirement !== '是'),
)
assert(neitherTechPack, 'mock 数据必须至少有一个技术包两者都不触发')

const allBomRows = techPacks.flatMap((techPack) => techPack.bomItems)
assert(allBomRows.filter((item) => item.shrinkRequirement === '是').length >= 3, 'mock 数据至少需要 3 条缩水需求为“是”的物料行')
assert(allBomRows.filter((item) => item.washRequirement === '是').length >= 3, 'mock 数据至少需要 3 条洗水需求为“是”的物料行')
assert(allBomRows.filter((item) => item.shrinkRequirement !== '是' && item.washRequirement !== '是').length >= 3, 'mock 数据至少需要 3 条缩水/洗水均为“否”的物料行')

const bothBomRows = buildBomItemsFromTechPack(bothTechPack!)
const bothTechniques = buildTechniquesFromTechPack(bothTechPack!, bothBomRows)
assert(bothTechniques.some((item) => item.processCode === 'PREP_SHRINKING' && item.sourceType === 'BOM'), '同时触发技术包工序工艺中必须有 BOM 自动生成缩水')
assert(bothTechniques.some((item) => item.processCode === 'PREP_WASHING' && item.sourceType === 'BOM'), '同时触发技术包工序工艺中必须有 BOM 自动生成洗水')
const shrinkOnlyTechniques = buildTechniquesFromTechPack(shrinkOnlyTechPack!, buildBomItemsFromTechPack(shrinkOnlyTechPack!))
assert(shrinkOnlyTechniques.some((item) => item.processCode === 'PREP_SHRINKING'), '只触发缩水技术包必须有缩水')
assert(!shrinkOnlyTechniques.some((item) => item.processCode === 'PREP_WASHING'), '只触发缩水技术包不得生成洗水')
const washOnlyTechniques = buildTechniquesFromTechPack(washOnlyTechPack!, buildBomItemsFromTechPack(washOnlyTechPack!))
assert(!washOnlyTechniques.some((item) => item.processCode === 'PREP_SHRINKING'), '只触发洗水技术包不得生成缩水')
assert(washOnlyTechniques.some((item) => item.processCode === 'PREP_WASHING'), '只触发洗水技术包必须有洗水')
const neitherTechniques = buildTechniquesFromTechPack(neitherTechPack!, buildBomItemsFromTechPack(neitherTechPack!))
assert(!neitherTechniques.some((item) => item.processCode === 'PREP_SHRINKING'), '两者都不触发技术包不得生成缩水')
assert(!neitherTechniques.some((item) => item.processCode === 'PREP_WASHING'), '两者都不触发技术包不得生成洗水')

assert(!listSpecialCrafts().some((item) => item.craftName === '洗水'), '洗水不得回到新特殊工艺清单')
assert(!listCutPiecePartCrafts().some((item) => ['缩水', '洗水'].includes(item.craftName)), '缩水/洗水不得进入裁片部位特殊工艺选择器')
assert(canSelectCraftInPatternPiece('缩水') === false, '缩水不得在裁片逐片特殊工艺中选择')
assert(canSelectCraftInPatternPiece('洗水') === false, '洗水不得在裁片逐片特殊工艺中选择')

assertIncludes('src/pages/tech-pack/bom-process-linkage.ts', "sourceType: 'BOM'", '联动函数必须生成 BOM 来源')
assertIncludes('src/pages/tech-pack/bom-process-linkage.ts', 'canRemoveAutomatically: true', '自动生成工序必须可自动移除')
assertIncludes('src/pages/tech-pack/process-domain.ts', 'keep-bom-prep-process', '有人工内容时必须提供保留确认路径')
assertIncludes('src/pages/tech-pack/process-domain.ts', 'remove-bom-prep-process', '有人工内容时必须提供移除确认路径')
assertNotIncludes('src/data/fcs/special-craft-task-generation.ts', 'PREP_WASHING', '本次不得改特殊工艺任务生成主流程')

for (const scriptPath of [
  'scripts/check-process-craft-dictionary-rebuild.ts',
  'scripts/check-three-end-process-chain-final.ts',
]) {
  assert(existsSync(resolve(root, scriptPath)), `既有检查脚本不存在：${scriptPath}`)
}

console.log('bom shrink wash process linkage checks passed')
