import { spawnSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'

import {
  canSelectCraftInPatternPiece,
  getCraftTargetObject,
  listAccessoryCrafts,
  listAuxiliaryCrafts,
  listCutPiecePartCrafts,
  listCuttingCrafts,
  listFabricCrafts,
  listPreparationProcesses,
  listSpecialCrafts,
  listSpecialTypeCrafts,
} from '../src/data/fcs/process-craft-dict.ts'
import { techPacks } from '../src/data/fcs/tech-packs.ts'
import {
  buildFeiTicketQrPayload,
  buildSpecialCraftSummary,
  generateFeiTicketsFromPieceInstances,
  getFeiTicketsNeedSpecialCraft,
  listCutPieceFeiTicketGenerationSourceOrders,
  listCutPieceFeiTickets,
  resetCutPieceFeiTicketRuntimeForTest,
} from '../src/data/fcs/cutting/fei-ticket-generation.ts'
import {
  getFeiTicketSpecialCraftFlowSummary,
  getFeiTicketsForSpecialCraft,
  getSpecialCraftsFromFeiTicket,
  groupFeiTicketsBySpecialCraft,
} from '../src/data/fcs/cutting/special-craft-fei-ticket-flow.ts'
import {
  buildPatternItemsFromTechPack,
  buildBomItemsFromTechPack,
  buildTechniquesFromTechPack,
  calculatePatternPieceTotalQty,
  calculatePatternTotalPieceQty,
  findConfiguredPieceInstancesRemoved,
  generatePieceInstancesFromColorQuantities,
  getPatternPieceInstanceSpecialCraftOptions,
  PATTERN_CRAFT_POSITION_OPTIONS,
  summarizePieceInstances,
} from '../src/pages/tech-pack/context.ts'
import {
  buildAutoGeneratedShrinkProcess,
  buildAutoGeneratedWashProcess,
  shouldGenerateShrinkProcess,
  shouldGenerateWashProcess,
  syncPreparationProcessesFromBom,
} from '../src/pages/tech-pack/bom-process-linkage.ts'
import {
  buildPatternSignature,
  checkDuplicateDxfFile,
  checkDuplicateLinkedMaterial,
  checkDuplicateMarkerImage,
  checkDuplicatePattern,
  checkDuplicatePatternName,
  checkDuplicatePrjFile,
  checkDuplicateRulFile,
  checkSimilarParsedStructure,
} from '../src/pages/tech-pack/pattern-duplicate-check.ts'

const ROOT = process.cwd()
const CHECK_SCRIPT_NAME = 'check-tech-pack-pattern-to-fei-ticket-final'

const previousScripts = [
  'scripts/check-process-craft-dictionary-rebuild.ts',
  'scripts/check-bom-shrink-wash-process-linkage.ts',
  'scripts/check-pattern-two-step-maintenance.ts',
  'scripts/check-pattern-binding-duplicate.ts',
  'scripts/check-pattern-piece-color-quantity.ts',
  'scripts/check-pattern-piece-instance-special-craft.ts',
  'scripts/check-fei-ticket-per-piece-generation.ts',
]

function file(relativePath: string): string {
  return path.join(ROOT, relativePath)
}

function read(relativePath: string): string {
  return readFileSync(file(relativePath), 'utf8')
}

function assert(condition: unknown, message: string): void {
  if (!condition) throw new Error(message)
}

function assertIncludes(source: string, value: string, message: string): void {
  assert(source.includes(value), message)
}

function names<T extends { craftName?: string; processName?: string }>(items: T[]): string[] {
  return items.map((item) => item.craftName || item.processName || '')
}

function runPreviousScripts(): void {
  previousScripts.forEach((script) => {
    assert(existsSync(file(script)), `缺少前置检查脚本：${script}`)
    const result = spawnSync('npx', ['tsx', script], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: 'pipe',
    })
    assert(
      result.status === 0,
      `前置检查脚本执行失败：${script}\n${result.stdout}\n${result.stderr}`,
    )
  })
}

function getPrimaryTechPack() {
  const techPack = techPacks.find((item) => item.spuCode === 'SPU-2024-001') || techPacks[0]
  assert(techPack, '缺少技术包 mock 数据')
  return techPack
}

function getAllPatternItems() {
  return techPacks.flatMap((techPack) => buildPatternItemsFromTechPack(techPack))
}

function checkCraftDictionary(): void {
  const prep = listPreparationProcesses()
  assert(prep.some((item) => item.processCode === 'PREP_SHRINKING' && item.processName === '缩水'), '准备阶段缺少 PREP_SHRINKING 缩水')
  assert(prep.some((item) => item.processCode === 'PREP_WASHING' && item.processName === '洗水'), '准备阶段缺少 PREP_WASHING 洗水')
  assert(!listSpecialCrafts().some((item) => item.craftName === '洗水'), '洗水仍存在于新特殊工艺清单')
  assert(listAuxiliaryCrafts().every((item) => item.craftCategoryName === '辅助工艺'), '辅助工艺类别不完整')
  assert(listSpecialTypeCrafts().every((item) => item.craftCategoryName === '特种工艺'), '特种工艺类别不完整')

  const auxiliaryNames = names(listAuxiliaryCrafts())
  ;['绣花', '打条', '压褶', '打揽', '烫画', '直喷', '贝壳绣', '曲牙绣', '一字贝绣花', '捆条'].forEach((name) =>
    assert(auxiliaryNames.includes(name), `辅助工艺缺少：${name}`),
  )
  const specialNames = names(listSpecialTypeCrafts())
  ;['模板工序', '激光开袋', '特种车缝（花样机）', '橡筋定长切割'].forEach((name) =>
    assert(specialNames.includes(name), `特种工艺缺少：${name}`),
  )

  assert(getCraftTargetObject('捆条') === 'FABRIC', '捆条适用对象必须为面料')
  assert(getCraftTargetObject('橡筋定长切割') === 'ACCESSORY', '橡筋定长切割适用对象必须为辅料')
  listSpecialCrafts()
    .filter((item) => !['捆条', '橡筋定长切割'].includes(item.craftName))
    .forEach((item) => assert(item.targetObject === 'CUT_PIECE_PART', `${item.craftName} 必须适用裁片部位`))
  ;['捆条', '橡筋定长切割', '缩水', '洗水'].forEach((name) =>
    assert(!canSelectCraftInPatternPiece(name), `${name} 不得进入裁片逐片特殊工艺选择器`),
  )
  const cutPieceCraftNames = names(listCutPiecePartCrafts())
  ;['捆条', '橡筋定长切割', '缩水', '洗水'].forEach((name) =>
    assert(!cutPieceCraftNames.includes(name), `${name} 不得出现在 listCutPiecePartCrafts`),
  )
  const cuttingCraftNames = names(listCuttingCrafts())
  ;['普通裁', '激光定位裁', '定向裁'].forEach((name) =>
    assert(cuttingCraftNames.includes(name), `裁床工序缺少：${name}`),
  )
  assert(listFabricCrafts().some((item) => item.craftName === '捆条'), '面料级工艺缺少捆条')
  assert(listAccessoryCrafts().some((item) => item.craftName === '橡筋定长切割'), '辅料级工艺缺少橡筋定长切割')
}

function checkBomLinkage(): void {
  const techPack = getPrimaryTechPack()
  const bomSource = read('src/pages/tech-pack/bom-domain.ts')
  const bomLinkageSource = read('src/pages/tech-pack/bom-process-linkage.ts')
  const techPackSource = read('src/data/fcs/tech-packs.ts')
  assertIncludes(techPackSource, 'shrinkRequirement', 'BomItemRow 或技术包 BOM 模型缺少 shrinkRequirement')
  assertIncludes(techPackSource, 'washRequirement', 'BomItemRow 或技术包 BOM 模型缺少 washRequirement')
  assertIncludes(bomSource, '缩水需求', '物料清单页面缺少缩水需求列')
  assertIncludes(bomSource, '洗水需求', '物料清单页面缺少洗水需求列')
  assertIncludes(bomLinkageSource, "'否'", '缩水/洗水需求默认值或选项缺少“否”')

  const shrinkRows = [{ ...techPack.bomItems[0], shrinkRequirement: '是', washRequirement: '否' }]
  const washRows = [{ ...techPack.bomItems[0], shrinkRequirement: '否', washRequirement: '是' }]
  assert(shouldGenerateShrinkProcess(shrinkRows), '任一 BOM 行缩水需求为是时未触发缩水')
  assert(shouldGenerateWashProcess(washRows), '任一 BOM 行洗水需求为是时未触发洗水')
  assert(!shouldGenerateShrinkProcess([{ ...techPack.bomItems[0], shrinkRequirement: '否' }]), '全部缩水需求为否时仍触发缩水')
  assert(!shouldGenerateWashProcess([{ ...techPack.bomItems[0], washRequirement: '否' }]), '全部洗水需求为否时仍触发洗水')

  const shrink = buildAutoGeneratedShrinkProcess()
  const wash = buildAutoGeneratedWashProcess()
  assert(shrink.sourceType === 'BOM' && shrink.triggerField === 'shrinkRequirement', '自动生成缩水来源或触发字段错误')
  assert(wash.sourceType === 'BOM' && wash.triggerField === 'washRequirement', '自动生成洗水来源或触发字段错误')

  const linked = syncPreparationProcessesFromBom([], [
      { ...techPack.bomItems[0], shrinkRequirement: '是', washRequirement: '是' },
      ...techPack.bomItems.slice(1),
    ])
  assert(linked.techniques.some((item) => item.processCode === 'PREP_SHRINKING'), 'BOM 联动未生成 PREP_SHRINKING')
  assert(linked.techniques.some((item) => item.processCode === 'PREP_WASHING'), 'BOM 联动未生成 PREP_WASHING')
  const manualRemoval = syncPreparationProcessesFromBom(
    [{ ...shrink, hasManualOverride: true, manualNotes: '人工备注' }],
    [{ ...techPack.bomItems[0], shrinkRequirement: '否', washRequirement: '否' }],
  )
  assert(
    manualRemoval.techniques.some((item) => item.processCode === 'PREP_SHRINKING' && item.requiresRemovalConfirmation),
    '有人工维护内容的缩水不应静默删除',
  )

  const snapshotSources = [
    read('src/data/pcs-technical-data-version-types.ts'),
    read('src/data/pcs-technical-data-fcs-adapter.ts'),
  ].join('\n')
  ;['shrinkRequirement', 'washRequirement'].forEach((field) =>
    assertIncludes(snapshotSources, field, `技术包版本快照缺少 ${field}`),
  )
  const linkedTechniques = buildTechniquesFromTechPack(techPack, buildBomItemsFromTechPack(techPack))
  assert(
    linkedTechniques.some((item) => item.processCode === 'PREP_SHRINKING' || item.processCode === 'PREP_WASHING'),
    '技术包快照派生工序缺少 PREP_SHRINKING/PREP_WASHING',
  )
}

function checkPatternTwoStepAndBinding(): void {
  const patternModelSource = read('src/data/fcs/tech-packs.ts')
  const patternPageSource = read('src/pages/tech-pack/pattern-domain.ts')
  const patternTwoStepSource = patternModelSource + patternPageSource + read('src/pages/tech-pack/context.ts')
  ;[
    ['patternName', ['patternName', 'name: string']],
    ['patternType', ['patternType', 'type: TechPackPatternCategory', 'patternMaterialType']],
    ['isKnitted', ['isKnitted']],
    ['fabricWidthCm', ['fabricWidthCm', 'widthCm']],
    ['linkedMaterialId', ['linkedMaterialId']],
    ['linkedMaterialName', ['linkedMaterialName']],
    ['linkedMaterialSku', ['linkedMaterialSku']],
    ['markerLengthM', ['markerLengthM']],
    ['prjFile', ['prjFile']],
    ['markerImage', ['markerImage']],
    ['dxfFile', ['dxfFile']],
    ['rulFile', ['rulFile']],
    ['merchandiserInfoStatus', ['merchandiserInfoStatus']],
    ['patternMakerInfoStatus', ['patternMakerInfoStatus']],
    ['maintainerStepStatus', ['maintainerStepStatus']],
  ].forEach(([field, candidates]) =>
    assert((candidates as string[]).some((candidate) => patternTwoStepSource.includes(candidate)), `纸样两步字段缺少 ${field}`),
  )
  ;['跟单基础信息', '版师技术信息', '排料长度（m）', '纸样 PRJ 文件', '唛架图片', 'DXF 文件', 'RUL 文件', '裁片明细'].forEach((text) =>
    assertIncludes(patternPageSource, text, `纸样页面缺少 ${text}`),
  )
  assert(!patternPageSource.includes('纸样图片'), '纸样页面仍出现用户可见旧文案“纸样图片”')
  assertIncludes(patternPageSource, '.prj', 'PRJ 文件缺少格式限制')
  assertIncludes(patternTwoStepSource, 'linkedMaterial', '关联物料未绑定 BOM 来源字段')

  ;['bindingStrips', 'bindingStripId', 'bindingStripNo', 'bindingStripName', 'lengthCm', 'widthCm'].forEach((field) =>
    assertIncludes(patternModelSource + patternPageSource, field, `捆条字段缺少 ${field}`),
  )
  const patternInteractionSource = patternPageSource + read('src/pages/tech-pack/events.ts')
  ;['捆条', '添加捆条', '确认删除该捆条'].forEach((text) =>
    assertIncludes(patternInteractionSource, text, `纸样版师技术信息缺少 ${text}`),
  )
  const patternItems = getAllPatternItems()
  assert(patternItems.some((item) => item.bindingStrips.length === 0), 'mock 数据缺少 0 个捆条纸样')
  assert(patternItems.some((item) => item.bindingStrips.length === 1), 'mock 数据缺少 1 个捆条纸样')
  assert(patternItems.some((item) => item.bindingStrips.length >= 2), 'mock 数据缺少 2 个以上捆条纸样')

  const base = patternItems.find((item) =>
    item.prjFile?.fileSize
    && item.markerImage?.fileSize
    && ((item.dxfFile?.fileSize || item.dxfFileSize || 0) > 0)
    && ((item.rulFile?.fileSize || item.rulFileSize || 0) > 0),
  )
  assert(base, '缺少可用于重复校验的完整纸样')
  const existing = patternItems.map((item) => ({
    id: item.id,
    patternName: item.name,
    patternType: item.patternMaterialType,
    linkedMaterialId: item.linkedMaterialId,
    prjFile: item.prjFile,
    dxfFile: item.dxfFile,
    rulFile: item.rulFile,
    markerImage: item.markerImage,
    selectedSizeCodes: item.selectedSizeCodes,
    pieceRows: item.pieceRows,
  }))
  assert(checkDuplicatePatternName({ patternId: 'NEW-NAME', patternName: base!.name }, existing).hasBlockingDuplicate, '同名纸样未阻止保存')
  assert(checkDuplicatePrjFile({ patternId: 'NEW-PRJ', prjFile: base!.prjFile }, existing).hasBlockingDuplicate, '重复 PRJ 未阻止保存')
  assert(checkDuplicateDxfFile({ patternId: 'NEW-DXF', dxfFile: base!.dxfFile }, existing).hasBlockingDuplicate, '重复 DXF 未阻止保存')
  assert(checkDuplicateRulFile({ patternId: 'NEW-RUL', rulFile: base!.rulFile }, existing).hasBlockingDuplicate, '重复 RUL 未阻止保存')
  assert(checkDuplicateLinkedMaterial({
    patternId: 'NEW-MAT',
    linkedMaterialId: base!.linkedMaterialId,
    patternType: base!.patternMaterialType,
  }, existing).hasWarningDuplicate, '关联物料重复未进入疑似重复确认')
  assert(checkDuplicateMarkerImage({ patternId: 'NEW-IMG', markerImage: base!.markerImage }, existing).hasWarningDuplicate, '唛架图片重复未进入疑似重复确认')
  assert(checkSimilarParsedStructure({
    patternId: 'NEW-STRUCT',
    patternType: base!.patternMaterialType,
    linkedMaterialId: base!.linkedMaterialId,
    selectedSizeCodes: base!.selectedSizeCodes,
    pieceRows: base!.pieceRows,
  }, existing).hasWarningDuplicate, '解析结构相似未进入疑似重复确认')
  assert(!checkDuplicatePattern({ patternId: base!.id, patternName: base!.name, prjFile: base!.prjFile }, existing).hasBlockingDuplicate, '编辑当前纸样时误识别自身重复')
  assert(Boolean(buildPatternSignature(base!)), 'patternSignature 构建失败')
  ;['patternSignature', 'duplicateConfirmed', 'duplicateWarningReasons', 'bindingStrips'].forEach((field) =>
    assertIncludes(patternModelSource, field, `技术包快照或模型缺少 ${field}`),
  )
}

function checkPieceRowsAndInstances(): void {
  const modelSource = read('src/data/fcs/tech-packs.ts')
  const pageSource = read('src/pages/tech-pack/pattern-domain.ts')
  const eventsSource = read('src/pages/tech-pack/events.ts')
  ;[
    'colorPieceQuantities',
    'colorId',
    'colorName',
    'pieceQty',
    'enabled',
    'parsedQuantity',
    'totalPieceQty',
    'patternTotalPieceQty',
  ].forEach((field) => assertIncludes(modelSource + pageSource, field, `裁片明细颜色片数字段缺少 ${field}`))
  ;['适用颜色', '颜色片数', '当前部位总片数', '当前总片数', '解析参考片数'].forEach((text) =>
    assertIncludes(pageSource, text, `裁片明细页面缺少 ${text}`),
  )
  assert(!pageSource.includes('<th class="px-2 py-1 text-left">片数</th>'), '裁片明细主表仍有可编辑片数列')

  const pattern = getAllPatternItems().find((item) => item.pieceRows.length > 0 && item.pieceInstances.length > 0)
  assert(pattern, '缺少带裁片明细和裁片实例的纸样')
  const row = pattern!.pieceRows.find((item) => item.colorPieceQuantities.length > 0)
  assert(row, '缺少带颜色片数的裁片明细')
  assert(
    calculatePatternPieceTotalQty(row!.colorPieceQuantities) === row!.totalPieceQty,
    'totalPieceQty 与启用颜色 pieceQty 合计不一致',
  )
  assert(calculatePatternTotalPieceQty(pattern!.pieceRows) === pattern!.patternTotalPieceQty, 'patternTotalPieceQty 与行合计不一致')
  assert(row!.colorPieceQuantities.every((item) => Number.isInteger(item.pieceQty) && item.pieceQty >= 0), 'pieceQty 必须为非负整数')

  ;[
    'pieceInstances',
    'pieceInstanceId',
    'sourcePieceId',
    'sequenceNo',
    'displayName',
    'specialCraftAssignments',
    'craftCode',
    'craftName',
    'craftPosition',
    'craftPositionName',
  ].forEach((field) => assertIncludes(modelSource + pageSource, field, `裁片实例或逐片特殊工艺字段缺少 ${field}`))
  assert(PATTERN_CRAFT_POSITION_OPTIONS.map((item) => item.code).join(',') === 'LEFT,RIGHT,BOTTOM,FACE', '工艺位置 code 必须为 LEFT/RIGHT/BOTTOM/FACE')
  assert(PATTERN_CRAFT_POSITION_OPTIONS.map((item) => item.name).join(',') === '左,右,底,面', '工艺位置中文必须为 左/右/底/面')
  const generated = generatePieceInstancesFromColorQuantities({
    id: pattern!.id,
    pieceRows: pattern!.pieceRows,
    pieceInstances: pattern!.pieceInstances,
  })
  assert(generated.length === pattern!.patternTotalPieceQty, '裁片实例数量必须等于启用颜色 pieceQty 合计')
  const increasedRows = pattern!.pieceRows.map((item, index) => index === 0 ? ({
    ...item,
    colorPieceQuantities: item.colorPieceQuantities.map((qty, qtyIndex) => qtyIndex === 0 ? { ...qty, enabled: true, pieceQty: qty.pieceQty + 1 } : qty),
  }) : item)
  assert(generatePieceInstancesFromColorQuantities({ id: pattern!.id, pieceRows: increasedRows, pieceInstances: generated }).length > generated.length, '颜色片数增加未新增实例')
  const removed = findConfiguredPieceInstancesRemoved(
    [{ ...generated[0], specialCraftAssignments: pattern!.pieceInstances.find((item) => item.specialCraftAssignments.length > 0)?.specialCraftAssignments || [] }],
    [],
  )
  assert(removed.length >= 1, '颜色片数减少时未识别已配置实例')
  assertIncludes(pageSource + eventsSource, '当前减少片数会删除已配置特殊工艺的裁片实例', '删除已配置实例前缺少确认逻辑')

  const craftOptions = getPatternPieceInstanceSpecialCraftOptions()
  const optionNames = names(craftOptions)
  ;['绣花', '打条', '压褶', '打揽', '烫画', '直喷', '贝壳绣', '曲牙绣', '一字贝绣花', '模板工序', '激光开袋', '特种车缝（花样机）'].forEach((name) =>
    assert(optionNames.includes(name), `逐片特殊工艺选择器缺少 ${name}`),
  )
  ;['捆条', '橡筋定长切割', '缩水', '洗水'].forEach((name) =>
    assert(!optionNames.includes(name), `逐片特殊工艺选择器错误包含 ${name}`),
  )
  assertIncludes(pageSource + eventsSource, '该裁片已配置该特殊工艺，请勿重复添加', '缺少重复 craftCode 校验提示')
  assertIncludes(pageSource + eventsSource, '请选择工艺位置', '缺少未选工艺位置提示')
  assertIncludes(pageSource, '维护逐片工艺', '页面缺少维护逐片工艺入口')
  assertIncludes(pageSource, '应用到同颜色全部片', '页面缺少批量应用能力')
  const summary = summarizePieceInstances(pattern!.pieceInstances)
  assert(summary.pieceInstanceTotal === pattern!.pieceInstances.length, '裁片实例统计错误')
}

function checkFeiTicketsAndSpecialCraftConsumption(): void {
  resetCutPieceFeiTicketRuntimeForTest()
  const feiSource = read('src/data/fcs/cutting/fei-ticket-generation.ts')
  const feiPageSource = read('src/pages/process-factory/cutting/fei-tickets.ts')
  const printSource = read('src/data/fcs/cutting-task-print-source.ts') + read('src/data/fcs/task-print-cards.ts')
  ;[
    'CutPieceFeiTicket',
    'feiTicketId',
    'feiTicketNo',
    'sourceTechPackVersionId',
    'sourcePatternId',
    'sourcePieceId',
    'sourcePieceInstanceId',
    'originalCutPieceOrderId',
    'originalCutPieceOrderNo',
    'mergeBatchId',
    'colorId',
    'colorName',
    'sizeName',
    'pieceName',
    'sequenceNo',
    'specialCrafts',
    'specialCraftSummary',
    'qrCodePayload',
    'FeiTicketSpecialCraft',
    'craftPosition',
    'craftPositionName',
  ].forEach((field) => assertIncludes(feiSource, field, `菲票模型或生成模块缺少 ${field}`))

  const sourceOrder = listCutPieceFeiTicketGenerationSourceOrders()[0]
  assert(sourceOrder, '缺少菲票生成源原始裁片单')
  const ticketsBefore = listCutPieceFeiTickets()
  const previewSource = ticketsBefore.filter((ticket) => ticket.originalCutPieceOrderId === sourceOrder.originalCutPieceOrderId)
  assert(previewSource.every((ticket) => ticket.originalCutPieceOrderId && ticket.originalCutPieceOrderNo), '菲票必须归属原始裁片单')
  assert(ticketsBefore.some((ticket) => ticket.mergeBatchId), 'mock 数据缺少合并裁剪批次执行上下文')
  assert(ticketsBefore.every((ticket) => !ticket.mergeBatchId || ticket.originalCutPieceOrderId), '合并裁剪批次不得替代原始裁片单归属')

  const pattern = getAllPatternItems().find((item) => item.pieceInstances.length >= 2)
  assert(pattern, '缺少用于生成菲票的裁片实例')
  const generatedTickets = generateFeiTicketsFromPieceInstances({
    techPackVersionId: 'CHECK-V1',
    patternId: pattern!.id,
    pieceInstances: pattern!.pieceInstances.slice(0, 4),
    originalCutPieceOrderId: 'CHECK-ORIGINAL',
    originalCutPieceOrderNo: 'CPO-CHECK-001',
    productionOrderId: 'PO-CHECK',
    productionOrderNo: 'PO-CHECK-001',
    mergeBatchId: 'MB-CHECK',
    mergeBatchNo: '合并裁剪批次-CHECK',
  })
  assert(generatedTickets.length === Math.min(pattern!.pieceInstances.length, 4), '每个 pieceInstance 必须生成一个菲票')
  assert(new Set(generatedTickets.map((ticket) => ticket.sourcePieceInstanceId)).size === generatedTickets.length, '同一 sourcePieceInstanceId 生成了多个有效菲票')
  generatedTickets.forEach((ticket) => {
    const source = pattern!.pieceInstances.find((item) => item.pieceInstanceId === ticket.sourcePieceInstanceId)
    assert(source, '菲票丢失来源裁片实例')
    assert(ticket.specialCrafts.length === source!.specialCraftAssignments.length, '菲票未复制裁片实例 specialCraftAssignments')
    assert(ticket.originalCutPieceOrderId === 'CHECK-ORIGINAL', '菲票 originalCutPieceOrderId 必填且应归属原始裁片单')
    const payload = JSON.parse(buildFeiTicketQrPayload(ticket))
    assert(payload.sourcePieceInstanceId === ticket.sourcePieceInstanceId, '二维码 payload 缺少 sourcePieceInstanceId')
    assert(payload.originalCutPieceOrderId === ticket.originalCutPieceOrderId, '二维码 payload 缺少 originalCutPieceOrderId')
  })
  assert(buildSpecialCraftSummary([]) === '无特殊工艺', '无特殊工艺 summary 错误')
  assertIncludes(feiPageSource, '逐片菲票', '打菲票页面未展示逐片菲票')
  assertIncludes(feiPageSource, '特殊工艺', '打菲票页面缺少特殊工艺列')
  assertIncludes(feiPageSource, '工艺位置', '菲票详情缺少工艺位置')
  assertIncludes(printSource, 'sourcePieceInstanceId', '打印源二维码缺少 sourcePieceInstanceId')
  assertIncludes(printSource, '特殊工艺', '打印源缺少特殊工艺')
  assertIncludes(feiSource + feiPageSource, '补打不生成新的业务菲票', '补打规则缺少“不生成新的业务菲票”')
  assertIncludes(feiSource + feiPageSource, '已打印菲票不能删除', '已打印菲票缺少作废保护')

  const ticketsWithCraft = getFeiTicketsNeedSpecialCraft()
  assert(ticketsWithCraft.length > 0, '有特殊工艺菲票无法被 getFeiTicketsNeedSpecialCraft 查询')
  const sampleCraft = ticketsWithCraft[0].specialCrafts[0]
  assert(getFeiTicketsForSpecialCraft(sampleCraft.craftCode).length > 0, '无法按特殊工艺查询菲票')
  const grouped = groupFeiTicketsBySpecialCraft(ticketsWithCraft)
  assert(grouped.some((group) => group.craftCode === sampleCraft.craftCode && group.feiTicketCount > 0), '无法按 craftCode 分组菲票')
  assert(getSpecialCraftsFromFeiTicket(ticketsWithCraft[0].feiTicketId).some((craft) => craft.craftPositionName), '菲票特殊工艺无法读取工艺位置')
  const flowSummary = getFeiTicketSpecialCraftFlowSummary(ticketsWithCraft[0].feiTicketId)
  assert(flowSummary && flowSummary.relatedFeiTicketIds.includes(ticketsWithCraft[0].feiTicketId), '特殊工艺流转摘要无法追溯 relatedFeiTicketIds')

  const wrongOwnershipText = [
    read('src/data/fcs/cutting/fei-ticket-generation.ts'),
    read('src/pages/process-factory/cutting/fei-tickets.ts'),
    read('docs/fcs-fei-ticket-per-piece-generation.md'),
  ].join('\n')
  assert(
    !wrongOwnershipText.includes('菲票归属合并裁剪批次')
      && !wrongOwnershipText.includes('合并裁剪批次作为菲票归属')
      && !wrongOwnershipText.includes('合并裁剪批次成为菲票归属主体'),
    '存在菲票归属合并裁剪批次的错误口径',
  )
}

function checkSnapshotCompleteness(): void {
  const snapshotSources = [
    read('src/data/pcs-technical-data-version-types.ts'),
    read('src/data/pcs-technical-data-fcs-adapter.ts'),
    read('src/data/fcs/tech-packs.ts'),
  ].join('\n')
  ;[
    'shrinkRequirement',
    'washRequirement',
    'prjFile',
    'markerImage',
    'bindingStrips',
    'patternSignature',
    'duplicateConfirmed',
    'duplicateWarningReasons',
    'colorPieceQuantities',
    'totalPieceQty',
    'patternTotalPieceQty',
    'pieceInstances',
    'specialCraftAssignments',
    'craftPosition',
    'craftPositionName',
    'pieceInstanceId',
    'specialCraftAssignments',
  ].forEach((field) => assertIncludes(snapshotSources, field, `技术包版本快照缺少 ${field}`))
}

assert(CHECK_SCRIPT_NAME === 'check-tech-pack-pattern-to-fei-ticket-final', '最终总检查脚本名异常')
runPreviousScripts()
checkCraftDictionary()
checkBomLinkage()
checkPatternTwoStepAndBinding()
checkPieceRowsAndInstances()
checkFeiTicketsAndSpecialCraftConsumption()
checkSnapshotCompleteness()

console.log('tech pack pattern to fei ticket final checks passed')
