import assert from 'node:assert/strict'
import {readWoolStore, replaceWoolStore, validateWoolStore, WOOL_DOMAIN_STORE_KEY} from '../src/data/fcs/wool-domain/store.ts'
import {addWoolProcessReport,addWoolHandover} from '../src/data/fcs/wool-domain/commands.ts'
import {executeWoolCraftAction,listWoolCraftTaskOrders} from '../src/data/fcs/wool-domain/craft-flow.ts'
import {captureFactoryReceivingData,restoreFactoryReceivingData,getDefaultFactoryReceiptPosition} from '../src/data/fcs/factory-receiving.ts'
import {confirmFactoryMaterialReceipt} from '../src/data/fcs/factory-receiving-links.ts'
import {buildFormalPostFinishingReturnSources} from '../src/data/fcs/post-finishing-return-source-adapter.ts'
import {listWoolPanelCuttingReceiptSources} from '../src/data/fcs/wool-domain/cutting-receipts.ts'
const original=readWoolStore(),receiving=captureFactoryReceivingData(),at='2026-09-18 17:00:00';let tests=0
function test(name:string,fn:()=>void){try{fn();console.log(`PASS ${name}`);tests++}finally{restoreFactoryReceivingData(receiving);replaceWoolStore(original)}}
try{
 test('A16 演示待收纱线通过正常接收入口开工',()=>{const source=receiving.sources.find(s=>s.id==='WDEMO-YARN:WOOL-STAGE-001')!;const r=confirmFactoryMaterialReceipt({id:'boundary-yarn',factoryId:source.targetFactoryId,operatorId:'test',operatorName:'验收',receivedAt:at,remark:'',lines:[{sourceId:source.id,sourceLineId:source.lines[0].id,pcs:1,grossKg:1.062,tubes:{PAPER:1,CONICAL:0,PAGODA:0},...getDefaultFactoryReceiptPosition(source.targetFactoryId)}]});assert.equal(r.lines[0].qty,1);assert.equal(readWoolStore().yarnReceipts.filter(r=>r.woolOrderId==='WOOL-STAGE-001:KNITTING').length,1)})
 test('A11 自动四事实保存失败不留下半组记录',()=>{const before=JSON.stringify(readWoolStore()),prior=(globalThis as any).window;let fail=true;const raw=new Map<string,string>();(globalThis as any).window={localStorage:{getItem:(k:string)=>raw.get(k)||null,setItem:(k:string,v:string)=>{if(k===WOOL_DOMAIN_STORE_KEY&&fail){fail=false;throw Error('模拟存储失败')}raw.set(k,v)},removeItem:(k:string)=>raw.delete(k)}};try{assert.throws(()=>addWoolProcessReport('WOOL-STAGE-002:KNITTING',{commandId:'fail-report',outputSkuCode:'CARDIGAN-CREAM-M',reportedQty:5,reportedAt:at,reportedBy:'验收'}),/模拟存储失败/);assert.equal(JSON.stringify(readWoolStore()),before)}finally{(globalThis as any).window=prior}})
 test('A11 横机交出与待接收跨存储失败一并回退',()=>{const before=JSON.stringify(readWoolStore()),recv=JSON.stringify(captureFactoryReceivingData()),prior=(globalThis as any).window;let fail=true;const raw=new Map<string,string>();(globalThis as any).window={localStorage:{getItem:(k:string)=>raw.get(k)||null,setItem:(k:string,v:string)=>{if(k===WOOL_DOMAIN_STORE_KEY&&fail){fail=false;throw Error('模拟存储失败')}raw.set(k,v)},removeItem:(k:string)=>raw.delete(k)}};try{const o=readWoolStore().workOrders['WOOL-STAGE-008:KNITTING'];assert.throws(()=>addWoolHandover(o.woolOrderId,{commandId:'fail-handover',outputSkuCode:o.outputPlanLines[0].outputSkuCode,pieceKey:o.externalPieces[0].pieceKey,handoverQty:1,handedOverAt:at,handedOverBy:'验收'}),/模拟存储失败/);assert.equal(JSON.stringify(readWoolStore()),before);assert.equal(JSON.stringify(captureFactoryReceivingData()),recv)}finally{(globalThis as any).window=prior}})
 test('工艺重复确认载荷不同不接受，重试不重复加工',()=>{const task=listWoolCraftTaskOrders().find(t=>t.woolOrderId==='WOOL-STAGE-009:KNITTING'&&t.receivedQty>0)!;const input={taskOrderId:task.taskOrderId,actionCode:'SPECIAL_CRAFT_PROCESS_REPORT',qty:1,operatorName:'验收',operatedAt:at,commandId:'craft-retry'};executeWoolCraftAction(input);executeWoolCraftAction(input);assert.equal(readWoolStore().craftRecords.filter(r=>r.commandId===input.commandId).length,1);assert.throws(()=>executeWoolCraftAction({...input,operatorName:'其他人'}),/不一致/)})
 test('A17 后道仅接指定后道厂的缝盘最终产物',()=>{const s=readWoolStore();const o=s.workOrders['WOOL-STAGE-003:LINKING'];s.handovers.push({handoverId:'probe',woolOrderId:o.woolOrderId,outputSkuCode:o.outputPlanLines[0].outputSkuCode,handoverQty:3,qtyUnit:'件',receiverType:'DOWNSTREAM_FACTORY',receiverId:'OTHER-FACTORY',receiverName:'其他厂',handedOverAt:at,handedOverBy:'验收',warehouseOutboundFlowId:'probe-flow',createdAt:at,updatedAt:at});const facts={woolStore:s,productionOrders:[],runtimeTasks:[],specialCraftTaskOrders:[]};assert.ok(!buildFormalPostFinishingReturnSources(facts).some(x=>x.executionTaskId.includes('probe')));assert.ok(listWoolPanelCuttingReceiptSources().every(x=>!JSON.stringify(x).includes(':KNITTING')))})
 test('保存边界拒绝跨片伪造回货与断开的配对',()=>{let s=readWoolStore();s.pieceReceipts[0].sourceHandoverId='missing';assert.throws(()=>validateWoolStore(s),/回货片/);s=readWoolStore();s.workOrders['WOOL-STAGE-001:LINKING'].sourceTaskId='other';assert.throws(()=>validateWoolStore(s),/配对/)})
 console.log(`${tests} boundary contracts passed`)
}finally{restoreFactoryReceivingData(receiving);replaceWoolStore(original)}
