import assert from 'node:assert/strict'
import {build} from 'esbuild'
import {execFileSync} from 'node:child_process'
import {runInNewContext} from 'node:vm'
const files=['factory-receiving.ts','factory-internal-warehouse.ts','warehouse-material-execution.ts','water-soluble-task-domain.ts','store-domain-progress.ts','printing-task-domain.ts','dyeing-task-domain.ts','printing-factory-demos.ts','pda-handover-events.ts','kol-goto-pda-domain.ts','process-mobile-task-binding.ts']
async function compile(baseline:boolean){
 const result=await build({stdin:{contents:`import {listKolGotoTasks,listKolGotoPickupBatches,getKolGotoHandoutQty} from './src/data/fcs/kol-goto-pda-domain.ts';import { listPdaMobileExecutionTasks } from './src/data/fcs/process-mobile-task-binding.ts';import { listProgressFacts } from './src/data/fcs/store-domain-progress.ts';import { listFactoryInternalWarehouses,listFactoryWarehouseInboundRecords,listFactoryWarehouseOutboundRecords,listFactoryWaitProcessStockItems,listFactoryWaitHandoverStockItems } from './src/data/fcs/factory-internal-warehouse.ts';import {getDefaultFactoryReceiptPosition,getFactoryReceiptLocations,listFactoryReceivingSources} from './src/data/fcs/factory-receiving.ts';export function facts(){return {tasks:listPdaMobileExecutionTasks(),progress:listProgressFacts(),inbound:listFactoryWarehouseInboundRecords(),outbound:listFactoryWarehouseOutboundRecords(),process:listFactoryWaitProcessStockItems(),handover:listFactoryWaitHandoverStockItems(),sources:listFactoryReceivingSources(undefined,true),positions:listFactoryInternalWarehouses().filter(w=>w.warehouseKind==='WAIT_PROCESS'&&w.isEnabled&&w.isDefault).map(w=>({factory:w.factoryId,position:getDefaultFactoryReceiptPosition(w.factoryId)})),kolTasks:listKolGotoTasks(),kolPickups:listKolGotoPickupBatches(),kolHandouts:listKolGotoTasks().map(t=>[t.taskId,getKolGotoHandoutQty(t.taskId)])}}`,resolveDir:process.cwd(),loader:'ts'},define:{'import.meta.url':JSON.stringify('file:///wool-perf-facts.ts'),'import.meta.hot':'undefined'},bundle:true,platform:'node',format:'iife',globalName:'api',write:false,logLevel:'silent',plugins:baseline?[{name:'baseline',setup(b){b.onLoad({filter:/\/src\/data\/fcs\/[^/]+\.ts$/},args=>{if(!files.includes(args.path.split('/').at(-1)!))return;const relative='src/data/fcs/'+args.path.split('/').at(-1);return {contents:execFileSync('git',['show',`HEAD:${relative}`],{encoding:'utf8'}),loader:'ts'}})}}]:[]})
 return result.outputFiles[0].text
}
const fixed=Date.parse('2026-09-18T12:00:00Z')
class FixedDate extends Date{constructor(...args:any[]){super(...(args.length?args:[fixed]) as [number])}static now(){return fixed}}
function run(code:string){const storage=new Map<string,string>();const localStorage={getItem:(k:string)=>storage.get(k)??null,setItem:(k:string,v:string)=>storage.set(k,v),removeItem:(k:string)=>storage.delete(k)};const context:any={console,Date:FixedDate,structuredClone,localStorage,window:{localStorage,addEventListener(){},location:{pathname:'/fcs/pda/exec',search:''}},document:{addEventListener(){},visibilityState:'visible'}};runInNewContext(code,context);return JSON.parse(JSON.stringify(context.api.facts()))}
const expected=run(await compile(true)),actual=run(await compile(false))
assert.deepEqual(actual,expected,'all task factories, task properties, readiness, stock, receipts and default locations unchanged')
console.log(`PASS unchanged ${actual.tasks.length} tasks, ${actual.progress.length} progress facts, ${actual.inbound.length} inbound / ${actual.outbound.length} outbound records, ${actual.positions.length} factory default locations`)
