import { appendStageReport } from '../src/data/fcs/wool-domain/stage-facts.ts'
import { confirmFactoryMaterialReceipt as confirmFactoryReceipt } from '../src/data/fcs/factory-receiving-links.ts'
import assert from 'node:assert/strict'
import { buildWoolFactWorkflowMockStore } from '../src/data/fcs/wool-domain/mock-data.ts'
import { readWoolStore, replaceWoolStore } from '../src/data/fcs/wool-domain/store.ts'
import { addWoolProcessReport, addWoolHandover, changeWoolFactQty, completeWoolWorkOrder } from '../src/data/fcs/wool-domain/commands.ts'
import { stageReportedQty, linkingCapacity, stageCompletionBlock } from '../src/data/fcs/wool-domain/stage-rules.ts'
import { getWoolAllowedActions, getWoolProcessingStatus, getWoolWorkOrderTabCounts } from '../src/data/fcs/wool-domain/queries.ts'
import { listWoolCraftTaskOrders, executeWoolCraftAction } from '../src/data/fcs/wool-domain/craft-flow.ts'
import { captureFactoryReceivingData,restoreFactoryReceivingData, getFactoryReceivingSourceByOriginalRecordId,getDefaultFactoryReceiptPosition } from '../src/data/fcs/factory-receiving.ts'
import { replaceWoolMachineAssociations } from '../src/data/fcs/wool-domain/machine-associations.ts'
const original=readWoolStore(),receiving=captureFactoryReceivingData(),sku='CARDIGAN-CREAM-M',at='2026-09-18 12:00:00';let count=0
function fixture(){const s=buildWoolFactWorkflowMockStore();s.processReports=[];s.handovers=[];s.warehouseFlows=[];s.internalReceipts=[];s.pieceReceipts=[];s.craftRecords=[];s.completions=[];s.operationLogs=[];s.machineAssociations=[];s.machineAssociationLogs=[];s.qtyChangeLogs=[];
 for(const [n,qty] of [['003',40],['004',100],['008',40],['009',100]] as const){const o=s.workOrders[`WOOL-STAGE-${n}:KNITTING`];appendStageReport(s,o,{reportId:`WOOL-STAGE-${n}:report`,woolOrderId:o.woolOrderId,outputSkuCode:sku,reportedQty:qty,reportedAt:at,reportedBy:'验收员',warehouseInboundFlowId:`WF-${n}`,createdAt:at,updatedAt:at})}
 return s}
function test(name:string,fn:()=>void){const r=structuredClone(receiving);const pieces=new Set(r.sources.filter(s=>s.lines.some(l=>l.material.kind==='WOOL_PIECE')).map(s=>s.id));r.sources=r.sources.filter(s=>!pieces.has(s.id));r.receipts=r.receipts.filter(r=>!r.lines.some(l=>pieces.has(l.sourceId)));r.deliveries=r.deliveries.filter(d=>!d.lines.some(l=>pieces.has(l.sourceId)));restoreFactoryReceivingData(r);replaceWoolStore(fixture());fn();count++;console.log(`PASS ${name}`)}
const knit=(n:string)=>`WOOL-STAGE-${n}:KNITTING`,link=(n:string)=>`WOOL-STAGE-${n}:LINKING`
const report=(id:string,qty:number,cmd='report')=>addWoolProcessReport(id,{commandId:cmd,outputSkuCode:sku,reportedQty:qty,reportedAt:at,reportedBy:'验收员'})
const hand=(id:string,qty:number,cmd:string,pieceKey?:string)=>addWoolHandover(id,{commandId:cmd,outputSkuCode:sku,pieceKey,handoverQty:qty,handedOverAt:at,handedOverBy:'验收员'})
function receive(originalId:string,qty:number,id:string){const source=getFactoryReceivingSourceByOriginalRecordId(originalId)!;assert.ok(source);return confirmFactoryReceipt({id,factoryId:source.targetFactoryId,operatorId:'test',operatorName:'验收员',receivedAt:at,remark:'专项验收',lines:[{sourceId:source.id,sourceLineId:source.lines[0].id,businessQty:qty,businessUnit:'片',...getDefaultFactoryReceiptPosition(source.targetFactoryId)}]})}
try{
 test('A01 整件100件四类事实同量且最终交出仍人工',()=>{report(knit('003'),60,'whole-to-100');const s=readWoolStore();assert.equal(stageReportedQty(s,knit('003'),sku),100);assert.equal(stageReportedQty(s,link('003'),sku),100);assert.equal(s.internalReceipts.filter(r=>r.woolOrderId===link('003')).reduce((n,r)=>n+r.qty,0),100);assert.equal(s.handovers.filter(r=>r.woolOrderId===knit('003')&&r.automatic).reduce((n,r)=>n+r.handoverQty,0),100);assert.equal(s.handovers.filter(r=>r.woolOrderId===link('003')).length,0)})
 test('A01/02 无外加工按件自动衔接且幂等',()=>{report(knit('002'),30);report(knit('002'),30);let s=readWoolStore();assert.equal(stageReportedQty(s,link('002'),sku),30);assert.equal(s.internalReceipts.filter(r=>r.woolOrderId===link('002')).reduce((n,r)=>n+r.qty,0),30);assert.equal(s.workOrders[knit('002')].externalPieces.length,0);assert.throws(()=>report(knit('002'),31),/幂等/);assert.throws(()=>report(link('002'),1,'manual'),/自动/);assert.ok(!getWoolAllowedActions(link('002')).includes('ASSOCIATE_MACHINE'))})
 test('A10 无料阻断及150%上限',()=>{assert.throws(()=>report(knit('001'),1),/纱线/);report(knit('002'),150);assert.throws(()=>report(knit('002'),1,'over'),/上限/);assert.equal(stageReportedQty(readWoolStore(),link('002'),sku),150)})
 test('A12 合法横机修正同步四类事实',()=>{changeWoolFactQty({commandId:'correct',recordType:'PROCESS_REPORT',recordId:'WOOL-STAGE-003:report',afterQty:30,changedAt:at,changedBy:'验收员',reason:'复核'});let s=readWoolStore();assert.equal(stageReportedQty(s,link('003'),sku),30);assert.equal(s.internalReceipts.find(r=>r.woolOrderId===link('003'))?.qty,30);assert.throws(()=>changeWoolFactQty({commandId:'child',recordType:'PROCESS_REPORT',recordId:'WOOL-STAGE-003:report:linking',afterQty:29,changedAt:at,changedBy:'验收员',reason:'复核'}),/自动/)})
 test('A12 最终交出后不能反向修正自动链',()=>{hand(link('003'),10,'final');const before=JSON.stringify(readWoolStore());assert.throws(()=>changeWoolFactQty({commandId:'late',recordType:'PROCESS_REPORT',recordId:'WOOL-STAGE-003:report',afterQty:30,changedAt:at,changedBy:'验收员',reason:'复核'}),/最终交出/);assert.equal(JSON.stringify(readWoolStore()),before)})
 test('A05/08 横机片按首厂独立交出及分批实收',()=>{const o=readWoolStore().workOrders[knit('008')],p=o.externalPieces[0];const h=hand(o.woolOrderId,40,'send',p.pieceKey);const source=getFactoryReceivingSourceByOriginalRecordId(h.handoverId)!;assert.equal(source.targetFactoryId,p.routeNodes[0].factoryId);receive(h.handoverId,25,'r1');assert.equal(listWoolCraftTaskOrders().find(t=>t.taskOrderId===p.routeNodes[0].taskOrderId)!.receivedQty,25);assert.equal(readWoolStore().pieceReceipts.length,0);receive(h.handoverId,15,'r2');assert.throws(()=>receive(h.handoverId,1,'r3'),/超过|剩余/);assert.equal(readWoolStore().handovers.find(t=>t.handoverId===h.handoverId)?.downstreamReceipt?.actualReceivedQty,40)})
 test('A03/04/06 回货取最短板且末工艺才进缝盘',()=>{const o=readWoolStore().workOrders[knit('009')];for(const [i,p]of o.externalPieces.entries()){const h=hand(o.woolOrderId,100,`s${i}`,p.pieceKey);receive(h.handoverId,100,`in${i}`);for(const [j,n] of p.routeNodes.entries()){const taskOrderId=n.taskOrderId!;executeWoolCraftAction({taskOrderId,actionCode:'SPECIAL_CRAFT_PROCESS_REPORT',qty:100,commandId:`p${i}${j}`,operatorName:'验收员',operatedAt:at});executeWoolCraftAction({taskOrderId,actionCode:'SPECIAL_CRAFT_SUBMIT_HANDOVER',qty:100,commandId:`h${i}${j}`,operatorName:'验收员',operatedAt:at});receive(`WCF:h${i}${j}`,j===p.routeNodes.length-1&&i===1?80:100,`back${i}${j}`)}}let s=readWoolStore();assert.equal(linkingCapacity(s,s.workOrders[link('009')],sku),80);report(link('009'),50,'linking');assert.throws(()=>report(link('009'),31,'overlink'),/上限/);assert.equal(stageReportedQty(readWoolStore(),link('009'),sku),50)})
 test('A09 未派工不能外发/误走自动链',()=>{report(knit('014'),10);const o=readWoolStore().workOrders[knit('014')];assert.equal(stageReportedQty(readWoolStore(),link('014'),sku),0);assert.throws(()=>hand(o.woolOrderId,1,'bad',o.externalPieces[0].pieceKey),/分配/)})
 test('A11/14 阶段完成独立且缝盘不能关联设备',()=>{assert.equal(getWoolProcessingStatus(knit('004')),'PROCESS_COMPLETE');assert.equal(stageCompletionBlock(readWoolStore(),readWoolStore().workOrders[knit('004')]),'');completeWoolWorkOrder(knit('004'),{commandId:'close',completedAt:at,completedBy:'验收员'});assert.equal(getWoolProcessingStatus(knit('004')),'COMPLETED');assert.notEqual(getWoolProcessingStatus(link('004')),'COMPLETED');assert.throws(()=>replaceWoolMachineAssociations(link('004'),['WM-001'],{operatedAt:at,operatedBy:'验收员'}),/仅横机/);const counts=getWoolWorkOrderTabCounts();assert.equal(counts.ALL,counts.UNPROCESSED+counts.READY+counts.PROCESSING+counts.PROCESS_COMPLETE+counts.COMPLETED)})
 console.log(`${count} two-stage contracts passed`)
}finally{restoreFactoryReceivingData(receiving);replaceWoolStore(original)}
