/** V7 accepted diagram templates. All facts are read from shared static source records. */
import { getTimingCaseByScene as makeCase, getTimingDiagramBranch as branchData, getTimingFacts as facts, getTimingIssues as issues, timingDocumentHref, findTimingDocument, TIMING_SCENES } from '../../data/production-timing/source';
import { materialFigure } from './material-image-view';
const ASOF: any = '2026-10-07 09:00';
const DAY: any = 86400000;
const DEMO_IMAGE: any = '/images/production-timing/shirt-086.jpg';
const labels: any = { late: '假设演示 · 三阶段超时／当前袖片工艺逾期', live: '假设演示 · 分批生产', unknown: '原型资料待核实 · 不推定业务未发生', unassigned: '假设演示 · 数量归属不完整', sameFactory: '假设演示 · 同厂任务分别判定' };
Object.entries(TIMING_SCENES).filter(([key])=>!['live','unknown','unassigned','sameFactory','handoverPartial'].includes(key)).forEach(([key,label])=>labels[key]='假设演示 · '+label);labels.handoverPartial='假设演示 · 交接部分实收／数量差异待确认';
const contracts: any = { sewing: { name: '独立车缝', days: [4, 8, 9] }, combined: { name: '车缝＋烫包', days: [5, 9, 10] }, full: { name: '裁剪＋车缝＋烫包', days: [6, 9, 12] } };
const esc: any = (value?: any): any => String(value ?? '').replace(/[&<>"']/g, (ch?: any): any => (({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' } as Record<string,string>)[ch]));
const badge: any = (text?: any, tone: any = ''): any => '<span class="badge ' + tone + '">' + esc(text) + '</span>';
const button: any = (text?: any, key?: any, primary: any = false): any => '<button class="' + (primary ? 'btn primary' : 'link') + '" data-detail="' + esc(key) + '">' + esc(text) + '</button>';
const table: any = (heads?: any, rows?: any): any => '<div class="table-wrap"><table><thead><tr>' + heads.map((h?: any): any => '<th>' + esc(h) + '</th>').join('') + '</tr></thead><tbody>' + rows.map((row?: any): any => '<tr>' + row.map((cell?: any): any => '<td>' + cell + '</td>').join('') + '</tr>').join('') + '</tbody></table></div>';
const phases: any = { prep: '生产准备', supply: '面辅料供给', craft: '裁片辅助工艺' };
const fullTime: any = (t?: any): any => !t ? null : t.startsWith('2026-') ? t : '2026-' + t;
const shortTime: any = (t?: any): any => t ? t.slice(5) : '待取得';
const arrow: any = (): any => '<span class="flow-arrow" aria-label="明确前后关系">→</span>';
const state: any = { scenario: 'late', detail: '', queue: false, expanded: { prep: false, supply: false, craft: false } };
function ms(value?: any): any { return Date.parse(value.replace(' ', 'T') + (value.length === 16 ? ':00' : '') + '+08:00'); }
function fmt(value?: any, short: any = false): any { const text: any = new Date(value + 8 * 3600000).toISOString().slice(0, 16).replace('T', ' '); return short ? text.slice(5) : text; }
function duration(value?: any): any { const minutes: any = Math.floor(Math.abs(value) / 60000), days: any = Math.floor(minutes / 1440), hours: any = Math.floor(minutes % 1440 / 60), rest: any = minutes % 60; return (days ? days + '天' : '') + (hours ? hours + '小时' : '') + (rest ? rest + '分钟' : '') || ('不足1分钟'); }
function receiptTotal(t?: any): any { return t.receipts.filter((r?: any): any => ms(r.at) <= ms(ASOF)).reduce((sum?: any, r?: any): any => sum + r.qty, 0); }
function nodeInfo(t?: any): any {
    return [30, 70, 100].map((pct?: any, i?: any): any => {
        const target: any = Math.ceil(t.held * pct / 100), deadline: any = ms(t.assigned + ' 00:00') + contracts[t.type].days[i] * DAY - 1;
        let sum: any = 0, reached: any = null;
        t.receipts.filter((r?: any): any => ms(r.at) <= ms(ASOF)).slice().sort((a?: any, b?: any): any => ms(a.at) - ms(b.at)).some((r?: any): any => { sum += r.qty; if (sum >= target) {
            reached = ms(r.at);
            return true;
        } return false; });
        const gap: any = Math.max(0, target - receiptTotal(t));
        return { pct, target, deadline, gap, reached, status: reached !== null ? (reached <= deadline ? '按期达成' : '逾期达成') : (ms(ASOF) > deadline ? '已逾期' : '尚未到期') };
    });
}
function timing(d?: any): any { return d.clock?.start ? timingBase(d) : null; }
function timingMark(d?: any): any { const t: any = timing(d); if (!t)
    return ''; const k: any = d.clock, actual: any = ms(k.end || ASOF), span: any = Math.max(k.sla * DAY, actual - ms(k.start)), cut: any = k.sla * DAY / span * 100, endPercent: any = (actual - ms(k.start)) / span * 100; return '<div class="time-result"><span class="timing-mark ' + (t.gap ? 'late-mark' : 'ok-mark') + '">' + (t.gap ? '! ' : '✓ ') + esc(t.label) + '</span><div class="deadline-meter"><i class="meter-normal" style="width:' + Math.min(cut, endPercent) + '%"></i>' + (t.gap ? '<i class="meter-over" style="left:' + cut + '%;width:' + (100 - cut) + '%"></i>' : '') + '<i class="meter-cut" style="left:' + cut + '%" title="应完成截止"></i><i class="meter-end" style="left:' + endPercent + '%" title="' + (t.done ? '实际完成' : '当前查看时点') + '"></i></div><small>截止 ' + shortTime(fmt(t.deadline)) + ' · ' + (t.done ? '实际完成 ' : '仍未完成，截至 ') + shortTime(k.end || ASOF) + '</small></div>'; }
function phaseTiming(b?: any, phase?: any): any { const ids: any = phase === 'prep' ? [b.master] : phase === 'supply' ? b.materials.map((m?: any): any => m.po).filter(Boolean) : b.parts.flatMap((p?: any): any => p.process.map((x?: any): any => x.work)); if (!ids.length)
    return '<div class="phase-time-summary"><span>适用执行记录待取得</span><small>当前时效待核实</small></div>'; const ts: any = ids.map((id?: any): any => timing(b.docs[id])).filter(Boolean), current: any = ts.filter((t?: any): any => t.gap && !t.done), history: any = ts.filter((t?: any): any => t.gap && t.done); return '<div class="phase-time-summary">' + (current.length ? '<b class="current-late">' + current.length + '项当前逾期 · 最长' + duration(Math.max(...current.map((t?: any): any => t.gap))) + '</b>' : '<span class="ok-mark">已知时效项无当前逾期</span>') + (history.length ? '<b class="history-late">' + history.length + '项逾期完成 · 最长' + duration(Math.max(...history.map((t?: any): any => t.gap))) + '</b>' : '') + '<small>' + esc(phase === 'prep' ? '阶段整体' + b.docs[b.master].clock.sla + '自然日；支线不累加' : phase === 'supply' ? '物料采购下单→面辅料仓入库8自然日' : '辅助工艺每道3自然日；交接另计') + '</small></div>'; }
function clockLabel(d?: any): any { const k: any = d.clock; if (!k)
    return ''; if (!k.start)
    return k.kind + '起点待取得，尚未计时'; if (ms(k.end || ASOF) < ms(k.start))
    return k.kind + '起点尚未发生，尚未计时'; return k.kind + ' ' + (k.kind === '交接' && !k.end ? '已等' : '已用') + duration(ms(k.end || ASOF) - ms(k.start)) + (k.sla ? ' · 要求' + k.sla + '自然日' : ' · 标准待配置'); }
function docButton(d?: any, label?: any): any { return '<button class="doc-link" data-document="' + esc(d.id) + '" aria-label="查看单据 ' + esc(d.no) + '">▤ ' + esc(label || d.no) + '</button>'; }
function docNode(b?: any, id?: any, title?: any): any { const d: any = b.docs[id]; if (!d)
    return '<div class="document-node missing">单据待取得</div>'; const time: any = Object.entries(d.times).filter(([, v]: any): any => v).slice(-1)[0]; return '<div class="document-node ' + (timing(d)?.gap ? 'overdue ' : '') + (d.clock && !d.clock.end ? 'pending' : '') + '"><strong>' + esc(title || d.type) + '</strong>' + timingMark(d) + docButton(d) + '<span class="doc-state">' + esc(d.status) + ' · ' + d.quantity + esc(d.unit) + '</span><span class="doc-time">' + esc(time ? time[0] + ' ' + shortTime(time[1]) : '时间待取得') + '</span>' + (d.clock ? '<span class="doc-time">' + esc((d.clock.kind === '采购到仓' ? '下单' : d.clock.kind === '交接' ? '交出' : '开始') + ' ' + shortTime(d.clock.start)) + '</span><span class="doc-clock">' + esc(clockLabel(d)) + '</span>' : '') + '<small>' + esc(d.executor + ' → ' + d.receiver) + '</small></div>'; }
function prepNode(b?: any, n?: any): any { const result: any = n.title.includes('成果已确认'); return '<div class="prep-node"><strong>' + esc(result ? '成果接收／确认' : n.title) + '</strong>' + n.ids.map((id?: any): any => { const d: any = b.docs[id], confirm: any = d.times.成果确认 || d.times.买手确认; return docButton(d) + '<span class="doc-state">' + esc(d.status) + ' · ' + d.quantity + d.unit + '</span>' + (result ? '<small>确认 ' + shortTime(confirm) + '</small>' : twoClocks(d)) + (d.roles ? '<small>' + esc(d.roles.执行 + '执行 → ' + d.roles.接收确认 + '接收确认') + '</small>' : ''); }).join('') + '</div>'; }
function legNode(b?: any, h?: any): any { return '<div class="handoff-node ' + (!h.end ? 'pending' : '') + '"><strong>' + esc(h.from + ' → ' + h.to) + '</strong><span class="doc-state">' + esc(b.docs[h.id].status) + '</span><div class="leg-docs">' + docButton(b.docs[h.id]) + docButton(b.docs[h.out], '交出记录') + (h.receipt ? docButton(b.docs[h.receipt], '接收记录') : '<span class="missing-receipt">接收记录待取得</span>') + docButton(b.docs[h.qc], '质检交接记录') + '</div><div class="handoff-facts"><span>交出 ' + shortTime(h.start) + ' · ' + h.qty + h.unit + '</span><span>' + (h.receivedAt ? '部分实收 ' + shortTime(h.receivedAt) + ' · ' + h.receivedQty + h.unit + ' · 数量差异' + h.pendingQty + h.unit + '待确认' : h.end ? '实收 ' + shortTime(h.end) + ' · ' + (b.docs[h.receipt]?.quantities?.实收 ?? h.qty) + h.unit + ' · 差异' + (b.docs[h.id]?.quantities?.数量差异 ?? 0) + h.unit : '实收、时间及差异待核实') + '</span></div><span class="doc-clock">' + esc(clockLabel(b.docs[h.id])) + '</span></div>'; }
function processRows(b?: any, rows?: any): any { return '<div class="process-rows">' + rows.map((p?: any, i?: any): any => '<div class="process-step">' + docNode(b, p.work) + arrow() + (p.leg ? legNode(b, p.leg) : '<div class="handoff-node awaiting-work"><strong>未交出 · 交接尚未开始</strong><span>完成量2400片／应加工3000片；本工序剩余600片</span><small>阿琳执行 → 裁床刘军接收确认</small></div>') + '</div>' + (i < rows.length - 1 ? '<div class="next-step">↓ 下道工厂实际接收后，开始下一道加工</div>' : '')).join('') + '</div>'; }
function branchHeader(phase?: any, text?: any): any { return '<div class="branch-head"><div><strong>' + esc(phases[phase]) + ' · 单据与交接链路</strong><small>' + esc(text) + '</small></div><button class="link" data-expand="' + phase + '">收起本阶段链路 ↑</button></div>'; }
function unknownBranches(c?: any, phase?: any): any { return '<div class="branch-panel" id="branch-' + phase + '">' + branchHeader(phase, '单据未取得时保留待核实，不生成示例单号或可点击假详情') + '<div class="unknown-branches">' + (phase === 'prep' ? ['准备单、BOM与前期输入', '适用专业任务与有效明细', '技术包确认与发布'] : phase === 'supply' ? ['库存采用与调拨单', '采购单与原料入库单', '逐道加工单与质检交接'] : ['裁剪单与部位批次', '逐道辅助工艺加工单', '工厂交接、质检与人工放行']).map((s?: any): any => '<div><strong>? ' + esc(s) + '</strong><span>单号、状态、数量、人员与时间待核实</span></div>').join('') + '</div><p class="branch-foot">陈静协调核对已有业务记录。缺资料不推定未生产，也不将未知实收填为0。</p></div>'; }
function prepDiagram(c?: any, b?: any): any { let s: any = prepDiagramBase(c, b).replace('本例无定位印，整体要求4天', (c.positioning ? '有定位印，整体要求5天' : '无定位印，整体要求4天')).replace('有定位印时阶段整体5天。', '支线制作和交接分别计时，不增加审版时段。').replace('全部有效明细完成；', '适用有效明细全部完成后汇合；'); for (const id of [b.paper.sample, b.paper.sizes]) {
    const d: any = b.docs[id];
    s = s.replace(docNode(b, id), docNode(b, id).slice(0, -6) + twoClocks({ handoverClock: d.handoverClock }) + '</div>');
} if (b.inactivePreparation?.length) {
    const history = '<div class="prep-inactive"><strong>不计当前欠项的准备记录</strong>' + b.inactivePreparation.map((id:any)=>{
        const d = b.docs[id];
        return '<div>' + docButton(d) + badge(d.status) + '<span>' + esc(d.object) + ' · ' + esc(d.timingExclusionReason) + '</span></div>';
    }).join('') + '</div>';
    s = s.replace('<div class="branch-foot">', history + '<div class="branch-foot">');
} return s; }
function materialProcess(b?: any, m?: any): any { return '<div class="material-process-track">' + m.process.map((p?: any, i?: any): any => '<div class="material-process-column"><div class="process-number">' + (i + 1) + ' · ' + esc(b.docs[p.work].type) + '</div>' + docNode(b, p.work) + '<div class="vertical-arrow">↓ 交出与下游实收</div>' + legNode(b, p.leg) + '</div>' + (i < m.process.length - 1 ? '<span class="trunk-arrow">→</span>' : '')).join('') + '</div>'; }
function materialReceipt(b?: any, m?: any): any { const records: any = [m.stockTransfer, m.purchaseTransfer].filter(Boolean).map((id?: any): any => b.docs[id]), expected: any = Number(m.use > 0) + Number(m.missing > 0), unknown: any = records.length < expected || records.some((d?: any): any => d.quantities.实收 === null || !d.times.下游接收); const values: any = records.map((d?: any): any => d.quantities.实收), total: any = unknown ? null : values.reduce((sum?: any, q?: any): any => sum + q, 0), latest: any = unknown ? null : records.map((d?: any): any => d.times.下游接收).sort((a?: any, b?: any): any => ms(b) - ms(a))[0]; return { total, latest, equation: unknown ? '实收待核实' : values.join('＋') + '＝' + total + m.unit }; }
function supplyDiagram(c?: any, b?: any): any {
    if (c.prepOpen)
        return '<div class="branch-panel" id="branch-supply">' + branchHeader('supply', '本场景检验生产准备；面辅料执行记录待核实') + '<div class="unknownrail">各项物料采购/调拨与下游实收待核实，不生成完成量。</div></div>';
    let s: any = supplyDiagramBase(c, b).replace('两条来源汇合后，共用下面的加工链', '本例采用全量加工单；实际可按已接收批次分别推进').replace('再跟进同一条加工链', '再按实际全量或分批加工单推进');
    if (c.key === 'materialPartial')
        s = s.replace('<b>待核实</b><span>实收待核实</span>', '<b>已确认600米</b><span>其余900米实收待核实</span>').replace('✓ 无需大货加工 · 实收后进入对应配料工作', '已确认的600米后续加工记录待取得；其余900米采购中，不能认定已入仓。');
    if (c.key !== 'materialBatches')
        return s;
    const m: any = b.materials[0];
    const header: any = s.slice(0, s.indexOf('<article class="material-object">'));
    const rest: any = supplyDiagramBase(c, { ...b, materials: b.materials.slice(1) });
    return header + '<article class="material-object"><div class="material-object-head"><div><strong>F01 主面料白坯布 · 分批加工</strong><small>同一物料需求1500米；成衣采购单未拆分</small></div><div class="material-equation"><b>600米库存批＋900米补采批</b><span>按各自实际实收进入加工；不强制等待汇合</span></div></div>' + m.batches.map((batch?: any): any => '<div class="batch-lane"><div class="batch-caption"><b>' + batch.id + ' · ' + batch.qty + '米 · ' + batch.source + '</b><span>' + shortTime(b.docs[batch.transfer].times.下游接收) + '染厂实收</span></div><div class="batch-source">' + (batch.source === '补采来源' ? docNode(b, m.po) + arrow() + docNode(b, m.receive) + arrow() : '') + docNode(b, batch.transfer) + '</div><div class="join-to-process">↓ 本批实际接收后加工，三道各自记录数量和交接</div>' + materialProcess(b, { process: batch.process }) + '</div>').join('') + '<div class="batch-caption">库存批09-24已先行，补采批09-30才收到；各批都有独立加工单和交出/接收/质检交接。</div></article>' + rest.slice(rest.indexOf('<article class="material-object">'));
}
function craftDiagram(c?: any, b?: any): any { return ['positioning', 'prepPending', 'materialBatches', 'materialPartial'].includes(c.key) ? '<div class="branch-panel" id="branch-craft">' + branchHeader('craft', '本场景未提供裁片工艺、交接和放行执行记录') + '<div class="unknownrail">后续工艺与人工放行待取得对应单据，不根据上游完成自动判断。</div></div>' : craftDiagramBase(c, b); }
function branchDiagram(c?: any, phase?: any): any { const b: any = branchData(c); return !b ? unknownBranches(c, phase) : phase === 'prep' ? prepDiagram(c, b) : phase === 'supply' ? supplyDiagram(c, b) : craftDiagram(c, b); }
function collectBranchNodes(c?: any): any { const b: any = branchData(c); return b ? Object.values(b.docs) : []; }
function branchDetails(c?: any, key?: any): any { if (['prep', 'supply', 'release'].includes(key))
    return branchDiagram(c, key === 'release' ? 'craft' : key); return '<h3>对应单据待核实</h3><p>点击图中的具体单号查看该单据摘要。</p>'; }
function docSummary(b?: any, d?: any): any { const materials=(b.materials||[]).filter((m:any)=>/生产准备单|BOM/.test(d.type)||[m.stockTransfer,m.po,m.receive,m.purchaseTransfer,...(m.transitDocuments||[]),...m.process.flatMap((p:any)=>[p.work,p.leg?.id,p.leg?.out,p.leg?.receipt,p.leg?.qc]),...(m.batches||[]).flatMap((batch:any)=>batch.process.flatMap((p:any)=>[p.work,p.leg?.id,p.leg?.out,p.leg?.receipt,p.leg?.qc]))].includes(d.id));return documentSummaryBase(b, d)+ (materials.length?'<div class="factbox" style="display:flex;flex-wrap:wrap;gap:14px">'+materials.map((m:any)=>materialFigure(m.id)).join('')+'</div>':'') + twoClocks({ handoverClock: d.handoverClock }) + (d.roles ? factBox('明确责任', Object.entries(d.roles).map(([k, v]: any): any => esc(k) + '：' + esc(v)).join('<br>')) : '') + (d.sampleTiming ? factBox('样衣要求与回货分开', d.sampleTiming.due ? '领料后的第3天：' + d.sampleTiming.due + '（日期口径；日内截止时刻待确认）<br>' + sampleTimingLabel(d) : '领料日期未取得，样衣要求日期待核实') : ''); }
function currentHandoverDetails(c?: any): any { const b: any = branchData(c); return b?.current ? '<h3>本批加工与成衣仓交接</h3><div class="process-step">' + docNode(b, b.currentWork) + arrow() + legNode(b, b.current) + '</div><p>应交150件；实收与接收时间待核实。周婷12:00反馈，在原成衣仓接收页面办理。</p>' : '<h3>已有交接单据待核实</h3>'; }
function stageRiskOverview(c?: any): any { const b: any = branchData(c); return '<div class="stage-risk-overview">' + ['prep', 'supply', 'craft'].map((phase?: any): any => '<button class="stage-risk-card" data-stage-focus="' + phase + '"><strong>' + esc(phases[phase]) + '</strong>' + (!b ? '<span>资料待核实</span>' : phaseTiming(b, phase)) + '<small>查看阶段图与对应单据 ↓</small></button>').join('') + '</div>'; }
function lateSummary(c?: any): any { const f: any = facts(c); return '<div class="summary"><div class="cell"><div class="eyebrow">全部入成衣仓截止 · 采购下单＋28自然日</div><b class="deadline">' + fmt(f.deadline) + '</b><div class="sub">还剩11天 · 阶段逾期与整单截止分别判断</div></div><div class="cell"><div class="eyebrow">成衣仓已入库／应完成</div><b>0 <span style="font-size:16px;color:#8190a4">／1500件</span></b><div class="sub">本演示已核实入库0件 · 仍需入库1500件</div></div><div class="cell"><div class="eyebrow">当前优先处理 · 袖片绣花</div><b class="alert">逾期1天 · 剩余600片</b><div class="sub">阿琳执行 → 裁床刘军接收；王明11:00跟进</div></div></div>'; }
function lateQuantity(c?: any): any { return '<div class="sectiontop"><h2>数量现在在哪里</h2><small>成衣应完成1500件 · 裁片数量单独在工艺图看</small></div><div class="quantity-graph">' + [['尚未下发车缝任务', '1500', '本演示核实未分配、未领料', 'waiting'], ['工厂尚未回', '0', '未下发任务，没有工厂实领', 'waiting'], ['后道加工／交接', '0', '本演示尚未进入后道', 'waiting'], ['成衣仓已入库', '0', '仓库入库已核实为0件', 'warehouse']].map((x?: any): any => '<button class="qnode" data-detail="' + x[3] + '"><div class="title">' + x[0] + '</div><div class="n">' + x[1] + '<em>件</em></div><div class="hint">' + x[2] + '</div></button>').join('') + '</div><div class="balance-note">1500件＝未下发车缝1500＋工厂0＋后道0＋交接0＋入库0；工艺图中的片数不能加进这里。</div>'; }
function lateIssues(c?: any): any { return [{ id: 'sleeve-overdue', category: 'work', tone: 'bad', title: '袖片绣花 · 当前逾期1天／剩余600片', reason: '10-03 09:00开始；3自然日截止10-06 09:00，仍未完成', text: '应加工3000片，完成2400片，剩余600片；尚未交出，交接尚无计时起点。', executor: '绣花厂阿琳', receiver: '裁床刘军（下游接收）', owner: '王明', feedback: '10-07 11:00', latest: '10-07 08:30，阿琳反馈完成2400片，余600片安排待核实。', detail: 'release' }]; }
function lateDetails(c?: any, key?: any): any { if (key.startsWith('issue:')) {
    const i: any = lateIssues(c)[0];
    return '<h3>' + i.title + '</h3>' + factBox('时效要求', i.reason) + factBox('当前数量与交接', i.text) + factBox('责任与跟进', i.executor + ' → ' + i.receiver + '；' + i.owner + ' ' + i.feedback + '反馈');
} return '<h3>本演示当前生产情况</h3>' + factBox('整单数量', '商品采购1500件；未下发车缝任务1500件；工厂实领、后道、交接、成衣入库均已核实为0件。') + factBox('准备与物料', '生产准备已于09-25 09:00完成，逾期1天；主面料采购于09-30 12:00入仓，逾期完成2天。两个已结束时钟保留历史延误，不再作为当前欠项。') + factBox('当前工艺', '袖片绣花应完成3000片，完成2400片；当前逾期1天，剩余600片。其他部位情况见工艺图。') + '<p>本例尚未办理裁片放行。业务人员可以按实际范围决定是否分批放行，系统不按所有部位齐套自动判断。</p>'; }
function lateChart(c?: any): any {
    const f: any = facts(c), start: any = ms(f.first.at);
    const ticks: any = [0, 4, 8, 12, 17, 21, 28].map((d?: any): any => '<span class="tick ' + (d === 17 ? 'today' : d === 28 ? 'end' : d === 12 || d === 21 ? 'optional' : '') + '" style="left:' + d / 28 * 100 + '%">' + fmt(start + d * DAY, true).slice(0, 5) + '<br>' + (d === 17 ? '查看时点' : d === 28 ? '入库截止' : 'D' + d) + '</span>').join('');
    let rows: any = '';
    rows += row(c, '生产准备', '无定位印 · 阶段整体4天', 'prep', period(c, '2026-09-20 09:00', '2026-09-24 09:00', '要求4天', 'tech') + period(c, '2026-09-24 09:00', '2026-09-25 09:00', '超1天', 'overdue-period') + point(c, '2026-09-25 09:00', '逾期完成', '09-25', 'prep', 'bad'), '张琳完成 · 陈静核对', '查看准备单');
    rows += row(c, '面辅料供给', 'F01采购到仓 · 要求8天', 'supply', period(c, '2026-09-20 12:00', '2026-09-28 12:00', '采购8天', 'tech') + period(c, '2026-09-28 12:00', '2026-09-30 12:00', '超2天', 'overdue-period') + point(c, '2026-09-30 12:00', 'F01逾期入仓', '09-30', 'supply', 'bad'), '赵敏采购 → 周婷入仓确认', '查看物料单据');
    rows += row(c, '裁剪／辅助工艺', '袖片绣花 · 要求3天', 'release', period(c, '2026-10-03 09:00', '2026-10-06 09:00', '3天', 'process') + period(c, '2026-10-06 09:00', ASOF, '逾期1天', 'overdue-period') + point(c, '2026-10-06 09:00', '应完成', '10-06', 'release', 'bad'), '阿琳执行 → 刘军接收 · 王明跟进', '查看工艺单据');
    rows += row(c, '车缝任务', '本演示尚未分配', 'waiting', '<div class="fact-note">未分配，尚无合同计时起点</div>', '王明核对实际分配', '查看当前数量');
    rows += row(c, '成衣仓入库', '已核实0／应完成1500件', 'warehouse', '<div class="fact-note">尚未入库 · 整单截止10-18 09:00</div>', '成衣仓周婷确认', '查看实际入库依据');
    return '<div class="sectiontop"><h2>全程时效图</h2><div class="legend"><span class="alert">■ 红色延伸＝超时</span><span>逾期完成＝历史延误</span><span>当前逾期＝仍需处理</span></div></div><div class="chart"><div class="chart-head"><div>阶段／工作</div><div class="axis">' + ticks + '</div><div>经办与交接责任</div></div>' + rows + '</div><p class="chart-note">这是独立超时示例；准备、采购时钟已结束，袖片绣花仍在进行。交接标准未确认，不自行判交接逾期。</p>';
}
function pos(c?: any, time?: any): any { return Math.max(0, Math.min(100, (ms(time) - ms(facts(c).first.at)) / (timeHorizon(c) * DAY) * 100)); }
function point(c?: any, at?: any, title?: any, sub?: any, key?: any, tone: any = '', secondary: any = ''): any { return '<button class="point ' + tone + '" style="left:' + pos(c, at) + '%" data-detail="' + esc(key) + '" aria-label="' + esc(title + ' ' + sub) + '">' + esc(title) + '<i></i>' + esc(sub) + (secondary ? '<span class="secondary">' + esc(secondary) + '</span>' : '') + '</button>'; }
function period(c?: any, start?: any, end?: any, label?: any, type: any = ''): any { const x: any = pos(c, start), right: any = pos(c, end); return '<div class="period ' + type + '" style="left:' + x + '%;width:' + Math.max(0, right - x) + '%"><span class="bartext">' + esc(label) + '</span></div>'; }
function row(c?: any, name?: any, sub?: any, key?: any, rail?: any, owner?: any, action?: any, next: any = '', classes: any = ''): any {
    const phase: any = name === '生产准备' ? 'prep' : name === '面辅料供给' ? 'supply' : name === '裁剪／辅助工艺' ? 'craft' : null;
    const b: any = phase ? branchData(c) : null, open: any = phase && state.expanded[phase];
    const control: any = phase ? 'data-expand="' + phase + '" aria-expanded="' + !!open + '"' : 'data-detail="' + esc(key) + '"';
    if (b)
        sub = phase === 'prep' ? '6条准备链路 · 阶段整体' + b.docs[b.master].clock.sla + '天' : phase === 'supply' ? (b.materials.length ? b.materials.length + '项物料 · 库存/补采分别跟进' : '物料执行记录待取得') : (b.parts.length ? b.parts.length + '个部位 · 无需/单道/多道' : '裁片执行记录待取得');
    const main: any = '<div class="chart-row ' + classes + (phase ? ' stage-expand' : '') + '"><div class="stage"><span class="icon">' + (phase ? (open ? '−' : '+') : classes.includes('late') ? '!' : classes.includes('unknown') ? '?' : name === '成衣仓入库' && c.warehouse > 0 ? '✓' : '·') + '</span><button ' + control + '><strong>' + esc(name) + '</strong><small>' + esc(sub) + '</small></button></div><div class="rail" style="--today:' + pos(c, ASOF) + '%">' + rail + '</div><div class="responsibility"><span>' + esc(owner) + '</span>' + (phase ? '<button class="link" ' + control + '>' + (open ? '收起' : '展开') + esc(phases[phase]) + '链路</button>' : button(action, key)) + (classes.includes('task-row') ? '<span class="next">' + esc(next) + '</span>' : '') + '</div></div>';
    return main + (open ? branchDiagram(c, phase) : '');
}
function taskRow(c?: any, t?: any): any {
    const f: any = facts(c), nodes: any = nodeInfo(t), received: any = receiptTotal(t), late: any = nodes.find((n?: any): any => n.status === '已逾期'), key: any = 'task:' + t.id;
    const marks: any = nodes.map((n?: any): any => { const stale: any = f.complete && n.status === '已逾期', tone: any = stale ? 'future' : n.status === '逾期达成' ? 'history-goal' : n.status === '已逾期' ? 'bad' : n.reached !== null ? 'ok' : 'future'; return '<button class="point goal ' + tone + '" style="left:' + pos(c, fmt(n.deadline)) + '%;top:' + (n.pct === 100 ? 35 : 3) + 'px" data-detail="' + key + '" aria-label="' + n.pct + '% ' + n.status + ' 截止' + fmt(n.deadline) + ' 累计目标' + n.target + '件"><span>' + n.pct + '%</span><i></i><span class="secondary">' + (stale ? '旧记录待核实' : n.status === '已逾期' ? '欠' + n.gap + '件' : n.status === '逾期达成' ? '逾期达成' : n.reached !== null ? '按期达成' : '未到期') + '</span></button>'; }).join('');
    const delayed: any = nodes.filter((n?: any): any => n.status === '逾期达成'), historyBands: any = delayed.map((n?: any): any => '<span class="history-band" style="left:' + pos(c, fmt(n.deadline)) + '%;width:' + Math.max(0, pos(c, fmt(n.reached)) - pos(c, fmt(n.deadline))) + '%"></span><span class="history-actual" style="left:' + pos(c, fmt(n.reached)) + '%">● ' + fmt(n.reached, true) + '</span>').join(''), note: any = delayed.map((n?: any): any => n.pct + '%实收达成' + fmt(n.reached, true) + ' · 晚' + duration(n.reached - n.deadline) + ' · 当前欠0件').join('；');
    return row(c, t.factory + ' ' + t.id, contracts[t.type].name + ' · ' + t.assigned.slice(5) + '分配', key, period(c, t.assigned + ' 00:00', fmt(nodes[2].deadline), '', 'contract') + (!f.complete && late ? '<span class="late-band" style="left:' + pos(c, fmt(late.deadline)) + '%;width:' + Math.max(0, pos(c, ASOF) - pos(c, fmt(late.deadline))) + '%"></span>' : '') + marks + historyBands, t.executor + '执行 → ' + t.receiver + '接收', f.complete ? '查看历史任务' : late ? '核对当前欠' + late.gap + '件' : '查看未来节点', note || '实收' + received + '／实领' + t.held + ' · 未回' + Math.max(0, t.held - received) + '件', 'task-row ' + (!f.complete && late ? 'late' : ''));
}
function identity(c?: any): any { const f: any = facts(c), photo: any = c.photo ? '<img class="photo" src="' + DEMO_IMAGE + '" alt="演示款蓝白印花衬衫实图">' : '<div class="photo missing">实图<br>待取得</div>'; return '<div class="identity"><div class="style">' + photo + '<div><h2>' + esc(c.title) + '</h2><div class="meta">' + esc(c.style) + ' · 跟单' + esc(c.merch) + ' · ' + button(c.purchases.length + '张采购单／查看起算依据', 'source') + '</div></div></div><div class="clock">' + (c.key === 'unknown' ? '实际核实截至时间未取得' : '业务核实截至 10-07 09:00（演示）') + '<br>' + esc(labels[c.key]) + '</div></div>'; }
function summary(c?: any): any { const f: any = facts(c), delta: any = f.deadline - ms(ASOF), list: any = issues(c), priority: any = list.find((i?: any): any => i.category === 'work' && i.tone === 'bad') || list[0]; return '<div class="summary"><div class="cell"><div class="eyebrow">全部入成衣仓截止 · 最早采购下单＋28自然日</div><b class="deadline">' + fmt(f.deadline) + '</b><div class="sub">' + esc(f.complete ? f.result : delta >= 0 ? '还剩' + duration(delta) + '；整单按期把握待核实' : f.result) + '</div></div><div class="cell"><div class="eyebrow">成衣仓已入库／应完成</div><b>' + (c.warehouse === null ? '待核实' : c.warehouse) + '<span style="font-size:16px;color:#8190a4">／' + f.required + '件</span></b><div class="sub">' + esc(c.warehouse === null ? '实际完成量未知，保留问号' : f.complete ? '全部应完成数量已入库 · 剩余0件' : '剩余' + f.remaining + '件需入库') + '</div></div><div class="cell"><div class="eyebrow">' + (f.complete ? '整单结果／资料核实' : '当前优先处理') + '</div><b class="' + (priority?.tone === 'bad' ? 'alert' : 'neutral') + '">' + esc(f.complete ? f.result : priority?.title || '已知时效项无当前逾期') + '</b><div class="sub">' + esc(priority ? priority.latest : f.complete ? '保留历史时效记录；不继续安排生产' : '下一合同节点独立跟进，未确认标准仍标待配置') + '</div></div></div>'; }
function quantityGraph(c?: any): any {
    if (c.key === 'late')
        return lateQuantity(c);
    const f: any = facts(c), b: any = f.balance;
    if (!b)
        return '<h2>数量现在在哪里</h2><div class="missing-balance">? ' + f.required + '件当前位置及历史入库待核实</div>';
    const items: any = [];
    if (b.waiting)
        items.push(['尚未下发车缝', b.waiting, '已核实未分配', 'balance', 'factory']);
    else
        items.push(['工厂尚未回', b.factory, '逐任务实领－后道实收', 'all', 'factory']);
    items.push(['后道加工中', !f.complete && !c.processing ? '待取得' : b.processing, f.complete ? '已全量入库' : c.processing?.id || '加工位置记录缺失', 'post', 'processing'], ['已交出待接收', b.handover, c.inbound?.id || '无当前交接批次', 'inbound', 'handover'], ['成衣仓已入库', c.warehouse, c.warehouseAt ? '最后入库 ' + shortTime(c.warehouseAt) : '最后入库时间待取得', 'warehouse', 'warehouse']);
    const pieces: any = [[b.waiting, '未下发'], [b.factory, '工厂未回'], [b.processing, '后道加工'], [b.handover, '交出待收'], [b.unknown, '任务归属待核实'], [b.position, '后道位置待核实'], [c.warehouse, '已入库']].filter(([q]: any): any => q);
    return '<div class="sectiontop"><h2>数量现在在哪里</h2><small>应完成' + f.required + '件 · ' + (f.conflicts.length ? '位置资料有冲突，核对后再汇总' : '以下数量互不重复') + '</small></div><div class="quantity-graph">' + items.map((i?: any): any => '<button class="qnode ' + i[4] + '" data-detail="' + i[3] + '"><div class="title">' + i[0] + '</div><div class="n">' + i[1] + (typeof i[1] === 'number' ? '<em>件</em>' : '') + '</div><div class="hint">' + esc(i[2]) + '</div></button>').join('') + '</div>' + (b.unknown || b.position ? '<div class="missing-balance">' + (b.unknown ? b.unknown + '件任务归属待核实 · ' : '') + (b.position ? b.position + '件已实收、后道当前位置待核实' : '') + ' ' + button('核对数量覆盖', 'balance') + '</div>' : '') + (!f.conflicts.length ? '<div class="distribution">' + pieces.map(([q]: any, i?: any): any => '<i style="width:' + q / f.required * 100 + '%;background:' + ['#8093ad', '#437cdb', '#e2a545', '#389878', '#a7b0bd'][i % 5] + '"></i>').join('') + '</div><div class="balance-note">' + f.required + '＝' + pieces.map(([q, name]: any): any => name + q).join('＋') + '件</div>' : '<div class="missing-balance">' + esc(f.conflicts.join('；')) + '</div>');
}
function chart(c?: any): any {
    if (c.key === 'unknown')
        return chartBase(c);
    if (c.key === 'late')
        return lateChart(c);
    const f: any = facts(c), b: any = branchData(c), master: any = b.docs[b.master], start: any = ms(f.first.at), horizon: any = timeHorizon(c), today: any = (ms(ASOF) - start) / DAY, ticks: any = [0, 4, 8, 12, 21, 28, ...(horizon > 28 ? [horizon] : []), ...(today > 0 && today < horizon ? [today] : [])].sort((a?: any, b?: any): any => a - b);
    const axis: any = ticks.map((d?: any): any => '<span class="tick ' + (d === today ? 'today' : d === 28 ? 'end' : d === 12 || d === 21 ? 'optional' : '') + '" style="left:' + d / horizon * 100 + '%">' + fmt(start + d * DAY, true).slice(0, 5) + '<br>' + (d === today ? '查看时点' : 'D' + d) + '</span>').join('');
    let rows: any = '';
    rows += row(c, '生产准备', '整体' + master.clock.sla + '自然日', 'prep', period(c, master.clock.start, fmt(ms(master.clock.start) + master.clock.sla * DAY), '要求' + master.clock.sla + '天', 'tech') + (master.clock.end ? point(c, master.clock.end, '实际关闭', shortTime(master.clock.end), 'prep', timing(master).gap ? 'bad' : 'ok') : '<div class="fact-note">' + esc(timing(master).label) + ' · 当前未关闭</div>'), '张琳执行 · 陈静完成确认', '查看生产准备单');
    rows += row(c, '面辅料供给', '逐物料采购/调拨与加工', 'supply', '<div class="fact-note">' + (c.key === 'materialBatches' ? 'F01库存600米批先行，补采900米批另计' : c.positioning || !b.materials.length ? '逐项供给记录待核实，不根据需求填满' : b.materials.length+'项物料 · 展开看各自实收与加工单') + '</div>', '赵敏采购 → 对应仓库实收确认', '查看物料单据');
    rows += row(c, '裁剪／辅助工艺', '辅助每道3天 · 人工放行', 'release', '<div class="fact-note">' + (c.prepOpen || !b.parts.length ? '裁片工艺、交接与放行记录待取得' : b.parts.length+'个部位 · 单道/多道分别跟进') + '</div>', '刘军裁剪 · 陈静人工放行', '查看工艺与交接');
    rows += c.tasks.map((t?: any): any => taskRow(c, t)).join('');
    if (!f.complete && c.processing)
        rows += row(c, '后道加工', c.processing.id + ' · ' + c.processing.qty + '件', 'post', period(c, c.processing.start, c.processing.finished || ASOF, '加工', 'process'), '吴芳执行 → 李梅完成确认', '查看加工事实');
    else if (!f.complete && !c.waitingConfirmed)
        rows += row(c, '后道加工', '记录待取得', 'post', '<div class="unknownrail">当前位置待核实' + (f.balance.position ? ' · ' + f.balance.position + '件' : '') + '</div>', '李梅核对已有处理记录', '核实当前位置');
    if (!f.complete && c.inbound)
        rows += row(c, '后道→成衣仓交接', c.inbound.id + ' · ' + c.inbound.qty + '件', 'inbound', period(c, c.inbound.out, c.inbound.in || ASOF, '交接', 'wait') + point(c, c.inbound.out, '已交出', shortTime(c.inbound.out), 'inbound', 'warn'), '李梅交出确认 → 周婷接收确认', '核对实收 · 标准待配置');
    rows += row(c, '成衣仓入库', '累计' + c.warehouse + '／应完成' + f.required + '件', 'warehouse', (c.warehouseAt ? (f.complete && ms(c.warehouseAt) > f.deadline ? period(c, fmt(f.deadline), c.warehouseAt, '逾期' + duration(ms(c.warehouseAt) - f.deadline), 'overdue-period') : '') + point(c, c.warehouseAt, f.complete ? '全部入库' : '实际入库', c.warehouse + '件 · ' + shortTime(c.warehouseAt), 'warehouse', f.complete && ms(c.warehouseAt) > f.deadline ? 'bad' : 'ok') : '<div class="fact-note">' + (f.complete ? '已全量入库 · 最后时间待取得' : '尚无入库时间') + '</div>') + '<div class="endflag" style="right:' + (100 - pos(c, fmt(f.deadline))) + '%"><span>' + f.required + '件全部入库</span></div>', '成衣仓周婷实收确认', '查看入库凭据');
    return '<div class="sectiontop"><h2>全程时效图</h2><div class="legend"><span class="ok-mark">◇ 按期达成</span><span class="history-late">◇ 逾期达成（历史）</span><span class="alert">◆ 当前逾期</span><span>◇ 未到期</span></div></div><div class="chart"><div class="chart-head"><div>工作／任务 · 点击查看</div><div class="axis">' + axis + '</div><div>执行与交接责任／下一动作</div></div>' + rows + '</div><p class="chart-note">合同从各任务业务分配日起算；制作和交接分别计时。历史逾期保留实际达成时点，当前欠量归零。没有时效标准的工作只展示用时。</p>' + (c.key === 'sameFactory' ? '<div class="missing-balance"><span>B厂汇总200／500＝40% · <b>'+esc(c.tasks.find((t:any)=>t.factory==='B厂'&&t.type==='sewing')?.id)+'仍欠90件</b></span><small>同厂另一任务已全量回货，不能冲抵其他任务</small></div>' : '');
}
function queueStrip(c?: any): any { const list: any = issues(c), work: any = list.filter((i?: any): any => i.category === 'work').length; return '<div class="queue-strip"><strong>当前跟进' + work + '项 · 资料核实' + (list.length - work) + '项</strong><span class="result">' + esc(list[0]?.latest || '已知时效项无当前逾期；继续核对未来节点') + '</span><button class="link" data-queue>' + (state.queue ? '收起完整跟进清单' : '展开完整跟进清单') + '</button></div>' + (state.queue ? '<div class="queue-list">' + (list.length ? list.map((i?: any): any => '<article>' + badge(i.category === 'facts' ? '资料核实' : '当前工作', i.tone) + button(i.title, 'issue:' + i.id) + '<div>' + esc(i.latest) + '</div><div>' + esc(i.owner) + ' · 下次反馈' + esc(i.feedback) + '</div></article>').join('') : '<article>没有当前未完成事项；历史延误继续保留在图中。</article>') + '</div>' : ''); }
function factBox(title?: any, body?: any): any { return '<div class="fact"><strong>' + esc(title) + '</strong>' + body + '</div>'; }
function details(c?: any, key?: any): any {
    const f: any = facts(c);
    if (key === 'warehouse')
        return '<h3>成衣仓入库依据</h3><div class="big">' + (c.warehouse === null ? '待核实' : c.warehouse) + '／' + f.required + '件</div>' + factBox('整单结果', esc(f.result)) + factBox('最后实际入库', c.warehouseAt || '时间待取得，不判断按期或逾期') + factBox('应完成依据', '最早商品采购' + f.first.id + ' ' + f.first.at + '；截止' + fmt(f.deadline) + '；剩余' + (f.remaining === null ? '待核实' : f.remaining) + '件') + (f.conflicts.length ? factBox('过程资料核实', esc(f.conflicts.join('；'))) : '');
    if (key === 'balance' || key === 'all')
        return '<h3>数量归属与当前位置</h3>' + quantityGraph(c) + table(['任务', '工厂实领', '后道实收', '任务未回（历史事实）'], c.tasks.map((t?: any): any => [button(t.id, 'task:' + t.id), t.held + '件', receiptTotal(t) + '件', Math.max(0, t.held - receiptTotal(t)) + '件'])) + '<p>任务覆盖缺失与后道位置缺失分别核实；全量入库后不安排重复生产。</p>';
    if (key.startsWith('task:')) {
        const t: any = c.tasks.find((t?: any): any => t.id === key.slice(5));
        if (!t)
            return '<h3>任务记录待取得</h3>';
        return '<h3>' + esc(t.factory + ' ' + t.id) + '</h3><p>' + contracts[t.type].name + ' · 业务分配' + t.assigned + '（第1天）</p><div class="big">' + receiptTotal(t) + '／' + t.held + '件</div>' + table(['节点', '累计目标', '截止', '当前/历史结果'], nodeInfo(t).map((n?: any): any => [n.pct + '%', n.target + '件', fmt(n.deadline), esc(n.status) + (n.reached ? '<br>实际达成 ' + fmt(n.reached) + '<br>' + (n.status === '逾期达成' ? '历史延误' + duration(n.reached - n.deadline) + ' · ' : '') + '当前欠0件' : '<br>' + (f.complete ? '上游资料核实' : n.status === '已逾期' ? '当前欠' + n.gap + '件' : '未来目标' + n.target + '件'))])) + factBox('执行与交接', esc(t.executor) + '执行/交出确认 → ' + esc(t.receiver) + '后道接收确认；王明跟进。') + '<p>样衣结果不改变本合同要求；其他任务回货不可冲抵本任务。</p>';
    }
    if (key === 'post' && !c.processing)
        return '<h3>后道位置记录待取得</h3>' + factBox('已有事实', f.complete ? '成衣仓已全量入库，过程记录另核对' : (f.balance?.position || '对应') + '件已实收，具体加工/交接位置待核实；不填0件。');
    if (key.startsWith('sample:')) {
        const b: any = branchData(c);
        return docSummary(b, b.docs[key.slice(7)]);
    }
    if (key.startsWith('issue:')) {
        const i: any = issues(c).find((i?: any): any => i.id === key.slice(6));
        return i ? '<h3>' + esc(i.title) + '</h3>' + factBox('现在核对什么', esc(i.latest)) + factBox('责任与反馈', esc(i.owner) + ' · ' + esc(i.feedback)) + button('查看对应事实', i.detail) : '<h3>该事项已结束</h3>';
    }
    if (key === 'impact')
        return impactGraph(c);
    return detailFallback(c, key);
}
function twoClocks(d?: any): any { const show: any = (k?: any): any => !k ? '' : !k.start ? '<div class="clock-chip">' + k.kind + '起点待取得</div>' : '<div class="clock-chip ' + (k.kind === '交接' ? 'handover-chip' : '') + '"><b>' + k.kind + '</b> ' + shortTime(k.start) + ' → ' + (k.end ? shortTime(k.end) : '接收待取得') + '<small>' + esc(clockLabel({ clock: k })) + '</small></div>'; return show(d.clock) + show(d.handoverClock); }
function sampleTimingLabel(d?: any): any { const t: any = d.sampleTiming; return !t.due ? '要求日期待核实' : t.late ? (t.done ? '逾期交出 · 历史延误' : '已过要求日期 · 尚未交出') : t.done ? '按期交出' : '尚未到要求日期'; }
function factorySamples(c?: any): any { const b: any = branchData(c); if (!b?.factorySamples.length)
    return ''; return '<div class="sample-section"><div class="sectiontop"><h2>工厂产前版样衣 · 与回货分别计时</h2><small>领料后的第3天 · 样衣结果不改变合同节点</small></div><div class="sample-grid">' + b.factorySamples.map((s?: any): any => { const d: any = b.docs[s.id], t: any = c.tasks.find((t?: any): any => t.id === s.task); return '<article class="sample-card"><strong>' + esc(t.factory + ' ' + t.id) + '</strong><div class="sample-mini-flow"><div>实领<br><b>' + shortTime(t.picked) + '</b></div>' + arrow() + '<div>要求交出<br><b>' + d.sampleTiming.due + '</b></div>' + arrow() + '<div>' + esc(sampleTimingLabel(d)) + '<br><b>' + shortTime(d.times.样衣交出) + '</b></div></div>' + docButton(d) + '<span class="' + (d.sampleTiming.late ? 'history-late' : 'ok-mark') + '">' + esc(d.status) + '</span><small>' + esc(t.executor) + '执行 → 技术张琳接收确认</small><small>合同从' + t.assigned + '业务分配起算；样衣结果独立记录</small></article>'; }).join('') + '</div></div>'; }
function impactGraph(c?: any): any {
    const b: any = branchData(c), f: any = facts(c);
    if (c.key === 'unknown')
        return '';
    const delayed: any = b.parts.flatMap((p?: any): any => p.process.map((x?: any): any => ({ p, d: b.docs[x.work] }))).filter((x?: any): any => timing(x.d)?.gap);
    const supply: any = b.materials.filter((m?: any): any => m.po && timing(b.docs[m.po])?.gap);
    const prep: any = timing(b.docs[b.master]);
    const contractImpacts: any = f.complete ? [] : c.tasks.map((t?: any): any => ({ t, n: nodeInfo(t).filter((n?: any): any => n.status === '已逾期').at(-1) })).filter((v?: any): any => v.n);
    if (!delayed.length && !supply.length && !prep.gap && !contractImpacts.length)
        return '';
    const cards: any = contractImpacts.map(({ t, n }: any): any => ({ title: t.factory + ' ' + t.id + ' · ' + n.pct + '%当前逾期', id: 'taskdoc-' + t.id, source: '本任务欠回' + n.gap + '件；尚未回' + (t.held - receiptTotal(t)) + '件', next: '对应任务后道实收 → 适用后道加工 → 成衣仓', result: t.executor + '执行 → ' + t.receiver + '接收；不影响其他任务的已实收判断', tone: 'bad' }));
    if (prep.gap)
        cards.push({ title: '生产准备 ' + (prep.done ? '已逾期关闭' : '当前逾期'), id: b.master, source: '本款适用准备成果', next: '正式技术包／对应加工资料', result: prep.done ? '已经结束 · 后续实际单据另看' : '当前准备结果尚未全部接收', tone: prep.done ? 'history' : 'bad' });
    supply.forEach((m?: any): any => cards.push({ title: m.name + '采购 ' + timing(b.docs[m.po]).label, id: m.po, source: m.id + '补采' + m.missing + m.unit, next: '采购批调拨 → 实际关联加工批', result: '按采购批记录追溯；库存来源不自动受影响', tone: timing(b.docs[m.po]).done ? 'history' : 'bad' }));
    delayed.forEach(({ p, d }: any): any => cards.push({ title: p.part + ' ' + d.type + ' · ' + timing(d).label, id: d.id, source: p.id + ' · ' + d.quantity + '片／未完成' + (d.quantities?.未完成 || 0) + '片', next: p.part === '袖片' ? '袖片批：蓝白 M/L/XL → 对应人工放行范围待核对' : p.id + '下游接收与人工放行记录', result: timing(d).done ? '已经交接 · 保留历史影响' : '尚未交出 → 裁床刘军接收待开始 → 车缝任务尚未分配', tone: timing(d).done ? 'history' : 'bad' }));
    return '<section class="impact-panel"><div class="sectiontop"><h2>超时工作影响到哪里</h2><small>' + (f.complete ? '已完成订单 · 历史延误追溯' : '只标明确关联；整单按期风险待负责人核实') + '</small></div>' + cards.map((x?: any): any => '<div class="impact-row ' + x.tone + '"><div class="impact-cell"><strong>' + esc(x.title) + '</strong>' + docButton(b.docs[x.id]) + '</div>' + arrow() + '<div class="impact-cell"><b>' + esc(x.source) + '</b><small>受影响对象／数量范围</small></div>' + arrow() + '<div class="impact-cell"><b>' + esc(x.next) + '</b><small>' + esc(x.result) + '</small></div></div>').join('') + (f.complete ? '<div class="impact-note">历史延误不再形成当前欠生产事项。已知整单结果：' + esc(f.result) + '；过程资料冲突另外核实。</div>' : delayed.some((x?: any): any => !timing(x.d).done) ? '<div class="impact-note"><b>未确认的成衣件数保持待核实</b> · 600袖片不换算为600件成衣，不把整单1500件全部标为受阻。前片、领片等独立部位按自己的实际记录推进。王明11:00核对受影响颜色/尺码与放行范围；陈静在裁片放行管理手动决定。</div>' : '<div class="impact-note">按明确对象和下游记录跟进，已结束的时钟只保留历史。当前超时不自动判定裁片放行或其他任务停工。</div>') + '<div class="impact-deadline">' + (f.complete ? '整单入库结果：' + esc(f.result) + ' · 最后实际入库 ' + shortTime(c.warehouseAt) : '整单仍按 ' + fmt(f.deadline) + ' 全部入成衣仓判断 · 无可靠预计完成时间时，不预测整单必然逾期。') + '</div></section>';
}
function timeHorizon(c?: any): any { const f: any = facts(c); return f.complete && c.warehouseAt && ms(c.warehouseAt) > f.deadline ? Math.max(29, Math.ceil((Math.max(ms(c.warehouseAt), ms(ASOF), ...c.tasks.flatMap((t?: any): any => nodeInfo(t).map((n?: any): any => n.deadline))) - ms(f.first.at)) / DAY) + 1) : 28; }
function detailFallback(c?: any, key?: any): any {
    if (key === 'inbound' && c.key !== 'unknown')
        return currentHandoverDetails(c);
    if (key.startsWith('branch:') || ['prep', 'supply', 'release'].includes(key))
        return branchDetails(c, key);
    if (c.key === 'late' && !['source', 'rule'].includes(key))
        return lateDetails(c, key);
    const f: any = facts(c), unknown: any = c.key === 'unknown';
    if (key === 'source')
        return '<h3>采购起点与整单截止</h3>' + table(['商品采购单', '下单时间', '应完成'], c.purchases.map((p?: any): any => [esc(p.id), esc(p.at), p.qty + '件'])) + factBox('最早下单决定整单截止', esc(f.first.at) + ' ＋28自然日<br><b>' + fmt(f.deadline) + '</b>') + '<p>原始采购应完成' + f.required + '件；消费者取消不改变该数量。合并采购不顺延截止，单张采购不拆成多张生产单。</p>' + (unknown ? '<p>下单时间沿用用户确认的需求下达默认时间；关联生产单事实待核实，不直接认为现场未建单。</p>' : '');
    if (key === 'rule')
        return '<h3>图中采用的业务口径</h3>' + factBox('整单完成', '最早关联采购下单＋28自然日，全部应完成量入成衣仓。已有全部入库数量与最后入库时间时，直接判断整单结果，过程资料缺口另列。') + factBox('阶段与合同', '生产准备有定位印5天、无定位印4天；物料采购到面辅料仓8天；辅助工艺每道3天。独立车缝4／8／9、车缝＋烫包5／9／10、裁剪＋车缝＋烫包6／9／12天，对应累计30%／70%／100%，分配日为第1天。') + factBox('时间与责任', '自然日；加工和交接分别计时。只跟踪上游交出／调拨出及下游接收，不增加运输、审版或返工时段。产前版样衣领料后第3天，其是否通过不改变回货节点。') + '<p>节点达成后结束当前欠回事项；逾期达成保留历史，未来节点单独判断。节点异常不能直接代替整单逾期判断。</p>';
    if (key.startsWith('issue:')) {
        const i: any = issues(c).find((i?: any): any => i.id === key.slice(6));
        if (!i)
            return '<h3>当前场景没有此事项</h3>';
        return '<h3>' + esc(i.title) + '</h3>' + factBox('为什么现在处理', esc(i.reason)) + factBox('当前动作', esc(i.text)) + factBox('责任与反馈', esc(i.category === 'facts' ? '核实对接：' : '执行：') + esc(i.executor) + '<br>' + esc(i.category === 'facts' ? '结果核对：' : '交接确认：') + esc(i.receiver) + '<br>当前跟进' + esc(i.owner) + '；下次反馈' + esc(i.feedback)) + factBox('最近反馈', esc(i.latest)) + '<p>预计交出属于负责人反馈，不能算入后道实收或成衣仓入库。</p>';
    }
    if (unknown)
        return '<h3>' + esc(({ all: '车缝任务与数量归属', post: '后道加工事实', inbound: '后道→成衣仓交接', warehouse: '历史成衣仓入库结果', balance: '数量所在位置', prep: '生产准备与物料供给', release: '裁剪与人工放行' } as Record<string,string>)[key] || '实际业务事实') + '待核实</h3>' + factBox('已取得', '商品采购240776，原始应完成1500件；下单2026-03-01 09:00，截止2026-03-29 09:00。技术包v1.0已发布。') + factBox('需要核实', '实际生产单、任务、工厂、实领／实收、加工起止、交出／接收和成衣仓入库结果未取得。具体执行人与交接确认人待落实。') + '<div class="actionbox"><strong>陈静协调对应岗位核对已有记录</strong><p>先查现有生产单、历史入库，反馈时间待约定。不推定未建单、未放行、未生产，不填0件。</p></div>';
    if (key === 'balance' || key === 'all')
        return '<h3>当前数量覆盖与分布</h3>' + factBox('总量平衡', '应完成' + f.required + '－已入库' + c.warehouse + '＝剩余' + f.remaining + '件<br>剩余＝工厂未回' + f.balance.factory + '＋后道加工' + f.balance.processing + '＋交出待收' + f.balance.handover + (f.balance.unknown ? '＋归属待核实' + f.balance.unknown : '') + '件') + table(['对应任务', '工厂实领', '后道实收', '尚未回'], c.tasks.map((t?: any): any => [button(t.id, 'task:' + t.id), t.held + '件', receiptTotal(t) + '件', (t.held - receiptTotal(t)) + '件'])) + (f.balance.unknown ? '<p>300件的实际归属待核实，不能按差额直接判为未分配或未领料。</p>' : '') + '<p>各位置数量互不重复。任务尚未回总量与当前合同节点欠量是不同指标。</p>';
    if (key.startsWith('task:')) {
        const t: any = c.tasks.find((t?: any): any => t.id === key.slice(5));
        if (!t)
            return '<h3>当前场景没有此任务</h3>';
        const nodes: any = nodeInfo(t), r: any = receiptTotal(t);
        return '<h3>' + esc(t.factory + ' ' + t.id) + '</h3><p>' + esc(contracts[t.type].name) + ' · 业务分配' + t.assigned + '（第1天）</p><div class="big">' + r + '／' + t.held + '件</div><p>后道实收／本任务工厂实领 · 本任务尚未回' + (t.held - r) + '件</p>' + table(['节点', '累计目标', '截止', '实际结果'], nodes.map((n?: any): any => [n.pct + '%', n.target + '件', fmt(n.deadline, true), esc(n.status) + (n.reached !== null ? '<br>实收达成' + fmt(n.reached, true) : n.status === '已逾期' ? '<br>当前欠' + n.gap + '件' : '<br>尚未到期')])) + factBox('执行与接收责任', esc(t.executor) + '执行 → ' + esc(t.receiver) + '后道接收；王明跟进，10-07 11:00反馈。') + factBox('事实时间', t.receipts.length ? '最后实际接收' + t.receipts[t.receipts.length - 1].at + '<br>业务核实截至' + t.checkedAt : '无接收记录，演示核实实收0件截至' + t.checkedAt) + (t.id === 'SWT-B-01' ? factBox('最近反馈', esc(issues(c).find((i?: any): any => i.id === 'return-b').latest)) : '') + '<p>浅色轨道只是合同观察区间，不代表实际加工起止或预计完成。加工起止与工厂交出记录需分别核对；其他任务回货不能冲抵本任务。</p><div class="actionbox">在车缝任务／后道接收页面办理。当前图示仅查看，不新增回货或交接事实。</div>';
    }
    if (key === 'post') {
        const p: any = c.processing;
        return '<h3>' + esc(p.id) + ' · 后道加工150件</h3><p>' + esc(c.style) + ' · ' + esc(p.color) + ' · ' + esc(p.sizes) + '</p>' + factBox('加工计时', '开始' + p.start + '<br>完成待确认 · 已用' + duration(ms(ASOF) - ms(p.start)) + '<br>标准待配置，不自动判逾期') + factBox('责任', '吴芳执行；李梅确认当前处理结果；10-07 13:00反馈。') + factBox('交接计时', '尚未取得本批交出记录，交接尚无计时起点。') + '<p>这150件与已交出' + esc(c.inbound.id) + '的150件分开；不能要求成衣仓接收300件。</p>';
    }
    if (key === 'inbound') {
        const b: any = c.inbound;
        return '<h3>' + esc(b.id) + ' · 已交出150件</h3><p>' + esc(c.style) + '<br>' + esc(b.color) + ' · ' + esc(b.sizes) + '<br>交接凭据' + esc(b.voucher) + '</p>' + factBox('① 加工已完成', b.start + '开始<br>' + b.finished + '完成 · 用时' + duration(ms(b.finished) - ms(b.start))) + factBox('② 交接接收待确认', b.out + ' 李梅交出150件<br>周婷接收时间与实收数量待确认<br>当前等待' + duration(ms(ASOF) - ms(b.out)) + '，交接标准待配置，不判逾期') + '<div class="actionbox"><strong>周婷：核对本批实际接收记录</strong><p>应交150件，实收待确认；10-07 12:00反馈。在原成衣仓收货页面办理，不由监控重复确认。</p></div>';
    }
    if (key === 'warehouse')
        return '<h3>成衣仓实际入库</h3><div class="big">600／1500件</div>' + factBox('已取得入库依据', '累计600件；最近入库' + c.warehouseAt + (c.warehouseBreakdown ? '<br>' + esc(c.warehouseBreakdown) : '') + '<br>演示核实截至' + c.verifiedAt + '；确认周婷') + factBox('还需入库', f.remaining + '件＝工厂未回' + f.balance.factory + '＋后道加工' + f.balance.processing + '＋已交出待收' + f.balance.handover + (f.balance.unknown ? '＋归属待核实' + f.balance.unknown : '') + '件。') + '<p>已交出待接收的150件没有计入这600件实际入库。全部应完成量入库后才认定生产完成。</p>';
    if (key === 'prep')
        return '<h3>准备与物料并行推进</h3>' + factBox('生产准备', '无定位印，整个阶段4天；09-20 09:00开始，09-24 09:00完成（演示）。张琳执行、确认。有定位印则整个阶段5天。') + factBox('面辅料供给', '3项适用物料已可用；每项从各自采购下单至面辅料仓入库计8天。各项实际到仓日期未逐项设定，不画假日期。采购赵敏负责，对应仓库确认。') + '<p>同一物料的加工按明确前置推进，独立物料可并行；不把辅助工艺每道3天套到所有染色、印花等工作。</p>';
    if (key === 'release')
        return '<h3>裁剪／辅助工艺与人工放行</h3>' + factBox('已取得事实', '对应裁片完成。陈静10-01 09:00人工放行本单1500件对应范围，王明接收任务（演示）。裁床执行刘军。') + factBox('计时边界', '适用辅助工艺每道3天；裁剪和加工的实际起止尚未逐项设定，因此图上只画已取得的放行时点。') + '<p>是否放行由业务人员在裁片放行管理办理，监控读取记录。分批按实际前置推进，不默认所有工作必须齐套或可以并行。</p>';
    return '<h3>当前单据明细</h3>';
}
function chartBase(c?: any): any {
    if (c.key === 'late')
        return lateChart(c);
    const f: any = facts(c), unknown: any = c.key === 'unknown', start: any = ms(f.first.at), ticks: any = [0, 4, 8, 12, 17, 21, 28];
    const axis: any = ticks.map((d?: any): any => '<span class="tick ' + (d === 17 ? 'today' : d === 28 ? 'end' : d === 12 || d === 21 ? 'optional' : '') + '" style="left:' + d / 28 * 100 + '%">' + fmt(start + d * DAY, true).slice(0, 5) + '<br>' + (d === 17 ? '查看时点' : d === 28 ? '入库截止' : 'D' + d) + '</span>').join('');
    let rows: any = '';
    if (unknown) {
        const placeholders: any = [['生产准备', '技术包v1.0已发布', 'prep', '定位印及实际起止待核实', '技术执行人待落实', '核对准备记录'], ['面辅料供给', '采购→面辅料仓8天', 'prep', '实际到仓时间、数量待核实', '采购／仓库人员待落实', '核对物料记录'], ['裁剪／辅助工艺', '人工放行；辅助每道3天', 'release', '对象、进度、放行记录待核实', '工艺与放行人员待落实', '核对人工放行'], ['车缝回货任务', '合同按具体任务判断', 'all', '工厂、合同、实领、实收待核实', '分配／交接人员待落实', '核对已有任务'], ['后道加工', '加工单独计时', 'post', '实际开始／完成时间待核实', '执行与确认人待落实', '核对后道事实'], ['后道→成衣仓交接', '交接单独计时', 'inbound', '交出／接收时间与数量待核实', '交出／接收人待落实', '核对交接事实'], ['成衣仓入库', '全部应完成1500件', 'warehouse', '已入库数量与最后入库时间待核实', '陈静协调仓库核实', '核实历史入库结果']];
        rows = placeholders.map((r?: any): any => row(c, r[0], r[1], r[2], '<div class="unknownrail">? ' + esc(r[3]) + '</div>', r[4], r[5], '实际事实未取得，不推定停工', 'unknown')).join('');
        return '<div class="sectiontop"><h2>全程时效图</h2><div class="legend"><span><i style="background:#a2adbc"></i>资料待核实</span><small>历史期限已过；执行过程不画假时段</small></div></div><div class="chart"><div class="chart-head"><div>工作与对应对象</div><div>' + f.first.at + '下单 → ' + fmt(f.deadline) + '截止</div><div>现在核实什么／谁负责</div></div>' + rows + '</div><p class="chart-note">先核实现有生产单和历史入库结果；不能根据资料缺口直接安排补生产或重复建单。</p>';
    }
    rows += row(c, '生产准备', '与物料供给并行', 'prep', period(c, f.first.at, '2026-09-24 09:00', '4天 · 无定位印', 'tech') + point(c, '2026-09-24 09:00', '完成', '09-24', 'prep', 'ok'), '张琳执行 · 技术确认张琳', '查看准备结果', '有定位印则整个阶段5天');
    rows += row(c, '面辅料供给', '采购下单→面辅料仓8天', 'prep', '<div class="fact-note">✓ 5项物料已满足 · 展开看库存/采购与大货加工</div>', '赵敏执行 → 对应仓库确认', '核对各项到仓记录', '图上不补造物料到仓日期');
    rows += row(c, '裁剪／辅助工艺', '辅助每道3天 · 人工放行', 'release', point(c, '2026-10-01 09:00', '人工放行', '10-01 09:00', 'release', 'ok'), '刘军执行 · 陈静放行 → 王明接手', '查看放行范围', '按实际前置衔接，不自动判断放行');
    rows += c.tasks.map((t?: any): any => taskRow(c, t)).join('');
    rows += row(c, '后道加工', c.processing.id + ' · 尚未完成150件', 'post', period(c, c.processing.start, ASOF, '', 'process') + point(c, c.processing.start, '开始', '10-06', 'post', '', '') + '<span class="fact-note" style="left:' + Math.min(76, pos(c, ASOF) + 3) + '%;top:17px">加工中 · ' + duration(ms(ASOF) - ms(c.processing.start)) + '</span>', '吴芳加工 · 李梅确认', '核对加工150件 · 李梅13:00', '加工已用' + duration(ms(ASOF) - ms(c.processing.start)) + '；标准待配置');
    rows += row(c, '后道→成衣仓交接', c.inbound.id + ' · 已交出150件', 'inbound', period(c, c.inbound.out, ASOF, '', 'wait') + point(c, c.inbound.out, '已交出', '10-06', 'inbound', 'warn') + '<span class="fact-note" style="left:' + Math.min(76, pos(c, ASOF) + 3) + '%;top:17px">待接收 · ' + duration(ms(ASOF) - ms(c.inbound.out)) + '</span>', '李梅交出 → 周婷接收确认', '核对接收150件 · 周婷12:00', '已等' + duration(ms(ASOF) - ms(c.inbound.out)) + '；周婷12:00反馈');
    rows += row(c, '成衣仓入库', '累计600／应完成1500件', 'warehouse', point(c, c.warehouseAt, '实际入库', '600件', 'warehouse', 'ok') + '<div class="endflag"><span>1500件全部入库</span></div>', '成衣仓周婷确认 · 王明总协调', '查看实际入库依据', '截止未到；整单按期把握待核实');
    return '<div class="sectiontop"><h2>全程时效图</h2><div class="legend"><span style="color:#258763">● 实际记录</span><span style="color:#258763">◇ 合同已达标</span><span style="color:#c33f48">◆ 节点逾期</span><span>◇ 未来合同节点</span><span><i style="background:#e2a545"></i>交出待收</span><span><i style="background:#326ada"></i>加工中／查看时点</span></div></div><div class="chart"><div class="chart-head"><div>工作／任务 · 点击查看</div><div class="axis">' + axis + '</div><div>经办动作与交接责任</div></div>' + rows + '</div><div class="chart-note"><span>◆／◇是合同累计实收要求，不是预计完成。浅色短条分别表示已取得的加工、交接计时。</span><span>回货分母＝本任务实领；分子＝本任务后道实收</span></div>' + (c.key === 'sameFactory' ? '<div class="missing-balance"><span>B厂汇总200／500＝40% · <b>SWT-B-01仍欠90件</b></span><small>SWT-B-02已全量回货，不能冲抵其他任务</small></div>' : '');
}
function prepDiagramBase(c?: any, b?: any): any { return '<div class="branch-panel" id="branch-prep">' + phaseTiming(b, 'prep') + branchHeader('prep', '生产准备单、BOM物料明细、前期输入及适用任务；本例无定位印，整体要求4天') + '<div class="prep-sources">' + [b.master, b.bom, b.prior].map((id?: any): any => docNode(b, id)).join('') + '</div><div class="prep-network"><div class="prep-lanes">' + b.prep.map((l?: any): any => '<div class="branch-lane"><div class="object-label"><strong>' + esc(l.label) + '</strong><small>' + esc(l.sub) + '</small></div><div class="mini-flow">' + l.nodes.map((n?: any): any => prepNode(b, n)).join(arrow()) + '</div></div>').join('') + '<div class="branch-lane"><div class="object-label"><strong>打版／首单样衣 · 本单M–XL</strong><small>基码前期复用，两个专业任务可并行</small></div><div class="paper-flow">' + prepNode(b, { title: '前期已确认基码', ids: [b.prior] }) + arrow() + '<div class="parallel-fork">' + [b.paper.sample, b.paper.sizes].map((id?: any): any => docNode(b, id)).join('') + '</div></div></div></div><div class="merge-result"><span class="join-label">适用成果汇合 →</span>' + docNode(b, b.packTask) + arrow() + docNode(b, b.pack) + '<small>全部有效明细完成；未启用／需求变更结束项不当作当前欠项。</small></div></div><div class="branch-foot"><span>调色是技术准备；辅料下单任务绑定采购单后满足，不代表物料已入库。有定位印时阶段整体5天。</span></div></div>'; }
function craftDiagramBase(c?: any, b?: any): any { return '<div class="branch-panel" id="branch-craft">' + phaseTiming(b, 'craft') + branchHeader('craft', '每个部位／批次有裁剪单，逐道加工单与工厂质检交接记录；辅助工艺每道3自然日') + b.parts.map((p?: any): any => '<article class="material-lane"><div class="material-identity"><strong>' + esc(p.part + ' · ' + p.qty + '片') + '</strong><small>' + esc(p.id) + '</small><span class="route-badge">' + esc(p.route) + '</span></div><div class="document-network"><div class="process-step">' + docNode(b, p.cutDoc) + (p.first ? arrow() + legNode(b, p.first) : '<div class="no-stock">无需辅助工艺 → 仍由业务人员人工放行</div>') + '</div>' + processRows(b, p.process) + '</div></article>').join('') + (b.releases.length ? '<div class="release-docs"><strong>业务人员人工放行</strong>' + b.releases.map((id?: any): any => docNode(b, id)).join('') + '</div>' : '<div class="no-release">本演示已核实：尚未办理裁片放行，没有车缝任务分配。是否分批放行由业务人员在原页面决定。</div>') + '<div class="branch-foot">上道工厂交出与下道实际接收分别记录。无需工艺也不自动视为已放行；片数不相加为成衣完成量。</div></div>'; }
function supplyDiagramBase(c?: any, b?: any): any { return '<div class="branch-panel" id="branch-supply">' + phaseTiming(b, 'supply') + branchHeader('supply', '每项物料先看需求和来源，按下游实收汇合，再跟进同一条加工链') + b.materials.map((m?: any): any => { const received: any = materialReceipt(b, m); return '<article class="material-object"><div class="material-object-head"><div><strong>' + esc(m.name) + '</strong><span class="object-code">物料 ' + m.id + '</span><small>' + esc(m.spec) + '</small></div><div class="material-equation"><b>需求 ' + m.need + m.unit + '</b><span>＝ 库存采用 ' + m.use + m.unit + ' ＋ 补采 ' + m.missing + m.unit + '</span></div></div><div class="source-join"><div class="source-paths">' + (m.stockTransfer ? '<div class="source-lane stock-source"><div class="source-label"><b>① 库存采用 ' + m.use + m.unit + '</b><small>下单时库存 ' + m.stock + m.unit + '</small></div>' + docNode(b, m.stockTransfer) + '</div>' : '') + (m.po ? '<div class="source-lane purchase-source"><div class="source-label"><b>② 缺口补采 ' + m.missing + m.unit + '</b><small>' + esc(m.source) + '</small></div>' + [m.po, m.receive, m.purchaseTransfer].map((id?: any): any => docNode(b, id)).join(arrow()) + '</div>' : '') + '</div><div class="source-join-line ' + (m.stockTransfer && m.po ? '' : 'single-source') + '"></div><div class="received-join"><strong>' + esc(m.target) + '已实收</strong><b>' + (received.total === null ? '待核实' : received.total + m.unit) + '</b><span>' + esc(received.equation) + '</span><small>' + shortTime(received.latest) + '</small></div></div>' + (m.process.length ? '<div class="join-to-process">↓ ' + (m.stockTransfer && m.po ? '两条来源汇合后，共用下面的加工链' : '下游实收后，沿下面的加工链推进') + '；各道数量分别记录</div>' + materialProcess(b, m) : '<div class="no-processing">✓ 无需大货加工 · 实收后进入对应配料工作</div>') + (m.transitDocuments?.length?'<div class="source-lane" style="margin-top:10px"><strong>中转仓接收 → 人工配料 → 裁床领料</strong>'+m.transitDocuments.map((id:any)=>docNode(b,id)).join(arrow())+'</div>':'') + '</article>'; }).join('') + '<div class="branch-foot">白坯布是加工前原料；蓝底、花型A/B是目标效果。采购数量不能直接算作已供给，以仓库及下游接收记录为准。米、粒、个不相加为成衣件数。</div></div>'; }
function documentSummaryBase(b?: any, d?: any, detailed: any = false): any {
    const q: any = d.quantities || { 数量: d.quantity };
    return '<div class="doc-heading"><div><span class="demo-label">' + esc(d.sourceLabel || '演示单据') + '</span><h2>' + esc(d.ownerId ? '生产准备单 · BOM物料明细' : d.type) + ' · ' + esc(d.no) + '</h2><p>' + esc(d.module || '生产协同') + '</p></div>' + badge(d.status, d.clock && !d.clock.end ? 'warn' : '') + '</div><div class="doc-identity"><strong>' + esc(d.production) + '</strong><span>' + esc(d.style) + '</span><span>对象／范围：' + esc(d.object) + '</span></div><div class="doc-quantities">' + Object.entries(q).map(([k, v]: any): any => '<div><small>' + esc(k) + '</small><b>' + (v === null ? '待核实' : esc(v) + esc(d.unit)) + '</b></div>').join('') + '</div>' + table(['关键事实', '时间'], Object.entries(d.times).map(([k, v]: any): any => [esc(k), v ? esc(v) : '待取得'])) + (d.clock ? '<div class="clock-summary">' + timingMark(d) + esc(clockLabel(d)) + '<br><small>' + (d.clock.sla ? '应完成截止 ' + fmt(ms(d.clock.start) + d.clock.sla * DAY) : '未配置交接／加工标准时，不自行判逾期') + '</small></div>' : '') + factBox('执行与交接确认', esc(d.executor) + ' → ' + esc(d.receiver)) + (d.qc ? factBox('质检交接结果', esc(d.qc)) : '') + (d.note ? factBox('业务说明', esc(d.note)) : '') + '<div class="doc-related"><strong>关联单据</strong><div>' + d.related.filter((id?: any): any => b.docs[id]).map((id?: any): any => docButton(b.docs[id], b.docs[id].type + ' · ' + b.docs[id].no)).join('') + '</div></div>' + (detailed ? '<p class="detail-note">该页与监控图使用同一张演示单据及同一组时间、状态、数量，仅用于查看，不办理业务。</p>' : '');
}
function timingBase(d?: any): any { const k: any = d.clock; if (!k || !k.sla)
    return null; const deadline: any = ms(k.start) + k.sla * DAY, end: any = ms(k.end || ASOF), gap: any = Math.max(0, end - deadline); return { deadline, gap, done: !!k.end, label: gap ? (k.end ? '逾期完成 ' : '当前逾期 ') + duration(gap) : (k.end ? '按期完成' : '尚未到期') }; }
function documentHref(d?: any): any { return timingDocumentHref(d.id) || null; }

export function setTimingDiagramScene(scene:string):void { state.scenario=scene; state.detail=''; state.queue=false; state.expanded={prep:false,supply:false,craft:false}; }
export function renderTimingDiagramBody():string { const c=makeCase(state.scenario);return identity(c)+summary(c)+quantityGraph(c)+stageRiskOverview(c)+'<div class="branch-nav"><button class="all-expand" data-expand-all>'+(['prep','supply','craft'].every(p=>state.expanded[p])?'收起全部阶段链路':'展开全部阶段链路')+'</button><span class="branch-note">阶段展开查看对象、单据、制作与交接；三种角色同屏读图</span></div>'+chart(c)+factorySamples(c)+impactGraph(c)+queueStrip(c)+'<footer class="footer"><span>一线看对象与动作 · 主管看影响和跟进 · 高管看整单目标与结果</span><div class="links">'+button('采购依据','source')+button('时效口径','rule')+'</div></footer>'; }
export function timingDiagramState(){return state}
export function renderTimingNodeDetail(key:string):string {const c=makeCase(state.scenario),b=branchData(c);const documents=b?Object.values(b.docs).filter((d:any)=>key==='warehouse'?d.type==='成衣仓入库单':key.startsWith('task:')?(d.object.includes(key.slice(5))&&/合同|车缝任务|领料|后道实收/.test(d.type)):false):[];return details(c,key)+(documents.length?'<div class="factbox">相关单据：'+documents.map((d:any)=>docButton(d)).join('')+'</div>':'')}
export function renderTimingDocumentSummary(id:string):string { const b=branchData(makeCase(state.scenario));return b?.docs[id]?docSummary(b,b.docs[id]):'<h3>单据未取得</h3>'; }
export function renderTimingSourceSummaryForCase(c:any,id:string):string {const b=branchData(c)??{docs:Object.fromEntries(c.purchases.map((p:any)=>[p.documentId,findTimingDocument(p.documentId)?.document]))};return b?.docs[id]?docSummary(b,b.docs[id]):'<h3>单据未取得</h3>'}
