import test from 'node:test'
import assert from 'node:assert/strict'
import { evaluateProcessing, compareProcessingCandidate, renderProcessingPanel, type ProcessingSupply, type ProcessingCandidate } from '../../src/pages/material-decision/processing.ts'
const supply: ProcessingSupply={targetSku:'TARGET',inputStock:100,committedInput:100,expectedOutput:90,awaitingDispatch:40,transit:20,receivedChecking:10,qualified:20,rejected:0,loss:0,unit:'Yard',conversion:1,yieldRate:.9,route:['染色','印花']}
test('AT05 committed greige is not available for a second allocation',()=>{const r=evaluateProcessing(supply);assert.equal(r.freeInput,0);assert.equal(r.futureSupply,60);assert.equal(r.currentUsable,20)})
test('AT06 partial receipt reduces expected supply; checking and qualified never duplicate',()=>{const r=evaluateProcessing(supply);assert.equal(r.received,30);assert.equal(r.remaining,60);assert.equal(r.futureSupply+r.received,90);assert.deepEqual(r.blockers,[])})
test('AT07 unmapped target preserves quantities but gives no target coverage',()=>{const r=evaluateProcessing({...supply,targetSku:''});assert.equal(r.futureSupply,0);assert.equal(r.currentUsable,0);assert.equal(r.received,30);assert.ok(r.blockers.includes('输出目标 SKU 为空'))})
test('§7.2 loss reduces future supply; rejected receipts never become usable',()=>{const r=evaluateProcessing({...supply,awaitingDispatch:35,loss:5,receivedChecking:5,rejected:5});assert.equal(r.remaining,55);assert.equal(r.currentUsable,20);assert.equal(r.received+r.remaining+5,90);assert.deepEqual(r.blockers,[])})
test('§7.3 unit/yield/route and conservation gaps block deterministic supply',()=>{for(const patch of [{conversion:null},{yieldRate:null},{route:[]},{transit:100},{committedInput:101},{expectedOutput:NaN}]){const r=evaluateProcessing({...supply,...patch});assert.ok(r.blockers.length);assert.equal(r.futureSupply,0)}})
const candidate:ProcessingCandidate={name:'调拨',quantity:40,days:3,route:'调拨',constraint:'',blockers:[],cost:null}
test('§7.3 candidate comparison reports remaining shortage and respects arrival deadline',()=>{assert.deepEqual(compareProcessingCandidate(candidate,80,5),{covered:40,residual:40,onTime:true});assert.deepEqual(compareProcessingCandidate({...candidate,days:8},80,5),{covered:0,residual:80,onTime:false});assert.equal(compareProcessingCandidate({...candidate,blockers:['原料占用']},80,5).covered,0);assert.equal(compareProcessingCandidate({...candidate,days:null},80,5).covered,0)})
test('§7.3 zero gap stays zero and nonfinite inputs cannot produce advice',()=>{assert.equal(compareProcessingCandidate(candidate,0,5).residual,0);assert.equal(compareProcessingCandidate(candidate,NaN,5).residual,null)})
test('panel uses owned local handlers and discloses mock and missing images',()=>{const html=renderProcessingPanel();assert.match(html,/id="md-processing"/);assert.match(html,/data-md-processing-action="compare"/);assert.match(html,/data-skip-page-rerender="true"/);assert.match(html,/真实物料图片待提供/);assert.match(html,/不生成真实/);assert.match(html,/采购坯布后加工/)})
