import {test} from 'node:test'
import assert from 'node:assert/strict'
import {evaluatePrep,validatePrep,createPrepRecord,receivePrep,type PrepRule} from '../../src/pages/material-decision/preparation'
const rule:PrepRule={id:'r',sku:'target',name:'target',unit:'Yard',category:'面料',active:true,mode:'固定数量',trigger:100,target:200,days:60,usage7:70,incoming:0,lots:[{warehouse:'w',qty:20,rolls:null,usable:true,reason:''}],processing:true,route:['染色','印花'],rawSku:'raw',rawUnit:'Yard',rawLots:[{warehouse:'w',qty:1000,rolls:null,usable:true,reason:''}],yieldRate:.9,moq:0,pack:10,note:''}
test('trigger distinct from target, existing supply produces explainable zero',()=>{assert.equal(evaluatePrep(rule).recommendation,180);assert.equal(evaluatePrep({...rule,incoming:180}).recommendation,0);assert.match(evaluatePrep({...rule,incoming:180}).reason,/覆盖/);assert.ok(validatePrep({...rule,target:50}).length)})
test('missing mapping or usage and incompatible raw unit block unsafe generation',()=>{assert.equal(evaluatePrep({...rule,mode:'覆盖天数',usage7:null}).recommendation,null);assert.throws(()=>createPrepRecord({...rule,lots:[{...rule.lots[0],warehouse:'待映射仓库'}]},[],'采购成品'));assert.throws(()=>createPrepRecord({...rule,rawUnit:'kg'},[],'调拨加工'))})
test('generation reserves remaining once and shared raw pool across target rules',()=>{const rec=createPrepRecord(rule,[],'调拨加工');assert.equal(rec.rawQty,200);assert.equal(evaluatePrep(rule,[rec]).recommendation,0);assert.throws(()=>createPrepRecord(rule,[rec],'调拨加工'));const other={...rule,id:'other',rawLots:[{...rule.rawLots[0],qty:300}]};assert.equal(evaluatePrep(other,[rec]).rawAvailable,100);assert.equal(evaluatePrep(other,[rec]).transferAllowed,false)})
test('production does not increase stock; actual SKU and output bound partial receipts',()=>{const rec=createPrepRecord(rule,[],'调拨加工');assert.throws(()=>receivePrep(rec,rule,10,'target'));rec.status='待交接';rec.produced=180;assert.equal(evaluatePrep(rule,[rec]).available,20);assert.throws(()=>receivePrep(rec,rule,10,''));receivePrep(rec,rule,80,'target');assert.equal(rec.status,'部分入库');assert.equal(evaluatePrep(rule,[rec]).available,100);assert.equal(evaluatePrep(rule,[rec]).remaining,100);receivePrep(rec,rule,100,'target');assert.equal(rec.status,'已入库');assert.equal(evaluatePrep(rule,[rec]).available,200);assert.equal(evaluatePrep(rule,[rec]).remaining,0)})
test('cancelled suggestion releases commitment and raw allocation',()=>{const rec=createPrepRecord(rule,[],'调拨加工');rec.status='已取消';assert.equal(evaluatePrep(rule,[rec]).recommendation,180);assert.equal(evaluatePrep(rule,[rec]).rawAvailable,1000)})
