import { test } from 'node:test'
import assert from 'node:assert/strict'
import { calculateWarning, filterWarnings, nearestWarningBatch, warningBatches, warningMaterials, renderWarningsView, type WarningFilter } from '../../src/pages/material-decision/warnings'
const filter:WarningFilter={query:'',coverage:'',transit:'',from:'',to:'',mode:'legacy',page:1,size:5}
test('P2 coefficients and coverage exclude transit',()=>{for(const i of [0,1]) assert.equal(calculateWarning(warningMaterials[i]).daily,10);assert.equal(calculateWarning(warningMaterials[1]).coverage,3);assert.equal(calculateWarning(warningMaterials[1],'qualified').coverage,2.5)})
test('P2 coverage buckets have exclusive shared boundaries',()=>{const list=(coverage:string)=>filterWarnings(warningMaterials,{...filter,coverage}).map(m=>m.sku);assert.ok(list('0-3').includes(warningMaterials[1].sku));assert.ok(!list('3-7').includes(warningMaterials[1].sku));assert.ok(list('3-7').includes(warningMaterials[3].sku));assert.ok(!list('7-10').includes(warningMaterials[3].sku));assert.ok(list('7-10').includes(warningMaterials[5].sku))})
test('P2 partial receipts and completed batches count remaining only',()=>{assert.equal(calculateWarning(warningMaterials[1]).transit,210);assert.equal(warningBatches(warningMaterials[1]).length,2)})
test('P2 latest overdue selected only if no future batch; today included',()=>{assert.equal(nearestWarningBatch(warningMaterials[2])?.eta,'2026-09-03');assert.equal(nearestWarningBatch(warningMaterials[1])?.eta,'2026-09-18');assert.equal(nearestWarningBatch(warningMaterials[1],'2026-09-03')?.eta,'2026-09-03')})
test('P2 search transit and ETA filters compose',()=>{const matches=filterWarnings(warningMaterials,{...filter,query:'white',transit:'yes',from:'2026-09-18',to:'2026-09-18'});assert.equal(matches.length,1);assert.equal(filterWarnings(matches,{...filter,transit:'no'}).length,0)})
test('P2 zero demand and missing BOM preserve distinct nulls; micro demand excluded',()=>{assert.equal(calculateWarning(warningMaterials[10]).coverage,null);assert.equal(calculateWarning(warningMaterials[10]).daily,0);assert.equal(calculateWarning(warningMaterials[11]).daily,null);assert.equal(calculateWarning(warningMaterials[12]).warning,false)})
test('P2 standard table renders and limits initial rows to first page',()=>{const html=renderWarningsView();assert.match(html,/md-warnings/);assert.match(html,/1 \/ 3/);assert.match(html,/历史口径参考/);assert.doesNotMatch(html,/DEMO-FAB-014/);assert.equal(warningMaterials.length,14)})
