// @page-pattern: dashboard

import { listPostFinishingDefectRecords, listPostFinishingFullFlowPostTasks } from '../../../data/fcs/post-finishing-full-flow.ts'
import { escapeHtml } from '../../../utils.ts'
import { renderPostFinishingPageHeader, renderPostStatusBadge } from './shared.ts'

export function renderPostFinishingWorkOrdersPage(): string {
  const params = typeof window === 'undefined' ? new URLSearchParams() : new URLSearchParams(window.location.search)
  const keyword = params.get('keyword')?.toLowerCase() || ''
  const tasks = listPostFinishingFullFlowPostTasks().filter((task) => !keyword || [task.postTaskNo, task.qcTaskNo, task.deliveryOrderNo, task.productionOrderNo].join(' ').toLowerCase().includes(keyword))
  const defects = listPostFinishingDefectRecords({ discoveryStage: '后道' })
  return `<div class="space-y-4 p-4" data-testid="post-finishing-work-orders-page">${renderPostFinishingPageHeader('后道任务', '质检合格数量进入后道；PDA 精确扫码执行，完成后唯一生成复检单')}<div class="grid gap-3 md:grid-cols-3"><div class="rounded-xl border bg-card p-4"><div class="text-xs text-muted-foreground">后道任务</div><strong class="mt-1 block text-2xl">${tasks.length}</strong></div><div class="rounded-xl border bg-card p-4"><div class="text-xs text-muted-foreground">后道瑕疵记录</div><strong class="mt-1 block text-2xl">${defects.length}</strong></div><div class="rounded-xl border bg-card p-4"><div class="text-xs text-muted-foreground">执行端</div><a data-nav="/fcs/pda/post-finishing/execute" class="mt-1 block text-sm font-semibold text-blue-700">打开 PDA 后道加工</a></div></div><form class="flex gap-2 rounded-xl border bg-card p-4"><input name="keyword" value="${escapeHtml(params.get('keyword') || '')}" class="h-9 min-w-0 flex-1 rounded-md border px-3 text-sm" placeholder="后道任务 / 质检任务 / 送货单 / 生产单"/><button class="rounded-md border px-4 text-sm">查询</button></form><div class="grid gap-3 lg:grid-cols-2">${tasks.map((task) => `<article class="rounded-xl border bg-card p-4"><div class="flex items-start justify-between gap-3"><div><div class="font-mono font-semibold">${escapeHtml(task.postTaskNo)}</div><div class="mt-1 text-xs text-muted-foreground">${escapeHtml(task.productionOrderNo)} · ${escapeHtml(task.qcTaskNo)} · 第 ${task.returnIndex} 次</div></div>${renderPostStatusBadge(task.status)}</div><div class="mt-3 grid grid-cols-3 gap-2 text-xs"><div class="rounded-lg bg-slate-50 p-2"><span class="text-muted-foreground">加工 SKU</span><strong class="mt-1 block">${task.lines.length}</strong></div><div class="rounded-lg bg-slate-50 p-2"><span class="text-muted-foreground">应加工</span><strong class="mt-1 block">${task.lines.reduce((sum, line) => sum + line.expectedQty, 0)} 件</strong></div><div class="rounded-lg bg-slate-50 p-2"><span class="text-muted-foreground">复检单</span><strong class="mt-1 block font-mono text-[11px]">${escapeHtml(task.recheckOrderNo || '待生成')}</strong></div></div><div class="mt-3 flex flex-wrap gap-2"><a data-nav="/fcs/craft/post-finishing/print?type=POST_ORDER&id=${encodeURIComponent(task.postTaskId)}" class="rounded-md border px-3 py-2 text-xs">打印后道工序加工单</a><a data-nav="/fcs/pda/post-finishing/execute?id=${encodeURIComponent(task.postTaskNo)}" class="rounded-md bg-blue-600 px-3 py-2 text-xs text-white">PDA 执行</a></div></article>`).join('') || '<div class="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground lg:col-span-2">质检选择“需要后道”后自动生成任务。</div>'}</div></div>`
}
